### ISSUE TITLE
Seeding database: get stuck in loop when trying to load data. 

### ISSUE THREAD

**Issue by jenpen** [ga-wdi-exercises/project3#10]
When trying to upload our seed data, we see an expected console.log for each of the memories we are trying to create, but the terminal doesn't exit the action. 

Terminal showing hard stop
![screenshot 2015-12-03 15 45 46](https://cloud.githubusercontent.com/assets/4039780/11573620/3f9a0610-99d5-11e5-8e39-1f2a720e11cb.png)

Seed file
![screenshot 2015-12-03 15 46 56](https://cloud.githubusercontent.com/assets/4039780/11573621/3f9c5d0c-99d5-11e5-9d2f-1cbb20ef9164.png)

Schema file
![screenshot 2015-12-03 15 47 13](https://cloud.githubusercontent.com/assets/4039780/11573619/3f9812ce-99d5-11e5-8f79-d6302feb71b8.png)

**Comment by RobertAKARobin** [comment]
Nodemon doesn't stop nodemon-ing until it runs into a `process.exit()` somewhere. Without `process.exit()`, you'll need to control-C out of Nodemon.

**Comment by nolds9** [comment]
What I think you are running into is an issue of asynchronicity, when you save a model, what do you want to happen after the process? hint: ^

**Comment by jenpen** [comment]
got it. Thanks!
