### ISSUE TITLE
Update exercise form reloading page instead

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#100]
We are currently having an issue with a form that updates our exercises.  Exercises are in workouts and when you display the workout all of the exercises appear.  When you click on the edit exercise button a form appears below the exercise.  When the update exercise form is click we want that form to disappear and update the exercise.  The functionality of it currently works but the form is submitted it reloads the page.  The URL of the page also has information in it regarding the exercise.  We have tried preventing the default functionality of the form but it no longer submits the request.  

The issue is on issue is on line 37 of public/js/views/exerciseView and the link to our repo is

https://github.com/murgia/SwoleMate

Thank you!

**Comment by jshawl** [comment]
can you add `event` and `event.preventDefault` here https://github.com/murgia/SwoleMate/blob/9cd56c54f4f7ed5f80a17c1a92de50ddbfd3f1dc/public/js/views/exerciseView.js#L37-L38 ?

**Comment by murgia** [comment]
I added them back in.  I have a log in there so the click event is firing but the update is not happening.  Do you think it has something to do with what we are rendering once its clicked.  Possibly needing to render the view that is showing the exercises.

**Comment by murgia** [comment]
OK so I did a little more investigating.  The click event works and updates the exercise when I manually reload the page so it looks like a rendering issue.

**Comment by jshawl** [comment]
recommend `console.log(self)` here https://github.com/murgia/SwoleMate/blob/master/public/js/views/exerciseView.js#L87

**Comment by jshawl** [comment]
also any errors in the console?

**Comment by murgia** [comment]
We are not currently getting any errors in the console.  This is what is being logged by self:

ExerciseView {exercise: Exercise, $el: n.fn.init[1]}

**Comment by jshawl** [comment]
I can't see any code that appends this element onto the page - https://github.com/murgia/SwoleMate/blob/master/public/js/views/exerciseView.js#L29

**Comment by murgia** [comment]
I am still taking a look at it and trying to understand how we can add to the render method so that when the render method is called it appends the exercise back onto the workout

**Comment by murgia** [comment]
I feel like I am still missing the boat on this.  So when we click create exercise we want to then re-append the exercise back to where it was?

**Comment by murgia** [comment]
i took at a look at line 29 and that edit template is appending to the bottom of the exercise and displaying.

**Comment by jshawl** [comment]
problem solved?

**Comment by murgia** [comment]
No the edit template has always been displaying.  The problem is once the edit template is displaying and then you click the update exercise button, the form would try to refresh the page.  The form doesn't refresh anymore because of the prevent default.  The patch request works because when you reload the page the exercise is changed.  Its when that update exercise button is click we want the form to disappear and the exercise to display the updated information.

**Comment by jshawl** [comment]
> Its when that update exercise button is click we want the form to disappear and the exercise to display the updated information.

When the update exercise button is clicked, can you console.log anything?

When the update exercise button is clicked, can you hide the form with `$.hide()`?

Does the exercise display the old information?

**Comment by murgia** [comment]
I got it to hide and show properly when update exercise is clicked.  The last piece of the puzzle is displaying an updated version of the exercise.  The exercise still displays the old information.

**Comment by jshawl** [comment]
what if you remove the old view, and create a new one?

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to close this. Feel free to open a new one!
