### ISSUE TITLE
adding delete button 

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project3#102]
I am having trouble conceptualizing how the delete function would work for this portion of my app.  There is a user model that has a reference to dashboardItems.  Right now it successfully creates the dashboardItems in the database and the handlebars function in the view displays them in a list.  Now I need to add a delete button next to each.  So in my controller I have 

```
destroy: function(request, response){
  // find the dashboard item
  var dbItem = request.user.dashboardItem
  //dashboarditem.destroy
  dbitem.remove(function(err){
    if (err){
      console.log(err)
    } else {
      response.redirect('/partners/dashboard')
    }
  });
```

in my routes I have 

```
router.route('/partners/dashboard')
  .get(authenticatedUser, dashboardController.new)
  .post(dashboardController.create)
  // .get(dashboardController.index)
  .delete(dashboardController.destroy)
```

and in the view I have 

```
<!--delete button  -->
<form method = "POST" action = 'partners/dashboard?_method=DELETE'>
    <button type='submit'>Delete</button>
</form>
```

The error I get is "Cannot POST /partners/partners/dashboard?_method=DELETE".  So I guess I am having trouble understanding how these things interact with each other to figure out what I am missing to make this function work.

**Comment by jshawl** [comment]
`Cannot POST /partners/partners/dashboard` looks a little weird. Try adding an initial slash here:

```
<form method="POST" action='/partners/dashboard?_method=DELETE'>
```

**Comment by dan-ator** [comment]
The route seems to work now, but now the delete button is adding empty entries instead.

**Comment by jshawl** [comment]
are you using method override? https://github.com/expressjs/method-override https://github.com/ga-dc/express-passport-local-authentication/blob/538581d6a46790dc5174b76b4076e95ee9a0ee52/config/routes.js#L6

**Comment by dan-ator** [comment]
Looks like I had installed it but had not required it.  But now it is saying "TypeError: Cannot read property 'remove' of undefined at dashboardController.destroy" But i just defined the thing the line before the .remove() so I am not sure why that would be.

```
destroy: function(request, response){
  // find the dashboard item
  var dbItem = request.user.dashboardItem
  //dashboarditem.destroy
  dbItem.remove(function(err){
    if (err){
      console.log(err)
    } else {
      response.redirect('/partners/dashboard')
    }
  });
```

So I console.logged dbItem right after that line and it is apparently undefined.  Not sure why.  I had previously used the syntax of request.user to populate the dashboardItems in the first place in another controller function.

**Comment by jshawl** [comment]
What is the output of console.log(request.user)?

**Comment by dan-ator** [comment]
```
{ local: 
   { email: 'dan@email.com',
     password: '$2a$08$2phJ1tMi0w/H/./GI.cTsOCsiaCKNoXiI7Wcd6uHfeKv5mVlJIbQS' },
  dashboardItems: 
   [ 566864ce82268baf2c71a90a,
     56688ef72545b00637aa1241,
     56688fe54a28744b3711e6e4,
     566892004a28744b3711e6e5,
     56689ac89eee0d2b3a1daf4c,
     56689bfd6a526c7f3a3b3878,
     56689dab000a53e93a82edaf,
     5668a06c95cfb1a73b1f0959,
     5668a638aa9620e63c4a6ca4,
     5668a63eaa9620e63c4a6ca5,
     5668a640aa9620e63c4a6ca6,
     5668a641aa9620e63c4a6ca7,
     5668b27e2b148f884038d8ff,
     566999474b8bceb547067208,
     566999484b8bceb547067209,
     566999db4b8bceb54706720a,
     566999df4b8bceb54706720b ],
  __v: 17,
  _id: 56685527632956a4274408de }
```

The user with all of the objectIDs of his dashboardItems.

**Comment by jshawl** [comment]
so you have `request.user.dashboardItems` but not `request.user.dashboardItem`

**Comment by dan-ator** [comment]
I changed that and I get this strange error: 

```
CastError: Cast to ObjectId failed for value "function (err){
   if (err){
     console.log(err)
   } else {
     response.redirect('/partners/dashboard')
   }
 }" at path "dashboardItems"
```

Although it appears that the variable is no longer undefined.  I guess now my variable is pulling every dashboardItem now and I need to separate each one.

**Comment by jshawl** [comment]
I think it's because you're calling `remove` on an array, check out http://stackoverflow.com/questions/16959099/how-to-remove-array-element-in-mongodb

**Comment by dan-ator** [comment]
I tried adapting that to mine but could not get it to work.  I don't have anything specific to reference, like each ID is just randomly generated.

**Comment by jshawl** [comment]
what do you mean by could not get it to work? are there any errors? does it fail silently?

**Comment by dan-ator** [comment]
Well I got "ReferenceError: id is not defined at dashboardController.destroy"
and my code was 

```
destroy: function(request, response){
  // find the dashboard item
  var dbItems = request.user.dashboardItems
  console.log(request.user)
  dbItems.update(
    { _id: id },
    { $pull: { _id: id } }
  );
  response.redirect('/partners/dashboard')
}
```

**Comment by jshawl** [comment]
are you trying to remove all of the `dbItems` with  

``` js
dbItems.update(
    { _id: id },
    { $pull: { _id: id } }
  )

```

?

**Comment by dan-ator** [comment]
I am trying to put a delete button next to each item on the list and to remove each one by itself.

**Comment by dan-ator** [comment]
I guess I am not sure how to reference an individual one.

**Comment by jshawl** [comment]
can i see the view that shows each item?

**Comment by dan-ator** [comment]
It's pretty hacky I think, but here it is:

```
<ul class="db_list">
  {{#each currentUser.dashboardItems}}
  <li>{{partner_message}}  -  {{partner_link}}</li>
  <form method = "POST" action = '/partners/dashboard?_method=DELETE'>
    <button type='submit'>Delete</button>
  </form>
  {{/each}}
</ul>
```

**Comment by jshawl** [comment]
what if you try

``` html
<form method = "POST" action = '/partners/dashboard?_method=DELETE'>
   <input type='hidden' value='{{this}}' >
    <button type='submit'>Delete</button>
</form>
```

where `{{this}}` is one of the dashboard items. Then you'll know which one to remove

**Comment by dan-ator** [comment]
I tried that with the code I had and got: 

```
ReferenceError: id is not defined
    at dashboardController.destroy (/Users/danielalexander/wdi/projects/projectThree/Project3/controllers/dashboard.js:44:12)
```

when I tried it with the original .remove() I got:

```
CastError: Cast to ObjectId failed for value "function (err){
   if (err){
     console.log(err)
   } else {
     response.redirect('/partners/dashboard')
   }
 }" at path "dashboardItems"
   at MongooseError.CastError 
```

**Comment by jshawl** [comment]
shouldn't it be `req.body.id` instead of just id? oh and sorry your input needs a name if you haven't given it one already:

``` html
<form method = "POST" action = '/partners/dashboard?_method=DELETE'>
   <input type='hidden' name="delete-this-dashboard" value='{{this}}' >
    <button type='submit'>Delete</button>
</form>
```

**Comment by dan-ator** [comment]
I added request.body.id and now I get error "TypeError: dbItems.update is not a function
   at dashboardController.destroy ".

**Comment by jshawl** [comment]
what is the output of `console.log(dbItems)`?

**Comment by dan-ator** [comment]
```
["566864ce82268baf2c71a90a","56688ef72545b00637aa1241","56688fe54a28744b3711e6e4","566892004a28744b3711e6e5","56689ac89eee0d2b3a1daf4c","56689bfd6a526c7f3a3b3878","56689dab000a53e93a82edaf","5668a06c95cfb1a73b1f0959","5668a638aa9620e63c4a6ca4","5668a63eaa9620e63c4a6ca5","5668a640aa9620e63c4a6ca6","5668a641aa9620e63c4a6ca7","5668b27e2b148f884038d8ff","566999474b8bceb547067208","566999484b8bceb547067209","566999db4b8bceb54706720a","566999df4b8bceb54706720b","5669ac13c803b7964c870e50"]
```

**Comment by jshawl** [comment]
can you link to your repo?

**Comment by dan-ator** [comment]
https://github.com/dan-ator/Project3/tree/add_user

**Comment by jshawl** [comment]
replace this line https://github.com/dan-ator/Project3/blob/272da41f3df82ed6f219b19c45a11799706f0489/controllers/dashboard.js#L43

with `DashboardItem.update( ...`

**Comment by jshawl** [comment]
update is a model method - http://mongoosejs.com/docs/2.7.x/docs/updating-documents.html

**Comment by dan-ator** [comment]
Now there is no error, but when I click the delete button it just refreshes the page basically and doesn't do any delete action.

**Comment by jshawl** [comment]
add a promise and check the return value?

``` js
DashboardItem.update( ... ).then(function(err, doc){
  console.log(err, doc)
})
```

**Comment by dan-ator** [comment]
```
DELETE /partners/dashboard?_method=DELETE 302 14.326 ms - 82
{ ok: 1, nModified: 0, n: 0 } undefined
GET /partners/dashboard 304 71.696 ms - -
```

**Comment by dan-ator** [comment]
that is what got console.logged

**Comment by jshawl** [comment]
so does it delete the dashboard item? if not please push your code

**Comment by dan-ator** [comment]
No, it doesn't delete it, still just refreshes page.  Ok I pushed.

**Comment by RobertAKARobin** [comment]
What's the status now, Dan?

**Comment by dan-ator** [comment]
https://media.giphy.com/media/1LmBFphV4XNSw/giphy.gif
![image](https://cloud.githubusercontent.com/assets/14224854/11726074/dd796afe-9f4a-11e5-82a3-8499955d50bd.png)

**Comment by dan-ator** [comment]
(confusion, hopelessness, bewilderment)

**Comment by dan-ator** [comment]
I tried a lot of different things, none of them work, same suite of error messages as above.

**Comment by nolds9** [comment]
@dan-ator Happy to talk about this at our group meeting this afternoon If you are still having trouble.

**Comment by dan-ator** [comment]
Still stuck on this...
