### ISSUE TITLE
Nodemon won't run on master branch

### ISSUE THREAD

**Issue by brittonwalker** [ga-wdi-exercises/project3#103]
This is what I'm getting when running nodemon. Usage: nodemon [nodemon options] [script.js] [args]

**Comment by jshawl** [comment]
what does package.json look like? what is the main server file name?

**Comment by brittonwalker** [comment]
Here is the package.json

{
  "name": "troll",
  "version": "1.0.0",
  "description": "Troll Quotes is a web application built on Express and MongoDB that provides users with a randomized assemblage containing a quote, author, and image that can be saved and shared on social media platforms.",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/brittonwalker/troll_quotes.git"
  },
  "author": "Britton Walker, Andrew Johnson, Armani Hall",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/brittonwalker/troll_quotes/issues"
  },
  "homepage": "https://github.com/brittonwalker/troll_quotes#readme",
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.14.1",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.0",
    "express": "^4.13.3",
    "express-session": "^1.12.1",
    "hbs": "^4.0.0",
    "html2canvas-proxy": "0.0.5",
    "mongoose": "^4.2.9",
    "method-override": "^2.3.5",
    "mongoose": "^4.2.9",
    "morgan": "^1.6.1",
    "passport": "^0.3.2",
    "passport-facebook": "^2.0.0",
    "passport-local": "^1.0.0",
    "passport-twitter": "^1.0.3",
    "path": "^0.12.7",
  },
  "devDependencies": {}
}

**Comment by brittonwalker** [comment]
I'm a little confused on the server file name, not sure exactly what I'm looking for.

**Comment by jshawl** [comment]
does `nodemon app.js` work?

**Comment by brittonwalker** [comment]
yes

**Comment by brittonwalker** [comment]
and on other branches i have, nodemon works

**Comment by brittonwalker** [comment]
it happened after a git pull

**Comment by jshawl** [comment]
maybe just run `nodemon app.js` for the time being? - your package.json looks right.

**Comment by jshawl** [comment]
which branch does nodemon work on?

**Comment by brittonwalker** [comment]
any branch that isn't master

**Comment by jshawl** [comment]
clonin! one sec

**Comment by jshawl** [comment]
remove this comma https://github.com/brittonwalker/troll_quotes/blob/f1103054acb8a1292b8bb59ac884f58f64df4be5/package.json#L37

**Comment by RobertAKARobin** [comment]
It's been half an hour, so I'm going to close this. Feel free to open a new one!
