### ISSUE TITLE
Hiding api_key in env.js

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project3#105]
We are trying one last time to hide our api key in the git ignored env.js file. The key is for our mapbox map and is entered along with the map in the index.hbs file in a script tag or in the script.js file. We have tried passing it to the view using handlebars but handlebars cant be used in a script tag. We have also tried requiring the env.js file in our script.js file but we are getting an undefined error "require is undefined".
<img width="507" alt="screen shot 2015-12-10 at 10 46 32 am" src="https://cloud.githubusercontent.com/assets/13842987/11720003/5ff1db76-9f2b-11e5-889b-87334cbf59ee.png">

**Comment by lewis2ba** [comment]
<img width="521" alt="screen shot 2015-12-10 at 10 47 35 am" src="https://cloud.githubusercontent.com/assets/13842987/11720019/709457b0-9f2b-11e5-8424-964ed52ce1bc.png">

**Comment by RobertAKARobin** [comment]
Can you make your API requests on the back-end?

You create a route that queries the mapbox API:

```
app.get("/mapboxapi", function(req, res){
  request({url: ""...
});
```

Then you use AJAX to query that route you created:

```
$.ajax({url: "./mapboxapi"...
```
