### ISSUE TITLE
Calling functions declared in a document.ready from elsewhere in the JS

### ISSUE THREAD

**Issue by mpopv** [ga-wdi-exercises/project3#106]
I'm having trouble integrating [Leaflet](http://leafletjs.com/) with our front-end OOJS model/view structure. The problem is that it seems that core JS that instantiates functions from the Leaflet module must be declared inside a document.ready because they reference the DOM.

A core chokepoint of our MVP is making API calls to Yelp from the Locations model that then append Leaflet map markers in the Locations view. We are unable to get past this because we are unable to use Leaflet functions in the Locations view. Leaflet functions return as undefined.

I have tried:
- Refactoring Leaflet functions out of document.ready; it breaks the map
- Same as above but linking scripts at the bottom of our index.hbs; it breaks the map
- Carefully stuffing the model/view structure into the document.ready; it breaks the model/view functions
- Attempting to hoist the function into the global scope with various variable declaration and window.myFunction hacks; they have all failed to allow the function to pass without returning undefined

Sort of at an impasse here and stumped as to what to try next.

**Comment by jshawl** [comment]
can you share your code and error?

**Comment by mpopv** [comment]
views/index.hbs

```
<!DOCTYPE html>
<html>
  <head>
    <title>Location Score</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.12.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.12.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
    <script src="leaflet.js"></script>
    <script src="js/views/location.js"></script>
    <script src="js/models/location.js"></script>
    <!-- <script src="script.js"></script> -->

  </head>
  <body>
    <div class="sidebar location">

    {{#if currentUser}}<p><a href="/logout">Log Out</a></p>
    {{else}}
      <p><a href="/signup">Sign Up</a> / <a href="/login">Log In</a></p>
       <p><button id="modal">Modal log in</button></p>
    {{/if}}

    <form class="search">
      <input class="searchLong" type="text" name ="long" placeholder="Longitude">
      <input class="searchLat" type="text" name ="lat" placeholder="Latitude">
      <input class="searchType" type="text" name ="type" placeholder="Category">
      <input id="passParams" type="submit" value="Get Locations">
    </form>

    <button class="test">Test this</button>

    </div>


    <div id="map">
    </div>
  </body>
</html>
```

public/js/views/location.js

```
console.log("/js/views/location.js is loaded");

var LocationView = function(location){
  this.location = location;
  this.$el = $(".location");

}

LocationView.prototype = {

  locationTemplate: function(location){
    var html = $("<div></div>");
    html.append("<h2>" + location.name + "</h2>");
    html.append("<p class='category'>Category: " + location.category + "</p>")
    html.append("<img class='business-photo' alt='Photograph of " + location.name + "' src='" + location.image_url + "'>");
    html.append("<p class='category'>Latitude: " + location.lat + "</p>")
    html.append("<p class='category'>Longitude: " + location.long + "</p>")
    return(html);
  },

  renderSidebarView: function(){
    var self = this;
    self.$el.html(self.locationTemplate(self.location).html());
  },

  clearSidebar: function(){
    this.$el.empty()
  },

  renderMarker: function(){
    // L.marker([location.lat, location.lng]).addTo(map);
    addMarker(location.lat, location.lng);
  }

}
```

public/js/models/location.js

```
console.log("/js/models/location.js is loaded");

var Location = function(info){
  this.lat = info.lat;
  this.long = info.long;
};

Location.prototype.loadLocation = function(){

  var self = this

  //  once we integrate bounds, will pass through a map bounds object, which will return this:
  //
  //  bounds.LatLngBounds
  //    _northEast: o.LatLng
  //        lat: 42.0468718
  //        lng: 2.7438793000000032
  //    _southWest: o.LatLng
  //        lat: 41.219172
  //        lng: 1.6023217
  //
  // now we have to parse these things into something

  var url = "/yelp"
  var request = $.getJSON(url).then(function(response){

    self.name = response.businesses[0].name
    self.category = response.businesses[0].categories[0][0]
    self.image_url = response.businesses[0].image_url
    self.lat = response.businesses[0].location.coordinate.latitude
    self.long = response.businesses[0].location.coordinate.longitude

    // --- Eventually: Loop over responses and return an array of hashes? -----
    //   for (var i = 0; i < response.businesses.length; i++) {
    //   var self = this
    //   ...whatever...
    // }

  }).fail(function(response){ console.log("Failed to load JSON."); });

  return request

}
```

public/js/leaflet.js
(i edited out the id and accessToken to be safe, though the accessToken is a publicly available one listed openly on the Leaflet website, so hopefully it shouldn't cause problems displaying directly on the front end)

```
console.log("leaflet.js is loaded");

$(document).ready(function(){

  var map = L.map('map').setView([38.900, -76.999], 13);
  L.tileLayer('https://api.tiles.mapbox.com/v4/rebeccae.ob42lgga/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicmViZWNjYWUiLCJhIjoiY2locW50eDhwMDRxaXRnbTQ4NGZqM3F4ZiJ9.bdeGen8FhiVQqFbI7Vz0lA', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
      id: "idishere",
      accessToken: "accesstokenishere"
  }).addTo(map);

  var popup = L.popup();

  printCircleMarker(38.91, -77.012);

  function drawLocation(lat, lng, color) {
    var newCircle = L.circle([lat, lng], 1000, {
      color: '#ffffff',
      fillColor: color,
      fillOpacity: 0.25,
    }).addTo(map);
  };

  function printCircleMarker(lat, lng) {
    var selectedColor = "#FF0000";
    drawLocation(lat, lng, selectedColor);
    L.marker([lat, lng]).addTo(map);
  };

  function saveLocation(e) {
    // post this to an API.
  }

  function onMapClick(e) {
    popup
        .setLatLng(e.latlng)
        .setContent("You clicked the map at " + e.latlng.toString())
        .openOn(map);
  }

});
```

EDIT: Sorry, forgot one important file:
script.js

```
console.log("script.js is loaded");

$(document).ready(function(){

     $('#modal').on('click', function(e){
        e.preventDefault();
   });

     $(".test").on("click", function(e){
       e.preventDefault();
       var location = new Location({lat: 34, long: 34})     // creates a new location object using our Location constructor
       location.loadLocation().then(function(){   // calls .loadLocation to make the API call

             var view = new LocationView(location) // in the promise we create a new view passing in the location object

             // Renders location info in the sidebar
         view.clearSidebar() // empties sidebar if one already exists
         view.renderSidebarView() // renders the new location

             //Adds location marker to the map
             view.renderMarker()

            })
        });



});
```

**Comment by mpopv** [comment]
The problem is that in `public/js/views/location.js` > `LocationView.prototype`, we are trying to add a function to print a marker via premade Leaflet functions:

```
  renderMarker: function(){
    // L.marker([location.lat, location.lng]).addTo(map);
    addMarker(location.lat, location.lng);
  }
```

`L.marker` is the actual Leaflet function, and `addMarker` was my attempt to somehow chain functions together to hoist `printCircleMarker` out of the `document.ready` in `leaflet.js`. (I think I may have removed the declaration for that function elsewhere, but it did not work when declared.)

Either approach returns that the Leaflet function is undefined.

Also, I'm not sure if this was unclear, but "/yelp" here refers to a view on our backend that calls the Yelp API via Yelp's module. For now it has hardcoded params.

**Comment by adambray** [comment]
Is this version pushed to a branch? I'd like to check it out to play with it.

**Comment by mpopv** [comment]
I believe the branch should be ajax-3 here

https://github.com/MarkhamShofner/Project-3-API/tree/ajax-3

**Comment by mpopv** [comment]
I just pushed a new commit with the most recent attempt functional--had to relink the script tag. Tried to hoist up one of our functions and you can see when you push the "Test this" button now it returns `Uncaught TypeError: Cannot read property 'lat' of null` in the console.

**Comment by mpopv** [comment]
Update: I just pushed a new commit that sort of... kind of... almost fixes the problem? Declared a var in the global scope and set it to equal a Leaflet function inside the document.ready, and the "Test this" button appears to be successfully appending a marker. But if I zoom the map afterward, it breaks the map--markers set to a fixed position and tiles stop loading.

![screen shot 2015-12-10 at 11 37 26 am](https://cloud.githubusercontent.com/assets/15032398/11721577/739f21d6-9f32-11e5-96cd-a95911747d34.png)

Here's an image of what happens. (I clicked the "Test this" button after the console.logs but before the error). The (left) marker appears to be appended, and yet I still get `Uncaught TypeError: Cannot read property 'lat' of null` and the map breaks afterward.

**Comment by adambray** [comment]
That's weird. My first thought is that you're passing an object to leaflet that later goes out of scope? I'd double check how you're using the leaflet API

**Comment by adambray** [comment]
I can take a look in a few minutes if you're still stuck

**Comment by mpopv** [comment]
Okay. I just refactored (in the latest commit to ajax-3) to stuff the contents of script.js, leaflet.js, the model, and the view into one file (soup.js) so I could put everything in the document.ready and I'm still getting `Uncaught TypeError: Cannot read property 'lat' of null`. So I'm thinking that scope might not be the culprit?

**Comment by adambray** [comment]
@mpopv can you slack me (privately) the contents of your env.js? I need it to get your app running.

**Comment by jshawl** [comment]
the only place i see `.lat` is here - https://github.com/MarkhamShofner/Project-3-API/blob/66c539aa2c09b855ede90ec37a719024bdf35535/public/js/models/location.js#L3

**Comment by adambray** [comment]
@mpopv look carefully at https://github.com/MarkhamShofner/Project-3-API/blob/ajax-3/public/soup.js#L90
(line 90)

Think about how you reference the `location` object associated with the view... you can't just say `location.lat`... there's something missing before it.

(Also, you have a typo for the second arg, it should be `.long`, not `.lng`.)

**Comment by mpopv** [comment]
Adam--thanks! Added `var self = this` and `this.` to the front of the params and that solved the problem.

Feel free to close.
