### ISSUE TITLE
html scroll link not working

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project3#109]
When a metro line color is clicked within our apps drop-down menu, we want the page to scroll down to the div that contains the metro lin's issue that's produced from the json at the bottom of our page (which is out of view). 

I tried a very simple solution to this problem by creating a link on the text in our menu that has the id of the div I wrapped around the metro station information. Short story: it doesn't work. I'm wonder if this function works differently on a single-page app.

Here's the code:

```
<div class="choosestation">
        <select class="selectpicker" data-style="btn-info">
          <option data-hidden="true">Choose Station</option>
          <option><a href="#scroll">Red</a></option>
          <option value="Blue"> Blue</option>
          <option value="Orange">Orange</option>
          <option value="Green">Green</option>
          <option value="Yellow">Yellow</option>
          <option value="Silver">Silver</option>
        </select>
      </div>
```

```
<div id="scroll">
      <div class="row">

        <hr>
        <div class="stations">
            {{{body}}}


        </div>


      <div class="row">
        <div class="commentdiv">

        </div>
      </div>
    </div>
  </div>
```

You'll see I only added the link to the "red" button. That was just to run a test.

**Comment by clarktsc39** [comment]
I'd like to use this code:

```
function top() {
    document.getElementById( 'top' ).scrollIntoView();    
};

function bottom() {
    document.getElementById( 'bottom' ).scrollIntoView();
    window.setTimeout( function () { top(); }, 2000 );
};

bottom();
```

**Comment by jshawl** [comment]
What do you mean "it doesnt work"? any errors in the console?

**Comment by clarktsc39** [comment]
According to the console there's no error. The app is loading fine, too.

**Comment by amaseda** [comment]
Instead of placing a link inside of an `<option>` tag, try creating an event listener for the `change` event. So it would look something like this…

``` js
$( “.chooseStation” ).on( “change”, function(){
    // Replace this content with whatever you want to happen when a new value is selected with the dropdown menu.
    console.log( this.value );
} );
```

**Comment by jshawl** [comment]
also check out this demo - http://codepen.io/jshawl/pen/jWPKvZ

**Comment by clarktsc39** [comment]
worked
