### ISSUE TITLE
Json rendering

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/project3#11]
Index.js

```
app.get("/", function(req, res){
  res.render("index.html");
});

app.use("*.json",function (req, res, next) {
  req.headers.accept = 'application/json';
  next();
});

app.use("/stations/?:format?", require("./controllers/stationsController"));
```

StationsController

```
router.get("/", function(req, res){
  StationModel.find({}).then(function(stations){
    res.json(stations);
  });
});
```

Why is this router.get showing JSON on /stations and not on the route page? How do we get JSON to stop showing on /station and who on /station.json? We can't get our html to show on /stations. If we change app.get("/") to ("/stations") we get an error stating "can't find html module"...

**Comment by RobertAKARobin** [comment]
What's the first `?` in `?:format?` doing?
