### ISSUE TITLE
delete action

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/project3#110]
Hi, I'm trying to add in delete functionality on comments, and I'm struggling to find why it doesn't work, especially given that I'm not receiving any errors..

On my views file i have a simple click action:

```
$('.deleteComment').on("click", function() {
      console.log("clicked?");
      console.log(self);
      console.log(self.comments);
      self.comments.destroy();
    });
```

where self.comments returns a comment object

my .destroy() is as follows:

```
destroy: function() {
    var comment = this
    console.log("DESTROY");
    var url = "/"+comment.id;
    console.log(url);
    var request = $.ajax( {url: url, method: "delete"} );
    console.log(request);
    return request;
  }
```

and finally my route is:

```
router.delete("/:id", function(req, res){
  CommentModel.findByIdAndRemove(req.params._id).then(function(){
    console.log(req.params.id);
    console.log("running?");
    res.json({success: true});
  });
});
```

As you can see, I've console logged just about everywhere imaginable, and it looks like everything is being defined properly. I'm sort of assuming I've just missed a step, but I'm not clear what it could be. Thanks for the help!

**Comment by joe-gz** [comment]
to go a little further, when i click the delete button, nothing actually happens other than the console logs. when i console log the request in my destroy method, i see the the router returns `({success: true})` as well, so everything is hitting as far as i can tell

**Comment by jshawl** [comment]
do you see console.log("DESTROY"); ??

**Comment by joe-gz** [comment]
yep! all of my console logs return what i would expect i think

**Comment by jshawl** [comment]
ok this lines of code:

``` js
CommentModel.findByIdAndRemove(req.params._id).then(function(){
    console.log(req.params.id);
    console.log("running?");
    res.json({success: true});
  });
```

can you change to:

``` js
CommentModel.findByIdAndRemove(req.params._id).then(function(err, doc){
   console.log(err,doc)
    console.log(req.params.id);
    console.log("running?");
    res.json({success: true});
  });
```

**Comment by joe-gz** [comment]
Thanks Jesse, the err,doc log returns null and undefined

**Comment by RobertAKARobin** [comment]
Why do you have both `req.params._id` and `req.params.id`? Are they returning the correct ID?

**Comment by joe-gz** [comment]
Thanks Robin, oddly enough the "_id" was a typo, and `req.params.id` in the console log returns the right comment id.  I changed the "_id", but that didn't change anything with regards to the outcome

**Comment by joe-gz** [comment]
Hey @RobertAKARobin , so I don't waste your time, I'm taking another approach to this and seeing if it works. I'm going to close this issue until I run into too many errors with my new approach and will open a new one at that point. Or, ideally, I just get it to work and we'll be all good! Ha
