### ISSUE TITLE
Attaching an event listener to async generated content

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project3#111]
```
       ________              
   _jgN########Ngg_          
 _N##N@@""  ""9NN##Np_       
d###P            N####p      
"^^"              T####      
                  d###P      
               _g###@F       
            _gN##@P          
          gN###F"            
         d###F               
        0###F     Halp!  
        0###F   Oh god! Please!
        0###F                
        "NN@'                

         ___                 
        q###r                
         ""      
```

Same Issue Day 2:
I'm trying to attach an event listener to content that is being generated asynchronously and it's not going so hot.

We've got a page with some filters at the top and user cards at the bottom. We want the filters to filter which cards are shown. The cards are generated with 

```
users.forEach( function(user) {
  var renUsers = new UserView(user).renderUsers(user);
});
```

The event listener works when it's in `js/views/userView.js`

```
var UserView = function(user) {
  this.$el blah blah blah...

  $('#filterLocation').change(function() {
    // FILTER STUFF (this works, omitted for brevity)
  }
};
```

The problem with that is it creates a new even listener `forEach` user.
we tried breaking out the event listener into a `filterView` file but it doesn't work, presumably because it's attached to content that hasn't finished being created

The question is how to either get it to generate only once / make it work in this other view. Callbacks? Promises? Crushed Dreams?

**Comment by jshawl** [comment]
what if you use `$.one()`? http://api.jquery.com/one/

**Comment by mattscilipoti** [comment]
Or create an event handler on a static ancestor: http://stackoverflow.com/a/1207393/232247

**Comment by tylercrosse** [comment]
I'll check these out thanks! Hopefully the melodrama was funny, also the 'waiting on student response' tag is cool!

**Comment by tylercrosse** [comment]
Still not really doing what I need, but we are just going to say it's good enough. Thanks again!
