### ISSUE TITLE
jQuery elements losing their jQuery-ness. $help is needed.

### ISSUE THREAD

**Issue by Briik** [ga-wdi-exercises/project3#112]
``` javascript
var $contender = $(this.parentElement)[0];
```

The above is my variable.
It works.
console.log($contender) returns the correct element. 
I need it so that I can select the parent element of div that is clickable and then heavily modify the parent element.
ISSUE:  Once I define it in my code about 30% of my jQuery variable things ($variable) stop working.
They stop working all over my code, in any function that is called in sequence after this variable is defined.  
Question: Dafuq?

**Comment by jshawl** [comment]
use `.eq(0)` instead of `[0]`

``` js
var $contender = $(this.parentElement).eq(0);

```

https://api.jquery.com/eq/

**Comment by Briik** [comment]
Also, $contender does not have jQueryness after the first time it is used.
First time it is used:

``` javascript
console.log($contender);
        var cityName = $contender.firstElementChild.innerText.toString();
```

**Comment by Briik** [comment]
Thank you!
