### ISSUE TITLE
JSON Advice

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#115]
Looking for advice using Handlebars & JSON. I am unable to route the JSON object to the site. Also, I would like a little guidance on how to move forward with my two file minimalist approach.

<img width="542" alt="screen shot 2015-12-10 at 1 36 32 pm" src="https://cloud.githubusercontent.com/assets/13697957/11725111/ee14162a-9f45-11e5-8a87-92e3dc4bf22d.png">

**Comment by amaseda** [comment]
For `dataType` you should just have `json`. This field is for indicating what type of data you are, in this case, `POST`ing.

`data` should contain the JSON representation of the data you are `POST`ing to your database. What you have currently — `$(“#formID”).serialize()` — is just a serialized version of an entire jQuery object.

**Comment by ghost** [comment]
Thanks
