### ISSUE TITLE
env.js not ignored by gitignore

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/project3#116]
I have env.js in my gitignore file and env.js is even dark as if it's being ignored, but it still got pushed to github :( https://github.com/MarkhamShofner/Project-3-API/commit/ec064860d540f499462d9ce05f03d00735627e4a

**Comment by RobertAKARobin** [comment]
You have to `git rm --cached env.js`.

**Comment by jacohen10** [comment]
thanks. any idea why that would happen?

**Comment by RobertAKARobin** [comment]
Yeah! If you add and commit something once, then it stays in Git -- Git just assumes that you didn't make any changes to it, rather than that you don't actually want it in your repo at all anymore. `git rm --cached` is the exact opposite of `git add`.
