### ISSUE TITLE
Delete function not working

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project3#117]
We are trying to implement a delete function for our perspective model. We added a delete button to a marker on mapbox. We are getting a mapbox error but it it because our delete button is actually creating a new perspective with no attributes.

<img width="403" alt="screen shot 2015-12-10 at 2 42 11 pm" src="https://cloud.githubusercontent.com/assets/13842987/11726360/3f651460-9f4c-11e5-92b8-95d18a706724.png">

The form:
<img width="800" alt="screen shot 2015-12-10 at 2 39 19 pm" src="https://cloud.githubusercontent.com/assets/13842987/11726265/d905ed52-9f4b-11e5-92a3-0fb7561b56f7.png">

We have method override in our app.js:

```
var methodOverride = require('method-override')
app.use(methodOverride('_method'));
```

Not quite there yet but our route:

```
app.delete("/perspectives/:id", perspectivesController.delete)
```

and controller:
<img width="449" alt="screen shot 2015-12-10 at 2 43 38 pm" src="https://cloud.githubusercontent.com/assets/13842987/11726394/737fdc58-9f4c-11e5-9289-fe1999d697b5.png">

**Comment by andrewsunglaekim** [comment]
Can you list out all the routes/paths that your app is listening for?

**Comment by lewis2ba** [comment]
<img width="664" alt="screen shot 2015-12-10 at 2 56 09 pm" src="https://cloud.githubusercontent.com/assets/13842987/11726772/3529095a-9f4e-11e5-8dbb-fe42ccc13cb2.png">

**Comment by RobertAKARobin** [comment]
That probably means you're not actually using the `delete` HTTP method; you're using `post`. Do you have `method-override` in your app?

**Comment by lewis2ba** [comment]
We have these two lines in our app.js

```
var methodOverride = require('method-override')
app.use(methodOverride('_method'));
```

Do we need it anywhere else?

**Comment by RobertAKARobin** [comment]
Instead of putting `?_method=delete` in your URL, try adding a hidden `input` field, Rails-style:

``` html
<input type="hidden" name="_method" value="delete" />
```

**Comment by lewis2ba** [comment]
Still getting the same issue, does this look right?
<img width="885" alt="screen shot 2015-12-10 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/13842987/11727306/28142cf6-9f51-11e5-8f26-2fd5378058c6.png">

**Comment by RobertAKARobin** [comment]
Can you push your code to GH and include the link here?

**Comment by lewis2ba** [comment]
https://github.com/lewis2ba/rembr/tree/delete-perspective

**Comment by RobertAKARobin** [comment]
After much poking at Mapbox on my end, I think part of the problem here is with trying to put too much HTML in these markers. They're not really supposed to contain forms and stuff.

**Comment by lewis2ba** [comment]
Just spoke with Nick and we agree but we got it working with the create functionality, it just doesnt seem to recognize the action in our delete form.
Here is our code snippet for our delete form:

```
"<form action='/perspectives/"+perspective.id+"' method='post'><input type='hidden' name='_method' value='delete'/><input class='btn btn-default' id='link-color' type='submit' name='delete' value='Delete'></form>"
```

Here is a screenshot of the html when we inspect the element:
<img width="380" alt="screen shot 2015-12-10 at 4 01 51 pm" src="https://cloud.githubusercontent.com/assets/13842987/11728365/70f1349a-9f57-11e5-8828-ef7957873365.png">

**Comment by RobertAKARobin** [comment]
The `form` no longer has an action.

**Comment by RobertAKARobin** [comment]
Welp, I got it to sort-of work with this:

``` js
Perspective.all.forEach(function(perspective){
      L.mapbox.featureLayer({
        // this feature is in the GeoJSON format: see geojson.org for the full specification
        type: 'Feature',
        geometry: {
          type: 'Point',
          // coordinates here are in longitude, latitude order because x, y is the standard for GeoJSON and many formats
          coordinates: [
            perspective.longitude,
            perspective.latitude
          ]
        },
        properties: {
          title: perspective.title + " "+ perspective.user,
          description: perspective.text + "<button class='deletePerspective' title=" + perspective.id + ">click</button>",
          // one can customize markers by adding simplestyle properties
          // https://www.mapbox.com/guides/an-open-platform/#simplestyle
          'marker-size': 'medium',
          'marker-color': '#FFA500',
          'marker-symbol': 'camera'
        }
      }).addTo(map);
    });
  });

  $("#map").on("click", ".deletePerspective", function(e){
    var perspectiveId = this.title;
    $.ajax({
      url: "./perspectives/" + perspectiveId,
      method: "DELETE"
    }).then(function(response){
      console.dir(response)
    });
  });
```

But now the server fails with a "currentUser not defined" error.

**Comment by lewis2ba** [comment]
Does it say something about "local" when trying to delete? I think you have to sign up to delete them

**Comment by RobertAKARobin** [comment]
How's it hanging?

**Comment by lewis2ba** [comment]
It looks like it is deleting correctly, but now we have a 404 error

```
DELETE http://localhost:7812/perspectives 404 (Not Found)
```

This happened when we were using postman to test.

**Comment by lewis2ba** [comment]
```
delete: function(req,res){
    console.log("inside delete action")
    //find the record given an id
    console.log(req.params.id)
    perspective.findOne({_id:req.params.id},function(err,doc){
      if(!err){
          doc.remove().then(function(){
          console.log("no error, redirecting")
          res.redirect("/")
        })
      }
      else{
        console.log(err)
      }
    })
    },
```

**Comment by RobertAKARobin** [comment]
Shouldn't `http://localhost:7812/perspectives` have an ID in it?

**Comment by lewis2ba** [comment]
From my terminal:

```
DELETE /perspectives/5669fbb33b55047e5156a3b8 302 5.211 ms - 23
DELETE / 404 4.106 ms - 16
```

It deletes it but doesnt redirect correctly? Its trying to delete it again? Not sure whats going on here

**Comment by lewis2ba** [comment]
```
GET / 304 53.648 ms - -
GET /css/bootstrap.min.css 304 11.517 ms - -
GET /css/application.css 304 2.321 ms - -
GET /js/script.js 304 2.047 ms - -
GET /js/models/perspective.js 304 0.460 ms - -
GET /perspectives 200 16.499 ms - 3962
POST /signup 302 107.936 ms - 46
GET / 200 13.604 ms - 3847
GET /css/bootstrap.min.css 304 7.937 ms - -
GET /css/application.css 304 3.772 ms - -
GET /js/script.js 304 1.816 ms - -
GET /js/models/perspective.js 304 1.367 ms - -
GET /perspectives 304 9.256 ms - -
Saved
Saved
POST / 302 19.513 ms - 46
GET / 200 16.370 ms - 3847
GET /css/bootstrap.min.css 304 2.761 ms - -
GET /css/application.css 304 1.316 ms - -
GET /js/script.js 304 6.566 ms - -
GET /js/models/perspective.js 304 5.775 ms - -
GET /perspectives 200 6.895 ms - 4168
inside delete action
5669fbb33b55047e5156a3b8
no error, redirecting
DELETE /perspectives/5669fbb33b55047e5156a3b8 302 5.211 ms - 23
DELETE / 404 4.106 ms - 16
```

The whole thing

**Comment by RobertAKARobin** [comment]
Don't redirect on delete. You're making an AJAX request, and you can't really redirect an AJAX request. Instead, just send back some data with `res.json({success: true})` or something.

**Comment by lewis2ba** [comment]
Problem is, we need the refresh to have the marker disappear

**Comment by RobertAKARobin** [comment]
Make the refresh happen with front-end JS, not back-end.

**Comment by lewis2ba** [comment]
How would I do that?

**Comment by lewis2ba** [comment]
We dont have much front end, and I'm very shaky on it.

**Comment by RobertAKARobin** [comment]
``` js

  $("#map").on("click", ".deletePerspective", function(e){
    var perspectiveId = this.title;
    $.ajax({
      url: "./perspectives/" + perspectiveId,
      method: "DELETE"
    }).then(function(response){
// Refresh function goes here
    });
  });
```

Use your Google-fu to find using Javascript to refresh your browser!

**Comment by lewis2ba** [comment]
location.reload()

Thanks!
