### ISSUE TITLE
Killing Mongod

### ISSUE THREAD

**Issue by qadriyyah119** [ga-wdi-exercises/project3#12]
Hi,

We didn't exit Mongod properly and now we're having issues starting over in a new terminal. 

We're getting the following error:

Listen (): bind() failed errno:48 Address already in use for socket.

**Comment by RobertAKARobin** [comment]
Alright, try this:

```
$ px aux | grep mongod
```

You'll probably get something like:

```
$ ps aux | grep mongod
robertthomas    13858   0.5  2.0  3846836 164680 s003  S+    4:24PM   0:00.35 mongod
robertthomas    13861   0.0  0.0  2434836    712 s001  R+    4:24PM   0:00.00 grep mongod
```

Take note of the **first** number in there -- 13858 in this case. Then, run:

```
$ kill 13858
```

That should be it!

**Comment by qadriyyah119** [comment]
Thank you. It worked!
