### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#120]
Trying to resolve conflicts in a pull request and running into trouble checking out the branch via command line.

I am trying 
- git fetch origin
- git checkout -b views-branch origin/views-branch

so that I can compare differences in text editor.

The error message is 

"fatal: Cannot update paths and switch to branch 'teddys-views-branch' at the same time.
Did you intend to checkout 'origin/views-branch' which can not be resolved as commit?"

Should I clone git://github.com/onesick/campaign-finance.git prior to fetching and checking out?

Our repo is https://github.com/onesick/campaign-finance, and the pull request I'm trying to resolve is 'Teddy's latest. . . ."

**Comment by RobertAKARobin** [comment]
Try just `git checkout views-branch`.

**Comment by RobertAKARobin** [comment]
Do you have an existing `views-branch` in your local repo?

If not, try just `git checkout views-branch`.

If you do, either delete it, rename it, or pull down `views-branch` under a different name:

`git checkout -b some-other-name origin/views-branch`

**Comment by ghost** [comment]
views-branch is on the project repo but i don't have that branch.  that branch is teddy's work that i'm trying to merge into the project master branch.  is that a bad approach?

![screen shot 2015-12-10 at 5 13 27 pm](https://cloud.githubusercontent.com/assets/13954451/11730202/8866ff2e-9f61-11e5-8eec-97bcbfa4c3f9.png)

**Comment by RobertAKARobin** [comment]
Nope! That's a great approach.

**Comment by ghost** [comment]
okay, good to know.  still unsure how to implement that approach.  the github instructions i'm following are pushing me into a wall of stop.

way off or path of truth (or some muddled mix of both?):
1.  i need the project master on my machine?  git pull upstream master?  that will overwrite the master i currently have locally?
2.  i need teddy's views-branch on my machine?  git pull upstream views-branch?
3.  then instead of a pull request, i should merge?  in master, git merge views-branch master?
4.  then git push origin master.
5.  git push upstream master.

**Comment by RobertAKARobin** [comment]
Try it!

**Comment by ghost** [comment]
breaking things at a late hour.  oh no!

so 

```<<<<<<< HEAD
var bodyParser = require('body-parser');
var passport = require("passport");
var flash = require("connect-flash");
var hbs = require("hbs");
var cookieParser = require('cookie-parser');
var session = require('express-session');
var mongoose = require("mongoose");

mongoose.connect('mongodb://localhost/local-authentication-with-passport');

var candidatesController = require("./controllers/candidatesController");

# var usersController = require("./controllers/usersController");

<<<<<<< HEAD
var request=require('request');
var mongoose=require('mongoose');
var passport=require('passport');
var env=require('./env');

// establish database connection to mongoDB
mongoose.connect('mongodb://localhost/project3');

> > > > > > > 282e6dcd0c7a2ffead376acd8a397ec23f5eeea4```

becomes (see db comment in code below for a new specific question)

```
var bodyParser = require('body-parser');
var passport = require("passport");
var flash = require("connect-flash");
var hbs = require("hbs");
var cookieParser = require('cookie-parser');
var session = require('express-session');
var mongoose = require("mongoose");
var request=require('request');
var passport=require('passport');
var env=require('./env');

var candidatesController = require("./controllers/candidatesController");
var usersController = require("./controllers/usersController");

// establish database connection to mongoDB
// but this is a big problem isn't it, since i we have two dbs?  unsure how to resolve
mongoose.connect('mongodb://localhost/project3');
mongoose.connect('mongodb://localhost/local-authentication-with-passport');
```

**Comment by ghost** [comment]
think i am on my way to breaking the entire project.

biggest concern now is that i see two different db names - one i created for passport, one won created for the data.  

otherwise, i think i see how to resolve most of the other conflicts in my index.js.

**Comment by RobertAKARobin** [comment]
Relax, Thom. Merge conflicts are no big deal. Just remove any lines that you don't want. Presumably, that includes lines like `<<<<<HEAD` and `>>>>>>> 282e6dcd0c7`.

**Comment by ghost** [comment]
Ok
