### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by MohamedGood** [ga-wdi-exercises/project3#124]
Chauncey and I are having a difficult time trying to get the signup, login and logout functionality to cooperate within our app.

**Comment by RobertAKARobin** [comment]
Cool! Are you getting an error?

**Comment by MohamedGood** [comment]
No error the signup page refreshes when you click the submit button

**Comment by RobertAKARobin** [comment]
OK, what do you expect to happen? Should something show up?

**Comment by MohamedGood** [comment]
I expect the page to save user the data thats signed in within the data base.

**Comment by RobertAKARobin** [comment]
I just saw Erica's message. Could you work on adding seed data before starting on authentication?

**Comment by adambray** [comment]
@MohamedGood As I mentioned yesterday, the problem is definitely in your app.js. I agree with Robin that seed data should come first, but if you finish that and come back to authentication, you should try to make your app.js look as much like our example app as possible.

**Comment by MohamedGood** [comment]
Ok were moving from the authentication issue. Now we are trying to deploy on Heroku. I signed up for MongoLab and im a still seeing a Application Error upon deployment

**Comment by RobertAKARobin** [comment]
Do you have a seeds file set up? This will be easier to figure out if you do.

**Comment by MohamedGood** [comment]
yes

**Comment by ebirving** [comment]
I've figured it out! Let me see if I can summarize it in writing. If not, I'll come find you at 10:45...hang tight...

**Comment by ebirving** [comment]
And by "it", I mean the auth issue

**Comment by ebirving** [comment]
Ok, step one:
Change your `app.get` commands in `app.js` to use `usersController` instead of anonymous functions (like your `app.post` commands). Also add `app.get('/logout', usersController.getLogout):` while you're at it.

**Comment by ebirving** [comment]
Step Two:
In `passport.js`, replace both instances of `done` with `callback`.

Step Three:
Delete `routes.js`.

**Comment by ebirving** [comment]
Step Four:
In `controllers/users.js`, add `var User = require("../models/user");` at the very top. Delete everything that has to do with `secret`.

Step Five: 
In `models/user.js`, add `require("../db/schema")` at the very top. Remove the `bcrypt` line. And both of the `User.methods` assignments. Replace `module.exports = mongoose.model('User', User);` with `module.exports=User;`

**Comment by ebirving** [comment]
Step Six:
In `layout.hbs`, add a "Log out" link to the navbar. While you're there, move the Bootstrap CSS stylesheet to just under `<title>`. Now your custom styles will take effect.

Step Seven:
In `index.hbs`, add 

```
{{#if}}
  <p>You are logged in as {{currentUser.local.email}}</p>
{{/if}}
```

above the map canvas.

**Comment by ebirving** [comment]
@MohamedGood ^^

**Comment by ebirving** [comment]
Step Eight: Keep me posted.

**Comment by MohamedGood** [comment]
Thanks alot Erica we ran thru the steps everything was clear except for Step 5 and 7
