### ISSUE TITLE
Passport issue

### ISSUE THREAD

**Issue by ddayporter** [ga-wdi-exercises/project3#125]
Hi there,

I'm having a hard time with passport. Trying to do local and twitter login, followed the passport lesson plan pretty closely but have possibly over-tweaked it to try to hack it into our single page app. What I'm now trying to accomplish is having backend views render the login activities and then go back to our single page app. When I try to do a Twitter login, it hangs for a long time and then the browser says "No Data Received". When I try to sign up with the local strategy, my app crashes and I get this error:

```
/Users/rachel2/wdi/projects/tldr-history/config/passport.js:63
        newUser.local.password = newUser.encrypt(password);
                                         ^

TypeError: newUser.encrypt is not a function
```

I have bcrypt required in my app, not sure where to look next.. Any ideas?

PS I read through Mo's issue and it looks like you guys were recommending doing user seeds before implementing passport? I didn't realize we needed user seeds - would that help my issue?

**Comment by RobertAKARobin** [comment]
You don't _need_ seeds, I just like them because they're an easy way to test whether my database and schema are working, and they're helpful for debugging when trying to deploy. It's also nice for us to have some sample data to play around with when we clone down your project. Not necessary; just nice to have.

Try doing a `console.log(newUser)` there. What's the output?

**Comment by ddayporter** [comment]
I see - I'll work on adding some. 

Here is the output:

```
{ local: {}, twitter: {}, _id: 566aee0e4bbc7ca8333a845c }
```

So it's not pulling anything in from my form, right?

**Comment by ddayporter** [comment]
wait, I put the console log in the wrong spot.. my first console log was before it actually passed in the data. d'oh. I tried it right after it adds the email and this is what I got:

```
{ local: { email: 'rachel@email.com' },
  twitter: {},
  _id: 566aeec7fbf38db43374ab88 }
```

I then tried putting it after the password.encrypt line and the app crashed before logging any output

**Comment by RobertAKARobin** [comment]
Progress! Could you push your code up to Github so I can take a look at it?

**Comment by ddayporter** [comment]
sure! I just pushed it up to the branch rachel-passport: https://github.com/ddayporter/TLDR-History/tree/rachel-passport

**Comment by ddayporter** [comment]
aaand just pushed again to include a working user seed

**Comment by RobertAKARobin** [comment]
First things first: don't include `node_modules` in your repo!

Run `git rm -r --cached node_modules`. Then add and commit. You'll see a BUNCH of "delete" messages, but don't worry -- it's not deleting anything from your computer, it's just removing it from your repo.

**Comment by ddayporter** [comment]
OH shoot. I think at some point we pushed it when it wasn't in gitignore, and forgot to figure out  how to get it out of the repo after we put it back in the gitignore. should I run this from the master branch or is it ok to run this on my branch?

**Comment by RobertAKARobin** [comment]
You can run it in either, but I'd just do it in yours for now.

It looks like the problem is in your `models/user.js` file. You're trying to use an `.encrypt` method attached to the User model, but you haven't defined `encrypt` anywhere in that file.

**Comment by ddayporter** [comment]
ok - is that requiring bcrypt or something else? I had it defined in the Schema because that's where the user methods were defined but I can't remember now why I moved that stuff over to the schema rather than the model as it is in the lesson plan.. should my user model look basically like this? 

```
var mongoose = require('mongoose');
var bcrypt   = require('bcrypt-nodejs');

var User = mongoose.Schema({
  local : {
    email        : String,
    password     : String,
  },
  twitter : {
    id: String,
    token: String,
    username: String,
    displayName: String
  }
});

User.methods.validPassword = function(password) {
  return bcrypt.compareSync(password, this.local.password);
};

User.methods.encrypt = function(password) {
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

module.exports = mongoose.model('User', User);
```

**Comment by RobertAKARobin** [comment]
That looks good to me, but I'd just go back to [this](https://github.com/ga-dc/express-passport-local-authentication/tree/twitter-solution) to make sure.

**Comment by ddayporter** [comment]
I actually just pulled that directly from the twitter solution over there :) I guess I'm still confused why all this needs to be in the model rather than the schema - there's no schema on the twitter solution branch at all, but with our other models we have them defined in the schema and just require the schema in the model files, and that seemed to work for those. are we just not requiring bcrypt in the right places?

**Comment by ddayporter** [comment]
is it ok if I come over and chat with you?

**Comment by RobertAKARobin** [comment]
It doesn't need to. Node has a super-flexible file structure. You can name your files and folders anything you want, except for `public`. We just went two different routes between those repos.

**Comment by RobertAKARobin** [comment]
You should have `bcrypt` required anywhere you have `bcrypt.something()` written. The code you have above looks great -- give it a shot first. Then, if still no dice, come on over.

**Comment by ddayporter** [comment]
I updated the model file and my app crashed with this error:

```
/Users/rachel2/wdi/projects/tldr-history/node_modules/mongoose/lib/index.js:346
      throw new mongoose.Error.OverwriteModelError(name);
      ^
OverwriteModelError: Cannot overwrite `User` model once compiled.
```

I haven't updated the schema file yet, is that what's causing this? how should I be referencing the user model in the schema?

**Comment by ddayporter** [comment]
thanks Robin!

**Comment by RobertAKARobin** [comment]
Yesss, excellent use of giphy
