### ISSUE TITLE
css bootstrap navbar

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project3#126]
So we have our navbar set to up modals for /login /signup and /about which works and looks great...
<img width="1032" alt="screen shot 2015-12-11 at 10 34 26 am" src="https://cloud.githubusercontent.com/assets/13460389/11747776/1a3bc09c-9ff3-11e5-8c57-aa954f50d345.png">
<img width="1048" alt="screen shot 2015-12-11 at 10 34 42 am" src="https://cloud.githubusercontent.com/assets/13460389/11747777/1bb99660-9ff3-11e5-8ffd-a4b047d5d375.png">

but only in desktop view. 
When the window shrinks to mobile view the nav automatically turns into a dropdown and falls behind our map : (

<img width="411" alt="screen shot 2015-12-11 at 10 34 59 am" src="https://cloud.githubusercontent.com/assets/13460389/11747824/565facd2-9ff3-11e5-838f-ed9cefb1e01c.png">

**Comment by RobertAKARobin** [comment]
That's a result of whatever CSS framework you're using. If a cursory Google doesn't turn up a bunch of people who had the same problem and found a solution, then you'll need to find one yourself. That probably involves a lot of inspecting elements and playing with z-indexes in your CSS.

Or maybe you can turn off the responsiveness so you don't get that dropdown menu? Again, how to do that will depend on the framework you're using. You'll need to consult their documentation.
