### ISSUE TITLE
Event listener target not working properly

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#128]
I am having trouble targeting an event listener.  I want to target the event listener so I can run a prevent default and start checking out console.logs to figure out why I the create new exercise function is not working.

The HTML for the area I am targeting is

``` html
<div class="workout-attachment">
   <form style="margin-top: 10px;" role="form>
   <div class="form-group">
   <div class="form-group">
   <div class="form-group">
   <div class="form-group">
   <div class="form-group">
   <button type="submit class="btn btn-default addExercise"> Add Exervise </button>
</form
```

I am trying to select the submit button and have tried

``` js
var newExerciseBar = $(".updateExercise");
var createExercise = $(".workout-attachment");
  createExercise.on("click", ".updateExercise", function(evt){
    evt.preventDefault();
```

I have done this because throughout this project I have had to select child elements this way to add event listeners.  I have also tried the traditional way of 

``` js
createExercise.on("click", newExerciseBar, function(evt){
   evt.preventDefault();
```

The issue I have is on line 24 of the exerciseview file.  The link to my repo is

https://github.com/murgia/SwoleMate

Thank you

**Comment by murgia** [comment]
Let me re-type that HTML.  I am not sure why it did not save.

**Comment by murgia** [comment]
div class = workout-attachment"
div class - form-group
div class - form-group
div class - form-group
div class - form-group
div class - form-group
button type=submit class=btn btn-default addExercise
</form>

**Comment by RobertAKARobin** [comment]
It's because Github's trying to render the HTML -- not display the code. Fix it by putting the three backtics on either end.

**Comment by murgia** [comment]
`$("<form style='margin-top: 10px;' role='form'>\
    <div class='form-group'>\
    <label for='exercise-name'>Exercise Name:</label>\
    <input class='form-control' name='name' value=''>\
    </div>\
    <div class='form-group'>\
    <label for='exercise-description'>Exercise Description: </label>\
    <textarea class='form-control' rows='5' name='description'></textarea>\
    </div>\
    <div class='form-group'>\
    <label for='exercise-video_url'>Exercise Video Demo: </label>\
    <input class='form-control' name='video_url' value=''>\
    </div>\
    <div class='form-group'>\
    <label for='sets'>Sets </label>\
    <input class='form-control' name='sets' value=''>\
    </div>\
    <div class='form-group'>\
    <label for='reps'>Reps: </label>\
    <input class='form-control' name='reps' value=''>\
    </div>\
    <button type='submit' class='btn btn-default addExercise'>Add Exercise</button>\
    </form>");`
