### ISSUE TITLE
requiring d3

### ISSUE THREAD

**Issue by clarissastark** [ga-wdi-exercises/project3#135]
We're trying to require d3 to draw a map for our app, and can't find a clear answer on where to require d3 – in the vender folder? 

We've already added "meta charset="UTF-8" and <%=csrf_meta_tags%> in the application.html.erb file, which are required for d3.

**Comment by RobertAKARobin** [comment]
If you have it in the `vendor` folder, just make sure you `//= require d3` in your `app/assets/application.js`.

**Comment by clarissastark** [comment]
ok - if we're not downloading d3 and just want to link to the cdn, do we still need //= require d3? and where is the right place to put the link to the cnd?

**Comment by RobertAKARobin** [comment]
If you're using a CDN, you can just plop the `<script>` in the `<head>` of your `application.html.erb` like any JS file.
