### ISSUE TITLE
Pushing data to json

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-wdi-exercises/project3#136]
We're having a little trouble getting this form to add data to our remote json. For a little while we got a POST 400 error but now it's stopped talking to the server at all (hitting Submit causes no reaction in the rails server). 

Here is our factory which communicates with the other server:

```
  function cityFactoryFunction($resource){
    return $resource("http://localhost:3000/cities/:id.json", {}, {
      update: {method: "PUT"}
    });
  }
```

and here is the function for the form:

```
  function cityFormFunction(CityFactory){
    var vm = this;
    vm.newCity = new CityFactory();
    return{
      templateUrl: "city.form.html",
      scope: {
        city: "=",
        formMethod: "@"
      },
      link: function(scope){
        scope.create = function(){
          CityFactory.save(vm.newCity, function(response){
            console.log("hi!");
            response.lat = parseFloat(response.lat);
            response.long = parseFloat(response.long);
            CityFactory.push(response);
          });
        };
      }
    }
  }
```

and here is the form itself:

```
<input type="text" data-ng-model="vm.newCity.name" />
<label for="name">City</label>

<input type="text" data-ng-model="vm.newCity.desc" />
<label for="desc">Description</label>

<input type="text" data-ng-model="vm.newCity.lat" />
<label for="lat">Latitude</label>

<input type="text" data-ng-model="vm.newCity.long" />
<label for="long">Longitude</label>

<button type="button" data-ng-click="vm.create()">Submit</button>
```

**Comment by jeffreyeaton76** [comment]
Oh, and the directive calling the form:

```
<div data-city-form data-city="vm.newCity" data-form-method="create"></div>
</div>
```

**Comment by RobertAKARobin** [comment]
Let's diagnose whether the problem's with Rails or Angular. Try `console.log(response)`. Everything there look OK?

**Comment by jeffreyeaton76** [comment]
Nope. Not even that "Hi!" I forgot to delete is showing up.

**Comment by RobertAKARobin** [comment]
Ah. That's because you have `vm.create()`. `vm` refers to the controller. Anything you attach to `scope` inside your directive can be accessed without a `something.`, e.g. just `data-ng-click="create()"`

`¯\_(ツ)_/¯`

**Comment by jeffreyeaton76** [comment]
OK, so now I get `POST http://localhost:3000/cities.json 400 (Bad Request)` and no console.log for `response`

**Comment by RobertAKARobin** [comment]
Alright, that means there must be an error in your Terminal, where `rails s` is running. What are the first few lines of the error?

**Comment by jeffreyeaton76** [comment]
Hmm. This is interesting . . .

```
Started POST "/cities.json" for ::1 at 2016-04-04 12:24:43 -0400
Processing by CitiesController#create as JSON
  Parameters: {"city"=>{}}
Can't verify CSRF token authenticity
Completed 400 Bad Request in 1ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: city):
  app/controllers/cities_controller.rb:35:in `city_params'
  app/controllers/cities_controller.rb:13:in `create'
```

**Comment by RobertAKARobin** [comment]
So this indicates that data isn't actually being passed to Rails. Therefore it must be an Angular problem.

Above your `console.log("hi!")`, try `console.log(vm.newCity)`. What does it contain?

**Comment by jeffreyeaton76** [comment]
zippo. it's just the error message, no log

**Comment by RobertAKARobin** [comment]
So `vm.newCity` must not be where the data is stored.

Directives don't automatically "know" about the controllers in which they're found. You have to explicitly pass in whatever data you want the directive to be able to access. You did that here with these lines:

``` js
scope: {
  city: "=",
```

and:

``` html
data-city="vm.newCity"
```

This takes `vm.newCity`, and passes it into the directive, saving it to `scope.city`. So the data you want is in `scope.city`. Try `CityFactory.save(scope.city`

**Comment by jeffreyeaton76** [comment]
I tried `CityFactory.save(scope.city, response){` and `CityFactory.save(scope.newCity, response){` and both continued with the same error.

**Comment by jeffreyeaton76** [comment]
I tried passing in `scope` to the `scope.create` function and have produced an error that is now inside that function (progress?!), though still one line away from console.log. Now I get:
`TypeError: Cannot read property 'newCity' of undefined`

**Comment by RobertAKARobin** [comment]
~~Can you show me the full text of your controller now?~~ Sorry, I mean directive?

**Comment by jeffreyeaton76** [comment]
```
  function cityFormFunction(CityFactory){
    var vm = this;
    vm.newCity = new CityFactory();
    return{
      templateUrl: "city.form.html",
      scope: {
        city: "=",
        formMethod: "@"
      },
      link: function(scope){
        scope.create = function(scope){
          CityFactory.save(scope.newCity, function(response){
            console.log(vm.newCity);
            console.log(response);
            response.lat = parseFloat(response.lat);
            response.long = parseFloat(response.long);
            CityFactory.push(response);
          });
        };
```

**Comment by RobertAKARobin** [comment]
You're taking `vm.newCity` and saving it to `scope.city`, not `scope.newCity`.

**Comment by RobertAKARobin** [comment]
`vm.newCity` => `data-city="vm.newCity"` => `scope: {city: "="}` => `scope.city`

`vm.newCity` => `data-wombat="vm.newCity"` => `scope: {wombat: "="}` => `scope.wombat`

**Comment by jeffreyeaton76** [comment]
So I changed the city to newCity and it still says  Cannot read property 'newCity' of undefined

```
function cityFormFunction(CityFactory){
    var vm = this;
    vm.newCity = new CityFactory();
    return{
      templateUrl: "city.form.html",
      scope: {
        newCity: "=",
        formMethod: "@"
      },
      link: function(scope){
        scope.create = function(scope){
          CityFactory.save(scope.newCity, function(response){
            console.log(vm.newCity);
            console.log(response);
            response.lat = parseFloat(response.lat);
            response.long = parseFloat(response.long);
            CityFactory.push(response);
          });
        };
```

**Comment by RobertAKARobin** [comment]
I meant, take `CityFactory.save(scope.newCity` and make it `CityFactory.save(scope.city`. There is not and should not be any `newCity` inside your directive.

**Comment by jeffreyeaton76** [comment]
After careful consideration and group consultation I am sorry to report angular says `TypeError: Cannot read property 'city' of undefined`

**Comment by RobertAKARobin** [comment]
I'm coming over!
