### ISSUE TITLE
Reference Error: Attempting to create new entry with Form

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/project3#139]
I'm trying to add a create method for my form but I'm getting a reference error for 'Restaurant'.

Error:
![snip20160404_3](https://cloud.githubusercontent.com/assets/16657107/14263218/65da5092-fa87-11e5-8d95-535ff05c06e4.png)

Form Function:
![snip20160404_2](https://cloud.githubusercontent.com/assets/16657107/14263229/72034c2a-fa87-11e5-83f5-00b1ec2e43c4.png)

Restaurant Index Controller:
![image](https://cloud.githubusercontent.com/assets/16657107/14263355/21a5ab8c-fa88-11e5-9ddc-0cb689781c5b.png)

**Comment by RobertAKARobin** [comment]
`Restaurant` isn't defined; but `RestaurantFactory` is!

**Comment by winishahines** [comment]
I updated the code to reflect 'RestaurantFactory' but now I'm getting a 404 error for localhost 3000:/restaurants (This is where our API is). I'm adding the screenshots below.

![snip20160405_2](https://cloud.githubusercontent.com/assets/16657107/14282522/c17fcb0e-fb0c-11e5-9069-f0d24332def5.png)

![snip20160405_1](https://cloud.githubusercontent.com/assets/16657107/14282527/c66462a6-fb0c-11e5-9be4-e8dcb028d6af.png)

**Comment by RobertAKARobin** [comment]
Note that it's a POST to `localhost:3000/restaurants`. Do you have a "create" route set up?

**Comment by winishahines** [comment]
I created a 'create' method in the controller...not sure what you mean by a 'create route'. This is what the route.rb looks like:

![snip20160405_3](https://cloud.githubusercontent.com/assets/16657107/14292155/d1f3b824-fb34-11e5-9f83-70d50c883f30.png)

**Comment by RobertAKARobin** [comment]
That looks great! As long as you have `def create` in your controller, you should be good to go.

**Comment by winishahines** [comment]
Thanks Robin! I got it to work a little while ago :-)
