### ISSUE TITLE
Handlebars issue

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project3#14]
We expected handlebars to render our data in html on the users/index.hbs view - the vanilla html displays (so we know the route works) but not the mongo data, so we must have an error with our handlebar syntax. 

``` hbs
{{#each users}}
  <div><a href="/user/{{_id}}">{{name}}</a></div>
  {{#each cities}}
    <div class="city">
      <div class="cityName"><a href="/city/{{_id}}">{{name}}</a></div>
      <!-- For each city, it will iterate through their notes-->
      {{#each notes}}
        <p class="note">{{body}}</p>
      {{/each}}
    </div>
  {{/each}}
{{/each}}
```

**Comment by RobertAKARobin** [comment]
The issue wasn't handlebars, but rather having the correct database connection.
