### ISSUE TITLE
Changing the name of our project repo

### ISSUE THREAD

**Issue by brendaneamon** [ga-wdi-exercises/project3#142]
Our group (Group 13) has run into an issue wherein our app, tentatively titled "ZoogramZ," must be renamed to comply with Instagram's guidelines in their API terms of use. We have looked into the issue and found [this "help" article](https://help.github.com/articles/renaming-a-repository/). Should we follow the approach described therein, or is there a better option? Is renaming the repo the best course of action, or should we create a new repo and just make that the remote repo for our existing project?

**Comment by RobertAKARobin** [comment]
Wow, really? That's bizarre. Well, start off just renaming the repo on Github, and see if that works. If it doesn't, we'll go from there.

**Comment by brendaneamon** [comment]
OK, thanks. We're working on a feature branch now and will rename the repo when that branch has been merged into the master branch.

**Comment by RobertAKARobin** [comment]
:+1: I'ma close this for now, but feel free to open a new issue if things get weird.

**Comment by christine-sm** [comment]
We renamed it successfully! Surprisingly painless process.
