### ISSUE TITLE
Template is missing 

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project3#144]
Trying to figure out why it's giving us this error.

Our routes look correct, so we're confused

<img width="971" alt="screen shot 2016-04-05 at 3 04 53 pm" src="https://cloud.githubusercontent.com/assets/14954458/14294606/f4eafa62-fb3f-11e5-8d44-8328feba0fd4.png">

**Comment by RobertAKARobin** [comment]
It's saying you're either missing `app/views/states/index.html.erb` or `app/views/layouts/application.html.erb`.

**Comment by Crunchwrap78** [comment]
we don't know if need it exactly since it's empty and we're rendering everything in 

```
app/views/layouts/application.html.erb.
```

**Comment by RobertAKARobin** [comment]
Unless you tell it to do otherwise, Rails is going to always look for a view that matches your controller action. Even if it's blank, you need to have that `index.html.erb` there.

**Comment by Crunchwrap78** [comment]
That seems pretty stupid since that's a waste of space, but that fixed the problem.

Thanks!

**Comment by RobertAKARobin** [comment]
Meh. Your model files usually have like 3 lines of code in them. Not to mention all those empty `.keep` files. `¯\_(ツ)_/¯`
