### ISSUE TITLE
Issue with Linking Submit Button

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/project3#146]
Link to project repo: (https://github.com/aklein916/iCare-Volunteer-Project)

Hi all,

We're having some issues with a particular button...

Within our public/ng-view/event.index.html is a "Submit" button. That button, when clicked, should link to the public/ng-view/event.show.html page. We're wracking our brains over why it's not working xD 

Would really appreciate another pair of eyes!

Many thanks!

**Comment by RobertAKARobin** [comment]
Are you getting an error?
