### ISSUE TITLE
Issue with link to stories

### ISSUE THREAD

**Issue by aklein916** [ga-wdi-exercises/project3#148]
I am getting the attached error when I click on "stories" from nav bar on the application.html.erb page. 

I do have the storyIndex defined, but I think the problem is related to the fact that our welcome page is part of the events.js, and we do not have nested resources.  our github repo is: https://github.com/aklein916/iCare-Volunteer-Project

![screen shot 2016-04-06 at 3 06 58 pm](https://cloud.githubusercontent.com/assets/16639601/14329531/b450ee7e-fc09-11e5-9156-cf27b97d9185.png)

Thanks!

**Comment by RobertAKARobin** [comment]
Sorry for the delay, Alexa. This probably means one of your "states" in your Angular router doesn't have a name, or you've misspelled the name. I'll look.

**Comment by RobertAKARobin** [comment]
The problem is a module can have only one `.config`. You have two: one in `events.js` and one in `stories.js`.
