### ISSUE TITLE
Want to use data-ui-sref instead of hardcoding link

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/project3#149]
`<li><a href="zoos#/1/reptiles">Reptiles</a></li>` leads to http://localhost:3000/zoos#/1/reptiles.
`<li><a data-ui-sref="reptileIndex">Reptiles</a></li>` leads to http://localhost:3000/zoos#//reptiles. Note that the 1 is missing when I try to use `ui-sref`. The link still works... but how do I correct the path?

**Comment by RobertAKARobin** [comment]
`data-ui-sref="reptileIndex({id: zoo.id})"` or similar

**Comment by christine-sm** [comment]
Ah yes I was trying that earlier but didn't have luck:

```
<li><a data-ui-sref="reptileIndex({id: ZooShowVM.zoo.id})">Reptiles</a></li>
```

This line of code is on my mammals index page though... So can I not access ZooShowVM because technically I'm in the world of MammalsIndexVM?

**Comment by RobertAKARobin** [comment]
Can you be more specific about what didn't work? did you get an error? What URL did it take you to?

**Comment by RobertAKARobin** [comment]
Oh. Yes, that would be a problem. You can't access another controller inside the current controller.

**Comment by christine-sm** [comment]
So should I stick with hardcoding the link? When I tried `ui-sref` it visually leads to the correct page, but the path is technically incorrect:
`<li><a href="zoos#/1/reptiles">Reptiles</a></li>` leads to http://localhost:3000/zoos#/1/reptiles.
`<li><a data-ui-sref="reptileIndex">Reptiles</a></li>` leads to http://localhost:3000/zoos#//reptiles.

**Comment by RobertAKARobin** [comment]
Can you push this code up to Github?

**Comment by christine-sm** [comment]
https://github.com/cmmovius/zoosnapz/blob/master/public/ng-views/mammals.index.html

See Lines 15 & 17

**Comment by RobertAKARobin** [comment]
Add the National Zoo as a property of `MammalIndexVM`, e.g:

``` js
var MammalIndexVM = this;
MammalIndexVM = ZooFactory.all[0]
```

...or something. Then you don't need to hardcode it in your view.
