### ISSUE TITLE
Is it me or is it Github? (A message from Lyndsey)

### ISSUE THREAD

**Issue by LNewsome** [ga-wdi-exercises/project3#150]
I pushed my project up to my branch and then I proceeded to merge my branch into the master branch but none of my pushes are showing on the repo. Is Github being slow or am I doing something wrong?

**Comment by mattscilipoti** [comment]
Make sure you are viewing the right branch on github.  ![the branches](http://g.recordit.co/FJOuYjO3xq.gif)
