### ISSUE TITLE
Attempted to establish a root page for my app and ended up breaking the whole thing

### ISSUE THREAD

**Issue by brendaneamon** [ga-wdi-exercises/project3#153]
The current version of our app is available on Heroku:  [http://zoosnapz.herokuapp.com/](http://zoosnapz.herokuapp.com/)

I added a root controller to the code, and it seems to display the correct template, but none of the content shows up and none of the links work. The app was working previously, except for the fact that you need to manually navigate to `/zoos#/1` to see the homepage content. Will continue working on this tomorrow, but we're basically looking for guidance as to how to configure our app so that the user automatically lands on the page we want them to see first.

**Comment by brendaneamon** [comment]
This is the link to the code I added that broke everything: [https://github.com/cmmovius/zoosnapz/commit/1a34a55bf558424abc6bb4018e8f88fa86ee1a3c](https://github.com/cmmovius/zoosnapz/commit/1a34a55bf558424abc6bb4018e8f88fa86ee1a3c)

**Comment by RobertAKARobin** [comment]
How about `http://localhost:3000/#/`?

**Comment by brendaneamon** [comment]
That takes us to our zoos index page, which is really just a blank page that says "I am working". This is because our zoos show state is meant to be the landing page for our app.

**Comment by RobertAKARobin** [comment]
How about this instead:

``` rb
root to: redirect('/zoos')
```

**Comment by brendaneamon** [comment]
Wait! We tried this, and it worked: `root to: redirect('/zoos#/1')`

**Comment by RobertAKARobin** [comment]
I don't think that's a routing problem. I'm getting a 500 error here:

http://zoosnapz.herokuapp.com/zoos.json

Check your server log for an error.

**Comment by brendaneamon** [comment]
I haven't pushed the changes up yet, but everything seems to be functioning now. Will keep testing and will try pushing changes to Herooku. Thanks!
