### ISSUE TITLE
Comments are screwy!

### ISSUE THREAD

**Issue by tvcrawley** [ga-wdi-exercises/project3#154]
Link to repo: https://github.com/Chibiania/Project3/tree/testing
Link to deployed app: https://the-snack-app.herokuapp.com

Things you'd like specific feedback on:
In the ng-views/snack.show.html, is an ng-repeat that cycles through comments (not the problem).

In the snacks.js, in the show controller function is the logic for the comments. Comments are nested with snacks. When a comment is saved, it goes to vm.comments, BUT (problem) when they are being displayed in the html, alllllllll the comments are coming up as opposed to just the specific comments for that snack.

**Comment by RobertAKARobin** [comment]
@Chibiania Woo! Are you submitting your project? If so, could you please post it to https://github.com/ga-dc/wdi8-project3-gallery

**Comment by tvcrawley** [comment]
It's been deployed/posted on the gallery page
