### ISSUE TITLE
Help on comments!!!!

### ISSUE THREAD

**Issue by tvcrawley** [ga-wdi-exercises/project3#155]
Link to repo: https://github.com/Chibiania/Project3/tree/testing
Link to deployed app: https://the-snack-app.herokuapp.com

Things you'd like specific feedback on:
In the ng-views/snack.show.html, is an ng-repeat that cycles through comments (not the problem).

!!!!!!!!!!!!!!!!!!
In the snacks.js, in the show controller function is the logic for the comments. Comments are nested with snacks. When a comment is saved, it goes to vm.comments, BUT (PROBLEM) when they are being displayed in the html, alllllllll the comments are coming up as opposed to just the specific comments for that snack.
!!!!!!!!!!!!!!!!!!!!

**Comment by amaseda** [comment]
Hey @Chibiania! Can you include the Angular controller and view responsible for this functionality?

**Comment by tvcrawley** [comment]
Controller:

```
// comments logic
vm.comments = CommentFactory.query({snack_id: $stateParams.id});
console.log(vm.comments)
vm.comment = new CommentFactory({snack_id: $stateParams.id});
// vm.snack_id = $stateParams.id;
// vm.comment.snack_id = vm.snack;
this.create = function(){
  vm.comment.$save(function(response){
    vm.comments.push(response);
  });
  vm.comment = {};
  console.log(vm.comment);
  console.log(vm.comment.name);
  console.log(vm.comment.message);
};
```

View:
**purposely removed < > to show actual code

div     data-ng-repeat="comment in SnackShowVM.comments | orderBy: '-created_at'"
        p     {{comment.name}}     /p
        p    {{comment.message}}    /p
  /div
