### ISSUE TITLE
Merges not updating correctly

### ISSUE THREAD

**Issue by Crunchwrap78** [ga-wdi-exercises/project3#157]
We've tried to merge fatai's comments branch for about an hour and it won't merge correctly with master for some reason. We can see the differences in the code, and when we try to merge again it says it's up to date when it isn't

**Comment by RobertAKARobin** [comment]
Did someone reset or rebase at some point?

**Comment by Crunchwrap78** [comment]
I'm pretty sure none of us did. Fatai reverted a merge, but that's about it

**Comment by RobertAKARobin** [comment]
That may do it. No worries.
