### ISSUE TITLE
Heroku Doesn't reflect Master Branch

### ISSUE THREAD

**Issue by winishahines** [ga-wdi-exercises/project3#158]
All of our teams' changes have been added to Master but Heroku isn't recognizing the latest updates. Is anyone around to help us with this?

**Comment by RobertAKARobin** [comment]
What's different?

**Comment by winishahines** [comment]
Changes to the HTML aren't reflect even though they're on master.

**Comment by winishahines** [comment]
*reflected

**Comment by RobertAKARobin** [comment]
Try `git push -f heroku master`.

**Comment by RobertAKARobin** [comment]
Make sure you're in the `master` branch on your computer.

**Comment by winishahines** [comment]
It says everything up to date. Anissa is trying to create a new app from her computer to see if it'll work.

**Comment by winishahines** [comment]
The foods aren't showing up

**Comment by RobertAKARobin** [comment]
Did you `heroku run rake db:migrate` and seed?

**Comment by winishahines** [comment]
We seeded and migrated twice
