### ISSUE TITLE
Issue with git merge

### ISSUE THREAD

**Issue by lknapalolo** [ga-wdi-exercises/project3#159]
We tried:

On master branch:
git merge lk_branch

On lk_branch:
git merge master

Atom popped up with this message: 

> > Merge branch 'lk_branch'
> 
> Please enter a commit message to explain why this merge is necessary,
> especially if it merges an updated upstream into a topic branch.
> 
>  Lines starting with '#' will be ignored, and an empty message aborts
>  the commit.

**Comment by andrewsunglaekim** [comment]
just commit

**Comment by tylercrosse** [comment]
Just commit
