### ISSUE TITLE
Issue with create feature

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project3#161]
Error in the console:
![screen shot 2016-05-09 at 10 56 36 am](https://cloud.githubusercontent.com/assets/8240318/15117222/8d0a286e-15d4-11e6-916d-65807251a7a0.png)

Server Error:
![screen shot 2016-05-09 at 10 57 52 am](https://cloud.githubusercontent.com/assets/8240318/15117264/b7a0600c-15d4-11e6-919c-0a91dd50d214.png)

Users controller:
![screen shot 2016-05-09 at 10 58 45 am](https://cloud.githubusercontent.com/assets/8240318/15117297/e26a557c-15d4-11e6-9426-608d8a667adb.png)

...help?

<3 Team ramrod

**Comment by andrewsunglaekim** [comment]
have you installed the `rack-cors` gem?

**Comment by lknapalolo** [comment]
Yup

https://github.com/jball23/brokers-open/commit/2e525652d523e0ede741c7920b8ca54b0758305d

**Comment by lknapalolo** [comment]
The Users/Create New feature is the only feature that isn't working

**Comment by andrewsunglaekim** [comment]
seems like params is missing, any reason for that? in a meeting, ill come see you guys after.

**Comment by tylercrosse** [comment]
You need to comment out the [line 4](https://github.com/jball23/brokers-open/blob/master/brokers-open-rails%2Fbrokers-open%2Fapp%2Fcontrollers%2Fapplication_controller.rb)

**Comment by lknapalolo** [comment]
![screen shot 2016-05-09 at 11 31 09 am](https://cloud.githubusercontent.com/assets/17017604/15118294/95d25cdc-15d9-11e6-8c4e-b8255534392b.png)
Params is right here ¯_(ツ)_/¯
