### ISSUE TITLE
Issue with create feature

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project3#162]
We have two models: users and listings, in a user has_many listings relationship.

On the user_show page, we attempted to list each user's listings: 
![screen shot 2016-05-09 at 12 12 03 pm](https://cloud.githubusercontent.com/assets/8240318/15119471/130f1c3a-15df-11e6-9380-17dc8359c454.png)

Nothing appears on the screen, and when we tried to console.log(user.listings) and console.log(usersShowVm.user.listings) , we received the following errors: 
![screen shot 2016-05-09 at 12 13 04 pm](https://cloud.githubusercontent.com/assets/8240318/15119502/3a478030-15df-11e6-8325-1970040c288c.png)

Any thoughts for Team Ramrod? :)

**Comment by andrewsunglaekim** [comment]
you aren't going to be able to access variables taht are scoped to IIFE's. console.log inside your controller

**Comment by MichaelNahum** [comment]
console.log(this.user.listings) in the ShowController returns undefined. any idea why the model association wouldn't be enough?

**Comment by tylercrosse** [comment]
Can you `console.log(usersShowVm.user)`? is .listings a part of it? Where is `.user` defined/attached to the controller?

**Comment by andrewsunglaekim** [comment]
gonna close, reopen if you have issues
