### ISSUE TITLE
UserListingsFactory

### ISSUE THREAD

**Issue by MichaelNahum** [ga-wdi-exercises/project3#163]
We are getting this error:
https://docs.angularjs.org/error/$resource/badcfg?p0=get&p1=object&p2=array&p3=GET&p4=http%3A%2F%2Flocalhost%3A3000%2Fusers%2F3%2Flistings

**Comment by nolds9** [comment]
Can I see the code where you are making the request? Looks like Angular couldn't differentiate between a `.query()` call which should return an `array` and a `.get()` call which needs an id to get back one `object`
