### ISSUE TITLE
Hewan, James, Josh, Wes: Migrations Pending 

### ISSUE THREAD

**Issue by wesareed** [ga-wdi-exercises/project3#164]
migration is looking for a table we've dropped. Need help getting around this.

**Comment by tylercrosse** [comment]
Could you provide a little more information. What errors are you getting? Presumably, this is being triggered by `rake db:migrate`. What changed since the last time that command was run?

**Comment by wesareed** [comment]
PG::UndefinedColumn: ERROR:  column "comment_id" of relation "posts" does not exist
: ALTER TABLE "posts" DROP "comment_id"

this is a column we dropped earlier this afternoon with rails d ...

The tables are no longer migrating.
