### ISSUE TITLE
Heroku's Beloved Application Error 

### ISSUE THREAD

**Issue by wesareed** [ga-wdi-exercises/project3#168]
We created a local heroku branch and merged  the master into in and now getting this error.

**Comment by tylercrosse** [comment]
Did you run `heroku run rake db:migrate`? Which branch did you push to heroku? 

When you type `git push heroku master`, it tries to push your master branch to Heroku. If all your changes are in a branch other than master, this will be a problem!

**Comment by wesareed** [comment]
did not run migration on heroku will try that when we finish with outcomes. our master branch is up to date. Thanks man.

**Comment by wesareed** [comment]
Tried that and still having trouble. Saying we have a duplicate table and not allowing us to drop table on heroku app b/c we don't have 'permission'.
