### ISSUE TITLE
trying to get comments to post

### ISSUE THREAD

**Issue by superbuggy** [ga-wdi-exercises/project3#169]
![screen shot 2016-05-11 at 1 55 17 pm](https://cloud.githubusercontent.com/assets/17716232/15191354/5d681652-1782-11e6-8961-e506b2220a0b.png)
I am using a Factory for comment to save the comment, and supplying the post_id from a form with a hidden field (hacky). I expect the comment to be able to save :/

**Comment by tylercrosse** [comment]
👍
