### ISSUE TITLE
Troubles with API

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project3#171]
our rep with branch API: https://github.com/adina-pollack/project3rails/tree/api

right now our api works when we search for one word queries, so if we search for "boston," all the concerts in boston will appear. However, if we search for multiple word cities, like "new york city", the query gets messed up and does not work. How would you recommend going about fixing it? We looked into using gsub but could not get it to work. 
Also the api we are using is called bandsintown. 
Thanks!

**Comment by amaseda** [comment]
I'm guessing that if you replace the space with `%20`, like in the below link, that should do the trick.

http://api.bandsintown.com/artists/Crystal%20Castles.json?app_id=YOUR_APP_ID&api_version=2.0&callback=showArtist

What you can do is clean up the search query prior to adding it to the full URL using split/join or replace (see Stackoverflow link below). Once you've got the `%20`s in there, you can then add it to the full URL.

http://stackoverflow.com/questions/441018/replacing-spaces-with-underscores-in-javascript

**Comment by amaseda** [comment]
@JuliaNajafi Did this work out?

**Comment by JuliaNajafi** [comment]
i think we got it mostly working. do you have any recommendations for dealing with user input spelling errors.. (maybe using 'like'). I've been searching but I haven't been able to figure out a solution

**Comment by amaseda** [comment]
Depends what you'd like to happen when a user doesn't submit a valid input. What would a user story be for this situation in your app?

**Comment by JuliaNajafi** [comment]
We would want the results most like what they searched for to be shown, if thats possible. so if a user typed in 'san fransisco', they would results most like their search query, i.e. 'san francisco'

**Comment by JuliaNajafi** [comment]
sorry that wasn't english. *\* the results shown would be most like their search query, i.e. san francisco

**Comment by amaseda** [comment]
One option is to compare the user input to an approved list of cities / artists. I would look into how you can do this with Regex or "fuzzy search" options that are out there ([like this](http://kiro.me/projects/fuse.html)).

I'm sure there are also some useful auto-complete libraries out there. I'm just not too familiar with them.

Another option is to use the API response generated by an incorrect input to trigger a "You did not search for a valid city" warning to the user.

**Comment by JuliaNajafi** [comment]
@amaseda is it possible to seed your database with a foreign api? for example if i get 10 different concerts from searching boston in my bandsintown api, is it possible to then seed that into my database?

**Comment by amaseda** [comment]
@JuliaNajafi Yup! You can make an API call using HTTParty and then generate models based on whatever you get back in the response.

Code would roughly look something like this...

```
response = HTTParty.get("insert-url-here")
Concert.create(location: response["location"])
```

**Comment by JuliaNajafi** [comment]
thanks!

**Comment by amaseda** [comment]
Going to close this but feel free to re-open if you have any more questions!
