### ISSUE TITLE
$save not a function

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project3#173]
Trying to save records to our deployed rails db but the angular is saying $save is not a function. Can't figure it out because I'm doing the exact same thing with playlists but it's only failing for songs.

Factory:

```
function SongFactoryFunction ( $resource, $stateParams ) {
        return $resource( "https://dry-citadel-69831.herokuapp.com/playlists/:id/songs/:id.json", {}, {
            update: {method: "PUT"}
        });
    }
```

Controller:

```
function AddControllerFunction ($state, $stateParams, SpotifyFactory, SongFactory) {
        console.log("I'm in the invite controller!")
        var vm = this;
        vm.playlist_id = $stateParams.playlist_id;
        console.log(vm.playlist_id);

        vm.add_song = function (title, artist, album, image_url, duration, preview) {
            console.log("clicked button");
            vm.new_song = new SongFactory();
            console.log(vm.new_song);
            vm.new_song = {
                "user": "Anh",
                "playlist_id": vm.playlist_id,
                "title": title,
                "artist": artist,
                "album": album,
                "album_art": image_url,
                "duration": duration,
                "audio_url": preview,
                "score": 0
            }
            console.log(vm.new_song);
            vm.new_song.$save().then(function() {
                $state.go("Add", {playlist_id: vm.playlist_id});
            })
        }
    }
```

**Comment by jshawl** [comment]
`vm.new_song = {
                "user": "Anh",`

removes the $save method

**Comment by wombatdev** [comment]
If we get $save working, how do we pass in the ID of the model songs are nested in? I.e. so the post request goes to playlists/3/songs instead of playlists/songs? Is that configured in the factory or in the $save?

**Comment by jshawl** [comment]
i believe it's in the $save. What if you use ng-model to set the properties of `vm.new_song`?

**Comment by wombatdev** [comment]
Right now we're using an API to display a list of songs in a table, and clicking a button pulls the song values (title, artist, etc.) into an object, which is what we want to post to rails. Can we use ng-model in `<td>`s or does that have to be used in `<input>`s?

**Comment by jshawl** [comment]
td's should work! try it out

**Comment by amaseda** [comment]
@wombatdev You good to go here? If so, please close. If not, let us know how we can help!
