### ISSUE TITLE
Database is in csv (it needs to be in sql?) 

### ISSUE THREAD

**Issue by BlvckYuppie** [ga-wdi-exercises/project3#174]
https://github.com/kwg58/WDI10-Project-3/tree/build-rails-api 

( Necessary disclaimer, we're essentially building two self contained app's, a rails app to contain our db and process ajax requests, and an angular front end to serve the end user.)
Kevin created the api portion of our application this weekend.  Unfortunately, it's in csv format, and we're not sure how it's going to be possible to serve this with ajax requests from our angular app. We've hit a point of frustration (everyone's going home to beer / not code) and we're not sure how to proceed forward.  Help us obi-wan.

**Comment by BlvckYuppie** [comment]
Also, the crud functionality in the csv format works, and works well.  But again, we have no idea how to connect this with our angular app.

**Comment by nolds9** [comment]
At a high level, 
- you need to seed you database from the CSV
- Then query your database and render JSON

**Comment by jshawl** [comment]
when you visit `localhost:3000/monuments.json`, do you see json? https://github.com/kwg58/WDI10-Project-3/blob/447de8b18e900831f2c5b19d1e4f1030349a2dd2/pokemonument-api/config/routes.rb#L3

**Comment by BlvckYuppie** [comment]
No, i see a rendered page. 

Nick, thats a high level step in the right direction.  I'll look into it. 
![screen shot 2016-07-18 at 5 14 19 pm](https://cloud.githubusercontent.com/assets/18303341/16930651/2f39c0c8-4d0b-11e6-89ff-c9ef2504a81b.png)

**Comment by amaseda** [comment]
@BlvckYuppie https://www.sitepoint.com/guide-ruby-csv-library-part/

**Comment by amaseda** [comment]
Going to close this one since we worked on it last night, but feel free to re-open if the same issue comes up.
