### ISSUE TITLE
Inserting lat/lng from address 

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project3#176]
I'm trying to get the lat/long of locations for each place based on their address that is in our JSON. I have my location.rb file opened and when I place a hardcoded lat and long there, it merges it to all the locations. This is what I mean:

![screen shot 2016-07-20 at 9 21 21 am](https://cloud.githubusercontent.com/assets/19437889/16987703/a872c2cc-4e5b-11e6-8811-ece93922b520.png)

**My question would be how do we retrieve different lats and longs for each location?**

**Comment by amaseda** [comment]
Where/how are you calling `as_json` in your code?

**Comment by kristinmaripasive** [comment]
I have a location factory set up:

```
function LocationFactoryFunction($resource){
   return $resource("http://localhost:3000/locations/:id", {}, {
     update: { method: "PUT" }
   });
```

Also, I'm not sure if it would be something like this. I placed the code below in my map. I tried it but it doesn't seem to work. I'm guessing there's just something missing. 

```
<script>
function convertAddressToLatLong(address, callback){
  $.getJSON("https://maps.googleapis.com/maps/api/geocode/json?address=" + address, function(response){
    callback(response.results[0].geometry.location);
  })
}
</script>
```

**Comment by jshawl** [comment]
in your ruby model, you need to geocode the location https://github.com/alexreisner/geocoder

**Comment by kristinmaripasive** [comment]
trying to go through the geocode gem, but its retrieving i think using mongoDB and I don't know how to work with that. I have set up a migration file which added two columns called latitude and longitude to my location model. Now my location.rb looks like this:

```
class Location < ApplicationRecord
  has_many :comments, dependent: :destroy

  field :coordinates, :type => Array
  include Geocoder::Model::Mongoid
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def as_json(options={})
    super(options).merge(Lat: 2, Lng: 6)
  end

end
```

I don't know how to go forward from there using JSON

**Comment by kristinmaripasive** [comment]
sanigo_development=# SELECT \* FROM locations;
 id | name | address | latitude | longitude 
----+------+---------+----------+-----------
(0 rows)

**Comment by jshawl** [comment]
use the active record section? https://github.com/alexreisner/geocoder#activerecord

**Comment by kristinmaripasive** [comment]
ohhh my bad, i thought I had to do active record and the Mongoid section

**Comment by kristinmaripasive** [comment]
this issue can be closed. Thanks for all the help!

**Comment by jshawl** [comment]
👍
