### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by chapel-of-bools** [ga-wdi-exercises/project3#178]
Can't redirect after my delete function here:
https://github.com/kristinmaripasive/sanigo/blob/update/sanigo_angular/js/locations/edit.controller.js

**Comment by jshawl** [comment]
what does the error say?

**Comment by chapel-of-bools** [comment]
"DELETE http://localhost:3000/locations/18 500 (Internal Server Error)"

**Comment by jshawl** [comment]
any error messages in the rails console?

**Comment by chapel-of-bools** [comment]
No errors there, just the browser console

**Comment by jshawl** [comment]
can you see what the error means in network tab?

![](https://dl.dropbox.com/s/od4sam0kfndy2mx/Screenshot%202016-07-20%2011.35.38.png?dl=0)

**Comment by chapel-of-bools** [comment]
it says template is missing

Missing template locations/destroy, application/destroy with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in: \* "/Users/mattscott/wdi/projects/sanigo/app/views"

**Comment by jshawl** [comment]
alright nice! so instead of template, try `render nothing: true`

**Comment by jhugheswebdev** [comment]
Where do we place that?

**Comment by jshawl** [comment]
in the controllers delete action after you do the deleting

**Comment by chapel-of-bools** [comment]
I'm confused, this is what we have now, so where is template coming from?

this.destroy = function(){
      this.location.$delete({id: $stateParams.id}).then(function(response){
        $state.go("locationIndex");
      })
    }

**Comment by jshawl** [comment]
in the rails controller delete action

**Comment by chapel-of-bools** [comment]
That works!  Thank you!

**Comment by jhugheswebdev** [comment]
http://reactiongifs.me/wp-content/uploads/2013/09/clapping-crowd-applause.gif

**Comment by jshawl** [comment]
👍
