### ISSUE TITLE
We've completely botched a pull request, amongst other maladies 

### ISSUE THREAD

**Issue by BlvckYuppie** [ga-wdi-exercises/project3#179]
We've ruined our master branch trying to merge all of our disparate work into master.  I have no idea where to begin to fix this. We also need (General) guidance.

**Comment by jshawl** [comment]
what do you mean by ruined?

**Comment by BlvckYuppie** [comment]
Ruin is a poor choice of words. our master branch now has the data from like 3 merge conflicts in all of its files
![screen shot 2016-07-20 at 11 58 03 am](https://cloud.githubusercontent.com/assets/18303341/16993408/4ea5e222-4e71-11e6-86c7-00b1c83f1691.png)

**Comment by jshawl** [comment]
Ok I recommend getting together as a group, look for all instances of `<<<` and fix by hand

use command-shift-f to find all in project

**Comment by amaseda** [comment]
Going to close this one but please re-open if you have more questions / errors.
