### ISSUE TITLE
git pull issue 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#18]
Joe pushed his changes up to master and we see them there but when we try to pull them down it doesn't pull down the master branch information even though we are putting git pull origin master.  

We can see some lines of code in the repository and our master branches in our git says its up to date but it clearly does not have the missing lines of code.  

we tried git pull origin master
then git fetch master, and git merge

each time it says its up to date

**Comment by RobertAKARobin** [comment]
Try `git remote -v`. Is it using the URL that you would expect it to use? Does it have the correct username?

**Comment by ghost** [comment]
yes it has the correct origin 
origin  git@github.com:joe-gz/trans.hit.git (fetch)
origin  git@github.com:joe-gz/trans.hit.git (push)

**Comment by RobertAKARobin** [comment]
Is this happening on multiple computers, or just one?

Also, did Joe force-push (`git pull -f origin master`) or `git rebase`? (Neither of these are recommended, so don't do them unless you're sure of what you're doing!)

**Comment by RobertAKARobin** [comment]
Is this happening on multiple computers, or just one?

Also, did Joe force-push (`git push -f origin master`)? (This isn't recommended so don't do it unless you're sure of what you're doing!)

**Comment by ghost** [comment]
yes it looks like its happening to thomas too. Joe didn't force push yet, but we see the changes in the github repo it just doesn't pull down from github for thomas and I

**Comment by RobertAKARobin** [comment]
Did a `git reset --hard origin/master` and all is well.
