### ISSUE TITLE
How to ngRails

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project3#180]
Yeah, just need some pointing in the right direction

**Comment by jshawl** [comment]
are you trying to implement a new feature or fix an existing bug?

**Comment by dcordz** [comment]
We got the app set up in rails, but we're a little stuck with implementing angular with it, nothing too specific I guess

**Comment by amaseda** [comment]
Do you mean that you have your Rails API currently separate from your front-end app and now you want to join them? In that case, I'd direct you to the [Angular x Rails lesson plan](https://github.com/ga-wdi-lessons/angular-on-rails). Not too many different ways of doing that.

Is there something other than that you'd like guidance on?

**Comment by dcordz** [comment]
We separated our rails and angular apps into different repos and we're really not getting how to use an api with that lesson plan

**Comment by dcordz** [comment]
Would we be using `<%= javascript_include_tag 'app'>` instead `<script src="">` in our application.html.erb file?

**Comment by amaseda** [comment]
You'll use `javascript_include_tag`. Although if you're following that lesson plan, you may have renamed it from `app.js` to something else (e.g., `products.js`).

**Comment by dcordz** [comment]
Sounds good, thanks
