### ISSUE TITLE
trouble accessing variables in controller 

### ISSUE THREAD

**Issue by JuliaNajafi** [ga-wdi-exercises/project3#181]
heres the repo on working on, on branch mapsmarker : https://github.com/jschultz21/project3angular/tree/mapsmarker

within my show controller, I want to access the variable venue_latitude and venue_longitude and set it to my map marker. right now if i hardcode the lat and long, the map works, but I want to dynamically set those things to the variables we store in our rails database. when i console.log(this.concert), the venue_long and venue_lat show up in the object concert, but when I console.log(this.concert.venue_latitude), it comes back undefined. 
Any help would be greatly appreciated!

**Comment by JuliaNajafi** [comment]
![screen shot 2016-07-20 at 12 03 12 pm](https://cloud.githubusercontent.com/assets/19292741/16993741/8fac1e52-4e72-11e6-8a33-212565b2706e.png)

**Comment by JuliaNajafi** [comment]
![screen shot 2016-07-20 at 12 08 36 pm](https://cloud.githubusercontent.com/assets/19292741/16993777/c5c9fcf2-4e72-11e6-8ef3-e7cc8a731b25.png)

**Comment by JuliaNajafi** [comment]
above is when I 1. console.log(vm.concert) and 2. console.log(vm.concert.venue_latitude)

**Comment by jshawl** [comment]
1. is undefined because `query` is asynchronous. try adding a promise to the get request

**Comment by JuliaNajafi** [comment]
![screen shot 2016-07-20 at 1 49 46 pm](https://cloud.githubusercontent.com/assets/19292741/16997317/ccc96a6e-4e82-11e6-9df6-0ef533e81db0.png)

**Comment by JuliaNajafi** [comment]
![screen shot 2016-07-20 at 2 04 23 pm](https://cloud.githubusercontent.com/assets/19292741/16997336/e44c71c2-4e82-11e6-9c34-c301530e4d10.png)

**Comment by JuliaNajafi** [comment]
now I have access to venue locations, but the $cope.map doesnt work within a promise function

**Comment by JuliaNajafi** [comment]
would that be something related to $scope ? the map works outside of the promise function, but not within it - even with hardcoded lat and long

**Comment by jshawl** [comment]
are you still working w/ that angular-google-maps center of bounds error?

**Comment by JuliaNajafi** [comment]
yep!

**Comment by jshawl** [comment]
sorry forgot you were workin w/ andy

**Comment by jshawl** [comment]
can close?

**Comment by JuliaNajafi** [comment]
well, still haven't found a solution

**Comment by jshawl** [comment]
ok what progress have you made? any new errors?

**Comment by JuliaNajafi** [comment]
still at the same point, I believe it has something to do with $scope, and that it isn't being passed into the promise function correctly

**Comment by jshawl** [comment]
can you try integrating the example code and work backwards? https://github.com/angular-ui/angular-google-maps/blob/master/example/dragzoom.html
