### ISSUE TITLE
injector module error

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project3#182]
Trying to use this directive, https://github.com/jshor/angular-addtocalendar, but the dependencies are throwing an error on page load.
https://github.com/jschultz21/project3angular (used in app.js and js/concerts.js)

**Comment by amaseda** [comment]
Are you passing in `jshor.angular-addtocalendar` as a dependency anywhere? Don't see it.

https://github.com/jshor/angular-addtocalendar#installation

**Comment by jschultz21** [comment]
ah - sorry, meant to send the correct branch link: https://github.com/jschultz21/project3angular/tree/add-to-cal

**Comment by amaseda** [comment]
Are you linking to a CDN in `index.html`? Don't think I see one.

**Comment by jschultz21** [comment]
nope  - that's what I was trying to figure out, since the readme doesn't
mention one.

**Comment by amaseda** [comment]
Did you try installing it using npm or Bower? Try the former and make sure to reference the right file path in your `<script>`.

**Comment by jschultz21** [comment]
I used NPM originally but I don't know what file is supposed be included in index.html. would the npm install have added that automatically?

**Comment by jshawl** [comment]
npm will only download files to node_modules folder

**Comment by jschultz21** [comment]
I do see that the angular files are in my node_modules folder.

**Comment by amaseda** [comment]
So now you should have a `<script>` in `index.html` whose path points to wherever the `add-to-cal.js` file (or whatever it's called) is inside of `node_modules`.

**Comment by amaseda** [comment]
@jschultz21 I'm going to close this since we talked about it a bit earlier but feel free to re-open if you have more questions.
