### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project3#183]
Merged our angular and rails repos into a new repo and now can't get past a 404 error screen, can't figure out what I'm missing here

repo - https://github.com/dcordz/Congreddit/tree/merged-app

**Comment by amaseda** [comment]
Can you include a screenshot of the error?

**Comment by nolds9** [comment]
@dcordz One issue I see is where you are passing in a templateUrl to the states.

one way to avoid these absolute paths is to put your templates in Rails's public folder since it will already serve everything in that folder...then you can just use a relative path: `/legislators/index.html.erb`

**Comment by dcordz** [comment]
legislators/index.html.erb to the public folder and changed the path, no luck

**Comment by dcordz** [comment]
![screen shot 2016-07-20 at 2 55 12 pm](https://cloud.githubusercontent.com/assets/17937472/16999051/139f83f4-4e8a-11e6-8e78-858cdda62ab7.png)
