### ISSUE TITLE
params not passing - new

### ISSUE THREAD

**Issue by marasanders** [ga-wdi-exercises/project3#185]
if I pass in params it works fine if not I have an empty array?

```
<main data-ng-controller="post_controller as vm">
<h3>Create a New Post</h3>
<form data-ng-submit="PostIndexViewModel.create()">
  <input placeholder= "Title" data-ng-model="PostIndexViewModel.post.title" />
  <input placeholder= "Description" data-ng-model="PostIndexViewModel.post.description" />
  <input placeholder= "Email" data-ng-model="PostIndexViewModel.post.email" />
  <input placeholder= "Phone" data-ng-model="PostIndexViewModel.post.phone" />
  <input placeholder= "Street" data-ng-model="PostIndexViewModel.post.street" />
  <input placeholder= "City" data-ng-model="PostIndexViewModel.post.city" />
  <input placeholder= "State" data-ng-model="PostIndexViewModel.post.state" />
  <input placeholder= "Picture_url" data-ng-model="PostIndexViewModel.post.picture_url" />
  <button type = "submit">Create</button>
</form>

<main data-ng-controller="post_controller as vm">
<h3>Create a New Post</h3>
<form>
  <input placeholder= "Title" data-ng-model="vm.new_post.title" />
  <input placeholder= "Description" data-ng-model="vm.new_post.description" />
  <input placeholder= "Email" data-ng-model="vm.new_post.email" />
  <input placeholder= "Phone" data-ng-model="vm.new_post.phone" />
  <input placeholder= "Street" data-ng-model="vm.new_post.street" />
  <input placeholder= "City" data-ng-model="vm.new_post.city" />
  <input placeholder= "State" data-ng-model="vm.new_post.state" />
  <input placeholder= "Picture_url" data-ng-model="vm.new_post.picture_url" />
  <button type = "button" data-ng-click="PostIndexViewModel.create()">Create</button>
</form>
</main>
```

```
vm.new_post = {};
console.log("NEW POST")
vm.create = function(title, description){
  console.log(vm.new_post);
  vm.new_post = new PostFactory({
    "title": title,
    "description": description
  });
  console.log(vm.new_post);
  vm.new_post.$save().then(function(response){
    console.log(response)
    // vm.post_data.push(response);
    vm.new_post = {};
  });
}
```

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

**Comment by nolds9** [comment]
@marasanders  what do you mean by params not passing?
In the Angular New Controller - Try setting `vm.new_post = new PostFactory()`

Then, since you are alread binding user input to `new_post` in the view,  in the controller you should just be able to use `vm.new_post.$save()` to pass the post and all of its params to the back-end

**Comment by marasanders** [comment]
param is missing or the value is empty: post

Extracted source (around line #71):
69
70
71
72
73

```
# Never trust parameters from the scary internet, only allow the white list through.
def post_params
  params.require(:post).permit(:title, :description, :email, :phone, :street, :city, :state, 
```

:picture_url)

```
end
```

end

**Comment by amaseda** [comment]
What have you changed in your code since Nick's answer?

Can you push your code and send over the repo link / correct branch?

**Comment by marasanders** [comment]
thanks!

```
<main data-ng-controller="post_controller as vm">
<h3>Create a New Post</h3>
<form>
  <input placeholder= "Title" data-ng-model="vm.new_post.title" />
  <input placeholder= "Description" data-ng-model="vm.new_post.description" />
  <input placeholder= "Email" data-ng-model="vm.new_post.email" />
  <input placeholder= "Phone" data-ng-model="vm.new_post.phone" />
  <input placeholder= "Street" data-ng-model="vm.new_post.street" />
  <input placeholder= "City" data-ng-model="vm.new_post.city" />
  <input placeholder= "State" data-ng-model="vm.new_post.state" />
  <input placeholder= "Picture_url" data-ng-model="vm.new_post.picture_url" />
  <button type = "button" data-ng-click="PostIndexViewModel.create()">Create</button>
</form>
</main>
```

"use strict";

(function(){
  angular
  .module("posts", ["ngResource"])
  .controller("post_controller", ["$resource", "PostFactory", PostController]);

  function PostController($resource, PostFactory){
    var vm = this;
    var Post = $resource("/posts/:id.json", {}, {
      update: {method: "PUT"}
    });
    vm.post_data = Post.query();

```
vm.sort_post_data_by = function(name){
  vm.sort_on = name;
  vm.is_descending = !(vm.is_descending);
}

vm.destroy = function(post_index){
  var post = vm.post_data[post_index];
  Post.remove(post_index, function(response){
    if(response.success) vm.post_data.splice(post_index, 1);
  });
}

vm.new_post = {};
console.log("NEW POST")
vm.create = function(title, description){
  console.log(vm.new_post);
  vm.new_post = new PostFactory();
  console.log(vm.new_post);
  vm.new_post.$save().then(function(response){
    console.log(response)
    // vm.post_data.push(response);
    vm.new_post = {};
  });
}

vm.update = function(post){
  Post.update({id: post.id}, post, function(response){
    console.log("Post updated!");
  });
}
```

  }
})();

**Comment by marasanders** [comment]
still not working

**Comment by amaseda** [comment]
You initialize `vm.new_post` as an empty object. If you're using `$resource`, it should be initialized as a new instance of whatever `$resource` is saved to (so either `new Post()` or `new PostFactory()` depending on how your app is wired up).

**Comment by marasanders** [comment]
I have that inside the function do I need it outside the function too? why?

**Comment by nolds9** [comment]
@marasanders yes you need it outside too. The reason being, when the page loads, we initialize a new object called `vm.newPost` that is a blank template of whatever we have a defined a `Post` to be. Then as the user creates a new post, they are populating the fields of the `newPost`, after they press submit, and we make the `save` request to the backend, we need to re-initalize the object so the next user can start from a blank template.

**Comment by marasanders** [comment]
right so why does my original code not work?

```
vm.new_post = {};
console.log("NEW POST")
vm.create = function(){
  console.log(vm.new_post);
  vm.new_post = new PostFactory();
  console.log(vm.new_post);
  vm.new_post.$save().then(function(response){
    console.log(response)
    // vm.post_data.push(response);
    vm.new_post = {};
  });
}
```

**Comment by nolds9** [comment]
By not work, what do you mean? 

I would remove the first line where you are doing `vm.new_post` = {};

Then after you save, I would add a line `vm.new_post = new PostFactory()`

**Comment by amaseda** [comment]
@marasanders `vm.new_post = new PostFactory()` needs to go outside of `vm.create`. I would replace your first line with that.

**Comment by marasanders** [comment]
still no go - there are no params coming to my controller from my index page unless I pass them in one by one

**Comment by nolds9** [comment]
can you `console.log` `vm.new_post` right before you call `$save`?

**Comment by marasanders** [comment]
I am - empty

**Comment by nolds9** [comment]
so I see in the view you have `main-ng-controller="some controller"` you dont need that if you are using `uiRouter` to set the controller for a state. Try removing that

**Comment by marasanders** [comment]
Still empty -

**Comment by nolds9** [comment]
hmm, that's interesting. If you want to use a token, I'd be happy to take a look.

**Comment by marasanders** [comment]
your on - when's a good time

**Comment by nolds9** [comment]
i can take a look now
