### ISSUE TITLE
Storing user sessions and scheduled functions in angular

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/project3#186]
We'd like to use our first token for help with a couple things:

1) Storing user sessions
Right now we do not have user auth, but we'd like to store sessions so we can limit the # of songs a user can add to a playlist. Currently, someone could just change their name and keep submitting songs.

2) Scheduled functions
We have a function to update our Spotify playlist with the highest-voted song. It works when someone clicks a button. We would like to set this to run on an interval.

**Comment by jshawl** [comment]
2) can you use setInterval?

**Comment by jshawl** [comment]
1) don't think sessions are possible with token based auth. Instead, can you store the token used when a song is up voted server side?

**Comment by wombatdev** [comment]
We've got the real token handled through the database. We're talking about a session token for our front-end. Not connected to user auth.

**Comment by jshawl** [comment]
can you use the auth token as the session token? e.g. store the token anytime an upvote happens. reject the upvote if the `song.upvotes.where(token: blabla).count > 5`?

**Comment by wombatdev** [comment]
The spotify access token is generated when the "host" user creates the playlist, and we store it in the playlist table so when someone else on another device adds songs to the playlist, we have the token for that to happen. So ideally each of the other users would have a separate ID so I could only add 5 songs, you could only add 5 songs, Tyson could only add 5, etc.

**Comment by jshawl** [comment]
oooo. maybe when the user visits the app, you can generate a unique token and save to localstorage? then send that on every request

**Comment by wombatdev** [comment]
Works like a charm, thanks.

For setInterval, how do we set that to run ad infinitum?

One other question--during a class, I remember you figured out a way to update an ng-repeat when you deleted an object with have to use `$state.reload()`. How could we do that? Code:

```
<div class="adminsong" data-ng-repeat="song in AdminPlistViewModel.songs | orderBy: 'score' : true">
        <p><button class="button" data-ng-click="AdminPlistViewModel.remove_song(song)">&#x2717</button>
```

```
vm.remove_song = function (song) {
            song.$delete({playlist_id: vm.playlist.id, id: song.id});
            $state.reload();
        }
```

**Comment by jshawl** [comment]
setInterval runs forever! err... till a new page reload

an maybe you can `$state.go`...
