### ISSUE TITLE
Accessing a value in a json object

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project3#187]
We have a json object, `voter_ids` which has key-value pairs of `bio_id : vote`

Each `legislator` has a unique `bio_id`

How can we access the `bio_id` for the instance of our `legislator` through Angular?

For example, we are on /legislators/1 and need to access the `bio_id` of that legislator.

We have tried filters with the ng-repeat directive, creating variables in the Angular show controller, and all sorts of dot and array notation combinations with no luck.

Here's a link to the repos - https://github.com/dcordz/Congreddit_Angular
https://github.com/gardner589/Congreddit_Rails

**Comment by jshawl** [comment]
Can you do this server-side w/ rails?

e.g. create a route for `legislators/11/votes`

`.select` the voter_ids where bio_id == legistaltor id

then send back the json you want

**Comment by dcordz** [comment]
We were able to do it in the Legislators rails view with 

```
<% @votes.each do |vote| %>
    <tr>
      <td><%= JSON.parse(vote.voter_ids)[@legislator.bio_id] %></td>
      <td><%= vote.bill_id %></td>
    </tr><% end %>
```

do you mean put something in the legislators controller like

`def show
    @votes = Vote.where(@legislator.bio_id == Vote.all.voter_ids)
  end`

**Comment by jshawl** [comment]
yes exactly! need to change up the syntax but you have the right idea

**Comment by dcordz** [comment]
Actually Chris just figured it out:

Rails show controller:

```
def show
    @legislator = Legislator.find(params[:id])
    @votes_id = Vote.all.pluck(:voter_ids)
    @votes = @votes_id.each do |vote|
     @legVotes = JSON.parse(vote)
    end
    @legVotes = @votes.map do |vote|
      JSON.parse(vote)
    end
    # render json: @legislator.to_json, status: :ok
    # render json: @legislator, status: :ok
   render :json => {:votes => @legVotes, :legislator => @legislator }
  end
```

Angular show.html:

```
<tbody ng-repeat="thing in legislatorsShowVM.legislator['votes']">
    <tr>
      <td>{{thing[legislatorsShowVM.legislator["legislator"].bio_id]}}</td>
    </tr>
  </tbody>
```

Feel free to start laughing/crying

**Comment by jshawl** [comment]
👍 😢 😆
