### ISSUE TITLE
Trying to get profile_id 

### ISSUE THREAD

**Issue by SeanTay** [ga-wdi-exercises/project3#188]
I'm trying to pass in the profile_id for each story posted. but it keeps coming up on the backend as null. 

show.html 

```
  {{ProfileShowViewModel.profile.id}}
  <form name="momentsForm" ng-submit="MomentsNewController()">
    <input placeholder="Share your moment" data-ng-model="ProfileShowViewModel.story.content" />
    <input type="hidden" value="ProfileShowViewModel.profile.id" data-ng-model="ProfileShowViewModel.story.profile_id" />
    <button class="waves-effect waves-light btn" type="button" data-ng-click="ProfileShowViewModel.create()">Create</button>
  </form>
```

**Comment by jshawl** [comment]
`ProfileShowViewModel.profile.id` vs `ProfileShowViewModel.profile_id`

**Comment by jshawl** [comment]
shouldn't the value match the ng-model

**Comment by SeanTay** [comment]
ng-model is saving to the property of story 

story is nested inside profile with t.reference

**Comment by SeanTay** [comment]
I tried to put the value manually value=20 for example and it worked.

**Comment by jshawl** [comment]
does this show up in the view `{{ProfileShowViewModel.profile.id}}`

**Comment by SeanTay** [comment]
yeah when i move it out of the form it shows the value.

**Comment by jshawl** [comment]
what about inside the form, remove the hidden, does the value show correctly?

**Comment by SeanTay** [comment]
no the value is not showing even when I just put value="20" or placeholder="20"

**Comment by jshawl** [comment]
is it still hideen? can you share the code you're working with?

**Comment by SeanTay** [comment]
`<input value="20" data-ng-model="ProfileShowViewModel.story.profile_id" />`

**Comment by SeanTay** [comment]
when I switch it to placeholder it shows up now.

**Comment by jshawl** [comment]
what if you remove value? `<input data-ng-model="ProfileShowViewModel.story.profile_id" />`

**Comment by SeanTay** [comment]
okay now it shows up

**Comment by SeanTay** [comment]
`{{ProfileShowViewModel.profile.id}}
  <form name="momentsForm">
    <input placeholder="Share your moment" data-ng-model="ProfileShowViewModel.story.content" />
    <input value="ProfileShowViewModel.profile.id" />
    <button class="waves-effect waves-light btn" type="button" data-ng-click="ProfileShowViewModel.create()">Create</button>
  </form>`

**Comment by SeanTay** [comment]
```
  {{ProfileShowViewModel.profile.id}} << this is showing
<form name="momentsForm">
<input placeholder="Share your moment" data-ng-model="ProfileShowViewModel.story.content" />

    <input value="ProfileShowViewModel.profile.id" /> << this is not showing as string

    <button class="waves-effect waves-light btn" type="button" data-ng-click="ProfileShowViewModel.create()">Create</button>
  </form>
```

**Comment by SeanTay** [comment]
Input value isn't showing as a number.

**Comment by jshawl** [comment]
can you take a screenshot?

**Comment by SeanTay** [comment]
Okay this works

```
    <input value= {{ProfileShowViewModel.profile.id}} /> 
```

but when I add 

```
    <input value= {{ProfileShowViewModel.profile.id}} data-ng-model="ProfileShowViewModel.story.profile_id" />
```

It shows up as blank.

**Comment by jshawl** [comment]
and if you only have ng-model?

**Comment by SeanTay** [comment]
when I left the value blank and manual enter it with that ng-model it assigns the profile_id.

**Comment by jshawl** [comment]
oooo quotes around the curly braces?

**Comment by SeanTay** [comment]
Nope. its so weird, they are both working individually but not working together.

**Comment by jshawl** [comment]
I think you only need ng-model. do you need value?

**Comment by SeanTay** [comment]
yes because I want to hide it once it's working. so when someone write a story, it automatically take the profile_id and assign it to that story.

**Comment by jshawl** [comment]
i recommend only having ng-model - then what issue is there?

**Comment by SeanTay** [comment]
how will i pass the id to the ng-model?

**Comment by jshawl** [comment]
ng-model is set by the controller, do you mean how to access the value of ng-model?

**Comment by SeanTay** [comment]
currently I'm only taking the content.  There're no IDs associate with each content.

**Comment by SeanTay** [comment]
I can't filter the content without the id.

**Comment by jshawl** [comment]
can you share a little more code and describe the issue like:

when i _____ i expect ____ but ______ happens instead

**Comment by SeanTay** [comment]
okay. 

When I write this code 

```
<input value={{ProfileShowViewModel.profile.id}} data-ng-model="ProfileShowViewModel.story.profile_id"/>
```

I expect to get a value to show up in 

![image](https://cloud.githubusercontent.com/assets/6488375/17001688/14c12f2e-4e96-11e6-9d28-2a8132470bf1.png)

**Comment by SeanTay** [comment]
but it's blank on the second line.

**Comment by jshawl** [comment]
can you remove value=''

**Comment by SeanTay** [comment]
around the ng-model? it throws an error when i do that?

**Comment by nolds9** [comment]
so there should be no attribute `value` only the `ng-model`.

**Comment by jshawl** [comment]
```
<input data-ng-model="ProfileShowViewModel.story.profile_id"/>
```

**Comment by SeanTay** [comment]
I got it to work.  I put this in controller. 

```
      this.story.profile_id = $stateParams.id
```

**Comment by jshawl** [comment]
👍
