### ISSUE TITLE
ng-model won't work with type="hidden" on a form

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project3#189]
The input won't save data with a type="hidden" or with style: display:none. Console.log in the controller tests this when submit clicked.
https://github.com/jschultz21/project3angular/tree/commentbox (code is in concerts/index.html lines 55-59 are a few iterations of my attempts)

**Comment by jshawl** [comment]
whoah did not know this http://stackoverflow.com/a/18446730/850825

**Comment by jschultz21** [comment]
I've been trying these solutions but it's being really tricky when I try to use the value as a variable {{global.search}}

**Comment by jshawl** [comment]
tricky as in not solved or tricky as in solved, but tricky! ?

**Comment by jschultz21** [comment]
not solved, I've bee trying the ng-init to set comment.city={{global.search}} but hasn't worked yet. not sure if it's syntax or not allowed.

**Comment by jshawl** [comment]
do you have quotes around those curly braces?

**Comment by jschultz21** [comment]
```
<input type="hidden" ng-model="ConcertIndexViewModel.comment.content" value="{{global.search}}" ng-init="ConcertIndexViewModel.comment.content='{{global.search}}'"/> 
```

**Comment by jschultz21** [comment]
I'm wondering if there's a way to assign the city in the controller instead...but am not sure how to go about that.

**Comment by amaseda** [comment]
What if you try removing the single quotes from the `'{{global.search}}'` in `ng-init=`. But keep the double quotes in `value=`.

**Comment by jschultz21** [comment]
error message is `` Syntax Error: Token '{' invalid key at column 40 of the expression [ConcertIndexViewModel.comment.content={{global.search}}] starting at [{global.search}}].

**Comment by jschultz21** [comment]
woohooooo resolved using      ' vm.comment.city = $scope.global.search '

**Comment by jschultz21** [comment]
in the controller

**Comment by amaseda** [comment]
Oh nice! Good to know. Going to close this one now but re-open if something else comes up.
