### ISSUE TITLE
Adding event listener on a map marker

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project3#190]
Is it possible to redirect to a different state in a function? We created an event listener for a marker but not sure how to redirect from there. 

```

marker.addListener('click', redirectShow); //this would be in the initMap function

    function redirectShow(location, $state) {
      console.log("clicked") //this shows up in the console so we know that the event listener works
      $state.go("locationShow", ({id: location.id})); //trying to redirect to our location's show page via their ID
    }
```

This is the error that we get:
**Uncaught TypeError: Cannot read property 'go' of undefined**

**Comment by amaseda** [comment]
What happens if you use `ng-click` to trigger this function instead of a Vanilla JS event listener?

**Comment by jshawl** [comment]
need to inject `$state` into the controller that's running that code

**Comment by kristinmaripasive** [comment]
it was already there when the wild error appeared

```
  .controller("MapIndexController", ["LocationFactory", "$state", "$stateParams", MapIndexControllerFunction])
```

**Comment by jshawl** [comment]
can i see mapindexcontrollerfunction definition?

**Comment by kristinmaripasive** [comment]
```
function MapIndexControllerFunction(LocationFactory){
      // this.locations = LocationFactory.query()
      var vm = this;
      var marker;
      vm.initMap = function() {
        var latlng = new google.maps.LatLng(38.904864, -77.033996);
        var myOptions = {
          zoom: 18,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
        myOptions);

        LocationFactory.query().$promise.then(function(locations){
          console.log(locations)

          locations.forEach(function(location){
            var image = 'http://i.imgur.com/MuAdxDX.png';
            var markerLatLng = new google.maps.LatLng(location.latitude, location.longitude)
            var marker = new google.maps.Marker({
              animation: google.maps.Animation.DROP,
              position: markerLatLng,
              icon: image

            });
            marker.setMap(map);
            marker.addListener('click', redirectShow);
          });
        });

    // To add the marker to the map, call setMap();

    }

    function redirectShow(location, $state, $stateParams) {
      console.log("clicked")
      $state.go("locationShow", ({id: location.id}));
    }





  }
```

**Comment by amaseda** [comment]
What happens if you pass `$state` in as an argument to `MapIndexControllerFunction`?

**Comment by kristinmaripasive** [comment]
the wild error still attacks

**Comment by amaseda** [comment]
Is there a reason you're not defining the function like...

```
vm.redirectShow = function(location, $state, $stateParams) {
   console.log("clicked")
   $state.go("locationShow", ({id: location.id}));
}
```

It may not know about `$state` because of that.

And while you're at it, should probably pass in `$stateParams` as an argument to your control since you're referencing it.

**Comment by nolds9** [comment]
so where you define your controller function, you need to make sure to pass in all dependencies in the order you injected them...
I.e. if you have a controller that looks like `.controller("MapIndexController", ["LocationFactory", "$state", "$stateParams", MapIndexControllerFunction])`

Your function should look like:
`function MapIndexControllerFunction(LocationFactory, $state, $stateParams){...}`

**Comment by kristinmaripasive** [comment]
@amaseda yes, cause when I define it that way, it throws me this error:
ReferenceError: redirectShow is not defined

**Comment by kristinmaripasive** [comment]
and when I define it to var redirectShow on the top, it throws me this:
Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by nolds9** [comment]
Another idea for a possible work around is to add a link that will take them to the correct state, directly to the marker.

You should be able to do that by adding a `title` property to each marker, i.e.

``` js
var marker = new google.maps.Marker({
              animation: google.maps.Animation.DROP,
              position: markerLatLng,
              icon: image
              title: "<a data-ui-sref='locationShow({id:" + location.id + "})'>" + location.title + "</a>"
            });

```

**Comment by kristinmaripasive** [comment]
@nolds9 I see the logic in that, but the thing is its throwing me a syntax error when I inject title. I tried googling the syntax and putting a temporary title in there.... still throwing me a syntax error of unexpected identifier

**Comment by nolds9** [comment]
I think my example was missing a comma after `icon: image`

the docs seem to say you can set a title https://developers.google.com/maps/documentation/javascript/markers

**Comment by kristinmaripasive** [comment]
oh yes, thanks, it was that comma. Error ran away!

I don't see a title though.... where is it supposed to show on the map?

**Comment by nolds9** [comment]
when you hover over a marker?

**Comment by kristinmaripasive** [comment]
oh i see it now, but it's not clickable... it's literally just showing <a data-ui-sref='locationShow({id:2 })'>General Assembly </a>

**Comment by kristinmaripasive** [comment]
it's showing this I mean:

```
<a data-ui-sref='locationShow({id:2})'>General Assembly</a>
```

**Comment by nolds9** [comment]
hmmm, I would just mess with the syntax then. another possibility is to make it into an info window
https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

**Comment by kristinmaripasive** [comment]
This was super effective! Thanks! This can be closed :)
