### ISSUE TITLE
Circular Dependency Error?!?

### ISSUE THREAD

**Issue by BlvckYuppie** [ga-wdi-exercises/project3#191]
![screen shot 2016-07-20 at 4 42 43 pm](https://cloud.githubusercontent.com/assets/18303341/17002430/3cb98dde-4e99-11e6-9746-5e78d5279f01.png)
![screen shot 2016-07-20 at 4 42 37 pm](https://cloud.githubusercontent.com/assets/18303341/17002433/42782c08-4e99-11e6-9660-1c292fa8a666.png)
![screen shot 2016-07-20 at 4 42 30 pm](https://cloud.githubusercontent.com/assets/18303341/17002446/4d6106d0-4e99-11e6-9805-cb881f0e5337.png)

**Comment by amaseda** [comment]
You're not injecting `MonumentFactory` as a dependency into `EncounterIndexController`. I'm guessing that's causing it.

**Comment by jshawl** [comment]
can we see monument factory code?

**Comment by BlvckYuppie** [comment]
![screen shot 2016-07-20 at 4 48 08 pm](https://cloud.githubusercontent.com/assets/18303341/17002555/d39b9b20-4e99-11e6-80bd-8278ca4f9978.png)

**Comment by jshawl** [comment]
can you remove line 8?

**Comment by BlvckYuppie** [comment]
That set off a series of error fixes that leaves us errorless. But i thought the whole purpose of us passing the various factories as dependencies was so that we could use info from other controllers  concurrently.  We really just want to be able to show pokemon and locations on the same page

**Comment by nolds9** [comment]
nice 👍 !  The factories are separated and should not depend on one another because they are just a datasource. In the controller, you can inject multiple factories and use them to display different sets of data

**Comment by BlvckYuppie** [comment]
![screen shot 2016-07-21 at 12 28 37 pm](https://cloud.githubusercontent.com/assets/18303341/17032857/60d447da-4f49-11e6-96f9-aff9fd559c6c.png)
