### ISSUE TITLE
Updating and Deleting Nested Data. 

### ISSUE THREAD

**Issue by SeanTay** [ga-wdi-exercises/project3#192]
```
this.getstory = StoryFactory.get({id: $stateParams.id})

    this.update = function(){
      this.getstory.$update({id: $stateParams.id}).then(function(){
        $state.go("ProfileShow",{id: $stateParams.id},{reload:true})
      })
    }

    this.destroy = function(){
      this.story.$delete({id: $stateParams.id}).then(function(){
        console.log("delete function working")
        $state.go("ProfileShow",{id: $stateParams.id},{reload:true})
      })
```

I currently have $stateParams.id  but I know i need to change that. just not sure what to put in there.  I'm trying to update stories, which are nested on the backend inside profile. 

First we need to the specific story.  Not sure how to start.

**Comment by nolds9** [comment]
@SeanTay what does your `StoryFactory` look like.

At a high level: 
- From an angular perspective, whenever you call a method on `StoryFactory` you'll need to pass a `profile_id`

**Comment by SeanTay** [comment]
![image](https://cloud.githubusercontent.com/assets/6488375/17003351/9ae09cd2-4e9d-11e6-9e86-393e64b87211.png)

so yeah I figure we'll have to pass the profile_id but we also have a particular story id. 

We're displaying all of the story on profile page so the I can't even use it through the stateParams.

**Comment by nolds9** [comment]
Do you have a line somewhere that looks similar to this?

``` js
StoryFactory.query({profile_id: $stateParams.id})
```

**Comment by SeanTay** [comment]
I can't even get the stories to show up.  I think I'm gonna use the token.
