### ISSUE TITLE
How to save a search url so it can be re-used

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/project3#193]
In the index controller, I have code on line 26 that updates the url based on the city searched for by the user. The link looks like this, http://localhost:8080/#/concerts?city=Austin, but I want the user to be able to use that link to return to that same search. Ie, when the url is entered, the page pulls the city and runs the search automatically. Is this possible without adding a new state and moving all of the code off the concerts index.html view to a concerts/city view?

Here's the repo: https://github.com/jschultz21/project3angular/tree/url-search-save

**Comment by amaseda** [comment]
Assuming you can access the "city" value in the URL using `$stateParams.city`, I would try two things...
1. In your controller, have some code that immediately executes if `$stateParams.city` exists. In this conditional, execute whatever code you want (e.g., make an API call, set `vm.concerts`).
2. If that doesn't work, use `ng-init` to trigger a function that contains the code you wrote in the first option. This will run that function whenever the template is loaded. [Here's the documentation](https://docs.angularjs.org/api/ng/directive/ngInit).

**Comment by jschultz21** [comment]
and if I don't have access to $stateParams.city? 

I think the url is updating superficially, but I have access to its city via $location.search here: 

`` var searchObject = $location.search();
    console.log(searchObject.city)

```
var vm = this
vm.concerts = ConcertFactory.query();
$scope.changeUrl = function(){
  $location.search('city', $scope.global.search);
  console.log($stateParams)
}
```

**Comment by amaseda** [comment]
Oh, if you have access to it with `$location.search` then just use that.

**Comment by nolds9** [comment]
going to go ahead and close this, feel free to open another one if the issue persits
