### ISSUE TITLE
Parsing two json files

### ISSUE THREAD

**Issue by kristinmaripasive** [ga-wdi-exercises/project3#194]
We're currently trying to get a comment feature on our app. We've created a comment factory for it and its source is pointing to "http://locahost:3000/locations/:location_id/comments/:id"... We're trying to pass our seeds in there and we think the problem is parsing our **comments_data.json** file. Is there a way we can parse through multiple json files? This is how our seeds.rb is looking like:

```
# Comment.destroy_all
# Location.destroy_all
# locations = Location.create([
#   {name: "Postpub", address: "1422 L St NW, Washington, DC 20005"},
#   {name: "General Assembly", address: "1133 15th St NW, Washington, DC 20005"},
# ])
# Comment.create([
#   {title: "First comment", body: "This is a great bathroom!" , location: locations[0]},
#   {title: "Second comment", body: "This is a terrible place!" , location: locations[1]},
# ])


data = JSON.parse(File.read("db/locations_data.json"))
Location.destroy_all
Location.create!(data)
```

**Comment by nolds9** [comment]
@kristinmaripasive So is there any particular reason you need your data in `JSON` files?
I would recommend simplifying and just doing your seeds with ActiveRecord....

**Comment by kristinmaripasive** [comment]
Oh if we do that, will we still be able to inject the data here "http://localhost:3000/locations/1/comments.json"?

**Comment by nolds9** [comment]
yep, how you seed your database will not affect how Rails servers that data as `JSON`

**Comment by kristinmaripasive** [comment]
Oh, so if we're trying to place two modules in one controller, is it going to be two separate ones? Would that be possible? Cause we need the LocationFactory and the CommentFactory?

```
(function(){
  angular
  .module("locations")
  .module("comments") //is this possible?
  .controller("LocationShowController", ["LocationFactory", "$stateParams", "CommentFactory", LocationShowControllerFunction])




  function LocationShowControllerFunction(LocationFactory, $stateParams, CommentFactory){
    console.log($stateParams);
    this.location = LocationFactory.get({id: $stateParams.id});

    this.comment = CommentFactory.query()
    var vm = this;
    this.comment = new CommentFactory();
    this.create = function(){
      console.log("commented")
      this.comment.$save().then(function(response){
        vm.comments.push(response)
        $state.go("locationShow", ({id: response.id}));
      })
    }
  }
})();
```

**Comment by nolds9** [comment]
No, in this example, the controller will only be defined on `comments`.  What's the end goal?
Because you can always create a second module and define new controllers on that, the only thing you need to then make sure to do is inject the new module into the main one

**Comment by kristinmaripasive** [comment]
Oh yeah I injected the new module to the main one. The end goal would be to have seeds in our json for comments. That way, we know our database for that is up, then we cans start with CRUD. What I've already done to get it set up:
1. Created a comment factory
2. Placed some seeds for comments in the seed file
So, now, I'm basically trying to pass the comment factory in my show.controller.js, but the location factory is in there

**Comment by nolds9** [comment]
you can have multiple factories for one controller

**Comment by kristinmaripasive** [comment]
For our comments controller though, it has **.module("comments")** or can we just use the same module for locations?

**Comment by nolds9** [comment]
I would say, unless you have separate states for comments, then i think you are fine putting it all under `locations`. Theoritically, I think all the comment behavior will happen on the `location` show page, so everything would go in the `locationShow` controller

**Comment by kristinmaripasive** [comment]
Exactly, yes. That makes sense. So now, I'm trying to pass my seeds but I keep getting an error:
NameError: undefined local variable or method `locations' for main:Object

This is how my seeds.rb is right now:

```
# Comment.destroy_all
# Location.destroy_all
# locations = Location.create([
#   {name: "Postpub", address: "1422 L St NW, Washington, DC 20005"},
#   {name: "General Assembly", address: "1133 15th St NW, Washington, DC 20005"},
# ])
# Comment.create([
#   {title: "First comment", body: "This is a great bathroom!" , location: locations[0]},
#   {title: "Second comment", body: "This is a terrible place!" , location: locations[1]},
# ])

Comment.create(title: "First comment", body: "This is a great bathroom!" , location: locations[0])
Comment.create(title: "Second comment", body: "This is a terrible place!" , location: locations[1])


data = JSON.parse(File.read("db/locations_data.json"))
Location.destroy_all
Location.create!(data)
```

**Comment by nolds9** [comment]
that's because `locations` doesn't exist. I think you need to uncomment where you are defining it before you create comments

**Comment by kristinmaripasive** [comment]
when I do that, there are no errors on seeding but now I can't seem to navigate through each location with an id in the url. It's giving us this error:
ActiveRecord::RecordNotFound in LocationsController#show

I think I'm confused between having our seeds for locations inside our locations_data.json and also now in our seeds.rb?

**Comment by kristinmaripasive** [comment]
And on our browser, it's giving us the Error: [$injector:modulerr] but we already placed our scripts for our new comment.factory.js and comments.js

**Comment by nolds9** [comment]
that error could be caused by a lot of things, I would double check your syntax, and make sure you are not missing any commas in the array of dependencies. As far as record not found - make sure you are using `/#/locations/some id` to navigate in the browser.

**Comment by kristinmaripasive** [comment]
The injector module error was complaining about using the same locations module. So I had to change it back to .module("comments") for comments.controller.js
