### ISSUE TITLE
Passing new factory object from angular to rails as params

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/project3#195]
I'm trying to create a new comment on a show page using a factory in angular and the create method in my rails app. Comments are nested under legislators in rails.

I've been trying a few things here, it seems like the inputs from the show page are not being passed to the create function in the angular show controller, is there something wrong with my ng-model?

repos:
https://github.com/gardner589/Congreddit_Rails
https://github.com/dcordz/Congreddit_Angular

Here are the params as they are being passed now, the legislator_comment section is blank:

```
<ActionController::Parameters {"controller"=>"legislator_comments", "action"=>"create", "legislator_id"=>"1", "legislator_comment"=>{}} permitted: false>
```

new and create comment in legislator Show controller (angular)

```
this.legislator_comment = new legislatorsFactory.legislator_comments();

      this.create = function() {
        this.legislator_comment.$save({legislator_id: $stateParams.id});
      }
```

legislators factory, the legislator_comments is inside

```
function legislatorsFactoryFunction($resource) {
      return {
        legislators: $resource("http://localhost:3000/legislators/:id", {}, {}),

        legislator_comments: $resource("http://localhost:3000/legislators/:legislator_id/legislator_comments/:id", {}, {update: {method: 'PUT'}}),

        votes: $resource("http://localhost:3000/legislators/:id/votes",  {}, {
          'query': {method: 'GET', isArray: true}
        })
      }
    }
```

and finally, show.html for legislators in angular

```
<form>
        <td><input name="author" placeholder="Author" data-ng-model="legislatorsShowVM.legislator.legcomments.author" /></td>
        <td><input name="content" placeholder="Comment" data-ng-model="legislatorsShowVM.legislator.legcomments.content" /></td>
        <td><button ng-click="legislatorsShowVM.create()">Create</button></td>
</form>
```

**Comment by amaseda** [comment]
In `show.html`, should data-ng-model be pointing to `legislatorsShowVM.legislator_comment` instead of `legislatorsShowVM.legislator.legcomments`? It seems that you've defined the new comment as the former in your controller.

**Comment by dcordz** [comment]
yeah, that was it, damnit....

**Comment by amaseda** [comment]
Progress!
