### ISSUE TITLE
heroku deploy issues 

### ISSUE THREAD

**Issue by SeanTay** [ga-wdi-exercises/project3#197]

**Comment by SeanTay** [comment]
I'm getting an error regarding bad connection to pg.  Not sure how to fix that.  It was on sqlite but I deleted all the files and coverted the data to postgres.

**Comment by jshawl** [comment]
what is the output of `heroku logs`

**Comment by SeanTay** [comment]
`remote:  !
remote:  !     Precompiling assets failed.
remote:  !     Attempted to access a nonexistent database:
remote:  !     https://devcenter.heroku.com/articles/pre-provision-database
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !   Push rejected to group7-datingapp.`

**Comment by SeanTay** [comment]
I just checked the postgres and database is there.

**Comment by jshawl** [comment]
what if you try `heroku pg:reset`

**Comment by SeanTay** [comment]
must specify database to reset.

**Comment by jshawl** [comment]
`heroku config:get DATABASE_URL`

**Comment by SeanTay** [comment]
Okay it says your app has no databases.

**Comment by jshawl** [comment]
`heroku run rake db:create` ?

**Comment by SeanTay** [comment]
$ heroku run rake db:create

Running rake db:create on ⬢ group7-datingapp... up, run.5373

bash: rake: command not found

**Comment by jshawl** [comment]
hmm what?! maybe try destroying the heroku app and recreating

**Comment by SeanTay** [comment]
still the same error.

**Comment by SeanTay** [comment]
PG::ConnectionBad: could not connect to server: Connection refused

**Comment by jshawl** [comment]
can you share a link to your rails api code

**Comment by SeanTay** [comment]
database.yml

do i need username and password under production?

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: project_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username:
  password:

```

**Comment by SeanTay** [comment]
https://github.com/SeanTay/datingapp-rails

**Comment by jshawl** [comment]
ooooo can you remove username and password

**Comment by SeanTay** [comment]
still doesn't like it.

**Comment by jshawl** [comment]
output of heroku logs?
