### ISSUE TITLE
Heroku X Show page issues X 2

### ISSUE THREAD

**Issue by BlvckYuppie** [ga-wdi-exercises/project3#198]
After deploying api to heroku, our character page index page no longer shows information.  Of greater importance to eventual app functionality, we are having a hard time figuring out how to use our encounters api class in our pokemon / monument angular show pages. Given enough time, i could figure out both issues, but we have 2 hours, hence tokens... 

If possible, we'd like to use our two remaining tokens concurrently so that we have the maximum amount of instructor muscle available

**Comment by BlvckYuppie** [comment]
the key value pairs in our deployed data base are different than the ones in my local db ={  

that defines the root of the first problem, but i'd like help (even if its just instructor pair programming) to fix it because of time constraints

**Comment by amaseda** [comment]
Give me a few minutes and will come by.

**Comment by BlvckYuppie** [comment]
sweet
