### ISSUE TITLE
Question on app deployment...

### ISSUE THREAD

**Issue by jhugheswebdev** [ga-wdi-exercises/project3#199]
If we deploy would that affect the localhost resource that we put inside our factories?
Also, can we deploy Angular in the same file in Heroku or does it have to be deployed in GH pages?
Our Rails & Angular are not integrated, they're just in one folder inside our repo.

**Comment by jshawl** [comment]
if you keep your factory resource urls at localhost, your app will only work if the user viewing your app has the local api running

**Comment by jshawl** [comment]
Angular app can be same repo as heroku app, as per nick's lesson last week, though it might be easier to host on gh-pages if they are currently separate apps

**Comment by nolds9** [comment]
If your app is an angular on rails app, you change all the urls in the factories to be relative (remove the 'http://local host:3000'). Otherwise if your apps are separate you would deploy the rails api and then change your factories urls to point to the deployed url

**Comment by jhugheswebdev** [comment]
We're trying to deploy to Heroku and it keeps giving us this error

```
NameError: Uninitialized constant Rack::Cors

```

We had that gem before but we've deleted it & its still giving us the same error...

**Comment by nolds9** [comment]
thats probably due some old Config files, I would just add the gem back and then bundle install, make a new commit, and then try again.

**Comment by jhugheswebdev** [comment]
should we include 

```
require 'rack/cors'
use Rack::Cors do


  allow do
    origins '*'
    resource '*', 
        :headers => :any, 
        :methods => [:get, :post, :delete, :put, :options]
  end
end

```

in the config.ru?

**Comment by nolds9** [comment]
are you trying to setup Rack Cors, if so I would look at the instructions here https://github.com/cyu/rack-cors#rails

**Comment by jhugheswebdev** [comment]
We tried all the steps but we're still getting the same Rack::Cors error

**Comment by nolds9** [comment]
ill come take a look
