### ISSUE TITLE
issues with promises

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/project3#20]
I've been unable to use mongoose methods in conjunction with promises and I'm not sure why.  For example, this code runs fine:

``` js
var ProfileModel = require("./models/profile");

app.get("/", function(req, res){
  var allProfiles = ProfileModel.find({});
  console.log(allProfiles);
  res.send("hi");
});
```

But since I'm not using a promise, the thing that gets printed isn't profiles, it's a giant mongoose call.

My understanding is that I need to chain that call with .then to access the actual results of the search.  Like this:

``` js
var ProfileModel = require("./models/profile");

app.get("/", function(req, res){
  ProfileModel.find({}).then(function(profiles){
     console.log(profiles);
  })
  res.send("hi");
});
```

But that results in this error: "TypeError: ProfileModel.find(...).then is not a function at Object.handle (/home/thomas/wdi/projects/project3/gitstamps/index.js:12:25)" when it runs.

I'm requiring ProfileModel from models and I can use that model to edit my database using new and save, so it's working at least that much, but whenever I try to use promises I run into this issue.

**Comment by amaseda** [comment]
@solowt 

What happens if, instead of using `.then`, you pass in a callback to `.find()` after the empty object? So something like this...

``` js
ProfileModel.find({}, function (err, profiles) {
  console.log( profiles );
});
```

**Comment by solowt** [comment]
Ah, that worked.  I did try that, but I didn't pass in err before profiles so it was just printing null, which I guess was the error.

Do you know why .then isn't working?  I'd much rather use that over just passing the function if possible.

**Comment by amaseda** [comment]
To be honest, I haven't used promises with Mongoose myself. But apparently it is possible. Check this link out: [http://eddywashere.com/blog/switching-out-callbacks-with-promises-in-mongoose/](http://eddywashere.com/blog/switching-out-callbacks-with-promises-in-mongoose/).

Will play around with this and see if I can come up with some more helpful info.

Let me know if you have any additional questions. If not, I'll leave you to close this issue. Thanks!

**Comment by solowt** [comment]
Ahhhh, mongoose version must be the issue.  The version in our project is 3.8 and it looks like you need at least 4.0 to use promises like that.

**Comment by solowt** [comment]
Yep, that worked.  Thanks for your help, closing issue.

**Comment by amaseda** [comment]
:+1:
