### ISSUE TITLE
QUICK!!!! 

### ISSUE THREAD

**Issue by BlvckYuppie** [ga-wdi-exercises/project3#200]
We're trying to access the information from our respective factories to populate on our encounters show page.    we're pretty sure the code in our EncounterShowFunction is correct 

```
"use strict";

(function(){
  angular
  .module("encounters")
  .controller("EncounterShowController", [
    "EncounterFactory",
    "$stateParams",
    EncounterShowControllerFunction
  ]);

  function EncounterShowControllerFunction(EncounterFactory, $stateParams){
vm.encounter = EncounterFactory.get({id: $stateParams.id}, function(){
  vm.character = CharacterFactory.get({id: vm.encounter.character_id});
  vm.monument = MonumentFactory.get({id: vm.encounter.monument_id});
});
  }
}());


```

but we're not sure how to write it in the show.html 

```

<h2>{{vm.monument.site}}</h2>
<h2>{{vm.character.name}}</h2>


```

we're getting this error 

![screen shot 2016-07-21 at 12 11 26 pm](https://cloud.githubusercontent.com/assets/18303341/17030182/5fe44666-4f3c-11e6-9dd2-e7a695845b4f.png)

**Comment by nolds9** [comment]
@BlvckYuppie where is `vm` defined? You need to specify that in the state definition

**Comment by BlvckYuppie** [comment]
Our App Controller used to look like this 

```
.state("encounterShow", {
        url: "/encounters/:id",
        templateUrl: "js/encounters/show.html",
        controller: "EncounterShowController",
        controllerAs: "EncounterShowViewModel"
      });

```

and it now looks like 

```
.state("encounterShow", {
        url: "/encounters/:id",
        templateUrl: "js/encounters/show.html",
        controller: "EncounterShowController",
        controllerAs: "vm"
      });
```

but we're still getting this 

![screen shot 2016-07-21 at 12 19 33 pm](https://cloud.githubusercontent.com/assets/18303341/17030431/703d50d8-4f3d-11e6-8607-0a64a5ef0ab1.png)

**Comment by nolds9** [comment]
look in your `EncounterShowControllerFunction`, do you have a line that looks like this: `var vm = this;` if not add that as the first line in your controller

**Comment by BlvckYuppie** [comment]
![screen shot 2016-07-21 at 12 28 37 pm](https://cloud.githubusercontent.com/assets/18303341/17030701/b0e90676-4f3e-11e6-9adf-ff01f8663559.png)

**Comment by amaseda** [comment]
It's complaining about a `.get` statement, probably the one having to do with retrieving a character. What does that look like in your code?

**Comment by BlvckYuppie** [comment]
this one??? 

```
"use strict";

(function(){
  angular
  .module("encounters")
  .controller("EncounterShowController", [
    "EncounterFactory",
    "$stateParams",
    EncounterShowControllerFunction
  ]);

  function EncounterShowControllerFunction(EncounterFactory, $stateParams){
vm.encounter = EncounterFactory.get({id: $stateParams.id}, function(){
  vm.character = CharacterFactory.get({id: vm.encounter.character_id});
  vm.monument = MonumentFactory.get({id: vm.encounter.monument_id});
});
  }
}());
```

**Comment by BlvckYuppie** [comment]
do we have to write this code in all of our show controllers? 
just spitballing

**Comment by nolds9** [comment]
@BlvckYuppie so you need to make sure to inject `MonumentFactory` and `CharacterFactory` into this controller. The reason the  code is not working inside the callback is because you don't have access to `vm.encounter` inside the callback because it hasnt been set yet.

**Comment by nolds9** [comment]
You should be able to work around this by passing the returned object as an argument to the callback function, then using that object's id to get the right Character and Monument

**Comment by BlvckYuppie** [comment]
like so?

```
function EncounterShowControllerFunction(EncounterFactory,CharacterFactory,MonumentFactory, $stateParams){
  var vm = this;
vm.encounter = EncounterFactory.get({id: $stateParams.id}, function(CharacterFactory, MonumentFactory){
  vm.character = CharacterFactory.get({id: vm.encounter.character_id});
  vm.monument = MonumentFactory.get({id: vm.encounter.monument_id});
});
  }
```

**Comment by nolds9** [comment]
not exactly, try using a promise: 

``` js
function EncounterShowControllerFunction(EncounterFactory,CharacterFactory,MonumentFactory, $stateParams){
  var vm = this;
  EncounterFactory.get({id: $stateParams.id}).$promise.then(function(encounter) {
    vm.encounter = encounter;  
    vm.character = CharacterFactory.get({id: encounter.character_id});
    vm.monument = MonumentFactory.get({id: encounter.monument_id});
  })
}
```

**Comment by nolds9** [comment]
going to go ahead and close this but feel free to reopen

**Comment by BlvckYuppie** [comment]
Still no results =(

**Comment by nolds9** [comment]
what errors are you getting? What did you try? What did you expect to happen?

**Comment by BlvckYuppie** [comment]
we're getting a 500 error now

**Comment by nolds9** [comment]
so thats probably due to some issue on the backend

**Comment by BlvckYuppie** [comment]
we entered the code you suggested, the page is now blank and we're getting an internal server error

**Comment by nolds9** [comment]
can you inspect the request, and see what the error is?

**Comment by BlvckYuppie** [comment]
![screen shot 2016-07-21 at 1 45 53 pm](https://cloud.githubusercontent.com/assets/18303341/17032878/7e21f850-4f49-11e6-8353-6ed566029749.png)

**Comment by nolds9** [comment]
can click on preview

**Comment by BlvckYuppie** [comment]
apparently its trying to get 8.json and not characters/8.json or monuments/8.json?
