### ISSUE TITLE
Nav Template

### ISSUE THREAD

**Issue by SeanTay** [ga-wdi-exercises/project3#201]
After deploying my nav bar template is not working. it's saying js/nav/_auth.html has 404 error. but when I run it on localhost the nav bar shows up. I don't know whats going on.

**Comment by nolds9** [comment]
Interesting, this might be because of the path to the templates...what does your `templateUrl` look like and the file structure for your angular app?

**Comment by SeanTay** [comment]
templateUrl: "js/nav/_auth.html"

thats the file structure for our angular.

**Comment by amaseda** [comment]
Closing this since we discussed IRL. Looks like it's a gh-pages thing. Feel free to re-open if you have any more questions / developments.
