### ISSUE TITLE
Sojourn: the collaborative vacation-planning application

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#208]
There's not much better than vacationing with friends and loved ones - but coordinating travel, lodging, itinerary, and all the intricate details across several different people means your phone calls and email can quickly get out of hand. 

What if there was an application where you could centralize and collaborate on your trip plans?

A Trello-inspired Single Page Application, Sojourn will allow users to plan their trips - from plane tickets to hotel deals to fun destination activities - and share their creations with others.

Alternate names: Trippr, Travlr, Caravan

**Comment by megancoyle** [comment]
group 6

**Comment by brizzi10** [comment]
Group 6

**Comment by megancoyle** [comment]
we're going to incorporate a brainstorming functionality with this somehow. merging those group ideas ^_^
