### ISSUE TITLE
Git question

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project3#21]
Our team has one master branch on git. I had the same master on my local machine and on my remote. I created another branch locally (called workout_view) to work on the view in case I couldn't get it to work. It worked so I pushed the new branch to my remote repo. That was not a problem as it showed up as a new branch on my remote repo. 

Then I made a pull request from the new workout_view branch to my team's master thinking that it would make a workout_view branch there. Well, it didn't. I think the workout_view branch just merged into the master branch because I don't see a workout_view branch on our remote repo. 

What I did:
1. checked out new branch "workout_view" on local
2. pushed "workout_view" to my remote master
3. pull request from "workout_view" on remote to team's master
4. clicked merge pull request (I don't remember what the button said but it shows up after you do a pull request)

Questions: 
1. What happened?
2. How do I duplicate a branch on my remote repo into my team's repo without changing the master branch? Or is this not the correct process?
3. What is the best process to do something like this?

**Comment by jsm13** [comment]
This is correct that the pull came from workout_view was pulled into master. More [here](https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository). Best practice would be make the PR when you are ready to merge to changes. If someone else wants to see those changes without applying them to master, somebody should make a new branch in the original repo for the feature. Everybody working on that feature can push to the feature branch and then when it's done merge it into the master

**Comment by Ly900** [comment]
Ahh I see. Thank you!
