### ISSUE TITLE
Ben Brizzi - Find nearest free/semi-clean restroom in city

### ISSUE THREAD

**Issue by brizzi10** [ga-wdi-exercises/project3#214]
I am on a health kick where I drink a lot of water. Like stupid amounts. One of the biggest drawbacks of this excessive hydration is my own lack of city instincts; finding reliable public restrooms, where I won't have to make a small purchase to use their toilet, has been a real struggle.

A single page app that could direct me to the nearest free restroom, and perhaps even feature reviews regarding cleanliness, etc, would simply be fantastic. There is nothing worse than asking 6 places if they have an available restroom, only to finally arrive at one, realize it's gross, go anyway, then get hounded on the way out for not spending any money.

It could be called City Toilet. heh.

**Comment by aubreynortham** [comment]
I want you call this app "Flush your Fears Away"

**Comment by ghost** [comment]
Whizzr
