### ISSUE TITLE
Photo album sharing

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project3#216]
Why do we still come back from vacations and narrate photo slideshows to our friends/family like it's 1855? This super sleek photoshare app will let you create a log of your places visited, and when you click on any given destination, the show view will be a full background image of your photo, so it will feel like the viewer is standing ON THE CLIFF/wherever you took your pic. Right/left arrows to toggle through pics. You'll be able to add/delete/edit pics, and each pic will have properties that would be overlaid like captions or popovers (title = the location, recap = something interesting to say about the photo, etc.. maybe a background song you can play for ambiance)

**Comment by jacahn** [comment]
Group 2

**Comment by chaseTfreeman** [comment]
Yea Group 2!
