### ISSUE TITLE
Donation Station

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#220]
Angular on rails app:
I'd like to build an app that would help facilitate food donations from restaurants that have excess food. 

The hardest part about one of these drives right now is getting things coordinated between volunteers, the restaurants, nonprofit staff and syncing up on a volunteer day (also the majority of volunteers in this day and age are on the other end of the tech curve Apps are scary!). 

Problem: Restaurants don't all have the same schedule and will not put in any effort as far as transporting donations.

Solution:
First:
Restaurants are able to post and update food that they have to donate (location amount etc populated on a map/detail view) (Giant posting map board).

This posting is available in the donation affiliates view(shelters churches etc who sign up). They are able to accept a posting agreeing to be available to pick up that food.

Larger Solution: Allow individual views for donation affiliates volunteers so that their affiliate volunteers can download the app and work off of the pickups established.

**Comment by michaelmahony** [comment]
Group Chris, Mike, John
