### ISSUE TITLE
A People's Guide to Washington DC: forget about monuments and museums, this is an app curated by locals and travelers with their best recommendations about what to do in town.

### ISSUE THREAD

**Issue by GioSilva** [ga-wdi-exercises/project3#221]
A People's Guide to Washington DC

A DC tourist guide created by locals and travelers, this is a guide that focuses on the real DC as a creative, culturally diverse city with lots of hidden spots and events happening, for those visiting town who want more than a monuments and memorials tour. This is a Wikipedia-like app, where users can constantly update the contents. User interface will rely heavily on maps, photo and video.

**Comment by RasheedaAlexander** [comment]
group 1
