### ISSUE TITLE
trying to deploy

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/project3#229]
Hello,

I am trying to deploy our project. I have created an app with heroku and cannot push to heroku master. This is the error I get: 
![deploy](https://cloud.githubusercontent.com/assets/20133878/17863776/24c5977e-6869-11e6-891f-45ee7dd1d9f4.png)

I tried updating the buildpack by running  heroku buildpacks:set heroku/ruby  but it failed to detect the set buildpack. 

Does this have something to do with the buildpack or am I missing something?

**Comment by superbuggy** [comment]
do you have the 12-factor gem installed?

**Comment by danielanoir** [comment]
Yup

**Comment by superbuggy** [comment]
ok good! I would just verify that you have  `gem "rails_12factor"` in your `Gemfile` if you didn't run `bundle install` and commit the resulting changes, i'd try that next.

**Comment by danielanoir** [comment]
The gem is listed when I ran bundle install again. I did git add and git commit, but when I try git push heroku master I get this error: 

![screenshot from 2016-08-22 13-56-34](https://cloud.githubusercontent.com/assets/20133878/17865367/4753758e-6870-11e6-9b81-290bb9dc701c.png)

**Comment by superbuggy** [comment]
Hrm... what about if you delete the heroku app and then recreate by running `heroku create DAPi --buildpack heroku/ruby`

where *DAPi is whatever you want to call your app

**Comment by superbuggy** [comment]
`heroku apps:destroy --app example` where example is the name of your app

**Comment by danielanoir** [comment]
Thanks. I just tried that and it says no such app as dappi-app. 

![screenshot from 2016-08-22 14-08-41](https://cloud.githubusercontent.com/assets/20133878/17865879/46869d64-6872-11e6-84d2-0a461352fd2f.png)

**Comment by superbuggy** [comment]
try `heroku apps` to see your heroku apps listed

**Comment by danielanoir** [comment]
OK, dapi-app is there. I'm not sure why heroku can't see it

**Comment by danielanoir** [comment]
Would it matter that I'm on a branch right now and not the master? I tried it from the master too and was getting the same errors, but could that be a problem?

**Comment by superbuggy** [comment]
I would retry removing the app

**Comment by danielanoir** [comment]
I tried that a few more times. Pam and I also tried to add a package.json file following steps from this article (excluding adding this since we aren't using node): 

`heroku buildpacks:set heroku/nodejs
`

 http://crypt.codemancers.com/posts/2016-03-18-rails-webpack-heroku/

**Comment by superbuggy** [comment]
what happens when you try to remove (`heroku apps:destroy --app <thename_ofyour_app>`) the heroku app listed in `heroku app`?

**Comment by superbuggy** [comment]
if we can't clear the issue up, maybe it'd make sense for you to use a token

**Comment by danielanoir** [comment]
Hi James. thanks again for your help! Should my origins on the config.ru file look like this?: 

`origins 'https://danielanoir.github.io/project3/#/categories', '127.0.0.1:3000'`

Or should I be replacing the numbers with something else?

**Comment by danielanoir** [comment]
It's all working!! 

I have one last question. How should we be updating and deploying when we make changes? Do all the changes have to be made in these two separate branches instead of the master? Or can I somehow push both branches to master?
