### ISSUE TITLE
how to run post for new user without handlebars 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#23]
We are using one html page to handle the singup and login I can get the form to show up on our page but when I click submit it says it cannot post, I just need some guidance on what files I should look at to change in order to get post to work from our one index.html page.

**Comment by RobertAKARobin** [comment]
Can you show more of what the error looks like?

Also, do you have a route defined to handle the POST? It'd look something like `app.post(...`

**Comment by adambray** [comment]
@ScreenName4eva Can you update these 3 issues since we looked at them in person today?
