### ISSUE TITLE
Trying to make a post request to a model which is a property of another model in our rails json.

### ISSUE THREAD

**Issue by mfournier91** [ga-wdi-exercises/project3#231]
We are having trouble performing a simple post request from our angular app to our backend rails api server. It keeps saying bad request. We need to send the request to this model called "song requests", each instance belonging to objects called "venues"

**Comment by andrewsunglaekim** [comment]
1. what errors are you getting?
2. What is the backend endpoint you are trying to access in the create? (aka from rake routes)
3. What does your `$resource` look like in your factory thats making the request?

**Comment by mfournier91** [comment]
1. angular.js:9866 POST http://localhost:3000/requests 400 (Bad Request).
2. post /requests
3. `return $resource("http://localhost:3000/venues/:id", {}, {});`

**Comment by andrewsunglaekim** [comment]
can you post your controller code for the backend thats handling the creation of song requests

**Comment by andrewsunglaekim** [comment]
your request doesn't seem to matchup with your resource.
