### ISSUE TITLE
Having issues getting update/destroy/create to work

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/project3#232]
We're having issues trying to get update/destroy/create to work with our API:
https://github.com/megancoyle/sojourn/tree/rails-with-angular

Have been trying to follow the grumblr_angular solution, but we're having no luck.

When trying to update we get the following error:
PUT http://localhost:3000/api/trips/1 404 (Not Found)

When adding something new, it adds to the index but doesn't get added to the API.

When deleting something, it just redirects to the index without removing an item.

**Comment by andrewsunglaekim** [comment]
can you post your controller code thats handling trips?

**Comment by andrewsunglaekim** [comment]
ah, you did, sec.

**Comment by andrewsunglaekim** [comment]
your trips controller doesn't have any actions that handle those behaviors.

**Comment by megancoyle** [comment]
gotcha, thanks

**Comment by megancoyle** [comment]
Updated the controller, but seems like I'm still missing something...

**Comment by megancoyle** [comment]
when I try to update an item, I get the following error:
PUT http://localhost:3000/api/trips/1 422 (Unprocessable Entity)

Will try figuring it out, but not too sure what I'm missing...
