### ISSUE TITLE
Getting initial welcome view to show up in Angular on Rails

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/project3#234]
https://github.com/megancoyle/sojourn

I'm currently working on trying to get a welcome view to show up in Angular when you initially view the app. I tried to add a state to the index.js file (located in app/assets/javascripts/app): 

```

.state("indexShow", {
url: "/",
templateUrl: "welcome.html"
}
```

However, no luck. Do I need to set up something in the Rails routes that redirects to a new route located in Angular?

Thanks!

**Comment by andrewsunglaekim** [comment]
where do your views live in your repo? I'm not seeing them. I see `index.js` but not the `.html` files

**Comment by andrewsunglaekim** [comment]
does it work if you put a hashtag at the end of the url?

**Comment by megancoyle** [comment]
They live in app/assets/templates

**Comment by andrewsunglaekim** [comment]
ie something like this `http://localhost:3000/#/

**Comment by andrewsunglaekim** [comment]
if that works then try going to http://ga-wdi-lessons.github.io/angular-routing/lab.html#double-bonus to checkout how to make pretty URL's

**Comment by megancoyle** [comment]
yep, it sure does. Will adding html5Mode take care of that issue of having to add the hashtag?

**Comment by andrewsunglaekim** [comment]
that and adding a `<base>` tag, check out that link

**Comment by megancoyle** [comment]
great, thanks!

**Comment by megancoyle** [comment]
Actually, looks like when you refresh the page after adding html5mode, we get routing errors in Rails. Would it make more sense to set up a redirect for routes that automatically takes users to http://localhost:3000/#/ so Rails doesn't keep tripping on Angular paths?

**Comment by andrewsunglaekim** [comment]
yeah that could work

**Comment by megancoyle** [comment]
perfect, got it working!

**Comment by megancoyle** [comment]
Looks like the redirect doesn't work, trying to look into it... (I initially thought it was working because of page caching)

```
  get "welcome/index"
  root 'welcome#index'
  root :to => redirect('/#/')
```

**Comment by superbuggy** [comment]
are you using $locationProvider?

**Comment by andrewsunglaekim** [comment]
whats the url change to when the redirect happens?

**Comment by megancoyle** [comment]
Nope, not using $locationProvider anymore. And it doesn't do a redirect at all...

**Comment by megancoyle** [comment]
Might be an issue with the version of rails

**Comment by megancoyle** [comment]
yay, got it working. just added "" for the location in the Angular controller
