### ISSUE TITLE
AngularJS Nest Resources

### ISSUE THREAD

**Issue by pamelaolney** [ga-wdi-exercises/project3#235]
Hi!

My repo is linked below.

https://github.com/danielanoir/project3

I am looking to nest a submodule in my primary submodule.  My primary submodule is Categories.  I've been working to get Lessons to nest into Categories so that in the Catgories show.html you would be able to see individual lessons beneath each category.

I have found this website that seems like it is onto something but I am not sure exactly how to implement it into my code.

https://scotch.io/tutorials/angular-routing-using-ui-router

I tried different things like make a lessons directory in the js folder and then try to add lessons in the module for my app.js but that caused a lot of problems.

_app.js test_

```
"use strict";

  (function(){
    angular
    .module("dapi", [
      "ui.router",
      "categories",
      //added lessons submodule below
      "lessons"
    ])
    .config([
      "$stateProvider",
      "$urlRouterProvider",
      RouterFunction
    ]);


    function RouterFunction($stateProvider, $urlRouterProvider){

      $urlRouterProvider.otherwise("/categories");

      $stateProvider
      .state("categoryIndex", {
        url: "/categories",
        templateUrl: "js/categories/index.html",
        controller: "CategoryIndexController",
        controllerAs: "CategoryIndexViewModel"
      })
      .state("categoryIndex.lesson", {
        url: "/lesson",
        templateUrl: "show-lessons.html",
        controller: "CategoryShowController",
        controllerAs: "LessonViewModel"
      })
```

I also tried adding this to the app.js file

```
  .state("categoryIndex.lesson", {
        url: /lesson,
        templateUrl: 'show-lessons.html',
        controller: function($scope) {
          $scope.lessons = ['making shrimp, learning js']
        }
```

 And put this in my **show**.html

`<a data-ui-sref="categoryIndex.lesson">Lessons</a>
`

And made a show-lessons.html file inside of my categories directory within my js directory.

So not really sure what to do next.  Possibly add lessons in the state somehow?  Not sure.  Any tips on nesting would be fantastic!

**Comment by superbuggy** [comment]
```
  .state("categoryIndex.lesson", {
        url: /lesson,
        templateUrl: 'show-lessons.html',
        controller: function($scope) {
          $scope.lessons = ['making shrimp, learning js']
        }
```

should be
`url: "/lesson"`

but I'm not sure that's the easier way to get to where you want to go.

**Angular Solution:**

I would make a 2nd factory that takes 2 parameters for the nested resources i.e. `categories/:category_id/lessons/:id`

``` js
.factory('Categories', function($resource){
   return $resource("insert_domain_url_here/categories/:id");
})

.factory('Lesson', function($resource){
   return $resource("insert_domain_url_here/category/:category_id/bills/:id")
});
```

then inject LessonFactory and CategoryFactory into your controller.

**Rails Back-End Solution:**
Another option would be to include the child object along with the parent object:

Screencast: https://teamtreehouse.com/library/build-a-rails-api/coding-the-api/including-nested-resources-in-json-output

example:

``` rb
  def show
    list = TodoList.find(params[:id])
    render json: list.as_json(include:[:todo_items])
  end
```

**Comment by pamelaolney** [comment]
Thanks!
