### ISSUE TITLE
Data persisting problem

### ISSUE THREAD

**Issue by aubreynortham** [ga-wdi-exercises/project3#236]
We are using firebase to host json data as our backend. In the index html&controller we have our full crud functionality at the album level. In the show html&controller we have the logic for full crud functionality on individual photos within each album. From the index, the user should be able to add a new album (by creating an album title) and update albums (at the title-level only). The only problem is, when the user clicks on the newly created album, the "add photos" function no longer works like it does for albums that are already in the database. I'm not sure if this is because firebase assigns new objects a unique value (i.e. albums/-KPs7GjU8AVETI0M8UYn) instead of a normal index#. It still works fine for albums that are already hardcoded.

This is the issue I'm getting: angular.js:11655 TypeError: Cannot read property 'push' of undefined
    at AlbumShowControllerFunction.vm.create (show.controller.js:23)

And this is my logic for adding photos to albums: (show controller)

```
    vm.create = function(){
      vm.album.photos.push(vm.newPhoto)
      vm.album.$save().then(function(){
        vm.newPhoto = {};
      });
    }
```

show index: 

```
<h3>Add Photo to this Album</h3>
<form data-ng-submit="AlbumShowViewModel.create()">
  <input placeholder="Timestamp" data-ng-model="AlbumShowViewModel.newPhoto.timestamp">
  <input placeholder="Comment" data-ng-model="AlbumShowViewModel.newPhoto.comment">
  <input placeholder="Photo URL" data-ng-model="AlbumShowViewModel.newPhoto.photo_url">
  <button type="submit">Add Photo</button>
</form>
```

**Comment by superbuggy** [comment]
can you link where `vm.album.photos` is defined in your show controller? can you also `console.log(vm.album)` and check if that is defined?

**Comment by aubreynortham** [comment]
Here's the part in the show controller that precedes all the cruddy stuff: 

```
function AlbumShowControllerFunction($stateParams, $firebaseObject){
    var vm = this;
    var ref = firebase.database().ref().child("albums/" + $stateParams.id);

    var syncObject = $firebaseObject(ref);
    syncObject.$loaded().then(function(album){
      vm.album = album
    });
```

When I console logged it right after that last line, it logged an object with an id of that long gibberish string, and showed that it had album_title = the title I gave it.

**Comment by superbuggy** [comment]
and photos are nested within the album object you logged?

**Comment by aubreynortham** [comment]
Yep, here's the data structure: 

```
[
  {
    "album_title": "Madrid",
        "photos": [
                    {"photo_url": "https://thewildwanderer.files.wordpress.com/2013/06/retiro-park.jpg",
                    "latitude": "40.457023",
                    "longitude": "-3.677725",
                    "timestamp": "April 23, 2015 6:25pm"}, (etc)
```

**Comment by aubreynortham** [comment]
Oh I think I misunderstood your Q, photos are nested within the existing hardcoded objects if I log them, but there aren't any photos nested in the new album objects. It throws an error before the "create" submission goes through. Should there be any evidence of that photos array in the console log if the user hasn't added any yet?

**Comment by aubreynortham** [comment]
So I guess we are trying to push to an array (photos) that doesn't exist yet. I'm looking into how to fix that but haven't hit the right solution.

**Comment by superbuggy** [comment]
Try adding the photos to a local array (local to your program), and then `vm.album.photos =`(the local array)...

**Comment by aubreynortham** [comment]
I'm not sure I understand what you mean with the local array part. I think I only managed to empty out the existing photos array (on an album that does have a photos array) but still doesn't get anywhere with the array-less albums.
