### ISSUE TITLE
implementing flash messages without handlebars 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#24]
I tried using what we learned in class to implement flash messages when a user tries to sign up with info that already exists, but i'm not sure how to get it to only show when its supposed to since we are not using handle bars the mustache things show all the time in the index.html page.  I googled different flash message methods and connect-flash came up, but I wasn't sure if there was still some way to do it how we learned in class instead of implementing something new.

**Comment by RobertAKARobin** [comment]
Can you show some example code?

**Comment by ghost** [comment]
thanks adam helped me with this i'll close it
