### ISSUE TITLE
going back to older commit

### ISSUE THREAD

**Issue by jacahn** [ga-wdi-exercises/project3#241]
Hi guys, 

we accidentally merged some data to our Project 3 branch. Could someone help us revert to an old commit? We've used SOF to try and revert to no avail.

**Comment by andrewsunglaekim** [comment]
http://stackoverflow.com/questions/4114095/how-to-revert-git-repository-to-a-previous-commit

**Comment by andrewsunglaekim** [comment]
going to close this issue, please reopen if you still have a problem @jacahn
