### ISSUE TITLE
Page redirects upon form submission, but page needs manual refresh to reflect changes

### ISSUE THREAD

**Issue by ahmedelk91** [ga-wdi-exercises/project3#242]
Hello, 

As the title suggests, once a form has been submitted, it does redirect to the correct state, however, it does not reflect changes made from the form. 

edit.controller.js is where the change should be implemented in the code below: 

``` js
function CategoryEditControllerFunction( CategoryFactory, $stateParams, $state ){
    var vm = this
    vm.category = CategoryFactory.get({id: $stateParams.id});
    vm.update = function(){
      vm.category.$update({id: $stateParams.id});
      alert("You've successfully updated this Category!")
      $state.go("categoryIndex")
    }
    var vm = this;
    vm.destroy = function(){
      vm.category.$delete({id: $stateParams.id})
      alert("You've successfully deleted this Category!")
      $state.go("categoryIndex")
    }
  }


}());
function CategoryEditControllerFunction( CategoryFactory, $stateParams, $state ){
    var vm = this
    vm.category = CategoryFactory.get({id: $stateParams.id});
    vm.update = function(){
      vm.category.$update({id: $stateParams.id});
      alert("You've successfully updated this Category!")
      **$state.go("categoryIndex")**
    }
    var vm = this;
    vm.destroy = function(){
      vm.category.$delete({id: $stateParams.id})
      alert("You've successfully deleted this Category!")
      **$state.go("categoryIndex")**
    }
  }


}());
```

I read about $state.reload(), but when I implemented it, it did not work. Perhaps I was using it wrong? Please advise. Thanks!

**Comment by andrewsunglaekim** [comment]
have you tried `$state.go`? this should re render whichever state you pass in as an argument

**Comment by ahmedelk91** [comment]
Hey Andy, 

I used $state.go in my code and this problem persisted. I typed:
'''
$state.go("categoryIndex")
'''

This redirects me to the index but does not automatically refresh the page. That must be done manually. Is there something I might be missing in that line of code?

**Comment by andrewsunglaekim** [comment]
can you link the form that handles the update? and also the entire controller including injections

**Comment by ahmedelk91** [comment]
Hey Andy I actually solved the issue! 

I added .then to $update and used an anonymous callback function. The changes can be seen below: 
'''
  function CategoryEditControllerFunction( CategoryFactory, $stateParams, $state ){
    var vm = this
    vm.category = CategoryFactory.get({id: $stateParams.id});
    vm.update = function(){
      vm.category.$update({id: $stateParams.id}).then(function(){
        alert("You've successfully updated this Category!")
        $state.go("categoryIndex")
      });
    }
'''

Appreciate the help man!

**Comment by andrewsunglaekim** [comment]
Great!
