### ISSUE TITLE
Optimizing API Plan

### ISSUE THREAD

**Issue by brizzi10** [ga-wdi-exercises/project3#243]
I wish I had asked this during our meeting, but I was just curious about your opinion regarding the best way to implement lat/long in our project. We want our welcome page to allow the user to search a location, then the map on the trip show page would be centered based upon gps coordinates retrieved from this initial search.

Using the angular google map API, we can generate a search bar with a map, and even detach it from the map, but the map must still be present to use the bar. Our question is do you think it would be superior to detach the angular search bar then use css to hide the map, or should we look into a separate api call using the geocoding aspect of the google maps api (that does not exist in angular)

**Comment by andrewsunglaekim** [comment]
Sounds like you should use a service to connect two controllers

Check out this stackoverflow http://stackoverflow.com/questions/20181323/passing-data-between-controllers-in-angular-js

**Comment by andrewsunglaekim** [comment]
that way you can be in a separate view/controller, but still pass information from one to the other.

**Comment by andrewsunglaekim** [comment]
going to close this issue reopen if you have any lingering problems.
