### ISSUE TITLE
JSON files to seed DB in Rails

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/project3#244]
We're having trouble seeding our database with a second model. We're basically following the same format for the first model - is it necessary that we use json files in the DB folder? Or is it possible to do this just with Ruby?

https://www.youtube.com/watch?v=G6ipU6AiEXY

**Comment by andrewsunglaekim** [comment]
i mean, you can seed however you want. what do you mean?

**Comment by andrewsunglaekim** [comment]
Why not just hardcode some AR creations?

**Comment by superbuggy** [comment]
you don't need to seed with JSON files-- this will create pains with associating particular records (instances of AR objects) in your seed file. feel free to write all your seed data in `seeds.rb`

**Comment by megancoyle** [comment]
ah, gotcha. Thanks!
