### ISSUE TITLE
Rails validates Venue with (google's) place Id uniqueness. Need to be able to redirect to our associated id when place id is not unique

### ISSUE THREAD

**Issue by mfournier91** [ga-wdi-exercises/project3#246]
Need to be able to redirect to our associated id when place id is not unique. 
![screen shot 2016-08-24 at 11 48 26 am](https://cloud.githubusercontent.com/assets/19799962/17937829/77fd6c8a-69f1-11e6-9c6d-4e58ba513edf.png)
![screen shot 2016-08-24 at 11 52 38 am](https://cloud.githubusercontent.com/assets/19799962/17937871/9e6a031a-69f1-11e6-8f3b-3e0b1e24087f.png)

**Comment by andrewsunglaekim** [comment]
I think your looking for this sort of thing:

http://stackoverflow.com/questions/20584367/how-to-handle-resource-service-errors-in-angularjs
