### ISSUE TITLE
Firebase Injection

### ISSUE THREAD

**Issue by mrnelley** [ga-wdi-exercises/project3#248]
https://github.com/mrnelley/GoogleMaps/tree/firebase

firebase injection for module and controller are screwing with angular functionality. Not rendering the map and not reading $scope for the controller function. Not sure why. If you compare branches you can see that ive cleaned up the chaining of angular functions so that it is easier to read and making service and controller callback functions should not have affected the functionality at all, but for some reason variables defined in the service are not available in the controller.

**Comment by andrewsunglaekim** [comment]
i think we fixed the map during the token, plz reopen if you run into more issues.
