### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by mfournier91** [ga-wdi-exercises/project3#249]
Css is clearly working but no content.
![screen shot 2016-08-25 at 12 00 19 pm](https://cloud.githubusercontent.com/assets/19799962/17976506/d65ccf9e-6abb-11e6-9b95-a152adaddae5.png)

**Comment by superbuggy** [comment]
is the index.html in the root directory of your `gh-pages`? can you link your repo?

**Comment by mfournier91** [comment]
K. https requests to http request was the problem. Fixed. New Problem though. Assets aren't being received.

**Comment by superbuggy** [comment]
is your api not persisting data?

**Comment by mfournier91** [comment]
We can't test because our button on click creates data and our button is an asset that won't show up

**Comment by mfournier91** [comment]
![screen shot 2016-08-25 at 12 10 38 pm](https://cloud.githubusercontent.com/assets/19799962/17976847/390138c8-6abd-11e6-8fbe-2b24f0df45c4.png)

**Comment by superbuggy** [comment]
is the button is a part of your back end app?

**Comment by mfournier91** [comment]
nah

**Comment by mfournier91** [comment]
do the images need to be hosted on imgur instead of being assets in playThisAngular?

**Comment by superbuggy** [comment]
can you link to the part of your repo that has your button and the img that isn't showing up

**Comment by mfournier91** [comment]
Do you mean github pages branch?
Here's the stuff on master https://github.com/skshultis/playThis/tree/master/playThisAngular/assets

**Comment by superbuggy** [comment]
yes. can you link the portion of the code where the button that isn't showing up is?

**Comment by mfournier91** [comment]
`image = '../assets/img/playthismap1.png';` in https://github.com/skshultis/playThis/blob/master/playThisAngular/js/maps/directive.js
