### ISSUE TITLE
styles in css not showing up in index.html 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#25]
I have a css folder with a styles.css file under the public folder.  I can type in the url the path to the css file and see whats in there.  We also have the below to see the static files in the public folder 

```
app.use(express.static(path.join(__dirname, "public")))
```

I also have it linked in index.html 

```
<link rel="styesheet" type="text/css" href="css/styles.css">
```

It feels like it should be working, but i'm not sure if there is a missing step somewhere or it needs to be required somewhere.  I played around with the app.use path based on what I found online but it still didn't accept the changes in the css file so I wonder if its being overwritten? I tried removing what we have showing up on the page already and the css changes still didn't apply.  We are using bootstrap but it shouldn't overwrite simple changes like changing background color, which is what I used to test with.

**Comment by jshawl** [comment]
try a slash in the href:

```
<link rel="styesheet" type="text/css" href="/css/styles.css">
```

**Comment by ghost** [comment]
adam helped me find my typo and I spelled "stylesheet" wrong thanks i'll close my issues!
