### ISSUE TITLE
API Guidance

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project3#27]
I'm trying to pull in the wmata API and I have the key, but I'm not able to get the info to pull in -- in json or html

**Comment by RobertAKARobin** [comment]
Can you be more specific? Are you getting an error?

**Comment by clarktsc39** [comment]
I can be. This is what's in the index.html (I deleted the rest of the code so I could see if the API pulled info in correctly).

Here's the code in the index.html

```
<!DOCTYPE html>
<html>
<head>
    <title>JSSample</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
</head>
<body>
<script type="text/javascript">



      $.ajax({
          url: "https://api.wmata.com/Incidents.svc/json/BusIncidents?api_key=<api_key>",
          type: "GET",
          // Request body
          data: "{body}",
          dataType: "jsonp"
      })
      .done(function(data) {
          alert("success");
          console.log(data)
      })
      .fail(function() {
          alert("error");
      });

</script>
</body>
</html>
```

I'm thinking I haven't defined the routes..

**Comment by clark-thomas** [comment]
When I enter this code, there's a js alert that states: "The page at localhost:4000 says: error.

```
<!DOCTYPE html>
<html>
<head>
    <title>JSSample</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
</head>
<body>

<script type="text/javascript">
    $(function() {
        var params = {
            // Request parameters
        };

        $.ajax({
            url: "https://api.wmata.com/Incidents.svc/json/Incidents&" + $.param(params),
            beforeSend: function(xhrObj){
                // Request headers
                xhrObj.setRequestHeader("api_key","{3d68dbea57874f29a9a251bd8e860c5b}");
            },
            type: "GET",
            // Request body
            data: "{body}",
        })
        .done(function(data) {
            alert("success");
        })
        .fail(function() {
            alert("error");
        });
    });
</script>
</body>
</html>

```

**Comment by RobertAKARobin** [comment]
Woah, what's up with this `xhrObj` stuff? If you're making API requests, I'd so that on the back end. You almost never want to include API keys in your front-end code.

What I'd do is create a route for your _back end_ that queries the API. Then your front-end can query that route. 

So, your front-end Javascript makes a request to, say, `localhost:3000/api/wmata`. Then, Node makes a request to `wmata.com`, and responds to the front-end Javascript's request with the data from the API. You'd want to use the `request` [node module](https://github.com/request/request).

Something like:

``` js
var request = require("request");
// ...
app.get("/api/wmata", function(req, res){
  request.get({
    url: "http://wmata.com/api",
    headers: {
      api_key: "abc123"
    }
  }, function(err, data, body){
    res.send(data);
  });
});
```

...and then in your front-end:

``` js
$.getJSON("http://localhost:3000/api/wmata").then(function(response){
  console.log(response);
});
```

**Comment by RobertAKARobin** [comment]
This hasn't been updated in a while, so I'm closing it!
