### ISSUE TITLE
Commits behind the repo maintainer

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project3#277]
We created a repo and the repo maintainer merge the two collaborators' work. However, the collaborators' repos are not updated. Currently the collaborators are a few commits behind the maintainer. How can the collaborators' repo and text editor get the most updated version of work after the maintainer merges?

**Comment by jshawl** [comment]
```
$ git remote add upstream maintainers-url
$ git pull upstream master
```
