### ISSUE TITLE
Angular Integration Question

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project3#278]
Hello Captains!

We are struggling with initial setup. We are making a rails API and an Angular front end.  Where should the angular file live? We know that they are primarily separate but does that mean the js can't live somewhere in the rails repo? We noticed that convention dictates we don't write directly into application.js.

Thanks for the guidance!

**Comment by nolds9** [comment]
I recommend separate repos! This means you will have to deploy 2 things, but will be easier to develop / debug

**Comment by lizafloyd** [comment]
Thanks!
