### ISSUE TITLE
delete action on mongodb

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project3#28]
This is my error
`Cannot DELETE /user/56635e2043d4c1fb3f5ff305?_method=delete`

View

```
<form action="/user/{{user._id}}?_method=delete" method="post">
     <input type="submit" class="btn btn-danger" value="Delete Profile">
</form>
```

Route

```
router.delete("user/:id", usersController.deleteUserProfile);
```

Controller

```
function deleteUserProfile(req,res) {
  User.findByIdAndRemove( req.params.id , function(err, user) {
    if(err){res.send(err);} else {
      res.redirect("/user/index");
    }
  });
}
```

It is hitting my controller but not performing the delete action.
the code can be found here https://github.com/codedre/project-3/tree/master

**Comment by RobertAKARobin** [comment]
Is it because you're missing a slash? You have `user/:id` instead of `/user/:id`.

**Comment by codedre** [comment]
Thank you!
![](http://i.imgur.com/xFrJtHx.gif)
