### ISSUE TITLE
CSV Parsing

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project3#280]
![image](https://cloud.githubusercontent.com/assets/19317100/19821365/f0a943d0-9d2b-11e6-8084-d77f52634443.png)

I'm following this tutorial on github but I'm pretty sure this is going to turn each row into a hash, but my seed data is set up such that every column needs to be a hash.  Can you guide me on how to do that?

**Comment by jshawl** [comment]
wait, what? is `puts row.to_hash` what you want?

**Comment by alman92** [comment]
No i want to know if puts column.to_hash will actually create a hash from the column

**Comment by jshawl** [comment]
It looks like `to_hash` will collapse the row into a hash  - http://ruby-doc.org/stdlib-1.9.3/libdoc/csv/rdoc/CSV/Row.html#method-i-to_hash

**Comment by jshawl** [comment]
but I haven't used this method before - if you run it, does it do what you're expecting, or are you trying to modify the output in some way?

**Comment by alman92** [comment]
I'm trying to modify the output to have it return all the data from the columns in a hash.  So to_hash wouldn't work I don't think

**Comment by jshawl** [comment]
Does puts row contain all the info you want?

**Comment by alman92** [comment]
Can I come over and show you? Ill use a token

**Comment by jshawl** [comment]
@alman92 apologies for the delay - come on over when you're ready

**Comment by nolds9** [comment]
solved in IRL with excel
