### ISSUE TITLE
Using JSON Web Tokens to authenticate POST, DELETE (etc.) requests to our api

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/project3#282]
We are renegades and have a User model (devise) for our app and we are investigating solutions for protecting our api. We want to allow users to post, edit, and delete their data and right now, our best solution is using JSON Web Tokens via the 'jwt' gem.

Assuming we're going to absolutely continue with user auth, is this a reasonable approach? Are there any other methods you know of allowing an angular font-end to POST to a rails API with restrictions on who can make those AJAX requests?

**Comment by jshawl** [comment]
token based auth w/ rails - https://github.com/ga-wdi-lessons/angular-auth or firebase authentication

**Comment by nickoki** [comment]
Thank you for the resource, we're going to give it a shot!

**Comment by amaseda** [comment]
:+1: Closing but keep us posted if you have any questions

**Comment by nickoki** [comment]
I'm not able to run `rails g devise_token_auth:install User auth`

The command freezes my terminal

**Comment by nickoki** [comment]
Where do the following lines go in `config/application.rb`
![image](https://cloud.githubusercontent.com/assets/15880182/19860583/a7e1fd6e-9f5f-11e6-8c18-c7ab6900c9ec.png)

**Comment by jshawl** [comment]
https://github.com/ga-wdi-exercises/grumblr_rails_api/blob/devise_token_auth/config/application.rb#L31-L32

**Comment by nickoki** [comment]
Interesting, our config looks like this

``` ruby
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Recourse
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end
```

**Comment by bcope** [comment]
![image](https://cloud.githubusercontent.com/assets/3825779/19861853/7b8d6d48-9f64-11e6-9af6-76319ecfad3d.png)
I've been following the steps and I also am getting hung up. Here's the error I'm getting which Nick also has gotten.

**Comment by nolds9** [comment]
what's your `config/routes.rb` look like?

**Comment by jshawl** [comment]
looks like you have two user_sessions

**Comment by nickoki** [comment]
Here's `config/routes.rb`

``` ruby
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts

  root to: "posts#index"

end
```

**Comment by jshawl** [comment]
doesn't except need an array argument?

**Comment by jshawl** [comment]
also do you need devise_for :users? https://github.com/ga-wdi-exercises/grumblr_rails_api/blob/6a184e1d915ede56e92909dc2861d78215c575c6/config/routes.rb#L2

**Comment by nickoki** [comment]
Ah! Removing `devise_for :users` cleared the error, thank you

That makes sense too since devise is defining it's own routes

**Comment by jshawl** [comment]
👍

**Comment by nolds9** [comment]
going to go ahead and close this since we talked about this IRL, but feel free to reopen / open a new one in the future
