### ISSUE TITLE
best practice for scripts in angular

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project3#283]
I'm setting up the angular front end and I have a question about how to run scripts. 

I have 7 different scripts in our index.html page that holds the <ui-view>
![image](https://cloud.githubusercontent.com/assets/15305847/19857821/81509624-9f55-11e6-9956-7f69138123c4.png)

Would it be better to move the map and directions scripts to the ng-view that will actually show the map instead of loading them on every page?

**Comment by jshawl** [comment]
yes I think so!

**Comment by marks828** [comment]
Ok so I can get the map to show on the main index page
![image](https://cloud.githubusercontent.com/assets/15305847/19859163/bf389112-9f5a-11e6-84c2-677baf22253a.png)

but when I try to load the map on to another page it won't show. I've tried a number of different ways to load the scripts.
![image](https://cloud.githubusercontent.com/assets/15305847/19859186/d34dd0b8-9f5a-11e6-8e16-c9ff33ad7dd9.png)

file tree:
![image](https://cloud.githubusercontent.com/assets/15305847/19859235/eec05bcc-9f5a-11e6-8ad3-4f70c6baea7e.png)

**Comment by nolds9** [comment]
what if you loaded your maps on every page, i.e. put the cdns on the main `index.html`, then you moved your `div#map` to the `show` view or which ever view you only want the map on?

**Comment by marks828** [comment]
![image](https://cloud.githubusercontent.com/assets/15305847/19859452/afbf0d00-9f5b-11e6-91d9-b7c34ad72da6.png)

![image](https://cloud.githubusercontent.com/assets/15305847/19859472/bd35f552-9f5b-11e6-96e4-685ceb6400bb.png)

![image](https://cloud.githubusercontent.com/assets/15305847/19859488/cb962c48-9f5b-11e6-94ff-92faf6b85612.png)
 I have the #map set to red background

**Comment by nolds9** [comment]
and you move  script tag loading `map.js` into the head right before `app.js`?

**Comment by marks828** [comment]
![image](https://cloud.githubusercontent.com/assets/15305847/19859684/8eb7ad82-9f5c-11e6-8c6f-76a24d0523a8.png)

![image](https://cloud.githubusercontent.com/assets/15305847/19859663/7a7f412c-9f5c-11e6-8c71-626755797113.png)

**Comment by nolds9** [comment]
are you getting any errors in the console?

**Comment by marks828** [comment]
Yea

![image](https://cloud.githubusercontent.com/assets/15305847/19860343/b6ae3fac-9f5e-11e6-942f-856fd9382f13.png)

**Comment by nolds9** [comment]
something to google?!

**Comment by amaseda** [comment]
Any progress on this one?

**Comment by marks828** [comment]
Nope just a lot of googling

**Comment by nolds9** [comment]
what does your `map.js` look like?

**Comment by jshawl** [comment]
the only error you have is `t is null` ?

**Comment by superbuggy** [comment]
Maybe applicable: https://github.com/mapbox/mapbox.js/issues/983#issuecomment-91628927

**Comment by jshawl** [comment]
I googled `t is null` and found http://www.gisremotesensing.com/2014/08/leaflet-typeerror-t-is-null.html

can you share your code

**Comment by marks828** [comment]
map.js

![image](https://cloud.githubusercontent.com/assets/15305847/19862197/bdde3974-9f65-11e6-932f-df7a29884654.png)

**Comment by nolds9** [comment]
Cool, so this is some code that `mapbox` needs to run on page load to initialize your map, the only problem is that they `container` is not available when this script runs initially. What I might do, is to move this code into the controller for your show view and see if that solves it

**Comment by marks828** [comment]
like this?

![image](https://cloud.githubusercontent.com/assets/15305847/19862481/e7a0043a-9f66-11e6-9131-31ef5aab49d6.png)

**Comment by nolds9** [comment]
does it work?

**Comment by nolds9** [comment]
If not, I would try making `mapFunction` a property on your showController, then using a `ng-init` directive to call your `mapFunction` attached to the vm.
