### ISSUE TITLE
Getting strange db:migrate error

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project3#284]
![image](https://cloud.githubusercontent.com/assets/19317100/19858409/b169b10e-9f57-11e6-9658-67ca65be8ba7.png)

![image](https://cloud.githubusercontent.com/assets/19317100/19858450/d6af9a6e-9f57-11e6-9aad-9f1c379dfd41.png)

I've run all the commands I can think of to fix this, still not getting anywhere

**Comment by nolds9** [comment]
what happens when you run `rails db:migrate:reset` ?

**Comment by nolds9** [comment]
also, notice that this says `sqlite3` might want to switch to postgresql before you deploy...

**Comment by jshawl** [comment]
duplicate column error - do you have more than one migration that adds the same column?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19858509/1a927012-9f58-11e6-821a-ad958453958d.png)

Ran it and nothing happened.  Postgresql is running, we only have one that adds column.

**Comment by nolds9** [comment]
looks like Rails is telling you how to fix that error. Can you run the command you just posted...

**Comment by alman92** [comment]
Yea i did and it didn't change anything

**Comment by jshawl** [comment]
what is the ouput of running that command?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19858646/9dab9c30-9f58-11e6-83f0-31031c7e7454.png)

**Comment by alman92** [comment]
There was no output which makes me think it changed something

**Comment by jshawl** [comment]
ok perfect, and then try migrating

**Comment by nolds9** [comment]
now can you run `rails db:drop db:create db:migrate db:seed`

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19858675/c01e8412-9f58-11e6-97c3-916a2a16f11f.png)

I have no idea what sqlite3 is but the error keeps saying it alot.

**Comment by alman92** [comment]
Its a gem we have but i have no idea how it ended up in our Gemfile

**Comment by jshawl** [comment]
you are trying to create the same column twice can you push your code to github and share the link to your migration files?

**Comment by alman92** [comment]
https://github.com/marlungu/globeView/tree/master/db/migrate

**Comment by jshawl** [comment]
first time - https://github.com/marlungu/globeView/blob/1292033a6355ec4fce61ebb1b139f0f61367bffa/db/migrate/20161031142043_add_passport_to_destination.rb#L3

second time - https://github.com/marlungu/globeView/blob/1292033a6355ec4fce61ebb1b139f0f61367bffa/db/migrate/20161031142043_add_passport_to_destination.rb#L3

remove one of those

**Comment by alman92** [comment]
They are the same file I thought

**Comment by alman92** [comment]
Both of those links take me the same place

**Comment by jshawl** [comment]
you have three files in here - https://github.com/marlungu/globeView/tree/master/db/migrate

**Comment by jshawl** [comment]
sorry here's the other one https://github.com/marlungu/globeView/blob/1292033a6355ec4fce61ebb1b139f0f61367bffa/db/migrate/20161028155004_create_destinations.rb#L7

**Comment by alman92** [comment]
Ok, ill test it

**Comment by alman92** [comment]
Perfect its working now, thanks!!

**Comment by amaseda** [comment]
:+1:
