### ISSUE TITLE
Calling our API in the backend

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project3#285]
We're kinda stuck in making a call from our front end to our backend
![image](https://cloud.githubusercontent.com/assets/20713810/19859356/5d4b56a0-9f5b-11e6-9b88-b1eea607811e.png)

In our rails api, we're able to ping yelp for restaurant results. Can you confirm that we need to send a post request to the backend? We're stuck at getting the response from our front end application is where we're stuck. Our new controller needs to get the response from the front end and then initialize the create to our show page with the id.

![image](https://cloud.githubusercontent.com/assets/20713810/19859471/bca7cca0-9f5b-11e6-9387-065e829fb00a.png) ->
![image](https://cloud.githubusercontent.com/assets/20713810/19859484/c89d2aaa-9f5b-11e6-8b6f-05282e7f9566.png)

Ruby code
![image](https://cloud.githubusercontent.com/assets/20713810/19859409/8c4b250c-9f5b-11e6-8286-898e31142687.png)

**Comment by nolds9** [comment]
I think the `apiUrl` is wrong. I think you want to send a post request to `localhost:3000/foods`...When you do that, do you get any errors?

Also this is what `$resource` is very helpful with - normally we encapsulate our front-end requests via a factory, that is the interface to the backend....

**Comment by nolds9** [comment]
also, check you syntax for the `data` object you are sending over

**Comment by amaseda** [comment]
@MichaelZLai Any progress on this one?

**Comment by MichaelZLai** [comment]
no progress, I think we're going to use a token

**Comment by MichaelZLai** [comment]
now getting this. We think it has something to do with CORS (and we installed the gem). Kind of confused at our calls

![image](https://cloud.githubusercontent.com/assets/20713810/19862549/390dd0ae-9f67-11e6-861f-43d2ff357137.png)

**Comment by nolds9** [comment]
ok this is progress, it just means you have not configured `CORs` correctly to whitelist requests from `localhost:8080`...

I'd make sure you are following the instructions for Rails 5 mentioned here: https://github.com/cyu/rack-cors#rails

**Comment by MichaelZLai** [comment]
hmmm, we have that in our application.rb, but it's still throwing us an error

![image](https://cloud.githubusercontent.com/assets/20713810/19864142/53b716d0-9f6d-11e6-952d-448e36765057.png)

**Comment by nolds9** [comment]
have you restarted your server since modifying this config file?

**Comment by MichaelZLai** [comment]
Just restarted and getting a bad request now

![image](https://cloud.githubusercontent.com/assets/20713810/19864343/3081b5c0-9f6e-11e6-91f5-536e7cbb60b8.png)

**Comment by amaseda** [comment]
Is your Rails server running?

If so, is there any evidence your server received the request (e.g., is an error showing up in the tab running the server)?

**Comment by MichaelZLai** [comment]
Yes, Update so far: We've changed our factory to a hardcoded url with the method Get and we're able to retrieve data from that!
![image](https://cloud.githubusercontent.com/assets/20713810/19865628/6ecb48dc-9f73-11e6-84dd-eae8c5227d29.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19865634/7938c218-9f73-11e6-9297-cf600ba8f5a1.png)

However, still having trouble creating a post for a new location. 

![image](https://cloud.githubusercontent.com/assets/20713810/19866507/c8529a88-9f76-11e6-92d1-ff330a1e71c0.png)

**Comment by amaseda** [comment]
Gotcha, makes sense that you wouldn't be able to post anything with the hard-coded URL.

What did your factory and your controller's create function look like prior to hard-coding the URL?

**Comment by MichaelZLai** [comment]
On to something! Got this error. Not sure if it has to do with the CORS, but we were able to retrieve data. Now we're trying to redirect to our show page along with grabbing the new json from the search term on the "index" page

![image](https://cloud.githubusercontent.com/assets/20713810/19866742/b155144a-9f77-11e6-9847-72a8f18121c1.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19866765/c9246864-9f77-11e6-9e3a-7bdbf8c8252f.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19866776/cf7e1a8e-9f77-11e6-8495-34511c356f31.png)

**Comment by amaseda** [comment]
After you tried to create something, did you see any error in the tab that is running the Rails server? Might shed some light as to what's happening on the back-end.

**Comment by MichaelZLai** [comment]
So we're able to make a yelp api call,  however it's not redirecting us to the show page(#/feeded). Our backend is registering the location and sending an api request to Yelp and we're able to get the data. I'm just a little confused at the error (aka preflight)

![image](https://cloud.githubusercontent.com/assets/20713810/19867116/3d5dda2a-9f79-11e6-8e03-a2e1c22c97a1.png)

**Comment by MichaelZLai** [comment]
We're not able to hit our $save, but I'm not sure how it's making the yelp call if it isn't saving. 
![image](https://cloud.githubusercontent.com/assets/20713810/19868006/8f42099e-9f7c-11e6-96e2-5185c93e2a41.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19868015/9bf2db00-9f7c-11e6-9950-ff41ff1ce062.png)

**Comment by nolds9** [comment]
@MichaelZLai can you post your `foodFactory` definition and corresponding rails `create` action?

**Comment by MichaelZLai** [comment]
In Ruby

![image](https://cloud.githubusercontent.com/assets/20713810/19868336/fe2531a0-9f7d-11e6-8331-4a4924814c47.png)

In app.js
![image](https://cloud.githubusercontent.com/assets/20713810/19868373/25eefc16-9f7e-11e6-8066-e98968446816.png)

**Comment by nolds9** [comment]
in your `create` action, I don't think you want to redirect from the Rails side, you just want to send back some JSON with the newly created food, then use Angular to "redirect" the user to a new view...

**Comment by MichaelZLai** [comment]
ah ok, So I made some modification to the Rails side
![image](https://cloud.githubusercontent.com/assets/20713810/19868770/f5895f6a-9f7f-11e6-9a2d-bc2d5dc312b3.png)

and im redirected to the show page in the angular app. However i'm getting this console error
![image](https://cloud.githubusercontent.com/assets/20713810/19868847/3f1c4cdc-9f80-11e6-82fc-1c2322c9e7b1.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19868876/58225190-9f80-11e6-82ff-ffe3642ee6f5.png)

**Comment by jshawl** [comment]
what url is in your browser for angular show page?

**Comment by jshawl** [comment]
bad confg usually shows up when you're requesting an object but receive an array

**Comment by MichaelZLai** [comment]
It redirected me to http://localhost:8080/#/feeded (which is correct in the Router function)

![image](https://cloud.githubusercontent.com/assets/20713810/19869026/f82ef71a-9f80-11e6-8da9-ac96fa1393a4.png)

**Comment by jshawl** [comment]
alright cool but there is no id in `/feeded` - is that right? how do you know which food to load?

**Comment by MichaelZLai** [comment]
that's correct. We want the food to be uploaded right when the submit happens on the front end and not use any past searches. So immediately in feeded, it should use the last :id created. Not sure if we have to modify the show controller
![image](https://cloud.githubusercontent.com/assets/20713810/19869276/0ff08d2c-9f82-11e6-800b-fdf04c774ad0.png)

**Comment by jshawl** [comment]
I think you need to modify your URL to have a placeholder for `:id` in show state

**Comment by MichaelZLai** [comment]
hmmm, ok. So now our `:id` is present in our show page, however getting to  our show page from our index after inputting a location, we are still getting this error.

![image](https://cloud.githubusercontent.com/assets/20713810/19870068/53fbeb26-9f85-11e6-8ea9-73315765fbec.png)

**Comment by nolds9** [comment]
what does your `url` look like?

**Comment by MichaelZLai** [comment]
`http://localhost:8080/#/feeded/` **this happens after the index page -> show page. 

![image](https://cloud.githubusercontent.com/assets/20713810/19870156/c0b8a2ea-9f85-11e6-8eb0-f1508783be79.png)

**Comment by nolds9** [comment]
so looks like the id was not added to the url, I would double check that `food` in the above controller code is what you think it is...

**Comment by MichaelZLai** [comment]
hmm, I'm troubleshooting and I'm getting the exact same error message every single time. I'm using the WDInstagram for reference and on that homework, it's essentially the same format, however it's working there and not here. 
![image](https://cloud.githubusercontent.com/assets/20713810/19871608/0489514e-9f8c-11e6-8a44-963664258dc9.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19871614/0f6a764c-9f8c-11e6-8242-c42ac297eb73.png)

**Comment by nolds9** [comment]
There's your problem, `food.id == undefined`. Does it save the new item on the back-end? What does your `create` controller send back from rails?

**Comment by MichaelZLai** [comment]
It's returning an id when I do `puts @food.id` in the backend (ex id of 26)
![image](https://cloud.githubusercontent.com/assets/20713810/19873175/edba6d9c-9f93-11e6-8c94-7f8da0d7d746.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19873169/e194b810-9f93-11e6-8a35-29ce8b6e79ba.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19873227/3484d276-9f94-11e6-8ba6-ee1be0c4456c.png)

**Comment by nolds9** [comment]
The problem is you are rendering all the yelp results as `json` and not the single new `food` object that was just created.

I think you want your last line to be `render json: @food`

**Comment by MichaelZLai** [comment]
omg... after 4 hours of troubleshooting that one line worked. Thank you!

**Comment by nolds9** [comment]
🎉
