### ISSUE TITLE
Testing API in rails c 

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project3#286]
We are trying to get education info of a specific doctor through rails C, however, we are getting error from what we have in the doctor model file. Is the setup in the file correct?

![image](https://cloud.githubusercontent.com/assets/15622467/19860326/ae9b0e4e-9f5e-11e6-80e3-f0e61235aaff.png)

![image](https://cloud.githubusercontent.com/assets/15622467/19860385/e26e4362-9f5e-11e6-8e39-848a61746a8e.png)

**Comment by nolds9** [comment]
To start, looks like you have some syntax errors in that model code you posted...

**Comment by nolds9** [comment]
make sure there is a closing `"` mark at the end of your url line

**Comment by pohckuan** [comment]
yes , the closing " mark was missing, and I added it. 
when i entered  mark = Doctor.new("Mark Cinnamon, MD") again, I got this error:
NoMethodError: undefined method `[]' for nil:NilClass

**Comment by nolds9** [comment]
so this is because you are using your `Doctor` model which inherits from Active Record Base, but then you are overwriting the classes `initialize` method as well as the `name, school` properties on that mode. Active Record doesnt like this and therefore doesn't know how to create a new instance now...what is your end goal?

**Comment by amaseda** [comment]
Also, you can't just pass a string by itself into `.new`. What attribute does "Mark Cinnamon, MD" match with?

**Comment by pohckuan** [comment]
our end goal(for now) is to test out the api with the back end. We would like to get the educations(school), practices(phones) and etc in the terminal. 
@amaseda: "Mark Cinnamon, MD"  is the ":name" in the json object in the API,which is inside the "practices"

**Comment by pohckuan** [comment]
the overall goal is that we want to make a search box that allows users to search for doctors and show their infos (which are in the API) in their individual show pages.

**Comment by amaseda** [comment]
Doctor is an Active Record model, so you're going to have to match that value with an attribute (column) from your `doctors` table. Sounds like it's "name," which you'll have to mention inside of `.new`.

☝️ This is what's causing that error in the Rails console ☝️ Is there another error you're encountering?

**Comment by pohckuan** [comment]
Since all the info are from the API, do we still need to define the attributes in the table? Our doctor table is empty now, because we thought that we will not be editing doctors' info. 

we are also getting a nodatabase error while we run localhost 3000
![image](https://cloud.githubusercontent.com/assets/15622467/19861630/aeff03d6-9f63-11e6-88d3-b8d1e81ccd9d.png)

**Comment by amaseda** [comment]
Your error tells me that you haven't created your database yet.

As for the doctors, do you want to save in your database or not? The fact that Doctor is a class that inherits from ActiveRecord indicates yes.

**Comment by nolds9** [comment]
so if you are not going to persist any data about `Doctor`s then you do not need that class to inherit from `ActiveRecord::Base` and in that case you need to treat it as a normal Ruby Class.
I would look at some [examples from HTTparty ](https://github.com/jnunemaker/httparty/tree/master/examples) as well check out one of our instructor's (Andy's) blog post on [wrapping server-side api calls in Ruby Classes](http://andrewsunglaekim.github.io/Server-side-api-calls-wrapped-in-ruby-classes/)

Is your blue elephant running? Have you created your database?

**Comment by pohckuan** [comment]
We did create a database and the lil blue elephant is running. 
I think we will remove the ActiveRecord fro the Doctor class, since we are getting everything from the API and have nothing of Doctor in the database. 
The database was created by the repo maintainer, and I pulled the repo from github. Is that gonna affect the database?

**Comment by nolds9** [comment]
nope, shouldn't break anythng

**Comment by nolds9** [comment]
going to close this for now but free to open a new one if issue persists
