### ISSUE TITLE
migrations

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#287]
![image](https://cloud.githubusercontent.com/assets/8737117/19860706/28e96654-9f60-11e6-8708-7b4f63cfa592.png)

Hello fellas,

Does the datatype for each of my attributes look correct? I haven't used any of these before.

**Comment by jshawl** [comment]
yes! try it out with seeds and see if you get any errors

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8737117/19861041/69b8b058-9f61-11e6-9869-cf264bd046f8.png)

I got this error after running db:migrate. I'll try to fix then do a test with my seeds.rb file.

**Comment by jshawl** [comment]
does an opening have many skills?

**Comment by ghost** [comment]
Yes it does.

**Comment by jshawl** [comment]
ok perfect, so then you can that form this migration, and create another which references this model

**Comment by ghost** [comment]
Sorry. I don't understand what you mean. But do I need to add `array: true` after my symbol for skills? 
![image](https://cloud.githubusercontent.com/assets/8737117/19861218/227488ba-9f62-11e6-8cb5-3c1c2758bf6d.png)

**Comment by jshawl** [comment]
my recommendation is to create the migration for openings, ignoring skills and education for the moment, because skills an education will reference openings

**Comment by ghost** [comment]
Oh I think I get it!

**Comment by ghost** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/8737117/19861694/f334fdb2-9f63-11e6-8486-50d2e981000a.png)

**Comment by jshawl** [comment]
the references indicates that an opening belongs to a skill and belongs to an education - is that right?

**Comment by ghost** [comment]
Well skills and education are not models. Our models are Openings and Applicants, education and skills are shared attributes between the two and I need them to be arrays for the user to be able to CRUD.

**Comment by jshawl** [comment]
can you make them be models? Might be easier to manage over time

**Comment by ghost** [comment]
I can definitely do that, however I wouldn't really understand why unless you helped me to understand it better. :)

**Comment by jshawl** [comment]
having a separate model will allow you to edit one skill without affecting the others

**Comment by jshawl** [comment]
also, you could do a reverse search - find all the openings where the skills incudes X

**Comment by ghost** [comment]
This is the ERD we are working with:
![image](https://cloud.githubusercontent.com/assets/8737117/19862253/e23dfa02-9f65-11e6-8ef4-4129aad37b34.png)
Based on your recommendation, I should create entities for both Skills and Education. What attributes should I give them?

**Comment by jshawl** [comment]
idk - can you leave it as a string for right now just so you can keep making progress?

**Comment by ghost** [comment]
Definitely. I'll keep them as strings. Can you point me in the right direction for when I need to make them arrays?

**Comment by jshawl** [comment]
yes! closing for now - feel free to open a new one
