### ISSUE TITLE
Rails d model <Model name> is hanging

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/project3#289]
I'm not sure how long to wait or where to look for a resolution since there is no error message.

**Comment by amaseda** [comment]
Run `$ spring stop` in the Terminal and then try `rails g model` again.

**Comment by nolds9** [comment]
@bcope is this still an issue? 
When this happens to me I usually stop my server then run `$ spring stop`, followed by `$ spring start` and then I am able to use rails commands as normal
