### ISSUE TITLE
completing delete method

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#29]
We are currently trying to implement a "DELETE WORKOUT" function which will delete the workout.  We tried adding a click event to delete the workout on line 32 of the workoutView.js located within the public folder.  We expected the workout to delete but instead the error message "Uncaught TypeError: self.workout.destroy is not a function" was displayed in the console.  We believe we have not correctly added the delete method to the workoutview prototype.  We originally tried to add this 

``` js
  destroy: function(){
    var self = this;
    this.workout.destroy().then(function(){self.render();});
  },
```

and it did not work.  Thank you

**Comment by RobertAKARobin** [comment]
Your route looks fine. If you're getting `self.workout.destroy is not a function`, then that means that `self` or `self.workout` isn't what you think it is. The value of `this` can change a lot in Node apps. I'd recommend doing a `console.log(self.workout)` to see what it really is, and then going from there.

**Comment by murgia** [comment]
Just fixed it.  I blew it and put the destroy method in the view.  It should be in the model.
