### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project3#290]
we just created some seeds with the info we got from API. When we do Doctor.all in rails c, we got this message that says
 "
2.3.1 :001 > Doctor.all
  Doctor Load (0.6ms)  SELECT "doctors".* FROM "doctors"
 => #<ActiveRecord::Relation []> " 
![image](https://cloud.githubusercontent.com/assets/15622467/19867103/35711192-9f79-11e6-9832-2b5a2a9df1df.png)

![image](https://cloud.githubusercontent.com/assets/15622467/19867120/4068232e-9f79-11e6-9a10-cf84aea1e54a.png)

**Comment by nolds9** [comment]
if you have an ActiveRecord model called `Doctor` you need to use that to create a bunch of doctor records from that data

**Comment by nolds9** [comment]
i.e. `Doctor.create(name: "Mark Cinnamon", education: "GWU", specialty: "Internist", img_url: "....")`

**Comment by griffind2009** [comment]
@nolds9 do we still use the json format in another file?

 i.e. {
  "users": [
    {"name": "Bob", "id": 23},
    {"name": "Tim", "id": 72}
  ]
}

**Comment by nolds9** [comment]
you shouldn't need a JSON file to seed the database...what Im thinking is just using some of those key value pairs to help create each new doctor

**Comment by amaseda** [comment]
Any progress on this issue?

**Comment by pohckuan** [comment]
Its fixed! Thanks!
