### ISSUE TITLE
LinkedIn API Call Inquiry

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project3#291]
Gentlemen,

I am a tad confused. The documentation, below, seems to indicate that a standard call (r_basicprofile) should include a photo url, among many other things. We are only getting name, id, title, and page url. Why are we missing so much data, any thoughts?

https://developer.linkedin.com/docs/fields/basic-profile

![image](https://cloud.githubusercontent.com/assets/20960160/19869341/48d873ca-9f82-11e6-8d61-14c74a158272.png)

**Comment by jshawl** [comment]
is there anything above headline?

**Comment by lizafloyd** [comment]
Nope!

**Comment by nolds9** [comment]
Are you sure you are granting the necessary permissions?

> "To access any of the following basic profile fields, your app must request the `r_basicprofile` member permission"

**Comment by jshawl** [comment]
what happens if you visit this url? ![](https://dl.dropbox.com/s/31o0h67ge8rw49q/Screenshot%202016-10-31%2016.06.42.png?dl=0)

**Comment by lizafloyd** [comment]
Thank you guys! We just figured it out. Sorry for the goose chase.

**Comment by jshawl** [comment]
what is the solution?!

**Comment by lizafloyd** [comment]
``` js
function getProfileData() {
 IN.API.Raw("/people/~:(id,firstName,lastName,emailAddress,picture-urls::(original),headline)?format=json").result(onSuccess).error(onError);
}
```

**Comment by lizafloyd** [comment]
Latoya found it.

**Comment by jshawl** [comment]
👍 kk thanks!
