### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#292]
Hey fellas,

I came across this error yesterday when trying to create my delete functionality.
<img width="500" alt="statementinvaliderror" src="https://cloud.githubusercontent.com/assets/8737117/19890299/35d25c8a-a010-11e6-86a5-a50ad971276f.png">

I tried Googling for what the error meant but did not understand what I was reading. I know it has something to do with the `has_and_belongs_to_many` statements I wrote for both my `Openings` and `Applicants` model.

I'd like to get your help understanding what the error means and what you think I should do if I need to change my statements.

A little bit of context, our project is an API for Developer Job Openings and Applicants. The goal is to use Angular to perform an evaluation presenting employers with a top, middle and bottom tier of Applicants for their Opening.

Thanks guys!

**Comment by jshawl** [comment]
do you have a migration that creates the applicants_openings table?

**Comment by ghost** [comment]
Yezzir. `20161031182505_create_openings_applicants_join_table.rb`

``` ruby
class CreateOpeningsApplicantsJoinTable < ActiveRecord::Migration[5.0]
  def change
    create_table :openings_applicants, id: false do |t|
      t.integer :opening_id
      t.integer :applicant_id
    end

    add_index :openings_applicants, :opening_id
    add_index :openings_applicants, :applicant_id
  end
end
```

**Comment by jshawl** [comment]
you created a table named `openings_applicants` but active record is looking for a table named `applicants_openings`

**Comment by jshawl** [comment]
what's the name of your model?

**Comment by ghost** [comment]
I only have two models; `Openings` and `Applicants`. Will creating an `OpeningsApplicants` model solve this error? This is the Join Table?

**Comment by jshawl** [comment]
yeah try it out!

**Comment by jshawl** [comment]
also - try to solve this issue w/ seeds

**Comment by ghost** [comment]
Okay, I have seeds and I can do everything except destroy. Also, I thought that because I am using the HMABT, I did not need an intervening model. We don't need the Rails API to make the associations. We were planning on Angular handling all that. Do you think that is faulty?

Still testing.

**Comment by jshawl** [comment]
hmm can i see schema.rb? not sure yet

**Comment by ghost** [comment]
schema.rb

``` ruby
ActiveRecord::Schema.define(version: 20161031182505) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "applicants", force: :cascade do |t|
    t.string  "name"
    t.string  "skills"
    t.string  "education"
    t.integer "years_exp"
    t.boolean "local"
  end

  create_table "openings", force: :cascade do |t|
    t.string  "opening_name"
    t.string  "skills"
    t.string  "education"
    t.integer "years_exp"
    t.boolean "local"
  end

  create_table "openings_applicants", id: false, force: :cascade do |t|
    t.integer "opening_id"
    t.integer "applicant_id"
    t.index ["applicant_id"], name: "index_openings_applicants_on_applicant_id", using: :btree
    t.index ["opening_id"], name: "index_openings_applicants_on_opening_id", using: :btree
  end

end
```

**Comment by jshawl** [comment]
yes I believe you will need an intervening model  - try it and see if that solves the issue

**Comment by ghost** [comment]
Here's the model and now when I click the Delete, the previous error doesn't show!

``` ruby
class OpeningApplicant < ActiveRecord::Base
  create_join_table :openings, :applicants do |t|
    t.integer :opening_id
    t.integer :applicant_id
  end
end
```

**Comment by ghost** [comment]
my openings controller

``` ruby
  def destroy
    @opening = Opening.find(params[:id])
    @opening.destroy
    redirect_to openings_path
  end
```

**Comment by jshawl** [comment]
no more errors?

**Comment by ghost** [comment]
It came back after I added `method: :delete` to my erb link.
![image](https://cloud.githubusercontent.com/assets/8737117/19891040/9a1af28e-a014-11e6-8375-c3085546f228.png)

**Comment by jshawl** [comment]
I am totally happy to help you - but can you create a seed to fix this issue?

The problem is that some table doesnt exist. Can you create seed data and send that my way?

**Comment by ghost** [comment]
Yes. Can I use my token now?

**Comment by jshawl** [comment]
sure
