### ISSUE TITLE
Theory

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project3#293]
So I've come to the crux of my problem: my API is not connected in any way to my angular app. Sad that it took me 24 full hours to figure that out. Oh well.

I've referenced it in $resource, but I'm getting 404 Does Not Exist, which I believe means my API is not connecting right.  How should I have done that? And how should I have formatted my API to handle my data?

**Comment by jshawl** [comment]
ok 404 is a great sign! it means it's connected to your api (or some other server)

can you take a screenshot? everything sounds right so far

**Comment by jshawl** [comment]
specifically would like to see your resource definition and an error message

**Comment by lizafloyd** [comment]
![image](https://cloud.githubusercontent.com/assets/20960160/19890588/1b193e0c-a012-11e6-84e1-1b4da499955d.png)
 Error

**Comment by jshawl** [comment]
ok great! visit `http://localhost:3000/` in a separate browser window - what do you see?

**Comment by lizafloyd** [comment]
Resource Definition:
![image](https://cloud.githubusercontent.com/assets/20960160/19890616/37bd3af4-a012-11e6-9964-49417afe476f.png)

**Comment by lizafloyd** [comment]
Just that I'm on rails

**Comment by lizafloyd** [comment]
Ok, at 3000/events, I get 404

**Comment by jshawl** [comment]
and no route exists? can i see config/routes.rb?

**Comment by lizafloyd** [comment]
"#<AbstractController::ActionNotFound: The action 'index' could not be found for EventsController>",

**Comment by lizafloyd** [comment]
AbstractController::ActionNotFound: The action 'index' could not be found for EventsController>"

**Comment by jshawl** [comment]
ok excellent! do you have `resources :events` in config/routes?

**Comment by lizafloyd** [comment]
So what should I have in my rails controllers? Shouldn't crud be on the angular side?

**Comment by lizafloyd** [comment]
I believe so, will check

**Comment by jshawl** [comment]
angular intiates the CRUD, rails does the actually CRUDing, and responds to angular

**Comment by lizafloyd** [comment]
Yes, routes are a go: 

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
end

**Comment by lizafloyd** [comment]
Really? OK, that helps.

**Comment by jshawl** [comment]
what's the output of rails routes?

**Comment by jshawl** [comment]
are you sure the right server is running?

**Comment by lizafloyd** [comment]
![image](https://cloud.githubusercontent.com/assets/20960160/19890686/b9a0d3e6-a012-11e6-8ba4-147c85bfd19f.png)

**Comment by jshawl** [comment]
can I see your events controller in rails?

**Comment by jshawl** [comment]
The action 'index' could not be found for EventsController means there is no method `index` in that controller

**Comment by lizafloyd** [comment]
I think I've done my setup wrong then, is the issue.

So I want rails to be making instances of models, and angular calling them through ajax? if so, what role do factories have?

**Comment by lizafloyd** [comment]
Yes, that's right. I've been doing violent things to my controller. Give me a sec.

**Comment by lizafloyd** [comment]
Yay, new error! I put my controller back to where it was and I'm back to (what I thought was an old) error. 

```
ActionView::MissingTemplate: Missing template events/events, application/events with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "/Users/lizafloyd/wdi/projects/tatiana/app/views" >"
```

**Comment by jshawl** [comment]
ok - i think you want to respond with json, instead of html, right? can isee the definition of your index method

**Comment by lizafloyd** [comment]
![image](https://cloud.githubusercontent.com/assets/20960160/19890804/3e4179b6-a013-11e6-8a05-9ead33e50f52.png)

**Comment by jshawl** [comment]
ohhhh change your resource definition so that its `http://localhost:3000/events/:id.json`

orr remove the respond_to do block and only respond w/ json

**Comment by lizafloyd** [comment]
ArgumentError: too few arguments>

it's referencing line 6 in trace,
![image](https://cloud.githubusercontent.com/assets/20960160/19890950/136c011a-a014-11e6-8523-c44b71387847.png)

**Comment by jshawl** [comment]
remove everything on line 6 but `render json: @events`

**Comment by lizafloyd** [comment]
You're the best.

So to make sure I understand where to go from here: I have a rails controller doing crud. How does angular call rails instances? I was using factories but that's not going to work.

**Comment by jshawl** [comment]
strictly through api calls - I think what you have with factories is correct - keep going!

can you get Read done first? seed some data in rails - can you display it with angular?

**Comment by lizafloyd** [comment]
Yeah, it's coming through on localhost:3000, so for read OMG IT WORKS

**Comment by lizafloyd** [comment]
I guess I have no idea what factories do. Google here I come!

Thanks Jesse
