### ISSUE TITLE
jquery in angular 

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project3#294]
I wrote jquery inside a controller function for an index.html in the ng-views. But there's an $ not defined error when I load the page. 
![image](https://cloud.githubusercontent.com/assets/15622467/19890757/01f03362-a013-11e6-9f19-3503de38cd59.png)
![image](https://cloud.githubusercontent.com/assets/15622467/19890772/11cb67c0-a013-11e6-86a0-4c5f931dc3d3.png)

**Comment by jshawl** [comment]
are you linking to jquery via a script tag anywhere?

**Comment by pohckuan** [comment]
ahhhh okay. Just did it ! thanks!
