### ISSUE TITLE
Controllers and States for a Review

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project3#295]
Hello.  I just have a quick question.  For our group, our app is set up to display Doctors on a show.html page, so I just had a question about adding "reviews".  We decided add CRUD functionality for reviews of doctors.  

Can you help us understand how we'd set up the controllers and states for reviews if we're going to be displaying this on our show page?

**Comment by jshawl** [comment]
you could create a link:

```
<%= link_to "add a review", new_doctor_reviews_path(@doctor) %>
```

**Comment by brown2206** [comment]
Jessse, would reviews need their own Controller and state?

**Comment by jshawl** [comment]
I think that's the right move

**Comment by amaseda** [comment]
Going to close this one for now but feel free to re-open if you have any more questions about this issue.
