### ISSUE TITLE
Having Trouble with Factory and ngResource 

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project3#296]
I am trying to save the user's input and populate a drop down box with selections that matches or closely matches their input. However, I can only get it to save but not populate the selections drop-down using ngResource.

![screen shot 2016-11-01 at 9 55 24 am](https://cloud.githubusercontent.com/assets/20979785/19892099/95c3f398-a019-11e6-964a-442eb3e14db5.png)
![screen shot 2016-11-01 at 9 55 05 am](https://cloud.githubusercontent.com/assets/20979785/19892102/972fd666-a019-11e6-9565-eee84a05888f.png)

**Comment by amaseda** [comment]
How have you tried to populate the drop-down menu? Can you show some code? Are you getting any errors?

**Comment by griffind2009** [comment]
app.js
function DoctorIndexControllerFunction(DoctorFactory){
$('.button').on('click',()=>{
  var keyword = $('#doctor-search').val()
  console.log(keyword)
  })

**Comment by griffind2009** [comment]
html

![screen shot 2016-11-01 at 10 13 03 am](https://cloud.githubusercontent.com/assets/20979785/19892559/d39f36f8-a01b-11e6-81c6-0ad6d8f22536.png)

**Comment by griffind2009** [comment]
the rails server is running in the background

**Comment by jshawl** [comment]
can you put an ng-repeat inside that select? like we did w/ movie browser https://github.com/ga-wdi-exercises/movie-browser/blob/f55986184421e8f21bb72c0959e3e805432205e4/js/ng-views/index.html#L8

**Comment by griffind2009** [comment]
It's still not populating. Could it have to do with our backend? Or am I missing something from the function?

![screen shot 2016-11-01 at 10 17 58 am](https://cloud.githubusercontent.com/assets/20979785/19892690/8d24f8e2-a01c-11e6-804a-a50ae682d3c3.png)
![screen shot 2016-11-01 at 10 18 07 am](https://cloud.githubusercontent.com/assets/20979785/19892692/907bc6b0-a01c-11e6-8772-a420f87df196.png)

**Comment by amaseda** [comment]
What does the drop-down HTML look like in the page's source code (i.e., inspect the drop-down menu using Chrome dev tools)?

**Comment by griffind2009** [comment]
It's empty just the html that's above and the select is == to $0

![screen shot 2016-11-01 at 10 42 02 am](https://cloud.githubusercontent.com/assets/20979785/19893551/ee600e46-a01f-11e6-85b5-c35086a48c80.png)

**Comment by nolds9** [comment]
In your controller, I would make sure that `this.doctors` is what you think it is. Whats the output when you log `this.doctors` in the controller...

**Comment by amaseda** [comment]
What do you have saved in `vm.doctors`?

**Comment by griffind2009** [comment]
I had this.doctors = DoctorFactory.query() under
 function DoctorIndexControllerFunction(DoctorFactory), but it gave an error so I commented it out "angular.js:11655TypeError: Cannot read property 'query' of undefined"

**Comment by amaseda** [comment]
Sounds like it doesn't really that `DoctorFactory` uses `ngResource`. Are you passing in `DoctorFactory` as a dependency to your controller? Can you include all of you controller code?

**Comment by griffind2009** [comment]
vm is defined as an instance in the doctorsIndex state
![screen shot 2016-11-01 at 10 57 42 am](https://cloud.githubusercontent.com/assets/20979785/19894088/096a2ddc-a022-11e6-9dcc-3818a3dc3a3f.png)

**Comment by griffind2009** [comment]
![screen shot 2016-11-01 at 10 58 31 am](https://cloud.githubusercontent.com/assets/20979785/19894109/27be7252-a022-11e6-9af7-2411ebd953c3.png)

![screen shot 2016-11-01 at 10 58 15 am](https://cloud.githubusercontent.com/assets/20979785/19894110/2d16d032-a022-11e6-80ef-b092019e6df5.png)

**Comment by amaseda** [comment]
Don't think the issue is with your state. The fact that the error says your app doesn't recognize what `query` tells me there is a disconnect between your controller and factory. What exactly does your `DoctorIndexController` look like?

**Comment by amaseda** [comment]
Doesn't look like your including `DoctorFactory` as a dependency of your `DoctorIndexController`

**Comment by nolds9** [comment]
@griffind2009 can you show where you are injecting your factory in to your indexController? Also, can you post a bigger picture of your factory definition.

**Comment by griffind2009** [comment]
![screen shot 2016-11-01 at 11 01 11 am](https://cloud.githubusercontent.com/assets/20979785/19894202/87b92e86-a022-11e6-9679-07061a10caad.png)

**Comment by amaseda** [comment]
Start by fixing this: https://github.com/ga-wdi-exercises/project3/issues/296#issuecomment-257589312

...and that should allow you to use `.query`, which should then populate `vm.doctors` in your view.

**Comment by griffind2009** [comment]
Ok, I added "DoctorFactory" to the controller but I'm now getting a Cross Origin error. Do I need to add CORS now?

![screen shot 2016-11-01 at 11 08 03 am](https://cloud.githubusercontent.com/assets/20979785/19894448/7fe71a00-a023-11e6-9cf4-93a7ef5d27d2.png)

![screen shot 2016-11-01 at 11 08 35 am](https://cloud.githubusercontent.com/assets/20979785/19894530/bb37ee0e-a023-11e6-8b23-a4255abaa6fd.png)

**Comment by nolds9** [comment]
yes! You need to add `rackCors` gem to your Rails server, and follow the simple configuration guides for Rails 5 outlined here https://github.com/cyu/rack-cors#rails

**Comment by griffind2009** [comment]
Awesome, I'm not getting the error anymore, but I still can't get it to populate.

I fixed the factory in the index controller function. Was that the fix you were referring to "Start by fixing this: #296 (comment)"

**Comment by nolds9** [comment]
can we see where you are defining your factory and where you define your index controller in angular?

**Comment by griffind2009** [comment]
Yes

![screen shot 2016-11-01 at 11 36 57 am](https://cloud.githubusercontent.com/assets/20979785/19895545/8b31df4a-a027-11e6-8b34-8fdcea33e207.png)

**Comment by griffind2009** [comment]
![screen shot 2016-11-01 at 11 37 49 am](https://cloud.githubusercontent.com/assets/20979785/19895579/aac20a74-a027-11e6-82e0-d1e45d375857.png)

**Comment by nolds9** [comment]
So can you change your factory definition to follow the format that we've seen in class so far...https://github.com/ga-wdi-lessons/angular-resources#define-an-update-method-in-the-factory

**Comment by amaseda** [comment]
Going to close this one since it's been inactive for a few hours and we talked about it during our 1:1. Feel free to re-open if you have any more questions about it!
