### ISSUE TITLE
Using Factories with many to many relationship

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project3#297]
Hola!

Sorry to bother again--I am struggling with accessing a many to many relationship in angularjs.  

The code that I tried (that I'm not surprised didn't work is):
![image](https://cloud.githubusercontent.com/assets/20960160/19897512/aa7dfce2-a02e-11e6-8eda-8946d7b1b4bb.png)

The error is:
![image](https://cloud.githubusercontent.com/assets/20960160/19897525/b4803778-a02e-11e6-8fcf-7b12b09b46dd.png)

I am thinking that a next step might be to make a controller for my join table, but I'm not sure about that and thought I'd ask.

Thanks!

**Comment by nolds9** [comment]
What is your end goal? First, I would make sure that I have API routes for my join model that all respond to / with JSON.

**Comment by lizafloyd** [comment]
My end goal is to index associated users on the show page of an event. Those two are models.  So once I set up routes for my join table, what are my next steps after that? How do I get associated users. I tried doing this.attendees = UserFactory.get({event_id: $stateParams.id}). Didn't work.

**Comment by amaseda** [comment]
When you tried to retrieve the associated users, did you see a particular error on the back-end (i.e., in the terminal tab that's running your Rails server)? Will shed some light on whether it's a back-end issue and what the particular problem might be.

**Comment by lizafloyd** [comment]
Nick suggested that I do some form of route manipulation akin to:

``` rb
resources :songs, only: [:index, :show] do
  # This creates two custom routes for songs that correspond with controller actions of the same name.
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end  
end

resources :songs, only: [:index, :show] do
  # This creates two custom routes for songs that correspond with controller actions of the same name.
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end
end
```

But I'm a) not sure where I would then build the attendance function, in angular? and b) don't want to go to a different url in order to see associated users.

**Comment by lizafloyd** [comment]
When I do 
![image](https://cloud.githubusercontent.com/assets/20960160/19903084/aa1c5022-a043-11e6-8392-758e93838b70.png)

I can get the associated user to appear at localhost:3000/events/id.

How do I call @attendance on the page?

**Comment by lizafloyd** [comment]
Sorry, @attendees

**Comment by amaseda** [comment]
So the above `show` is in your Events controller? You could include it in the Event JSON that is served back to the user using `include`: https://github.com/ga-wdi-lessons/rails-api#pro-tip-include

**Comment by lizafloyd** [comment]
That worked great! Thanks Adrian!

The next problem is that I now cannot access the data in the object returned to me. I've tried dot and [] notation and I can't get inside! End goal is to get to this.event.attendances.user_id.

![image](https://cloud.githubusercontent.com/assets/20960160/19904441/ffaa7a1e-a048-11e6-9d51-736c7641d457.png)

**Comment by jshawl** [comment]
can you share some code?

**Comment by amaseda** [comment]
What does your controller action for this API route look like?

**Comment by lizafloyd** [comment]
I have played with a bunch of different forms of this code, but something like 

![image](https://cloud.githubusercontent.com/assets/20960160/19905018/66861624-a04b-11e6-9b98-7b6f69bc8a14.png)

**Comment by amaseda** [comment]
And what about the controller action on the back-end? Could fiddle around with both depending on the goal here.

**Comment by lizafloyd** [comment]
(Does using event as a model name cause problems? I've noticed it's a different color)

![image](https://cloud.githubusercontent.com/assets/20960160/19905054/8967ac5c-a04b-11e6-9457-b7e3c3db05fc.png)

**Comment by jshawl** [comment]
Eventfactory.get is asynchronous, can you add a callback there?

**Comment by amaseda** [comment]
Also, what happens when you dive into the `0: Object` in the response you referenced here: https://github.com/ga-wdi-exercises/project3/issues/297#issuecomment-257670924

**Comment by lizafloyd** [comment]
It's giving me that .then and .done are not functions. wouldn't that be the fix for the asynchronous problem?

Adrian, how do you mean? I am able to dig down in vm.event.attendances, but when I try to do this.event.attendances in my angular app, the whole thing become undefined.

**Comment by jshawl** [comment]
can you share then code w/ `.done` are not functions

**Comment by lizafloyd** [comment]
I tried this:
![image](https://cloud.githubusercontent.com/assets/20960160/19905391/ec3ec06c-a04c-11e6-8cf7-9a7023f6e5a1.png)

**Comment by lizafloyd** [comment]
And get this:
![image](https://cloud.githubusercontent.com/assets/20960160/19905400/f726496e-a04c-11e6-9d8f-8d7cc5d405c0.png)

**Comment by nolds9** [comment]
try adding `$promise` in between your `.get()` and `.then()` method calls.

I.e. `Eventfactory.get(..).$promise.then(function() {...})`

**Comment by jshawl** [comment]
The docs give this example:

``` js
var User = $resource('/user/:userId', {userId:'@id'});
var user = User.get({userId:123}, function() {
  user.abc = true;
  user.$save();
});
```

**Comment by lizafloyd** [comment]
# You guys are all the best

**Comment by jshawl** [comment]
# Couldn't do it without you!
