### ISSUE TITLE
dropdown menu 

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project3#298]
the drop-down menu on change it triggers itself, not sure how to fix to trigger its children
![image](https://cloud.githubusercontent.com/assets/18635698/19898224/813c9944-a031-11e6-9fcd-6c33e62fa593.png)

**Comment by nolds9** [comment]
Could you provide a little more context on what you are trying to accomplish? I think you want to use an Angular directive to trigger the change event, like `ng-change`...

**Comment by amaseda** [comment]
Going to close this one since it's been two hours, but feel free to re-open if you have any more questions about this issue.
