### ISSUE TITLE
redirect issue with CORS - preflight issue

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/project3#299]
Hey guys!

I'm running into a redirect issue with CORS. The data is saving but the redirect isn't working at all. Here's the error:

XMLHttpRequest cannot load http://localhost:3000/events. 
Redirect from 'http://localhost:3000/events' to 'http://localhost:3000/events/8' has been blocked by CORS policy: Request requires preflight, which is disallowed to follow cross-origin redirect.

Screenshot of issue:
http://screencast.com/t/VuO13ZKmQyM

Google tells me I need to 'preflight' my data but I'm not sure how or where to do this at?
http://stackoverflow.com/questions/8685678/cors-how-do-preflight-an-httprequest 

thanks!!

**Comment by jshawl** [comment]
diiiid you add rack-cors gem to your rails app?

**Comment by LWatsonlm** [comment]
yeah that gem is installed. I think I need to preflight somewhere in here.. config/app.rb file
![issue](https://cloud.githubusercontent.com/assets/6773087/19899592/183453f0-a037-11e6-871c-c6f4209b7ab5.png)

**Comment by jshawl** [comment]
oh dang did you restart the server?

**Comment by LWatsonlm** [comment]
yeah, sadly. multiple times. both the angular and rails

**Comment by jshawl** [comment]
can I see the code for your rails controller ? show action?

**Comment by jshawl** [comment]
sorry i mean create action

**Comment by LWatsonlm** [comment]
cool, okay 

here's the rails controller for event: 
![event rails](https://cloud.githubusercontent.com/assets/6773087/19900387/b14d9400-a039-11e6-9592-eae4010b2a80.png)

and the app.js has function for the saving
![app js](https://cloud.githubusercontent.com/assets/6773087/19900361/943d1516-a039-11e6-887c-09d89a2119f5.png)

**Comment by jshawl** [comment]
rails controller create: instead of redirecting, use `respond_to` or only `render json:`

**Comment by LWatsonlm** [comment]
what's after `respond_to`
?

**Comment by jshawl** [comment]
`do |format|`

**Comment by amaseda** [comment]
Any progress on this?

**Comment by LWatsonlm** [comment]
okay! progress update: needed the rails controller
`render json: @event`

and needed to add 'then' ... still working on the redirect with $state.go
`function eventNewControllerFunction(EventFactory, $state) {
  this.create = function(){
    Event = new EventFactory(this.event)
    Event.$save().then(event => {
      console.log(event);
      $state.go('eventShow')
    })
    }
}`

**Comment by LWatsonlm** [comment]
because that code came out funky: 
http://screencast.com/t/zy8xpeuyoi

**Comment by nolds9** [comment]
I think you need to pass the required parameters for the show route...Which `event` do you need to show?

**Comment by LWatsonlm** [comment]
looking to show the event that was just created

**Comment by amaseda** [comment]
`$state.go` requires another argument that indicates which particular event you want to show. Right now you're only indicating that you want to load the `eventShow` state.

Take a look at how `$state.go` is used in the routing lesson plan: https://github.com/ga-wdi-lessons/angular-routing

**Comment by LWatsonlm** [comment]
awesome, got it! thanks all for the team effort! or like I like to say, teffort!
