### ISSUE TITLE
Adding a heading to a workouts page

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#30]
We are having trouble visualizing how to add a basic h1 tag to one of the pages.  For exampling the top of the page should list Workouts and then next to that we would have a button to add a new workout.  We have tried adding it in the workout view folder but have only managed to get the tag to show up in every instance of a workout that is done.

**Comment by RobertAKARobin** [comment]
Did you add it to your `layout.hbs`?

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to close this!
