### ISSUE TITLE
Error Connection Refused

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project3#300]
![image](https://cloud.githubusercontent.com/assets/20567326/19900172/f8d020fa-a038-11e6-8741-199a1a8c3f38.png)

Can you help me look at this error connection refused issue.  We're attempting to get our show page to show Doctor information, but we're getting this error.

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19900248/308af5ec-a039-11e6-82f9-6e5c88d4c6c8.png)

**Comment by jshawl** [comment]
is your rails app running?

**Comment by brown2206** [comment]
yes

**Comment by jshawl** [comment]
what happens if you visit `http://localhost:3000/doctors?id=1` in a browser?

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19900355/91a386f0-a039-11e6-81dc-b895ee005e19.png)

**Comment by brown2206** [comment]
This is what I get.

**Comment by jshawl** [comment]
ok excellent! this indicates that you need to create the database

**Comment by brown2206** [comment]
Ok so I created the database and seeded.  Then I got this error...

![image](https://cloud.githubusercontent.com/assets/20567326/19900516/283d7940-a03a-11e6-8b84-8dbbfb8136a9.png)

Does this mean that we're not using this Angular library?

**Comment by jshawl** [comment]
what url is in your bowser when you get that error?

**Comment by brown2206** [comment]
http://localhost:8080/#/doctors/1

**Comment by jshawl** [comment]
ok can i see your factory definition?

**Comment by brown2206** [comment]
I think our factory definition may be wrong.  I'll show you what I have in about 5 min.

**Comment by amaseda** [comment]
Any progress on this?

**Comment by brown2206** [comment]
We're attempting to merge our changes with the new Factory.  I'll have an
update for you shortly.

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19903086/ab515dfc-a043-11e6-97a6-e37bb272b215.png)

Ok, I'm back.  This is the error message that I'm receiving when we try to view the show page.

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19903114/c934914a-a043-11e6-83ac-f66570515c21.png)

This is our FactoryFunction
![image](https://cloud.githubusercontent.com/assets/20567326/19903121/d12a35c6-a043-11e6-940b-f40d0f3b589e.png)

**Comment by nolds9** [comment]
missing the `/:id` on the end of your url ^

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19904437/f7754892-a048-11e6-9c0e-b3809d2e597d.png)

Nick, the show page appears to be working okay now.  I'm just curious, what does this error mean?

**Comment by jshawl** [comment]
can you remove the `.min` from the script tag?
