### ISSUE TITLE
Map already initialized

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project3#301]
Background: We have our map function working on initial load, however when we click "no" it populates a different location with a different address, however the error we get is that our map is already initialized. We've been messing around with different remove techniques, however it's just removing our entire map in general

![image](https://cloud.githubusercontent.com/assets/20713810/19900748/f67f5d28-a03a-11e6-9c59-f2f7f75bc463.png)

**Comment by jshawl** [comment]
can you share some code?

what is initializing the map (should be two different bits of code)

**Comment by MichaelZLai** [comment]
yup, here is where we initialize our map
![image](https://cloud.githubusercontent.com/assets/20713810/19900973/cd63e1a6-a03b-11e6-9737-1c27026f626a.png)

On ng-click, we initialize `getNextBiz()` which increments our array index and removes the map, however it removes it permanently. I thought it would be reinstantiated through the `mapfunction()`

![image](https://cloud.githubusercontent.com/assets/20713810/19901087/395a1cc2-a03c-11e6-90b2-1aa060e65fbc.png)

**Comment by jshawl** [comment]
hmm it looks like `L.map()` is the culprit. Can you create two different functions? One that creates the map, and another that manages the tile layer?

**Comment by MichaelZLai** [comment]
hmm, ok I think I get what you're saying. but how will we add our tilelayer to our map function if they are different functions??

![image](https://cloud.githubusercontent.com/assets/20713810/19902254/59fb16b2-a040-11e6-9ed7-f24d83fa8efa.png)

**Comment by jshawl** [comment]
can you return something from one of those functions and save it to a variable?
