### ISSUE TITLE
Triple Nesting Woes

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project3#302]
I'm trying to add a comments table which will have many destinations and the destinations will have many comments.  Comments will be nested inside destinations which is already nested inside passports.  

![image](https://cloud.githubusercontent.com/assets/19317100/19904942/201cc070-a04b-11e6-9afa-eb0c3940cbdc.png)

I created a migration for comments which contains references to destination (which I'm not sure is assigning destination an ID or not), a body for the comment and a name.  

![image](https://cloud.githubusercontent.com/assets/19317100/19905029/6ff34786-a04b-11e6-8aaa-ad7c987df305.png)

I was also trying a different way to add references by adding them separately.

![image](https://cloud.githubusercontent.com/assets/19317100/19905072/9b24b4ee-a04b-11e6-8760-f865cd212088.png)

Needless to say when I run rails db:migrate nothing is working properly so I'm unsure about the foreign key's this needs since it is triple nested.

**Comment by jshawl** [comment]
do you get any error essages w/ `rails db:migrate`?

**Comment by nolds9** [comment]
@alman92 don't think you want that last migration...

**Comment by alman92** [comment]
Yea that last one I'm sure is wrong at this point just a last stitch effort to make something work

**Comment by alman92** [comment]
No error message now and here is my schema.

![image](https://cloud.githubusercontent.com/assets/19317100/19905223/24e9a1d0-a04c-11e6-96e6-3c267e3e5b38.png)

My issue now is that when i seed I get an error and I'm baffled as to why.  There was nothing wrong with them before I made this table.

**Comment by alman92** [comment]
Asking for passport_id

![image](https://cloud.githubusercontent.com/assets/19317100/19905271/61bcbfd4-a04c-11e6-922a-a65ae37c8be2.png)

**Comment by jshawl** [comment]
can i see your seeds

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19905306/87979bfc-a04c-11e6-8d25-6faadb630deb.png)

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19905314/9363b8e4-a04c-11e6-9dcb-f88c85c04b88.png)

**Comment by nolds9** [comment]
I think you just need to add a column to `destinations` that is a foreign key for `passports`

**Comment by nolds9** [comment]
another way of saying, missing a `passport_id` column in the `destinations` table

**Comment by alman92** [comment]
so run a 

$ rails g migration add_column_to_destinations

and then a t.reference :passport

**Comment by alman92** [comment]
?

**Comment by amaseda** [comment]
That sounds right, give it a shot. Although `t.references` (with an s)

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19905613/f8ab5512-a04d-11e6-907b-99983179fe20.png)

![image](https://cloud.githubusercontent.com/assets/19317100/19905618/ffaa7bae-a04d-11e6-94fa-a526ae3eb969.png)

Making progress....

**Comment by jshawl** [comment]
should be `add_column, :destinations, :passport_id, :integer`

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19905780/8f3184de-a04e-11e6-9e0f-1a77cf0bf34f.png)

........? Does it need to be destinations: ?

**Comment by jshawl** [comment]
can i see what code you tried? no comma after `add_column`

**Comment by alman92** [comment]
It was the comma -_- but its seeding now!!!!

**Comment by jshawl** [comment]
👍 radical

**Comment by alman92** [comment]
Great i'm good to go now, thank you guys so much 👍 🇺🇸
