### ISSUE TITLE
dropdown menu cant make it function

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project3#303]
![image](https://cloud.githubusercontent.com/assets/18635698/19906300/99402cee-a050-11e6-9ccd-0140b1495ebc.png)
here is a code snippet of my function
![image](https://cloud.githubusercontent.com/assets/18635698/19906332/b7e5da9a-a050-11e6-8174-888f72a9bc35.png)

**Comment by jshawl** [comment]
what is `$response`?

**Comment by marlungu** [comment]
unsure, i tried without $ but is not working either

**Comment by jshawl** [comment]
what is the output of `console.log(select)`

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19906565/a5a829fe-a051-11e6-89af-137b5d948e94.png)

prints the country itself

**Comment by jshawl** [comment]
ah ok - what about `console.log(this.countrySelect)`?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19906688/26ef50b4-a052-11e6-888c-d68d82530500.png)

**Comment by jshawl** [comment]
ah ok - what about `console.log(this.countrySelect.id)`?

**Comment by marlungu** [comment]
prints out only the id

**Comment by jshawl** [comment]
can you use that id in `$state.go` ?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19907066/aedb3eb0-a053-11e6-81b8-adeee33d23a5.png)
![image](https://cloud.githubusercontent.com/assets/18635698/19907084/c3c829c8-a053-11e6-952c-347682a18346.png)

**Comment by jshawl** [comment]
can you use that id in `$state.go` ?

**Comment by marlungu** [comment]
just tried, no

**Comment by jshawl** [comment]
what did you try / are there any error messages?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19907279/8051d1c0-a054-11e6-9169-0add36cb9825.png)
![image](https://cloud.githubusercontent.com/assets/18635698/19907291/8bd9d2d6-a054-11e6-8088-8221ed78feaf.png)

**Comment by nolds9** [comment]
So now you are going to the index, I think you want to go to the show

**Comment by nolds9** [comment]
can you share you state definitions?

**Comment by marlungu** [comment]
ive tried different methods. when changed the show page is not working.

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19907404/10d956b4-a055-11e6-9e10-0d939fd1e544.png)

**Comment by amaseda** [comment]
What happens / what errors do you get when you try the same `$state.go` code you use [here](https://github.com/ga-wdi-exercises/project3/issues/303#issuecomment-257695048) except with directing the user to the show state, **not** the index.

**Comment by amaseda** [comment]
Going to close this one since we made some progress in-person, but feel free to re-open if you have any questions about this.

**Comment by marlungu** [comment]
ok, thank you
