### ISSUE TITLE
Reviews not rendering properly in browser.

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project3#305]
Hello.  We're trying to fix our reviews so that they render in the browser.  We listed each review using the "vm", but it's not displaying properly.  I remember we went over this is class, but can you explain what we may have mistyped here?  Thanks.

Our Code:
![image](https://cloud.githubusercontent.com/assets/20567326/19906671/107fa91e-a052-11e6-8e1b-e285c0356662.png)

The browser:
![image](https://cloud.githubusercontent.com/assets/20567326/19906698/33bfe1d2-a052-11e6-951e-db6f0b6eb786.png)

**Comment by jshawl** [comment]
thing to google is `ng-repeat`

**Comment by nolds9** [comment]
looks like `vm.doctor.reviews` is an array. Sounds like you want to iterate over that array and display out each review's information. Sounds like you are going to need an angular directive

**Comment by brown2206** [comment]
We were considering using ng-repeat but with ng-repeat, I haven't seen a way to display 

![image](https://cloud.githubusercontent.com/assets/20567326/19906964/52de2438-a053-11e6-9313-d98267436233.png)

**Comment by nolds9** [comment]
`ng-repeat` is what you want, check your syntax

**Comment by brown2206** [comment]
I agree with you Nick, but with ng-repeat, where would our headings go such as Name:, Speciality, etc?

**Comment by brown2206** [comment]
disregard

**Comment by brown2206** [comment]
disregard...found it

**Comment by brown2206** [comment]
thanks

**Comment by jshawl** [comment]
👍
