### ISSUE TITLE
dropdown Search Box

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/project3#306]
I want to make a search bar that shows items that match the input in a drop down . Right now, it is showing all the items and filtered item when I have input in the search box. 
![image](https://cloud.githubusercontent.com/assets/15622467/19907299/96776ac8-a054-11e6-85aa-aa44c0766280.png)
![image](https://cloud.githubusercontent.com/assets/15622467/19907316/af83fdba-a054-11e6-9d56-706b6aa9b8db.png)
I would like to make a search bar that will display " mark cinnamon" in a drop down when i type in "mark"

**Comment by jshawl** [comment]
highly highly recommend this plugin https://harvesthq.github.io/chosen/
