### ISSUE TITLE
Devise User Creation (registration) via AJAX

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/project3#307]
We're trying to allow users to sign-up via AJAX from our Angular front-end and we're being met with many an error. Our `email`, `password`, and `password_confirmation` params are being properly sent, but I think the problem might be that the params aren't permitted and I'm not sure how to permit them when they are coming from JSON.

I've been working loosely with [this guide](https://www.natashatherobot.com/devise-sign-up-ajax-rails/) to get this far.

**Comment by jshawl** [comment]
can you take a screenshot of the error message

**Comment by nickoki** [comment]
Here's the most recent screenshot. Sign Up seems to be working now, but Sign In and our method to create posts can't verify CSRF Token Authenticity
![image](https://cloud.githubusercontent.com/assets/15880182/19929981/7b62b9ee-a0dc-11e6-9951-0501af2b9a95.png)

Sign in is `POST "/auth_user"`

**Comment by jshawl** [comment]
thing to google is "skip authenticity token verification rails"

**Comment by nickoki** [comment]
We have this line in our controller `skip_before_action :verify_authenticity_token` but it doesn't seem to be working

**Comment by nolds9** [comment]
which controller @nickoki ?

**Comment by jshawl** [comment]
also what about http://stackoverflow.com/a/34431717/850825

I googled "skip_before_action :verify_authenticity_token not working"

**Comment by nickoki** [comment]
Tried @jshawl's line, but that didn't remove the error. @nolds9, it's at the top of our Posts Controller and Registrations Controller

Here's another look at the errors. Something might also be going on with `Unpermitted parameters: format`
![image](https://cloud.githubusercontent.com/assets/15880182/19930215/cb3a616e-a0dd-11e6-9f69-a5f1d35c99bf.png)

**Comment by nolds9** [comment]
can you share your `posts#create` controller action? Also, have you modified the `protect_from_forgery` line in the `application_controller`?

**Comment by nickoki** [comment]
Our `protect_from_forgery` in application controller was changed to `protect_from_forgery with: :null_session`

Here's `posts#create`:

``` ruby
def create
  @post = Post.new(post_params)
  @post.save
end
```

**Comment by jshawl** [comment]
and `post_params` method definition?

**Comment by nickoki** [comment]
`post_params`:

``` ruby
def post_params
  params.permit(:id, :title, :link, :level, :desc_what, :desc_why, :desc_who, :user_id, :pub_date, :created_at, :updated_at)
end
```

**Comment by jshawl** [comment]
can you add format and post to permit those?

**Comment by nickoki** [comment]
Error after permitting `format` and `post`.

![image](https://cloud.githubusercontent.com/assets/15880182/19930446/dea0817e-a0de-11e6-924c-613ea4fbec71.png)

**Comment by nolds9** [comment]
@nickoki looks like you have duplicative data coming in from params. Can you try changing your strong params definition to: 

``` ruby
params.require(:post).permit(:link, :title, etc...) 
```

**Comment by nickoki** [comment]
``` ruby
params.require(:post).permit(:id, :title, :link, :level, :desc_what, :desc_why, :desc_who, :user_id, :pub_date, :created_at, :updated_at)
```

![image](https://cloud.githubusercontent.com/assets/15880182/19930611/a04f47f6-a0df-11e6-9ea4-c414b81d8010.png)

**Comment by nolds9** [comment]
cool, can you try modifying the `protect_from_forgery` to the way this SO suggests

http://stackoverflow.com/questions/9362910/rails-warning-cant-verify-csrf-token-authenticity-for-json-devise-requests

**Comment by jshawl** [comment]
i feel like the rollback is something else - do you have a `!` after create?

**Comment by jshawl** [comment]
or save

**Comment by jshawl** [comment]
👍 fixed via token issue was not sending header correctly containing user auth token
