### ISSUE TITLE
trouble deploying the app to heroku

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project3#309]
I did install all the required gems, however still did not work
![image](https://cloud.githubusercontent.com/assets/18635698/19913892/e271d2ec-a07c-11e6-909b-fcf3848fd1ce.png)

**Comment by jshawl** [comment]
can you copy and paste the output - there might be more info above

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19929524/2d69be56-a0da-11e6-93aa-3d391aefa8fb.png)

**Comment by jshawl** [comment]
it looks like your rails app is using sqlite instead of postgres

**Comment by jshawl** [comment]
remove the gem 'sqlite' from your gemfile, and add pg.

Then you'll need to change the adapter and database names in `config/database.yml`

**Comment by marlungu** [comment]
i passed thru that, but i got another error
![image](https://cloud.githubusercontent.com/assets/18635698/19930245/e70367ec-a0dd-11e6-901e-5b4f6d285d07.png)

**Comment by jshawl** [comment]
can i see `config/database.yml`?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19930273/0f157572-a0de-11e6-91cd-db1e236ddeae.png)

**Comment by jshawl** [comment]
was there other stuff in there that you removed? speicifically a default: block?

**Comment by marlungu** [comment]
that was prior
![image](https://cloud.githubusercontent.com/assets/18635698/19930327/5ab656b8-a0de-11e6-8b1e-4b99bbf63a4b.png)

**Comment by jshawl** [comment]
ok perfect

keep all those.  change `adapter:sqlite3` to use postgresql

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19930537/4643aee6-a0df-11e6-9836-fe36dd529695.png)
 still not working

**Comment by jshawl** [comment]
> still not working

how do you know it's not working?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19930591/79c59702-a0df-11e6-9cb1-b7b4c30a8d9e.png)

**Comment by jshawl** [comment]
did you commit and push before migrating?

**Comment by amaseda** [comment]
You also need to change the value of the `database:` keys under development, test and production. [Here is a sample `database.yml` file that does it correctly](https://github.com/ga-wdi-exercises/grumblr_rails_api/blob/master/config/database.yml)

Do not copy and paste. Just change the value of `database:`. So each one should go from something like this...

``` rb
database: db/development.postgresql
```

...to this...

``` rb
database: databasename_development
```

Make sure to replace `databasename` with your actual app/database name.

**Comment by marlungu** [comment]
it worked. thank you
