### ISSUE TITLE
user authentication issue 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#31]
when a user tries to sign up or login in I see in the console the error
GET http://localhost:4000/login net::ERR_CONNECTION_REFUSED

and node has the error 
/Users/aleaq/wdi/projects/trans.hit/node_modules/passport/lib/middleware/authenticate.js:236
          if (err) { return next(err); }
                            ^

TypeError: next is not a function
    at /Users/aleaq/wdi/projects/trans.hit/node_modules/passport/lib/middleware/authenticate.js:236:29

I have express-session installed and required in my index.js 

in my controller i have the functions for get and post 

```
function getSignup(request, response) {
  // response.render("signup.hbs", { message: request.flash('signupMessage') });
}

// POST /signup
function postSignup(request, response) {
  var signupStrategy = passport.authenticate('local-signup', {
    successRedirect : '/',
    failureRedirect : '/',
    failureFlash : true
  });
  return signupStrategy(request, response);
}
```

in my passport.js i have the function to handle sessions 

```
//sessions
    module.exports = function(passport) {
      //add session to cache
   passport.serializeUser(function(user, callback) {
     callback(null, user.id);
   });
   //check session
   passport.deserializeUser(function(id, callback) {
     User.findById(id, function(err, user) {
         callback(err, user);
```

in my routes.js i have the routes set up  and authentication

```
function authenticatedUser(req, res, next) {
  // If the user is authenticated, then we continue the execution
  if (req.isAuthenticated()) return next();

router.route('/signup')
  .get(usersController.getSignup)
  .post(usersController.postSignup);

router.route('/login')
  .get(usersController.getLogin)
  .post(usersController.postLogin);

router.route("/logout")
  .get(usersController.getLogout);

router.route("/secret")
   .get(authenticatedUser, usersController.secret);

module.exports = router;
```

I don't understand what i'm supposed to turn this secret session into this was what was in the lesson plan 

```
app.use(session({ secret: 'WDI-GENERAL-ASSEMBLY-EXPRESS' }));
```

I also don't know if there is something additional to be installed I thought I got everything that was needed

```
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.14.1",
    "express": "^4.13.3",
    "express-session": "^1.12.1",
    "hbs": "^4.0.0",
    "method-override": "^2.3.5",
    "mongoose": "^4.2.9",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0"
```

**Comment by andrewsunglaekim** [comment]
mia had this same issue, she said restarting her computer fixed it? might be a long shot, but could you try that?

**Comment by ghost** [comment]
ok i'll try that

**Comment by ghost** [comment]
that didn't fix it

**Comment by ghost** [comment]
now the console says the below when i try to sign up 
http://localhost:4000/signup Failed to load resource: the server responded with a status of 404 (Not Found)

but node has the same next is not a function error
