### ISSUE TITLE
Angular will not load.

### ISSUE THREAD

**Issue by chrisjaff** [ga-wdi-exercises/project3#311]
I know that their is a syntax error somewhere in this code. Then I'm having trouble sending out requests from angular to my localhost: 3000. Can you take a look at my syntax and my http requests.

![](https://files.slack.com/files-pri/T2D6FU4JY-F2X7HFJUT/screen_shot_2016-11-01_at_7.46.06_pm.png)

![](https://files.slack.com/files-pri/T2D6FU4JY-F2X97EH45/screen_shot_2016-11-01_at_7.46.23_pm.png)

**Comment by jshawl** [comment]
do you get any errors in the console?

**Comment by nolds9** [comment]
Unable to see those images...

**Comment by chrisjaff** [comment]
My mistake. Here is my code and error messages.
<img width="664" alt="screen shot 2016-11-02 at 9 08 43 am" src="https://cloud.githubusercontent.com/assets/18494879/19929920/3b2d2b98-a0dc-11e6-8643-c7693c15f727.png">
<img width="666" alt="screen shot 2016-11-02 at 9 09 01 am" src="https://cloud.githubusercontent.com/assets/18494879/19929923/3ef1ed04-a0dc-11e6-9641-658908a92102.png">
<img width="1422" alt="screen shot 2016-11-02 at 9 09 19 am" src="https://cloud.githubusercontent.com/assets/18494879/19929926/41e580f2-a0dc-11e6-9e50-5d35e201087a.png">

**Comment by jshawl** [comment]
looks like your HTML is not linking to the js file correctly

**Comment by jshawl** [comment]
can we see index.html?

**Comment by chrisjaff** [comment]
<img width="1024" alt="screen shot 2016-11-02 at 9 12 25 am" src="https://cloud.githubusercontent.com/assets/18494879/19929987/82c3efe6-a0dc-11e6-9c9f-6db4452fd9f0.png">

**Comment by jshawl** [comment]
do you have a js folder? is there an app.js inside of it?

**Comment by chrisjaff** [comment]
Yes.
<img width="216" alt="screen shot 2016-11-02 at 9 13 36 am" src="https://cloud.githubusercontent.com/assets/18494879/19930016/b4f00b6c-a0dc-11e6-98ef-81e89fe275c1.png">

**Comment by chrisjaff** [comment]
I stored the angular module in my app.js

**Comment by jshawl** [comment]
app.js is not inside of the js folder. either move the js file to that folder or change your html so it links to "app.js"

**Comment by nolds9** [comment]
@chrisjaff any progress on this one?

**Comment by amaseda** [comment]
@chrisjaff Going to close this one since it's been quiet, but please feel free to re-open the issue if it persists / you have any questions about it.
