### ISSUE TITLE
ng-repeat

### ISSUE THREAD

**Issue by brown2206** [ga-wdi-exercises/project3#312]
Adrian, can you help us with our ng-repeat.  Here's a screenshot of a review that we're attempting to render in the browser.  For some odd reason, it keeps showing up with the curly brackets.

![image](https://cloud.githubusercontent.com/assets/20567326/19930117/5285fddc-a0dd-11e6-91c4-c6650fe89508.png)

Our current setup has reviews as a part of Doctors.  Please let me know if you need additional information.

**Comment by jshawl** [comment]
is this the same as https://github.com/ga-wdi-exercises/project3/issues/310 ?

**Comment by nolds9** [comment]
@brown2206 can you share your view code!

**Comment by brown2206** [comment]
[image: Inline image 1]

**Comment by brown2206** [comment]
Did the image show up on your end?

**Comment by jshawl** [comment]
no

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19930386/9b4afdf0-a0de-11e6-8334-2ad9fda3710b.png)

**Comment by amaseda** [comment]
`reviews` is an array. But you want to display a single review. You have already written some code in your view that allows you to access each single review.

**Comment by jshawl** [comment]
```html
<div data-ng-repeat="review in vm.reviews">
  {{review.name}}
</div>
```

**Comment by brown2206** [comment]
Jesse, we tried to play around with this and now, we don't have any reviews showing up

![image](https://cloud.githubusercontent.com/assets/20567326/19930769/48975390-a0e0-11e6-822a-0cbe2c7cad81.png)

**Comment by jshawl** [comment]
can we see the code

**Comment by brown2206** [comment]
![image](https://cloud.githubusercontent.com/assets/20567326/19930820/7d23eede-a0e0-11e6-898b-cab69d40ac36.png)

**Comment by nolds9** [comment]
`vm.doctor.reviews` no?

**Comment by brown2206** [comment]
We tried that...no result.

**Comment by jshawl** [comment]
``` html
<div data-ng-repeat="review in vm.reviews">
  here  - {{review.name}}
</div>

<div data-ng-repeat="review in vm.doctor.reviews">
  there  - {{review.name}}
</div>

{{vm.reviews}}
---
{{vm.doctor.reviews}}
```

what do you see in browser

**Comment by brown2206** [comment]
This is what we see in the browser once we've inserted the code.

![image](https://cloud.githubusercontent.com/assets/20567326/19930983/356177dc-a0e1-11e6-8cbd-af8276b8e6de.png)

**Comment by jshawl** [comment]
ok excellent!

**Comment by brown2206** [comment]
thank you...please close this issue.

**Comment by nolds9** [comment]
👍
