### ISSUE TITLE
Why do we not need require when posting information to our table?

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project3#313]
When we created our new factory
![image](https://cloud.githubusercontent.com/assets/15305847/19930881/c3ad1fe2-a0e0-11e6-9530-a91f96b77ecc.png)

and controller to send information from angular into our rails table, we were getting this error:
![image](https://cloud.githubusercontent.com/assets/15305847/19930908/e9108210-a0e0-11e6-9ec2-2a00e21da8df.png)

this is what our controller looked like with .require(:visit) which doesn't work
![image](https://cloud.githubusercontent.com/assets/15305847/19930856/a3b18868-a0e0-11e6-89c1-d634e7a4003d.png)

but when we remove .require(:visit) it works.
![image](https://cloud.githubusercontent.com/assets/15305847/19930935/05f70084-a0e1-11e6-924d-553f736dcee7.png)

Why?

**Comment by jshawl** [comment]
in your HTML, you didn't namespace your params.

You most likely have something like:

``` html
<input name='name'>

<!-- instead of -->

<input name='user[name]'>
```

**Comment by marks828** [comment]
So we would have to add a name attribute inside our button if we used .require?
![image](https://cloud.githubusercontent.com/assets/15305847/19931220/0fcdbe76-a0e2-11e6-99e7-ce7219b1cd6a.png)

**Comment by jshawl** [comment]
no - sendvisit - whenever a save is called, you would need to pass in a visit object

**Comment by amaseda** [comment]
Any progress on this one?

**Comment by marks828** [comment]
Oh sorry. We were just curious as to why. Everything is currently working but I'm sure there's a reason why we need to write with require. But I'm going to leave this open because we might run into a problem with our next step

**Comment by nolds9** [comment]
http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters

**Comment by marks828** [comment]
Now having a CORS issue
![image](https://cloud.githubusercontent.com/assets/15305847/19933646/7f357cc4-a0ea-11e6-81d4-a654060e90a9.png)

rack-cors gem is installed

**Comment by jshawl** [comment]
can you clikc on the network tab so see what the internal server error is?

**Comment by marks828** [comment]
![image](https://cloud.githubusercontent.com/assets/15305847/19935144/6698ddc8-a0ef-11e6-98cc-ffc089b61635.png)

**Comment by jshawl** [comment]
excellent! jsut need to see the server's respons

**Comment by marks828** [comment]
fixed it. postgres shut down on me again
