### ISSUE TITLE
Moving from Rails to Angular to render Views. 

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project3#314]
I am unable to render the google map api to a view in angular. I am unsure about what to put in my controller to render a template already made. 
<img width="1280" alt="screen shot 2016-11-02 at 9 50 08 am" src="https://cloud.githubusercontent.com/assets/20734065/19931131/ce51622c-a0e1-11e6-8bdd-b6e5df865765.png">
<img width="1280" alt="screen shot 2016-11-02 at 9 50 18 am" src="https://cloud.githubusercontent.com/assets/20734065/19931143/d0702890-a0e1-11e6-8a46-e970c22a184c.png">
<img width="1280" alt="screen shot 2016-11-02 at 9 49 59 am" src="https://cloud.githubusercontent.com/assets/20734065/19931144/d2407814-a0e1-11e6-9930-48f0814d89b6.png">

**Comment by jshawl** [comment]
missing `ui-view`?

**Comment by khoitle** [comment]
I've placed that into my body tag of my map.html

**Comment by khoitle** [comment]
Isnt it something with the controller?

**Comment by jshawl** [comment]
map.html is the template - should be something in index.html

**Comment by jshawl** [comment]
there are too many things going on here - can you narrow down the issue - does the template load at all? is the controller being invoked? is it a rails problem?

**Comment by khoitle** [comment]
Controller is being invoked, line 13 of map.html renders, but the problem is line 14. The Div id=map does not render

**Comment by jshawl** [comment]
any errors in the console?

**Comment by khoitle** [comment]
No errors. Just the console log from the controller stating "Rent Map Controller"

**Comment by jshawl** [comment]
ok - what code is initializing the map?

**Comment by khoitle** [comment]
The code works. We ran it a bunch using rails
<img width="1280" alt="screen shot 2016-11-02 at 9 57 34 am" src="https://cloud.githubusercontent.com/assets/20734065/19931408/cca4d23c-a0e2-11e6-851b-86b0b92dd89d.png">

**Comment by jshawl** [comment]
where are you calling the function `initMap()` ?

**Comment by nolds9** [comment]
where are you calling `initMap()`? I think you need to move that invocation to whichever controller is controlling the `map.html`

**Comment by khoitle** [comment]
line 8 of map.html. as a callback in the script tag

**Comment by khoitle** [comment]
<img width="496" alt="screen shot 2016-11-02 at 10 00 20 am" src="https://cloud.githubusercontent.com/assets/20734065/19931526/2f34fb02-a0e3-11e6-8ba9-8d4c56835a0e.png">

**Comment by jshawl** [comment]
can you put a console.log inside initmap?

**Comment by khoitle** [comment]
ah its not firing from the controller

**Comment by khoitle** [comment]
its not firing at all*

**Comment by nolds9** [comment]
What if you remove `&callback=initMap` from the cdn link, and then try manually calling `initMap()` in your controller

**Comment by khoitle** [comment]
how do i define initMap in the controller?

**Comment by nolds9** [comment]
first, I would just see if you can call it - no need to redefine it yet...

**Comment by khoitle** [comment]
when i invoke it in the controller i get 
<img width="415" alt="screen shot 2016-11-02 at 10 06 34 am" src="https://cloud.githubusercontent.com/assets/20734065/19931759/0f3ae16c-a0e4-11e6-829f-89002d9be3e8.png">

**Comment by nolds9** [comment]
ok, one quick fix might be to move all of your `initMap` code into the controller and then invoke it

**Comment by khoitle** [comment]
I've moved everything into the controller and then invoked it. But its still not firing 
<img width="270" alt="screen shot 2016-11-02 at 10 09 57 am" src="https://cloud.githubusercontent.com/assets/20734065/19931914/9345e6f0-a0e4-11e6-96ef-6e62ebda8d90.png">

**Comment by khoitle** [comment]
Is there anyway i could keep the code in map.js and then refer to it with  some sort of "this" statement?

**Comment by nolds9** [comment]
so you should be able to keep your code in `map.js` and as long as it is loaded before `app.js`, all of the top level the variables should be accessible in scope. Can you share you controller code after you moved the function def inside there?

**Comment by khoitle** [comment]
you want to see the controller code? Its 50 lines long after i moved the function into there

**Comment by khoitle** [comment]
also, i just placed line 11 in. 
<img width="1280" alt="screen shot 2016-11-02 at 10 15 45 am" src="https://cloud.githubusercontent.com/assets/20734065/19932154/5959c316-a0e5-11e6-82ca-eead3eb62cc5.png">

**Comment by nolds9** [comment]
yes, the `rentMapController` I believe. What do you mean you placed into `map.html`?

**Comment by nolds9** [comment]
might be easier to just commit and share your repo

**Comment by khoitle** [comment]
<img width="1280" alt="screen shot 2016-11-02 at 10 17 10 am" src="https://cloud.githubusercontent.com/assets/20734065/19932203/92f8cb76-a0e5-11e6-8091-22ea77274f74.png">
<img width="1280" alt="screen shot 2016-11-02 at 10 17 55 am" src="https://cloud.githubusercontent.com/assets/20734065/19932218/a3551d6c-a0e5-11e6-8fbf-b89d581fd302.png">
<img width="1280" alt="screen shot 2016-11-02 at 10 18 12 am" src="https://cloud.githubusercontent.com/assets/20734065/19932232/af77110e-a0e5-11e6-8a8d-26c9e16c2a1f.png">
<img width="1280" alt="screen shot 2016-11-02 at 10 18 37 am" src="https://cloud.githubusercontent.com/assets/20734065/19932240/bc2f17de-a0e5-11e6-85bb-e55b9b217c57.png">

**Comment by khoitle** [comment]
as for the second question, my map.html only had a script tag that refered to map.js(Which has all the javascript for the map) while i just added app.js( the controller code).

**Comment by nolds9** [comment]
@KhoiLe89 to be honest theres a lot of code here, so im starting to lose track how everything is organized, without seeing all the code, do you want to push your code to github or use a token?

**Comment by khoitle** [comment]
Me and Andy are going to try and figure it out. One sec! thank youu for your help

**Comment by nolds9** [comment]
Basically, how I would think to organize it is to have:
- a main `index.html` that loads in all of your cdns and `map.js` before `app.js`
- A template called `map.html` which just has a blank div for the map container
- Some controller code to initialize the map, whenever that state is hit

**Comment by khoitle** [comment]
problem solved! Thanks Jesse and Nick :)
