### ISSUE TITLE
Instead of creating a new row, we need to update the count

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project3#315]
MVP is almost done! We're having issues trying to find a record we already have saved and instead of creating a new row with the same restaurant, we want to update the counter for that row. Our unique identifier is the `yelp_id`
![image](https://cloud.githubusercontent.com/assets/20713810/19933531/0ac810ae-a0ea-11e6-81f2-8ded8cbedf2c.png)

our angular code is instantiating a new ajax call
![image](https://cloud.githubusercontent.com/assets/20713810/19933556/2928339e-a0ea-11e6-8f69-ecd8c1c634cc.png)

And our visits controller in ruby is finding that unique identifier `yelp_id` and trying to update the count
![image](https://cloud.githubusercontent.com/assets/20713810/19933809/06ae6666-a0eb-11e6-9c7e-94141a50fc0f.png)

**Comment by nolds9** [comment]
@MichaelZLai Are you getting any errors?

**Comment by nolds9** [comment]
is the problem that you need one route to do either an update or create? Can you just make the request map to your `visits#update` action?

**Comment by MichaelZLai** [comment]
yeah, im getting this post error with my updated rails code
![image](https://cloud.githubusercontent.com/assets/20713810/19934340/b27c8f3a-a0ec-11e6-90e5-4fcf47ae8251.png)
![image](https://cloud.githubusercontent.com/assets/20713810/19934377/cc4028fa-a0ec-11e6-8f84-e7e874fd6efe.png)

We don't have a `visits#update` action at all, since we're just creating a record if a user selects yes. We want to make sure when the create action is called in ruby, that instead of creating a new row (if a yelp_id is present), we want to just increment our counter by 1

**Comment by nolds9** [comment]
cool, sounds like you want to find by `yelp_id` not just `.find` which only takes a normal `id`

Also, I think you need to render the updated `@visit` as json after you save it

**Comment by MichaelZLai** [comment]
ah, that's right. We've changed the`.find`to a `.where`, however it's just bypassing the if statement and going straight to the `create!`
![image](https://cloud.githubusercontent.com/assets/20713810/19934840/788aa760-a0ee-11e6-8116-bebd44235edc.png)

![image](https://cloud.githubusercontent.com/assets/20713810/19934853/80c3ee32-a0ee-11e6-8406-3f969b3ae834.png)

**Comment by nolds9** [comment]
I think you want `find_by` over `where`.  Also this sounds like a good use case for http://apidock.com/rails/v4.0.2/ActiveRecord/Relation/find_or_create_by

**Comment by nolds9** [comment]
@MichaelZLai any progress with this one?

**Comment by MichaelZLai** [comment]
some progress, now using the `find or create by` use-case, which now bypasses creating a new row if the record exist. However now having trouble incrementing the actual count

![image](https://cloud.githubusercontent.com/assets/20713810/19935947/4b44a07c-a0f2-11e6-8211-3bc4f11e3c2b.png)

server error
![image](https://cloud.githubusercontent.com/assets/20713810/19935976/5b01222e-a0f2-11e6-84de-4b3d3f2432a2.png)

**Comment by jshawl** [comment]
did you define a method called increment on your visit model?

**Comment by nolds9** [comment]
I think you want to increment the count of `@visit` before you save it, but after your find or create it

**Comment by MichaelZLai** [comment]
Nick.... You're a genius. Thank you
