### ISSUE TITLE
Question about states

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project3#317]
I have a question about using states.  Right now our reviews are saving to the page but after we refresh the page, but we want the review to automatically post the show page without refreshing.  
When I use $state I get an error, but when I comment it out the error goes away. Right now $state is defined in the DoctorShowController and we use 'state.go' in the DoctorShowControllerFunction'
![screen shot 2016-11-02 at 11 33 55 am](https://cloud.githubusercontent.com/assets/20979785/19935565/def7b7d4-a0f0-11e6-954c-df4f198b5b6e.png)
![screen shot 2016-11-02 at 11 33 42 am](https://cloud.githubusercontent.com/assets/20979785/19935567/e2aba0e8-a0f0-11e6-91ef-971a9b4126bb.png)

**Comment by nolds9** [comment]
What was the error you got?

Looks like you are on the right track! If you want to redirect a user to a different state, you need to use `$state.go()` and pass it the name of the state you want to go to, plus any values to parameters that the state needs, i.e. an id

Make sure to inject `$state` in your controller, and remember to pass that as an argument to your controller function

**Comment by griffind2009** [comment]
Thanks, I think it's closer. No errors now, but the user input isn't clearing from the input box and text area and I still have to refresh the page in order for the input to post.

**Comment by griffind2009** [comment]
![screen shot 2016-11-02 at 11 50 21 am](https://cloud.githubusercontent.com/assets/20979785/19936042/9a927a6e-a0f2-11e6-8f4e-84ad385d02c9.png)

**Comment by jshawl** [comment]
I think you have to reset the values after the save, e.g. `this.review = new ReviewFactory()`

**Comment by griffind2009** [comment]
before or instead of state.go? I tried it before stat.go and kept that line, but the page still needs to be refreshed.

**Comment by griffind2009** [comment]
can we use a token?

**Comment by nolds9** [comment]
Happy to help out in one min
