### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/project3#318]
In our repository, we have two folders, one being our Yelp Rails aPI and the other being our angular front end. We're getting this no default language detected. Would we have to deploy each individual file separately?

![image](https://cloud.githubusercontent.com/assets/20713810/19941798/e77c8f08-a107-11e6-8ce4-febfc429095a.png)

![image](https://cloud.githubusercontent.com/assets/20713810/19941819/f3cfe2c8-a107-11e6-8e29-c864f9a5a78c.png)

**Comment by amaseda** [comment]
Just talked with y'all about this during office hours. Closing for now but please re-open if you have any more questions!
