### ISSUE TITLE
Creating Users with Data from an External API

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/project3#319]
Hi team!

I am struggling with getting new users created.  Adrian and I discussed this for a minute, and I am able to get the data I need into a function for user creation.  But asynchronicity was keeping the data from loading properly for a while.  Beat that by calling usercreate() in the onSuccess function. Now when I try to use UserFactory, I'm getting that it is not a constructor, even though it is connected to angular through a controller.  Please see below.

![image](https://cloud.githubusercontent.com/assets/20960160/19942595/aa08e98e-a10a-11e6-9642-a889d0dba5d4.png)

![image](https://cloud.githubusercontent.com/assets/20960160/19942611/b6076058-a10a-11e6-87de-8e5effef8b0e.png)

Error:

![image](https://cloud.githubusercontent.com/assets/20960160/19942628/c2fef866-a10a-11e6-8415-c8421c8aae73.png)

**Comment by nolds9** [comment]
remove the `data` argument to your `userCreate` function

**Comment by lizafloyd** [comment]
But I need the data

**Comment by nolds9** [comment]
where is the data?

if its a global var, you do not need to pass it into the controller

**Comment by lizafloyd** [comment]
It is not, just because I'm trying not to use global variables.  Can change that if recommended.

![image](https://cloud.githubusercontent.com/assets/20960160/19942951/c476e75c-a10b-11e6-957f-fa7889aaaa08.png)

**Comment by nolds9** [comment]
So you are running into an issue with Angular's dependency injection. You would need to pass in your factory where you are calling `userCreate`, but I do not believe that will work

**Comment by nolds9** [comment]
The other option might be to move all of your api calls into the controller

**Comment by lizafloyd** [comment]
Sorry, what?? I don't understand either thing you just said.

I thought I did feed my factory in:

![image](https://cloud.githubusercontent.com/assets/20960160/19943115/7b247ed8-a10c-11e6-83b3-c3ec62d76b96.png)

And the api option: do you mean put all crud functionality in **one** controller??

Thanks!

**Comment by nolds9** [comment]
Sorry did not mean to confuse, I would start by injecting the UserFactory into your controller

**Comment by lizafloyd** [comment]
I thought I did.

![image](https://cloud.githubusercontent.com/assets/20960160/19943504/16149dfa-a10e-11e6-9f84-49c64fa9208a.png)

**Comment by amaseda** [comment]
You also need to pass in EventFactory as an argument to your controller function. Make sure the arguments passed into your controller function are written in the same order as the dependencies that are injected into `.controller`

**Comment by lizafloyd** [comment]
https://github.com/a-espinoza/ng_tatiana

https://github.com/LWatsonlm/tatiana

The repos requested by Adrian!

**Comment by amaseda** [comment]
Taking a look now!

**Comment by amaseda** [comment]
@lizafloyd should I be looking at a particular branch?

**Comment by lizafloyd** [comment]
Junior!

**Comment by jshawl** [comment]
what url are you visiting - what error message do you get

**Comment by lizafloyd** [comment]
The url is the factory url, it's correct, I double checked it .
![image](https://cloud.githubusercontent.com/assets/20960160/19944670/30670b34-a113-11e6-8bda-77d37bde7a8d.png)

The error message is that userfactory is not a constructor.
![image](https://cloud.githubusercontent.com/assets/20960160/19944693/45fa2e86-a113-11e6-93c9-89a8f1c3f29c.png)

**Comment by jshawl** [comment]
@lizafloyd any updates? the async!

**Comment by amaseda** [comment]
Going to close this one since it's been a bit but feel free to re-open if you have any other questions.
