### ISSUE TITLE
Connecting to Mongo

### ISSUE THREAD

**Issue by MarkhamShofner** [ga-wdi-exercises/project3#32]
We're in a bit of a spot with our persistence of data using mongo. 

Our code of 

```
for (var i =0; i < locations.length; i++){
  // console.log(locations[i]);
  locations[i].save(function(err){
    if (err){
      console.log(err);
    } else {
      console.log("location was saved");// + locations[i]);
    }
  // console.log(locations[i]);
  });
}
```

console.logs that the "location was saved", but the locations do not end up in the database that the page is connected to.

Additionally, when we attempt to retrieve locations[i] after the location is saved, the element of the array is undefined, where it was not previously. Any help would be much appreciated!

**Comment by andrewsunglaekim** [comment]
have you connected to mongo and verified the documents in the database using the mongo REPL?

**Comment by MarkhamShofner** [comment]
that is what we are currently attempting. the mongo REPL isn't recognizing any changes, even tho the code is registering as "saved".
