### ISSUE TITLE
Error while trying to update

### ISSUE THREAD

**Issue by griffind2009** [ga-wdi-exercises/project3#320]
I'm trying to update the reviews associated with a doctor. I have the edit linked to the review on the show page.  When I click edit it takes me to the edit page for reviews. 
1. When I click update I get an error that says the property id cannot be defined.
2. It is not clear if we are updating the correct review (the review we are editing does not show up on the edit page)

![screen shot 2016-11-02 at 3 31 28 pm](https://cloud.githubusercontent.com/assets/20979785/19944264/790382fc-a111-11e6-93ea-595d005e5ff4.png)

![screen shot 2016-11-02 at 3 39 39 pm](https://cloud.githubusercontent.com/assets/20979785/19944517/a5b16872-a112-11e6-9d5c-62ab80e892c9.png)

![screen shot 2016-11-02 at 3 42 22 pm](https://cloud.githubusercontent.com/assets/20979785/19944605/fc21e736-a112-11e6-9668-d08f653d0a91.png)

![screen shot 2016-11-02 at 3 39 49 pm](https://cloud.githubusercontent.com/assets/20979785/19944520/aa5fc396-a112-11e6-84ee-573e568b8fda.png)

**Comment by jshawl** [comment]
instead of `this.doctor.id` can you try `review.doctor.id`?

**Comment by griffind2009** [comment]
do you think i should change it for all of the state.go

**Comment by nolds9** [comment]
To start, how do you know which review you are editing?

**Comment by pohckuan** [comment]
we have the review id in our show page

**Comment by jshawl** [comment]
any updates? what is the output of `console.log(review)`?

**Comment by brown2206** [comment]
the output is undefined.

**Comment by amaseda** [comment]
Where is `review` coming from? I see it's an argument to the `update` function, but I don't see it being passed in anywhere.

**Comment by griffind2009** [comment]
We passed it the destroy function and we set this.review = ReviewFactory () in the DoctorShowControllerFunction. Delete works and that's defined in DoctorShowControllerFunction. Could it be a scope issue with the ReviewEditController Function?

**Comment by amaseda** [comment]
Where is the value for review coming from when you reference it here?...

``` js
ReviewFactory.update({id: review.id})
```

It looks like `review` is an argument of your `this.update` method but I don't see it being passed in anywhere.

**Comment by griffind2009** [comment]
I think it's coming from   this.review = ReviewFactory.get({doctor_id: review.doctor.id).  I tried passing it in as an argument in the promise, but got the same error.

![screen shot 2016-11-02 at 7 22 52 pm](https://cloud.githubusercontent.com/assets/20979785/19951021/c9104fa8-a131-11e6-989a-979fa84f1667.png)

**Comment by jshawl** [comment]
can you screenshot the error message

**Comment by griffind2009** [comment]
![screen shot 2016-11-03 at 9 37 44 am](https://cloud.githubusercontent.com/assets/20979785/19968040/34a88d1c-a1a9-11e6-8c0c-c21ca3ff5c1e.png)

**Comment by griffind2009** [comment]
We also have an issue with our url not being reflected.
![screen shot 2016-11-03 at 9 38 29 am](https://cloud.githubusercontent.com/assets/20979785/19968089/64d9a9f8-a1a9-11e6-8e5b-a291e17bedd8.png)

**Comment by amaseda** [comment]
Put `console.log(review)` after your `console.log("click")`. What do you see in your console?
