### ISSUE TITLE
pulling info 

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project3#321]
![image](https://cloud.githubusercontent.com/assets/21348450/19944655/273e25e2-a113-11e6-8d6c-637eb2b3fb78.png)

we got all the information to show when we comment in {{vm.category.disasters}} but in trying to display the title of the disaster as a link to its own page it all dissappears. have even tried something as simple as {{vm.category.disasters.title}} to just try to get it to show but nothing comes up

**Comment by amaseda** [comment]
If you want to display information about individual disasters, you'll need to use another `ng-repeat`, but this time it iterates through `category.disasters`. From there you can say `disaster.title`.

**Comment by brophy2321** [comment]
so i rewrote it as so

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19944932/3a6d202c-a114-11e6-835d-2274e57f33dd.png)

**Comment by brophy2321** [comment]
it now shows the pictures but not a title. should i have kept it {{vm.category.disasters.title}}

**Comment by brophy2321** [comment]
nevermind, tried that with no success

**Comment by amaseda** [comment]
You're on the right track with `disasters in vm.category.disasters` (although I would say `disaster` in place of `disasters` since the left side represents each individual disaster).

From within the ng-repeat, you can now say something like `disaster.title`. You don't want to say `vm.disaster`, because that does not exist.

**Comment by brophy2321** [comment]
it worked when i changed the v.disaster.title to disaster.title.
when i changed disasters in vm.category.disasters, everything actually dissapeared

**Comment by amaseda** [comment]
you don't need to change it in `vm.category.disasters`, just the left side of the ng-repeat
