### ISSUE TITLE
(ngResource) factory query promise not resolving before view is loaded

### ISSUE THREAD

**Issue by AndyWhitley** [ga-wdi-exercises/project3#322]
<img width="846" alt="screen shot 2016-11-02 at 4 25 38 pm" src="https://cloud.githubusercontent.com/assets/21045394/19946088/52138f86-a119-11e6-8d46-ffc8d7260e96.png">

How do I force the promise to resolve before the controller function loads up the view?

**Comment by jshawl** [comment]
mm i don't think you want to do that - what problem are you trying to solve?

**Comment by AndyWhitley** [comment]
nvm, data was hiding behind a fixed element
