### ISSUE TITLE
disaster show model not displaying info

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project3#323]
![image](https://cloud.githubusercontent.com/assets/21348450/19946180/ab4a6e44-a119-11e6-9986-c452f18b415c.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19946188/ba3e385e-a119-11e6-9d5a-a2a3b720da51.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19946193/c0183d88-a119-11e6-93ba-08bdc60d7d1f.png)

**Comment by brophy2321** [comment]
got the individual disaster page to show. went into the disasters_controller.rb and made sure it was set for json

**Comment by brophy2321** [comment]
the error
![image](https://cloud.githubusercontent.com/assets/21348450/19946543/cba321ee-a11a-11e6-9662-1b942976cda8.png)
we have DisasterFactory defined though

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19946562/e5498caa-a11a-11e6-96fa-9f2a40b1c728.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19946582/f195a7e6-a11a-11e6-9892-5ff1b5e78873.png)

**Comment by jshawl** [comment]
cannot read property get of undefined... can i see where you create disastershowcontrollerunfction? specifically `angular.controller...`

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19946815/d286bccc-a11b-11e6-8c17-1f00a0d2ce33.png)

**Comment by jshawl** [comment]
can you add in $stateParams before DisasterFactory as well

**Comment by brophy2321** [comment]
Added that

**Comment by brophy2321** [comment]
got the title to show, Knew i was missing one thing. thanks
