### ISSUE TITLE
Figaro missing api keys

### ISSUE THREAD

**Issue by marks828** [ga-wdi-exercises/project3#324]
Heroku is giving an error saying we are missing an API key when we try to push heroku master

![image](https://cloud.githubusercontent.com/assets/15305847/19946471/a1df11e2-a11a-11e6-891a-af67c82bdd8b.png)

figaro keys:
![image](https://cloud.githubusercontent.com/assets/15305847/19946494/b2ddb480-a11a-11e6-9f47-4fb0ebf979ac.png)

![image](https://cloud.githubusercontent.com/assets/15305847/19946511/babad598-a11a-11e6-8c76-72f7b9f80c67.png)

**Comment by MichaelZLai** [comment]
So we've created two repositories (one for our angular front end, one for our rails backend). For our angular front end, we have it set up in github pages. The backend is where we're struggling. We're trying to deploy to heroku, however running into issues when we `git push heroku master`. 

We were given an error saying our yelp api keys aren't being found. We installed the gem figaro and configured it correctly (i think). We also realized we weren't on our master branch (we were in production). so we did `git push heroku production`, no errors... but still didnt work.

**Comment by jshawl** [comment]
if you visit herokuapp.com did you set the ENV variables there?

**Comment by marks828** [comment]
yup
![image](https://cloud.githubusercontent.com/assets/15305847/19946781/b5c0a878-a11b-11e6-988a-275229bd097b.png)

**Comment by amaseda** [comment]
Does it act any differently if you try to set those env variables from the command line like so...

`$ heroku config:set SECRET_TOKEN=12345`

> Replace SECRET_TOKEN=12345 with your key, secret, token, etc.

**Comment by marks828** [comment]
That's how we set the environment variables to start and it set it to our variables on the app page

**Comment by amaseda** [comment]
Based on what I saw before I left, it seems like you guys had solved the API key issue and moved on to a new Heroku one. Going to close this issue but feel free to re-open if the API problem persists.
