### ISSUE TITLE
What is the recommended Angular dependency for "Time Ago"?

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/project3#325]
I want to be able to easily display time as "14 hours ago" or "2 months ago".

**Comment by jshawl** [comment]
moment js is my favorite - http://momentjs.com/docs/#/displaying/fromnow/

**Comment by jshawl** [comment]
feel free to open another!

**Comment by nickoki** [comment]
Oh, Jesse this is working perfectly (thank you btw) -- we were coming to ask about this one https://github.com/ga-wdi-exercises/project3/issues/326
