### ISSUE TITLE
Backend URL Local vs Hosted

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project3#326]
We finally got our back-end hosted (Yea!) now we have a question on the best method to switch our front end $resource string with the address.  If we want to switch between local or remote what is a good way to do this? Should we put the address in an environment variable and use ENV to read it like we did for the keys? or maybe a environment variable that is a switch to switch between two hard coded URL's?

Thanks

Mike

```
//initial ajax call to our api for yelp data
  function FoodFactory($resource){
      return $resource("https://yelp-backend-rails.herokuapp.com/foods/:id", {}, {
        update: {method: "PUT"}
      })
    }
  //send yes information to visits table in our api
  function VisitFactory($resource){
      return $resource("https://yelp-backend-rails.herokuapp.com/visits/:id", {}, {
        update: {method: "PUT"}
      })
    }
```

**Comment by nickoki** [comment]
We're having the same issue. Our deployed Heroku App gives the following error in the Chrome console upon attempting to log in

> `POST https://recourse.herokuapp.com/auth_user 500 (Internal Server Error)`

If you want to try it, visit https://recourse.herokuapp.com/#/ and try to log in with email `tim@tim.tim` password `timtim`

**Comment by jshawl** [comment]
Instead of an environment variable, you can check whether the URL contains localhost with window.location (JavaScript)

**Comment by merubin** [comment]
The local front end URL has no relation to whether I am testing against a hosted backend or local backend we need to switch dynamically based on needs not where the front end is currently running
We need away to switch which backend URL we are talking to and where the front end is running .

**Comment by jshawl** [comment]
Oh I see - here's my recommended workflow:

**If you're testing production api for the first time**:

manually hardcode the production api url in your javascript file to make sure deployment was successful.

Once CRUD is working, future updates to the API should be nearly identical to development API.

**If production api is working already**:

And you're still developing features, use the development api when working with development front end, and production api if front end is in production

you can use `window.location` to see if the url contains localhost, if so, use development api. if not, use production api.

**Comment by jshawl** [comment]
> based on needs

what needs? happy to provide more thoughts - just not sure what needs to be tested

**Comment by jshawl** [comment]
@nickoki what do you think about https://github.com/ga-wdi-exercises/project3/issues/326#issuecomment-258119252

**Comment by nickoki** [comment]
@jshawl we hard coded the hosted API url, but we're still met with the same 500 error when trying to log in (and get our jwt). Could it possibly be a http vs https thing?

**Comment by nickoki** [comment]
The thing that's making this hard to diagnose is that this is the only error we've received: `POST https://recourse.herokuapp.com/auth_user 500 (Internal Server Error)`

Theres also nothing in the Heroku logs

**Comment by nolds9** [comment]
is there any more information in the network tab, if you drill into that error message?

**Comment by nickoki** [comment]
Here's our network tab for the `auth_user` request
![image](https://cloud.githubusercontent.com/assets/15880182/19968406/d68e8414-a1aa-11e6-908d-bebe754a4794.png)

**Comment by jshawl** [comment]
can you click on response tab there

**Comment by jshawl** [comment]
or preview

**Comment by jshawl** [comment]
also did you add 12 factor gem? what do the logs look like?

**Comment by nickoki** [comment]
![image](https://cloud.githubusercontent.com/assets/15880182/19968440/ff22e7d0-a1aa-11e6-8a28-1f9de392ec23.png)

**Comment by nickoki** [comment]
Here's the successful `auth_user` request on our localhost server
![image](https://cloud.githubusercontent.com/assets/15880182/19968456/1512842e-a1ab-11e6-85dd-cadf7c0840d6.png)

**Comment by jshawl** [comment]
what is the output of `heroku logs`

**Comment by nickoki** [comment]
`heroku logs` output:

```
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "tim@tim.tim"], ["LIMIT", 1]]
2016-11-03T13:53:48.349903+00:00 app[web.1]: W, [2016-11-03T13:53:48.349837 #3]  WARN -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292] Can't verify CSRF token authenticity.
2016-11-03T13:53:48.530366+00:00 app[web.1]: I, [2016-11-03T13:53:48.530257 #3]  INFO -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292] Completed 500 Internal Server Error in 181ms (ActiveRecord: 0.7ms)
2016-11-03T13:53:48.531767+00:00 app[web.1]: F, [2016-11-03T13:53:48.531700 #3] FATAL -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292]   
2016-11-03T13:53:48.532512+00:00 app[web.1]: F, [2016-11-03T13:53:48.531773 #3] FATAL -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292] NameError (uninitialized constant AuthenticationsController::Auth):
2016-11-03T13:53:48.532584+00:00 app[web.1]: F, [2016-11-03T13:53:48.532517 #3] FATAL -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292]   
2016-11-03T13:53:48.532636+00:00 app[web.1]: F, [2016-11-03T13:53:48.532588 #3] FATAL -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292] app/controllers/authentications_controller.rb:27:in `payload'
2016-11-03T13:53:48.532695+00:00 app[web.1]: F, [2016-11-03T13:53:48.532641 #3] FATAL -- : [eee5f56e-46d9-497d-aec2-3f3fe6d5f292] app/controllers/authentications_controller.rb:13:in `authenticate_user'
2016-11-03T13:53:48.529800+00:00 heroku[router]: at=info method=POST path="/auth_user" host=recourse.herokuapp.com request_id=eee5f56e-46d9-497d-aec2-3f3fe6d5f292 fwd="50.200.196.50" dyno=web.1 connect=1ms service=191ms status=500 bytes=1669
```

**Comment by jshawl** [comment]
NameError (uninitialized constant AuthenticationsController::Auth):

**Comment by jshawl** [comment]
also if you want to cheat, you can set the prod app env to devel - `heroku config:set RAILS_ENV=development`

**Comment by nickoki** [comment]
Okay that would mean Heroku doesn't know about our `lib/auth.rb`

https://github.com/nickoki/recourse/blob/master/lib/auth.rb

**Comment by jshawl** [comment]
oooo what's in there? anything good?

**Comment by bcope** [comment]
```
# Ruby file to help encode and decode JSON Web Tokens

# Use jwt gem
require 'jwt'

# Custom Authorization class
class Auth

  # Use HS256 as hashing alg, set as class constant to use in .issue and .decode
  ALGORITHM = 'HS256'

  # Method to issue tokens
  def self.issue(payload)
    # Use encode method (from jwt gem) to generate a token
    JWT.encode(payload, ENV["super_secret_info"], ALGORITHM)
  end

  # Method to decode tokens
  def self.decode(token)
    # Use decode method (from jwt gem) to interpret a token
    JWT.decode(token, ENV["super_secret_info"], true, { algorithm: ALGORITHM }).first
  end
end
```

**Comment by nickoki** [comment]
That's our class for issuing and decoding jwts. The way Rails knows about it is this line in `config/application.rb`

```
config.autoload_paths << Rails.root.join('lib')
```

Could that line possibly be breaking on Heroku?

**Comment by bcope** [comment]
It's where the jwt auth tokens are issued and decoded

**Comment by jshawl** [comment]
is this related? http://stackoverflow.com/questions/4074830/adding-lib-to-config-autoload-paths-in-rails-3-does-not-autoload-my-module

**Comment by nickoki** [comment]
Could the issue be that we've defined it as

``` ruby
class Auth
```

and not

``` ruby
module Auth
```

**Comment by jshawl** [comment]
no I think it's the requiring business

**Comment by jshawl** [comment]
I'm also happy to take your token now if you like!

**Comment by jshawl** [comment]
but in the meantime, `require_relative 'path_to_your_auth.rb'` should solve the issue!

**Comment by nickoki** [comment]
We'll give that a shot!

**Comment by nolds9** [comment]
@merubin you guys make any progress on your end?

**Comment by merubin** [comment]
We were done with this I will close.  We no longer have any issues.
