### ISSUE TITLE
routing issue

### ISSUE THREAD

**Issue by marlungu** [ga-wdi-exercises/project3#327]
I'm trying to change from localhost:8080 to heroku.com, but I'm unable to do that because it is not showing in the heroku.com (something like heroku.com/index/ 3
![image](https://cloud.githubusercontent.com/assets/18635698/19967380/5789a38c-a1a6-11e6-87d1-dbdd79c391b1.png)

**Comment by jshawl** [comment]
what do you see if you visit `https://globalcitizen.herokuapp.com/passports/1`

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19967553/339fb208-a1a7-11e6-8fe7-35bd0d1924b3.png)

**Comment by jshawl** [comment]
ok this looks great!

can you add that url as your resource in angular? instead of localhost?

**Comment by jshawl** [comment]
Any updates @marlungu

**Comment by jshawl** [comment]
@marlungu post here! I will help you!

**Comment by jshawl** [comment]
@marlungu !!

**Comment by marlungu** [comment]
the comment model in not working, when im trying to see it thru rails c, it throw an error
![image](https://cloud.githubusercontent.com/assets/18635698/19974213/108adc9a-a1be-11e6-8386-c97a7cffce8e.png)

**Comment by jshawl** [comment]
can you add `rb-readline` gem to gemfile, and bundle install?

then try

**Comment by marlungu** [comment]
getting this error
![image](https://cloud.githubusercontent.com/assets/18635698/19974544/32c3156a-a1bf-11e6-98c5-921717545acc.png)

**Comment by jshawl** [comment]
ok this is promising! 

can i see seeds.rb?

something on line 6 is nil

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19974868/56e97bae-a1c0-11e6-9f06-40f85ef2723a.png)

**Comment by jshawl** [comment]
can you try `p doc` after line 3? what is the output of that

**Comment by marlungu** [comment]
p doc ?

**Comment by jshawl** [comment]
in between lines 3 and 4 type:

``` rb
p doc # equivalent to puts doc.inspect
```

then run rails db:seed again

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19975134/3776ca8c-a1c1-11e6-90a4-c73b0d95199a.png)

**Comment by jshawl** [comment]
ok this looks good

did it seed successfully now then?

**Comment by marlungu** [comment]
![image](https://cloud.githubusercontent.com/assets/18635698/19975182/62411de4-a1c1-11e6-9267-fcac819244a1.png)
