### ISSUE TITLE
loaded files manually to server

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#328]
Good morning,

I just loaded up the our angular app onto a server and for some reason the `#/` is still needed to access the home page. 

http://quali-fi.jackfive.io vs. http://quali-fi.jackfive.io/#/

Any pro tips on how to deploy? Thanks!

**Comment by jshawl** [comment]
yes! in index.html, check the url to see if it has a `/`. If it doesn't redirect to `#/`

**Comment by ghost** [comment]
Okay. We don't have a `/` in our root index.html file at all because we are using `data-ui-sref`. Is it something I have to change in the app.js file?

**Comment by jshawl** [comment]
you do though! what is the output of

``` js
console.log(window.location.hash)
```

?

**Comment by ghost** [comment]
undefined

**Comment by jshawl** [comment]
exceeeeellllleeeent and when you visiti `/#/` ? what is the value then?

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/8737117/19968627/bdf03fdc-a1ab-11e6-9e34-5dbcdedd950d.png)

I get a #/

**Comment by jshawl** [comment]
aw hell yeah so your logic can be:

```
if window location hash is undefined
  then redirect to '/#'
otherwise
  dont do anything
```

**Comment by ghost** [comment]
Okay cool. I added this to my app.js file, `window.location.href = "http://quali-fi.jackfive.io/#/"`. So do all angular apps out there in the wild have that `#/` in the URL? Thanks again!

**Comment by nolds9** [comment]
Not all, but a lot do. If you want to remove the hash, you can use Angular's built in `$locationProvider` module, https://github.com/ga-wdi-lessons/angular-routing/blob/master/lab.md#locationprovider

But just fyi, there are some known bugs

**Comment by ghost** [comment]
Okay thanks @nolds9!

**Comment by jshawl** [comment]
not if they use html5mode - but hash in the url is very very common
