### ISSUE TITLE
Comments not saving or updating

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project3#330]
![image](https://cloud.githubusercontent.com/assets/21348450/19968038/335e80d8-a1a9-11e6-80b7-8cf5b1fb1e56.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19968062/499a4c88-a1a9-11e6-945e-ec929da9065e.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19968071/529bcb40-a1a9-11e6-889c-aa6ff9e9fe58.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19968086/5f6b2500-a1a9-11e6-860b-c566579d6095.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19968094/6d3e7fb0-a1a9-11e6-9541-488b188e1ddc.png)

**Comment by brophy2321** [comment]
got the comment box to show and when i type it adds directly to page 
![image](https://cloud.githubusercontent.com/assets/21348450/19968108/8447c626-a1a9-11e6-9067-f81f58bcb929.png)

**Comment by brophy2321** [comment]
got the comment box to show and when i type it adds directly to page but cant get it to actually update and save to the page of the specific disaster

**Comment by amaseda** [comment]
Are you getting any errors when you try to save/update?

Is your rails server acknowledging that it received a POST or PUT request (look in the tab that is running the rails server)?

**Comment by brophy2321** [comment]
all get requests

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19968358/9e31adbc-a1aa-11e6-8f6f-804f0a5d8eb6.png)

**Comment by brophy2321** [comment]
i believe it has to do with this, we nested the comments folder into the ng-views/disasters folder

**Comment by amaseda** [comment]
What do you mean by "all get requests"? Does that mean your Rails server is not acknowledging any incoming POST or PUT requests?

**Comment by brophy2321** [comment]
Wasnt sure if we had to do that since we want them to correspond with each individual disaster

**Comment by brophy2321** [comment]
It s definetely not acknowledgin any POSt or PUT

**Comment by amaseda** [comment]
Also, the URL in your CommentFactory doesn't include anything about comments. You need to makes sure you're using a path that includes `/comments/` somewhere. Use your `rails routes` to see what the correct one is.

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19968609/abde8272-a1ab-11e6-9aca-0fcd751d01e9.png)

**Comment by brophy2321** [comment]
![image](https://cloud.githubusercontent.com/assets/21348450/19968620/b859e19a-a1ab-11e6-8d2b-89477896ff46.png)

**Comment by brophy2321** [comment]
like this?

**Comment by brophy2321** [comment]
ran it and the server still is not showing a POST or PUT action

**Comment by amaseda** [comment]
Closing this one since we talked about it IRL. Feel free to re-open if you have more questions about it.
