### ISSUE TITLE
Comments not saving or posting

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project3#332]
![image](https://cloud.githubusercontent.com/assets/19317100/19969370/ae6df1aa-a1ae-11e6-9115-322698f9937d.png)

So far we have the comment area up but we can't get the comment to actually post

![image](https://cloud.githubusercontent.com/assets/19317100/19969400/c9ca92be-a1ae-11e6-8448-50b563783197.png)

**Comment by nolds9** [comment]
Are you getting any errors?

**Comment by alman92** [comment]
No errors just no function

**Comment by nolds9** [comment]
how do you know your function was called?

**Comment by alman92** [comment]
I don't think it is being called, right now we just have the form up.  Ive been console logging everything but I don't know what's not connected.

**Comment by jshawl** [comment]
see where you have `var self = this`

just above that line,

``` js
console.log("i got this far")
```

do you see that in the console?

**Comment by alman92** [comment]
Yea i get it when the index page loads

**Comment by jshawl** [comment]
ok excellent! see where you have `console.log(self.passport)`

just above that line,

``` js
console.log("i got this far")
```

do you see that in the console?

**Comment by alman92** [comment]
Yup!

**Comment by jshawl** [comment]
ok excellent! see where you have `this.newComment = ...`

just above that line,

``` js
console.log("i got this far")
```

do you see that in the console?

**Comment by jshawl** [comment]
also remember to remove the previous console.logs

**Comment by alman92** [comment]
this.newPassport = ... I don't see in the code

this.newComment.passport_id = ??

**Comment by jshawl** [comment]
can you copy/paste your code here so I can modify it or add another screenshot with line numbers

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19970051/2f923abe-a1b1-11e6-82ee-e6fc39f6d1ba.png)

**Comment by jshawl** [comment]
put the console.log on line 84

does it work?

**Comment by alman92** [comment]
Nope it doesn't

**Comment by jshawl** [comment]
ok what about right after line 80 as the first line of your create method - is create function ever being called?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19970170/92fdc9ce-a1b1-11e6-9be0-750a3756fb4b.png)

Yea i think its being called here in the show file

**Comment by alman92** [comment]
Not calling under line 80 either :/

**Comment by jshawl** [comment]
code should look like this:

``` js
this.create = function(){
  console.log("harambe")
}
```

can you tell if create method is being called?

**Comment by alman92** [comment]
No i don't think its being called

**Comment by jshawl** [comment]
when you click on the button "Create comment" - do you see harambe in the console?

If not, can you take another screenshot w/ line numbers

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19970380/3191dbd4-a1b2-11e6-9e03-b4662125a7c6.png)

No harambe in console :/

**Comment by jshawl** [comment]
can you take screenshot of view code as well

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19970439/58ebf0b6-a1b2-11e6-9d4f-66e05641360b.png)

**Comment by jshawl** [comment]
can you copy and paste your javascript code - i just recognized something but easiest way to explain is to edit

**Comment by jshawl** [comment]
the issue is that `this.create` is inside of your `Passport.get` it should be outside

**Comment by alman92** [comment]
``` js
function PassportShowControllerFunction(PassportFactory, DestinationFactory, $stateParams, $state) {
  var self = this
  this.passport = PassportFactory.get({id: $stateParams.id}, function(passport) {
    this.newDestination = new DestinationFactory();
    this.newComment = new PassportFactory();
    this.create = function() {
      console.log("harambe");
      this.newComment.passport_id = this.passport.id;
      if (this.newComment.body !=null) {
        this.newComment.$save().then(function(destination) {
          this.passport.destinations.push(destination);
          this.newComment = new PassportFactory();
        })
      }
    }
  });
}
```

**Comment by alman92** [comment]
Oh i see! Should it be over it or totally outside of that loop?

**Comment by jshawl** [comment]
``` js
function PassportShowControllerFunction(PassportFactory, DestinationFactory, $stateParams, $state) {
  var self = this
  this.passport = PassportFactory.get({id: $stateParams.id}, function(passport) {
    this.newDestination = new DestinationFactory();
    this.newComment = new PassportFactory();
  });
  this.create = function() {
    console.log("harambe");
    this.newComment.passport_id = this.passport.id;
    if (this.newComment.body !=null) {
      this.newComment.$save().then(function(destination) {
        this.passport.destinations.push(destination);
        this.newComment = new PassportFactory();
      })
    }
  }
}
```

**Comment by jshawl** [comment]
if you do that, do you see harambe in the console? if not, paste your code

**Comment by alman92** [comment]
YES!

**Comment by alman92** [comment]
That and angular errors but yes!

**Comment by jshawl** [comment]
what errors

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19970751/59b0ca20-a1b3-11e6-85eb-55bd4874686a.png)

**Comment by jshawl** [comment]
move `this.newComment` outside your callback as well:

``` js
function PassportShowControllerFunction(PassportFactory, DestinationFactory, $stateParams, $state) {
  var self = this
  this.passport = PassportFactory.get({id: $stateParams.id}, function(passport) {
    this.newDestination = new DestinationFactory();
  });
  this.newComment = new PassportFactory();
  this.create = function() {
    console.log("harambe");
    this.newComment.passport_id = this.passport.id;
    if (this.newComment.body !=null) {
      this.newComment.$save().then(function(destination) {
        this.passport.destinations.push(destination);
        this.newComment = new PassportFactory();
      })
    }
  }
}
```

**Comment by alman92** [comment]
GREAT! Ok now we just need to get it to show up

**Comment by alman92** [comment]
Thank you so much!

**Comment by jshawl** [comment]
👍
