### ISSUE TITLE
Having trouble accessing data from factories outside of current

### ISSUE THREAD

**Issue by ihollands** [ga-wdi-exercises/project3#334]

**Comment by nolds9** [comment]
What do you mean, can you provide a code snippet / what you tried / what errors you are getting?

**Comment by ihollands** [comment]
Here is the latest thing that I tried, although there were many iterations:

``` js
function OpeningIndexControllerFunction(OpeningFactory, ApplicantFactory) {
  this.openings = OpeningFactory.query()
  this.applicants = ApplicantFactory.query()
    console.log(this.openings)
    console.log(this.applicants)

}
```

I'm trying to retrieve applicants from within the show view for openings (merely using index controller to queue them up and push them into a global array before crunching on them for the show view).

**Comment by nolds9** [comment]
Ok, this looks good, what about your show controller? You will need to inject both factories there to use them

If I had to pseudo code:
- first find the opening using the `OpeningFactory`
- Then find all the applicants associated with that opening using the `ApplicantFactory`

**Comment by nolds9** [comment]
My advice would be to do your data fetching per controller, rather than try to use global vars

**Comment by ihollands** [comment]
I moved the code down to show and injected ApplicantFactory into the OpeningShowController:

``` js
.controller("OpeningShowController", ["OpeningFactory", "ApplicantFactory", "$stateParams", OpeningShowControllerFunction])

function OpeningShowControllerFunction(OpeningFactory, ApplicantFactory, $stateParams){
  // To access the full opening object
  // this.opening = OpeningFactory.get({id: $stateParams.id})
  // console.log(this.opening)

  OpeningFactory.get({id: $stateParams.id}).$promise.then(response => this.openingName = this.opening = response.opening_name)

  this.applicants = ApplicantFactory.query()
  console.log (this.applicants)

 }
```
