### ISSUE TITLE
Rails issues after merge

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project3#335]
When I run rails c I'm I'm no longer able to call my hard coded comment
![image](https://cloud.githubusercontent.com/assets/19317100/19972958/175e82aa-a1ba-11e6-87ab-1207b3102030.png)
![image](https://cloud.githubusercontent.com/assets/19317100/19972968/20583054-a1ba-11e6-8c61-d45d179af04a.png)

**Comment by jshawl** [comment]
type in `rails c`

then in the console, type in `Comment.all` what do you see?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19973015/492b03d0-a1ba-11e6-8708-0562810030ab.png)

this was working perfectly yesterday

**Comment by jshawl** [comment]
can you take a screenshot of what your `app/models` folder looks like?

Also can i see the contents of `app/models/comment.rb`?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19973060/78075a00-a1ba-11e6-9c03-7b358263b2a4.png)
![image](https://cloud.githubusercontent.com/assets/19317100/19973078/80b671e0-a1ba-11e6-93f8-8cff5259899a.png)

**Comment by jshawl** [comment]
and you typed in `rails c` ?

**Comment by alman92** [comment]
Yup!

**Comment by nolds9** [comment]
are you sure you are in the right directory?

**Comment by alman92** [comment]
Yea i definitely am, I called Passport.all and it worked

**Comment by jshawl** [comment]
what is the output of `Passport.last.comments` ? in rails console?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19973222/007a6b7a-a1bb-11e6-9671-d5ba66482f32.png)

**Comment by jshawl** [comment]
does a passport `has_many :comments` ?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19973254/1d3ad966-a1bb-11e6-8d1c-d0dbeab26183.png)

**Comment by jshawl** [comment]
what if you type `reload!` in rails console? an then try `Passport.last.comments` again?

**Comment by alman92** [comment]
It's still the same error

**Comment by jshawl** [comment]
can you stop rails console, then start it up again? then try?

**Comment by jshawl** [comment]
alternatively want to push your code up to github so we can clone down?

**Comment by alman92** [comment]
Sure I can do that give me one second

**Comment by alman92** [comment]
https://github.com/marlungu/globeView

**Comment by jshawl** [comment]
the last commit was an hour ago - is that right?

**Comment by alman92** [comment]
Yea but nothing has changed since then

**Comment by jshawl** [comment]
just did a fresh clone 

![image](https://cloud.githubusercontent.com/assets/3824954/19973685/48e3c52c-a1bc-11e6-9290-933c3b804b6b.png)

**Comment by alman92** [comment]
Wow ok.... So i should just reclone then?

**Comment by nolds9** [comment]
try recreating your database locally?

**Comment by jshawl** [comment]
what is the output of git status?

**Comment by alman92** [comment]
![image](https://cloud.githubusercontent.com/assets/19317100/19973785/9e770490-a1bc-11e6-8991-c04d466b2ae6.png)

**Comment by jshawl** [comment]
try `git add . && git stash`

then open a new rails console - do comments work then?

**Comment by alman92** [comment]
Nope :/ But if its working on the fresh clone can i just reclone?

**Comment by jshawl** [comment]
sure go for it!

**Comment by alman92** [comment]
I recloned and got this error when I ran rails c

![image](https://cloud.githubusercontent.com/assets/19317100/19974144/d5c4ea88-a1bd-11e6-9d68-8a1a83a2dbc4.png)

**Comment by alman92** [comment]
You cloned from the same repo right? How did it work for you?

**Comment by jshawl** [comment]
```
git clone git@github.com:marlungu/globeView.git
cd globeView
bundle install
rails db:create
rails db:migrate
rails db:seed
rails c

> Comment.all
```

**Comment by jshawl** [comment]
remember to bundle install

**Comment by alman92** [comment]
THANK YOU.

**Comment by jshawl** [comment]
👍
