### ISSUE TITLE
issue with server after merge of css with angular

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project3#336]
![image](https://cloud.githubusercontent.com/assets/21348450/19973556/e7f06eaa-a1bb-11e6-9e46-8f1c5197a115.png)
when we merged my hs server is giving me this

**Comment by brophy2321** [comment]
when i looked my merge had two of the same folders for comments so i deleted the one that was behind but everything else matches up

**Comment by amaseda** [comment]
Can you provide a screenshot of what your current folder/file structure is?

**Comment by jshawl** [comment]
try closing that terminal window, opening a new one and then running `hs`

**Comment by brophy2321** [comment]
it worked, thanks
