### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by brophy2321** [ga-wdi-exercises/project3#337]
![image](https://cloud.githubusercontent.com/assets/21348450/19975417/41b6e86e-a1c2-11e6-8a97-5174ca71c7bb.png)
![image](https://cloud.githubusercontent.com/assets/21348450/19975421/4825ed76-a1c2-11e6-81bb-af9aaaa2abbd.png)

**Comment by brophy2321** [comment]
getting error with heroku

**Comment by brophy2321** [comment]
thinking its because angular and rails are in same project 3 folder
![image](https://cloud.githubusercontent.com/assets/21348450/19976190/2367698a-a1c5-11e6-9ca4-acfe5e8d947b.png)

**Comment by nolds9** [comment]
you should have two separate repos for your project. one repo for the Rails API, and one for Angular.

That way you can deploy just the rails app with Heroku, and deploy the Angular app with Github pages
