### ISSUE TITLE
Difference in routing

### ISSUE THREAD

**Issue by qadriyyah119** [ga-wdi-exercises/project3#34]
I'm in the process of creating the routes for our project and I'm a little confused. 
Would you tell me the difference between the two routes. Which format should we be using? 

1:

```
router.post("/", function(req, res){
  new Artist(req.body).save().then(function(artist){
    res.json(artist);
  });
});
```

2:

```
create: function(req, res){
  var author = new AuthorModel({name: req.body.name})
  author.save(function(err){
    if (!err){
      res.redirect("authors")
    }
  })
}
```

**Comment by RobertAKARobin** [comment]
They're two ways of doing the same thing, so it doesn't really matter. Personally, I prefer the first way, but it's just an aesthetic thing.

**Comment by qadriyyah119** [comment]
So do I. 

Thank you Robin.
