### ISSUE TITLE
My idea (MINE MINE MINE)

### ISSUE THREAD

**Issue by nguyendthinh** [ga-wdi-exercises/project3#354]
Music composition apps where the interface consists of a virtual piano. When the users click on a piano key to make a melody, the app records it and stores it as a composition and has the ability to play back the melody strings. Users are able to do CRUD functions on the composition that they store. API stores the compositions~

**Comment by herrerake** [comment]
DIBS ej, jon r, kevin, sam

**Comment by superbuggy** [comment]
https://github.com/stuartmemo/qwerty-hancock
https://github.com/Tonejs/Tone.js/blob/master/examples/stepSequencer.html
https://github.com/Tonejs/Tone.js
