### ISSUE TITLE
Connecting to 3rd Party API via Express

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/project3#358]
We are using express to connect to a 3rd party API. We expected in our get HTTP request to receive the json data from the API. Instead, we are receiving an error in our terminal:

- getaddrinfo ENOTFOUND

We ensured that we had the http dependency installed and referenced these stackoverflow pages:
http://stackoverflow.com/questions/5432139/how-do-i-write-a-node-js-request-to-3rd-party-api
http://stackoverflow.com/questions/17690803/node-js-getaddrinfo-enotfound

We attempted to further troubleshoot by removing the "http" from the host property within var options (as suggested online), but this crashed our app server. Here is our code below:

```
var express = require("express");
var app = express();
var bodyParser = require("body-parser");
app.set("view engine", "hbs");
app.use(express.static("public"));
app.use(bodyParser.json());
var http = require('http');
http.createServer(function(req, res) {});



  app.get('/', function(req, res){
    var options = {
      host : 'http://api.eventful.com',
      path : '/json/events/search?q=music&l=San+Diego&app_key=WZS7fcgKG9x7ct3z',
      port : 80,
      method : 'GET'
    }

    var request = http.request(options, function(response){
      var body = ""
      response.on('data', function(data) {
        body += data;
        console.log(response)
      });
      response.on('end', function() {
        res.send(JSON.parse(body));
      });
    });
    request.on('error', function(e) {
      console.log('Problem with request: ' + e.message);
    });
    request.end();

    res.send("hello");

  });

app.listen(4000, () => {
  console.log("app listening on port 4000");
});
```

**Comment by andrewsunglaekim** [comment]
did you try accessing the API through the nav bar yet? IE, is it a valid url?

**Comment by julietberman** [comment]
Yes, that was the first thing we did: http://api.eventful.com/json/events/search?q=music&l=San+Diego&app_key=WZS7fcgKG9x7ct3z

**Comment by andrewsunglaekim** [comment]
what values are you getting for your `console.log()`
