### ISSUE TITLE
connecting angular.js to rails

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project3#359]
Having difficulty linking some of these files.

We put app.js in assets/javascripts and expected our index.html.erb file to be able to retrieve it, but are getting a 404

``` html
<script src="app.js" charset="utf-8"></script>
```

our app.js is located in app/assets/javascripts, and our application.js has require_tree removed

link to repo: https://github.com/robertzehnder/project3

**Comment by robertzehnder** [comment]
also tried updating assets.rb

```ruby
 Rails.application.config.assets.precompile += %w( app.js )
```

**Comment by superbuggy** [comment]
closing for now, let me know if you have issues de-coupling
