### ISSUE TITLE
statics js not working properly

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project3#36]
```
var request=require('request');
var env=require('../env');


console.log("controllers working");
function home(request, res){

  request("http://api.nytimes.com/svc/elections/us/v3/finances/2016/president/totals.json?api-key="+env.api_key+"", function(error, response, body){
    if(!error && response.statusCode ==200){
      console.log(body);
      var info=JSON.parse(body);
      console.log(body);
      console.log(candidates.results[0].name);
      for(var i=0; i<candidates.results.length; i++){
        console.log(candidates.results[i].name);
      }

    }
  });
  console.log(candidates.results);
  res.render('./candidates/index');
}

module.exports = {
  home: home
}
```

everything inside function home is not working. I cannt figure out the reason I want to be able to print these JSON data out in the index page

**Comment by RobertAKARobin** [comment]
Can you be more specific than "everything"? Are you getting an error?

**Comment by onesick** [comment]
Actually the problem was I was not refreshing browser, but constantly watching the console screen. because nodemon refreshed itself

**Comment by onesick** [comment]
now the problem is the following lines are not displaying as I wanted.
I have 

```
<ul>
  {{#each candidates.results}}
    <li>{{this.name}}</li>
  {{/each}}
</ul>
```

on views/candidates/index.hbs

and controller has the following code:

```
  res.render('./candidates/index', {candidates:[]});
```

but the candidates are not displaying

**Comment by RobertAKARobin** [comment]
That's because `candidates` is an empty array. You defined it with `{candidates:[]}`. It's working, there just aren't any candidates to show.
