### ISSUE TITLE
Referencing Rails Foreign Keys in Angular

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project3#362]
Hello, we are trying to reference the foreign key property in our angular view. 

We have two tables: cars and photos. Cars can have many photos. 

In our angular view, we attempted to render {{car.photo.photourl}}, but it did not work. Is this the right way to go about referencing foreign keys in Angular? That is the first thing we wanted to check. 

We also tried sending in the photo data in the same action where the car info is contained, but that did not work either. We thought it might be a factory, but did not understand how to associate the two things together. Any guidance would be great. thanks! 

@drewswinburne @bavphan

**Comment by robertzehnder** [comment]
Repo: https://github.com/robertzehnder/project3 

Our view can be found at ./angular/public/index.html

Our seeds can be found at ./db/seeds.rb

**Comment by andrewsunglaekim** [comment]
It depends on what your json response gives you back. If you're rendering json that allows for `car.photo.photourl` then yes. Otherwise, no, that won't work.  Angular doesn't automatically know about associations in your backend. It needs to get fed specific data.

**Comment by robertzehnder** [comment]
cool thanks! You can close this for now
