### ISSUE TITLE
Difficulty implementing functionality from resource outside app.js

### ISSUE THREAD

**Issue by jdreiser1** [ga-wdi-exercises/project3#363]
Right now, I have a large amount of functionality defined separately inside `piano.js` that I need inside `app.js`. How do I import that functionality in? Would a factory be the way to do that? If so, how? I just need a general direction.

**Comment by andrewsunglaekim** [comment]
If its angular, just have the `piano.js` file loaded before the other file in your `index.html`

**Comment by andrewsunglaekim** [comment]
you could put that logic in a factory if you wanted too, yes

**Comment by andrewsunglaekim** [comment]
Going to close this issue for now since no one has responded. Reopen if problem persists.
