### ISSUE TITLE
NgResource between CORS

### ISSUE THREAD

**Issue by donovanallen** [ga-wdi-exercises/project3#364]
We are trying to use Cors to access our JSON endpoints in express from our angular app.js. We are expecting to see ONE document of data from our database rendered on our show page, but we are getting the following error:

![screen shot 2016-12-05 at 3 29 58 pm](https://cloud.githubusercontent.com/assets/22160743/20901268/c303a686-baff-11e6-978d-2bbc86f970f5.png)

We did our research and it appears $resource service expects a response in an array but is receiving an object.

We tested our code within Express. When we send over ALL the data from Mongodb, it works and displays everything on the page. Snippet below:

```
UserEvent.find({}).then(function(events){
  //   res.json(events)
  // })
```

However, when we randomize and want to send over ONE random event data this error occurs. This is the data we are attempting to send (and this code worked prior within Handlebars view)

```
UserEvent.count().exec(function(err, count){
      var random = Math.floor(Math.random() * count);

      return UserEvent.findOne().skip(random).exec(
        function (err, result) {res.json(result)}
      )

    });
```
 
For reference, this is our "Eventfactory" in our angular app that is called in our show function, handling this the data:

```
.controller("ShowController", [
  "$scope",
  "EventFactory",
  ShowControllerFunction])
  .factory("EventFactory", [
    "$resource",
    EventFactoryFunction
  ])

  function EventFactoryFunction($resource) {
    return $resource("/api/events", {}, {
      update: {method: "PUT"}
    })
  }
```

```
function ShowControllerFunction($scope, EventFactory) {
  $scope.events = EventFactory.query();
  $scope.events.$promise.then(function(data){
    console.log(data);
  })
}
```

**Comment by andrewsunglaekim** [comment]
Looks like an angular error, not a backend one, not yet at least. What's the error message say?

**Comment by andrewsunglaekim** [comment]
Based on the cryptic error message, might have something to do with the response expecting an array but instead getting an object. (If you click on it it gives you more info)

**Comment by andrewsunglaekim** [comment]
Check `EventFactory.query()` thats where your issue is
