### ISSUE TITLE
How to post data to a express api endpoint using angular

### ISSUE THREAD

**Issue by jgrune** [ga-wdi-exercises/project3#365]
I am struggling to find some direciton with how to post data (i.e. via a form) via angular to my express backend.  I have verified that the backend functionality is working fine via postman.  My angular factory looks like this:

```
  function SearchFactoryFunction($resource){
    return $resource("http://localhost:4000/api/searches", {}, {
      update: {method: "PUT"}
    });
  }
```

I'd like the index controller to handle the functionality of sending a post request to that endpoint.. here's what I have:

```
function IndexController($state, SearchFactory){
    var indexCtrl = this
    indexCtrl.newSearch = new SearchFactory()

    indexCtrl.addSearch = function () {
      let search = indexCtrl.newSearch
      indexCtrl.newSearch.save()
      $state.go("show", {search});
  }
```

this is causing an error saying:
angular.js:13920 TypeError: indexCtrl.newSearch.save is not a function

**Comment by andrewsunglaekim** [comment]
hmm. That all looks right, can you put a `console.log` in the `addSearch` function? Whats the value of `indexCtrl.newSearch` at invocation?

**Comment by jgrune** [comment]
i think i fixed it - but im not sure if this is a best practice.. i had to pass in an object into the searchfactory containing the data I wanted to post:

```
  function IndexController($state, SearchFactory){

    this.addSearch = function () {
      let search = this.newSearch

      var newSearch = new SearchFactory({body: this.newSearch})
      newSearch.$save();
      console.log(newSearch)

      $state.go("show", {search});
  }

```

**Comment by andrewsunglaekim** [comment]
oooohh. newSearch is a string. I would change the input tag then.

**Comment by andrewsunglaekim** [comment]
Maybe something like this:

```html
<input data-ng-model="vm.newSearch.body">
```

**Comment by andrewsunglaekim** [comment]
reopen if you're still having issues
