### ISSUE TITLE
Issue with nested ng-repeat (trying to limit what is returned)

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project3#366]
Hello, we are trying to run a repeat of all cars, who have multiple photos and only show the first photo. We have been hung up on this for a while and are just wondering if there is a better way

line 2 prints out the all the car objects. These car objects have multiple photos. On line 5, we are trying to print out the first associated photo of the car object. 
```
<div data-ng-controller="indexController as vm">
  <div data-ng-repeat="car in vm.cars">

    <a data-ui-sref="cars/{{car.id}}"><h2>{{car.make}}</h2></a>
    <div data-ng-repeat="photo in vm.photos" ng-if="car.id == photo.car_id">

     <img src="{{photo.photoUrl}}">
</div>
</div>
</div>
```

**This is our controller right now:**
```
function indexControllerFunction($state, Car, Photo) {
 this.cars = Car.query()
 this.photos = Photo.query()
}
```

We tried narrowing down the scope of the photos with nested for loops here, but ran into issues, because it couldn't recognize the length of this.cars or this.photos due to the fact that the actual array that contained them was nested deep inside the promise that returned them.

**An attempt at narrowing down to one photo**
```
function indexControllerFunction($state, Car, Photo) {
 this.cars = Car.query()
 this.photos = Photo.query()

 firstPhotos = [];

 for (var car = 0; car < this.cars.length; car++) {
   for (var photo = 0; photo < this.photos.length; photo++) {
     if (this.cars[car] === this.photos[photo]) {
       firstPhotos.push(this.photos[photo])
       break;
     }
   }
 }

}
```

**Comment by robertzehnder** [comment]
@drewswinburne @bavphan

**Comment by andrewsunglaekim** [comment]
Why don't you have your backend do this heavy lifting? That's entirely too much logic in the front end. In your rails backend have the ability to query for all cars. Use `include` to include any photos associated with those cars. Then you can just grab the first photo from that array on the angular side.

**Comment by robertzehnder** [comment]
Worked perfectly thanks!
