### ISSUE TITLE
Passing data between angular and express

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/project3#367]
We are expecting to see our data in the post method of our express code when we console.log. Instead we are getting an empty object {}

This is our angular:
```
  this.newEvent = new EventFactory();
  this.create = function(user){
    console.log(user)
    this.newEvent.$save()
    // .then(() => {
    //    $state.go("show");
    // })
  }
```

The console.log shows that we successfully captured the data in object form within angular and EventFactory is a parameter being passed to the controller function.

This is our factory:
```
  function EventFactoryFunction($resource) {
    return $resource("http://localhost:4001/api/events", {}, {
      update: {method: "POST"}
    })
  }
```

This is our Express post method where we test/console.log what was passed through:
```
app.post("/api/events", function(req, res){
  console.log(req.body)
})
```

**Comment by nayana487** [comment]
Think the factory should be `update: {method: "PUT"}`

**Comment by julietberman** [comment]
We tried put and post, did not work

**Comment by superbuggy** [comment]
you definitely want `update: {method: "PUT"}`

**Comment by julietberman** [comment]
Okay added that, still no change and passing through an empty object

**Comment by julietberman** [comment]
Here is the checklist dependency we are using: https://www.npmjs.com/package/checklist-model

**Comment by julietberman** [comment]
Console logged newEvent and it is undefined. It seems that the new instance of the factory is not being created, however our factory is working correctly with delete and read functionality

```
  this.create = function(user, newEvent){
    this.newEvent = new EventFactory();
    
    console.log(newEvent)
    console.log(user)
    
    this.newEvent.$save()
    .then(() => {
      console.log("hello World")
    })
  }
```

**Comment by julietberman** [comment]
And to clarify, the EventFactory is being passed as a parameter through the controller function:
```
function IndexControllerFunction($scope, $state, EventFactory) 
```

**Comment by andrewsunglaekim** [comment]
you want some thing like this instead:

```js
function GrumbleNewControllerFunction( GrumbleFactory ){
  this.grumble = new GrumbleFactory();
  this.create = function(){
    this.grumble.$save()
  }
}
```

Right now, everytime you run create, you're overriding `this.newEvent` with a new factory which will have null properties.

**Comment by andrewsunglaekim** [comment]
Notice that the `new` keyword is used outside the create function.

**Comment by julietberman** [comment]
Cool, I had tried this before, outside the function, and I just tried again, same error "newEvent is not defined"

This is my new code:
```
this.newEvent = new EventFactory();

  this.create = function(){
    console.log(newEvent)
    this.newEvent.$save()
  }
```

**Comment by andrewsunglaekim** [comment]
that's because it isn't, try logging `this.newEvent`

**Comment by julietberman** [comment]
Okay, this is now showing an empty object. We console logged again in the post method of express and the red.body is still an empty {}. 

We also tested by passing in the user object (the data that is captured from the form)

```
this.create = function(user){

    console.log(this.newEvent)
    this.newEvent.$save(user)
    // .then(() => {
    //    $state.go("show");
    // })
  }
```

**Comment by andrewsunglaekim** [comment]
what does the `console.log` of `this.newEvent` have in it? Any properties from your form? Or are these values null as well?

**Comment by andrewsunglaekim** [comment]
Also, what is the user argument, where is that coming from.

**Comment by julietberman** [comment]
The console.log of  this.newEvent says: k { } No properties from our form

The user argument comes from the form, we previously console.logged this and it shows all our captured data in object form

**Comment by andrewsunglaekim** [comment]
can you post your html for your form?

**Comment by julietberman** [comment]
Sure thing. For reference, Thinh's code via $http is able to pass the user argument no problem, so it seems the issue is with the factory, not the form.

```
<form id = "zipcodeform" data-ng-submit="vm.create(user)">

    <input id="textbox" type="text" name="postal_code" placeholder="What's your zipcode?"  data-ng-model="user.postal_code"><br/>
    <section>
      <div class="icons">
        <label ng-repeat="category in categories">
          <div class="circle">
            <input type="checkbox" checklist-model="user.categories" checklist-value="category"> {{category}}
          </div>
        </label>
      </div>
    </section>
      <button type="submit">Let's Go!</button>
  </form>
```

**Comment by andrewsunglaekim** [comment]
It doesn't seem like you're defining an event at all. There are literally no properties for an event here. Are you trying to create a user or an event?

**Comment by julietberman** [comment]
They are defined by the checklist model dependency:
```
$scope.categories = [
    'Music',
    'Comedy',
    'Sports',
    'Arts',
    'Food',
    'Family'
  ];

  $scope.postal_code = []

  $scope.user = {
    categories: [],
    postal_code: []
  };
```

When we console log(user) the data is there and captured

**Comment by julietberman** [comment]
<img width="254" alt="screen shot 2016-12-06 at 11 33 40 am" src="https://cloud.githubusercontent.com/assets/17633399/20934050/dd32368c-bba7-11e6-97f0-325584fb8eb5.png">

**Comment by julietberman** [comment]
We are trying to use a new instance of the factory (called EventFactory) to pass the user object

**Comment by andrewsunglaekim** [comment]
are you trying to create an instance of an Event? If so, what are the properties that an event has?

**Comment by julietberman** [comment]
Within the object: categories and postal_code

Again, Thinh's http was able to pass this object, we are not understanding why the factory isnt able to...

**Comment by superbuggy** [comment]
what is `$http` being used for?

**Comment by andrewsunglaekim** [comment]
The factory knows about one thing, and thats `$resource` It's leveraging that to be able to do CRUD to `events` *not* `users` The reason why nothing is saving is because nothing is being stored as properties of `this.newEvent` (ie. `categories` and `postal_code`)

**Comment by julietberman** [comment]
So what is the resolution? We need to add these categories within the factory or within ngresource?

**Comment by andrewsunglaekim** [comment]
So you can have these properties be changed using `ng-model` in your form, or you can store them directly at the controller level. If you're passing in `user` to your create function, then you need to use `user` to populate those fields.

**Comment by superbuggy** [comment]
`this.newEvent` has no properties since you are adding no properties to it with `data-ng-model`
