### ISSUE TITLE
Accessing a property in a collection database to store its value in a variable

### ISSUE THREAD

**Issue by donovanallen** [ga-wdi-exercises/project3#369]
We are trying to access a property in a Mongodb collection in our express app and to grab its value and store it in a variable. The problem is we do not know the proper syntax in order to just grab the value of the property that we're looking for. 

We have confirmed that the model has been successfully created in the database via the following method:
```
app.post("/", function(req, res) {
  UserInput.collection.insert(req.body.User)
})
```

We've tried console logging UserInput.collection, UserInput.collection.query(), UserInput.collection.find() (and virtually every other combination thereof), but it retrieves a big complex object of collection properties, but not our data that we inputted into the DB.

What is the best way to grab the specific data that we just inputted into the User Input collection of our database?

**Comment by julietberman** [comment]
Update on this issue: we are able to access the values within a promise, but the explicit return is logging as [object Object]

UserInput = mongoose.model("UserInput")

Here is our code to grab a specific postal code value and set it to a variable:
```
var zipcode = UserInput.find({}).then(function(result){
     return result[0].postal_code
}).catch(console.log.bind(console))
```

When we console.log _inside_ the promise `console.log(result[0].postal_code)` it logs the zipcode number we want to access, seemingly successful. However, when we console.log the variable holding this value `console.log(zipcode)`  this is when we see ` [object Object]`.

**Comment by andrewsunglaekim** [comment]
zipcode is storing the request itself, do everything you need to do in that promise instead of returning. Alternatively you could do something like this:

```js
var zipcode = UserInput.find({}).then(function(result){
     return result[0].postal_code
})
zipcode.then(function(data){
  // do something with data
  // data is the postal code
}
```

**Comment by andrewsunglaekim** [comment]
going to close this issue, reopen if needed
