### ISSUE TITLE
Adding a Model

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project3#37]
I am working on adding the user model for our app.  I added all the authentication and it works fine.  Then we have a 'Dashboard' which is the name of the 'secret' page that can only be accessed by logged in user.

But now that I am adding a form to the page and I want the information generated by each post of the form to persist in the database and for the user to do full crud on each item I need to go beyond what was involved with the secret page example on the authentication lesson.

So at this point I figure I must create a schema for dashboard and make models and such and I am not sure of the best (or just a good) way to go about this.  We have a schema where our one other model is already defined and I could add it there, but a schema is also defined in the user.js model file.

So if I add it there, it is exported as part of the User model (which is I think what I want for the app) but the only place that the User model is required is in the passport.js file in the config folder.  Then the passport is required in routes.js.

It seems like this isn't a good way for my dashboard stuff to go all intertwined with the passport stuff, but perhaps it is necessary since it is part of the user model...?  
So I am looking for guidance on a good way to structure this aspect.

**Comment by RobertAKARobin** [comment]
I'd say that sounds reasonable. That said, the only way to really find out is to just try it. If it works, it's good enough for now. You can always refactor later.
