### ISSUE TITLE
String is not evaluating as Truthy

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/project3#372]
Purely out of curiosity, I'd love to know what is the problem. We did a hacky work-around but I still can't see what's wrong with my original code.

I am using an ng-show and ng-hide directive based on a boolean value within the show controller to display buttons. The boolean is based on whether an event title exists or not (truthy/falsey). I expect when the of a specific event title exists (as a string) it will evaluate to `true`, instead it is evaluating as false.

ng-show is binding to `$scope.EventValid` which is initially set as `true`

Here is my code within the show controller to switch `$scope.EventValid` to `false` if the event title is not a string. After many console.logs, the variable `validation` is evaluating as a string and is printing the correct title. However, this flag is being passed into this if/else statement as false:
```
    $scope.event = EventFactory.get({}, function(){
       var validation = ($scope.event.title)
       console.log(typeof validation) //evaluating as string

       if (validation == true){
         console.log("true");
       }
       else{
         console.log("false")
         console.log(validation) //printing out the title as a string
          $scope.EventValid = false;
       }
    })
```

**Comment by julietberman** [comment]
P.S. Our hacky solution was to instead use ` if (validation != undefined)` within our if/else statement and this now works fine

**Comment by andrewsunglaekim** [comment]
validation the string does not equal true, the sting is truthy, but does not *equal* true, hence

```js
validation == true
```
 will evaluate to false.

Try this:

```js
if (validation){

}

**Comment by andrewsunglaekim** [comment]
Reopen if you're unclear on this rationale
