### ISSUE TITLE
State change doesnt show new info unless refresh

### ISSUE THREAD

**Issue by julietberman** [ga-wdi-exercises/project3#373]
I am not quite sure the precise location of the issue, but I can explain what I expect to occur and what is resulting instead.

Upon changing states from index to show, I expect the show page to display new event data from the database. Upon clicking a button in the index, its controller passes the data to express and then changes state to show the resulting data. The state changes, but the new data does not display unless we manually refresh.

We checked the database and the new data did successfully insert into MongoDB before we refresh. We also wrapped the state change within a promise:
```
  this.create = function(user){
    // send this object to API and data.categories and data.postal_code
    $http({
      url: "http://localhost:4001/api/events",
      method: "post",
      data: user
    }).then(function(response){
      $state.go('show', { reload: true });
    });
  }
```

**Comment by julietberman** [comment]
Updated code, still not working
```
this.create = function(user){
    // send this object to API and data.categories and data.postal_code
    $http({
      url: "http://localhost:4001/api/events/",
      method: "post",
      data: user
    }).then(() => {
        EventFactory.get()
    }).then(() => {
    $state.go("show", {}, {reload: true})
  })
  }
```

**Comment by julietberman** [comment]
updated code
```js
this.create = function(user){
  // send this object to API and data.categories and data.postal_code
  $http({
    url: "http://localhost:4001/api/events/",
    method: "post",
    data: user
  }).then(() => {
    EventFactory.get()
  }).then(() => {
    $state.go("show", {}, {reload: true})
  })
}
```

**Comment by superbuggy** [comment]
does `{reload: true}` solve the issue, or does the issue persist despite having `{reload: true}`?

**Comment by superbuggy** [comment]
also you probably want to pass in some additional information (2nd argument) to your code here (i.e. which thing to show)

```js
$state.go("show", {}, {reload: true})
```

**Comment by julietberman** [comment]
We had previously tried both of those things. `{reload: true}` is already in the code and the issue persists. Adding the additional empty object as the 2nd argument `{}` breaks the code even further

**Comment by andrewsunglaekim** [comment]
can you post your entire controller?

**Comment by julietberman** [comment]
```js
function IndexControllerFunction($scope, $state, $http, EventFactory) {

  $scope.categories = [
    'Music',
    'Comedy',
    'Sports',
    'Arts',
    'Food',
    'Family'
  ];

  $scope.postal_code = []

  $scope.user = {
    categories: [],
    postal_code: []
  };


  this.create = function(user){
    // send this object to API and data.categories and data.postal_code
    $http({
      url: "http://localhost:4001/api/events/",
      method: "post",
      data: user
    }).then(() => {
    $state.go("show", {}, {reload: true})
  })
  }
}

```

**Comment by andrewsunglaekim** [comment]
can you post the code for your state configuration for your router that's using this controller?

**Comment by julietberman** [comment]
Sure thing, is this the code you mean?

```js
.state("show",{
  url: "/events",
  templateUrl: "/js/ng-views/show.html",
  controller: "ShowController",
  controllerAs: "vm"
})
```

**Comment by andrewsunglaekim** [comment]
can you post `js/ng-view/show.html`

**Comment by julietberman** [comment]
Here you go:
```
<h1>What do you think about...</h1>
<h2>{{event.title}}</h2>
<h2>{{event.comment}}</h2>
<p>{{event.venue_name}}</p>
<p>{{event.venue_address}}, {{event.city_name}}</p>

<button ng-show="EventValid" data-ng-click="vm.destroy(event)">Nahhh, I'll Pass</button>

<a href={{event.url}} target="blank"><button ng-show="EventValid">Hell, Yea!</button></a>

<button data-ng-click="vm.searchAgain()" ng-hide="EventValid">Search Again</button>
```

**Comment by andrewsunglaekim** [comment]
you linked the index controller, but then linked the show state? is there a different show controller?

**Comment by julietberman** [comment]
Yes, the show state connects to the show controller:
```
function ShowControllerFunction($scope, EventFactory, $state) {
  $scope.event = EventFactory.get();
  $scope.EventValid = true;

  this.destroy = function(event){
    $scope.event.$delete(event).then(function(){
    $scope.event = EventFactory.get({}, function(){
       var validation = ($scope.event.title)
       console.log(typeof validation)

       if (validation){
         console.log("true");
         console.log(validation)
       }
       else{
         console.log("false")
         console.log(validation)
         $scope.EventValid = false;
       }
    })
    $state.go("show")
    })
  }

  this.searchAgain = function(){
    $state.go("index");
  }

}
```

**Comment by superbuggy** [comment]
this is possibly related but a separate issue:
```js
.state("show",{
  url: "/events",
  templateUrl: "/js/ng-views/show.html",
  controller: "ShowController",
  controllerAs: "vm"
})
```

since show is for showing a particular item, you probably want `url: "/events/:id"`

**Comment by andrewsunglaekim** [comment]
Are events a model in your database?

**Comment by julietberman** [comment]
We had previously tired that and it broke the code with /:id

**Comment by superbuggy** [comment]
that shouldn't break your code

**Comment by julietberman** [comment]
Yes? We call it UserEvents as a model

**Comment by andrewsunglaekim** [comment]
So your storing multiple events in your database, and your show should be showing a single one? is taht correct?

**Comment by julietberman** [comment]
Yes, it randomizes in express and sends only one event over

**Comment by julietberman** [comment]
James - when we put in `/:id` this is the error:
XMLHttpRequest cannot load http://localhost:4001/api/events/E0-001-098342655-9?$promise=%7B%7D&$resolv…-009123027-3%3Futm_source%3Dapis%26utm_medium%3Dapim%26utm_campaign%3Dapic. Response for preflight has invalid HTTP status code 404

**Comment by julietberman** [comment]
Justttt kidding, put it in the wrong place!

**Comment by andrewsunglaekim** [comment]
In your index controller try this:

```js

this.create = function(user){
  // send this object to API and data.categories and data.postal_code
  $http({
    url: "http://localhost:4001/api/events/",
    method: "post",
    data: user
  }).then(() => {
    let event = EventFactory.get()
    event.$promise.then(() => {
      $state.go("show", {}, {reload: true})
    }
  })
}
```

**Comment by superbuggy** [comment]
You're not passing any arguments to `.get()` in the ShowControllerFunction
```js
  $scope.event = EventFactory.get();
```

**Comment by andrewsunglaekim** [comment]
Just to recap, this was not an angular issue, but a backend issue.
