### ISSUE TITLE
Put request not completing on backend

### ISSUE THREAD

**Issue by drewswinburne** [ga-wdi-exercises/project3#374]
I think I'm close here.  I'm getting the 'photo' from the Photo factory, then updating it with the info passed through the form. 

```javascript
this.update = function(photo){
      let photoToEdit = Photo.get({id: photo.id})
      photoToEdit.$promise.then(() => {
        photoToEdit.$update({id: photo.id, photoUrl: photo.photoUrl, color: photo.color, year: photo.year}).then(function(){
          console.log(photoToEdit);
        })
        })
      }
```

and rails even starts the put request with the updated info:

<img width="713" alt="screen shot 2016-12-07 at 12 17 14 pm" src="https://cloud.githubusercontent.com/assets/21972670/20978986/f1f9dbde-bc78-11e6-95db-4dbef7a012c9.png">

but for whatever reason it is not updating the database, nor is it giving me any errors. Is there something wrong with my $update syntax? Works fine with postman, so I assume something's up on the Angular side

**Comment by andrewsunglaekim** [comment]
can you post your photo factory?

**Comment by superbuggy** [comment]
do you ever see the output of the console.log in your `$update` callback?

**Comment by andrewsunglaekim** [comment]
Reopen if you still need resolution on this.
