### ISSUE TITLE
Vertical Align Text in Div

### ISSUE THREAD

**Issue by robertzehnder** [ga-wdi-exercises/project3#375]
I've tried a couple methods including Flexbox and vertical-align, but my text won't center over a div. The desired functionality is to show the text over the div with the image in it on hover. It does this just fine, but I want the text that shows up on the hover to be vertically aligned in the center, which it does not do.

My HTML:
```
<div class="parent" data-ng-controller="indexController as vm">
  <div class="child" data-ng-repeat="car in vm.cars">

    <a data-ui-sref="show({id: car.id})"><img src="{{car.photos[0].photoUrl}}"></a>

    <p class="imgDescription">{{car.make}}</p>
  </div>
</div>
```

My CSS
```
.imgDescription {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(29, 106, 154, 0.72);
  color: #fff;
  visibility: hidden;
  opacity: 0;
  
  height: 100%;
}

.parent {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.child {
  width: 33.33%;
  height: auto;
  position: relative;
  
}

.child:hover .imgDescription {
  visibility: visible;
  opacity: 1;
}
```
An example...I want honda to be centered in the middle of the image. I used the text-align for left and right alignment and I am not worried about that.

<img width="852" alt="screen shot 2016-12-07 at 2 02 49 pm" src="https://cloud.githubusercontent.com/assets/16313830/20982317/f158a23e-bc85-11e6-9f9d-95a5ad64f05c.png">

**Comment by nayana487** [comment]
It looks like you have a position absolute on the text. that's where you need an `align-content: center;`

**Comment by robertzehnder** [comment]
The position absolute is what holds the blue hover thing onto the div, that bumped it down

**Comment by nayana487** [comment]
maybe make `imgdescription` a div and put the text in a p tag inside the div and align-content on the p. Doesn't make sense for that block to be a p tag anyway

**Comment by robertzehnder** [comment]
ok I'll give that a shot thanks!

**Comment by robertzehnder** [comment]
I found out that I goofed on flexbox thanks!
