### ISSUE TITLE
Only allowed one checkbox to be selected at a time

### ISSUE THREAD

**Issue by nguyendthinh** [ga-wdi-exercises/project3#376]
I'm trying to make it so that the users can only select one checkbox/category at a time in Angular.

in my index view:
```        
<label ng-repeat="category in categories">
        <div>
<img ng-class="{'clicked': clicked}" ng-click="clicked = !clicked" src="../../css/{{category}}icon.png" />
<input id="Checkbox{{$index}}" ng-click="vm.selectOnlyThis($index)" type="checkbox" checklist-model="user.categories" checklist-value="category">
        </div>
      </label>
```

in my app.js:

```
 this.selectOnlyThis = function(id){
    console.log(id + "************");
    for (var i=0; i < $scope.categories.length; i++) {
      var element = angular.element(document.getElementById("Checkbox"+ i));
      if (element) {
        angular.element(document.getElementById("Checkbox" + i)).checked = false;
        console.log("it works");
      }
      angular.element(document.getElementById("Checkbox" + id)).checked = true;
      console.log("IT WORKS!");
    }
  }
```
Short explanation of the code: When one checkbox is clicked on, function will loop through all the boxes and make them false through .checked = false THEN it will make the checkbox that was just clicked on to be true i.e. it will be shown as checked while the other checkboxes will be unchecked.

But it is not working ..... and it's hitting all the console.log and no errors are shown~ HELP!

**Comment by andrewsunglaekim** [comment]
why don't you try radio buttons. that is the default behavior for those
