### ISSUE TITLE
Git Pull Question

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#38]
I'm trying to pull a branch on my fork to my machine. There are differences between what I see in the repo and what I have on my machine.

I tried git pull origin and expected the local to update to match what's in my repo.

Instead, the message is

branch thom-backend -> FETCH_HEAD Already up-to-date.

**Comment by RobertAKARobin** [comment]
This can be caused by `git reset` (or `git rebase` if you were getting all fancy).

If you just want what's online to match what's in your repo, without worrying about overwriting history, then try:

`git pull -X theirs origin the-branch-name`

**Comment by ghost** [comment]
how'd you get over here so fast?  weren't you just in /curriculum?

'theirs' is part of the syntax or a placeholder?

**Comment by RobertAKARobin** [comment]
Part of the syntax.

You know what, a better bet might be `git reset --hard origin/the-branch-name`.

**Comment by ghost** [comment]
Fabulous. I'll try the reset. 

```
_____________________________
```

**Comment by amaseda** [comment]
@thomhouseholder Based on our discussion this morning it sounds like you figured this out. Will close, but feel free to re-open if you're still having trouble with this.
