### ISSUE TITLE
updating mongo with mongoose

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/project3#39]
It looks like there's a lot of options for updating mongo collections using mongoose methods like : 

``` js
Model.findOneAndUpdate([conditions], [update], [options], [callback])
```

This is fine, but I'm wondering if you can attach a method to the schema of a model like this:

``` js
PersonSchema.methods.testEdit = function(name){
   this.name = name;
   this.save().then(function(err){
   if (err){
      console.log(err);
   } else {
      console.log("success!");
   }
 }
}
```

I tested this last week (without the promise) and it seemed to work.  But I wonder if there's something wrong with updating like that.  It feels a little hacky considering there are mongoose methods to do it for us.  Or maybe it's intended and totally normal, I really don't know.

I'll probably give both methods a go tomorrow, but I just wanted to get some input before I start.

**Comment by RobertAKARobin** [comment]
Sure! You can attached methods to whatever you want. You can attach methods to primitive objects like `Object` and `Array` if you'd like (although that's not recommended).

Here's Mongoose's documentation on it:

http://mongoosejs.com/docs/guide.html#methods
