### ISSUE TITLE
Cabral - Project 3 idea submission

### ISSUE THREAD

**Issue by cabralsylvester** [ga-wdi-exercises/project3#403]
An app called Schu-torial... The app would allow users to book Hannah Schuster to perform her remarkable 3 - 5 minute Angular, Ruby, Rails, & Active Record tutorials... The User Story is very simple. Schu-torial a single page application that will allow users to easily book time with Hannah to address their broken code. And voila, in 3- 5 minutes, she fixes it!

**Comment by hschuster9** [comment]
What the heck

**Comment by nairul** [comment]
LOL

**Comment by hawkins-will** [comment]
This is making me so happy!

**Comment by franciscocaballero** [comment]
Our group is doing this.

**Comment by rodneycurl** [comment]
Hahahaha!

**Comment by nfiona** [comment]
:fire:
