### ISSUE TITLE
Rendering JSON

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project3#41]
Users have perspectives, I can render JSON of the users(although its probably not good practice) but I cant quite figure out how to list out the full JSON for the perspectives of a user. 
Below is the JSON for Users.

<img width="473" alt="screen shot 2015-12-08 at 10 14 14 am" src="https://cloud.githubusercontent.com/assets/13842987/11659106/7ea50f9a-9d94-11e5-90d2-812c77bb09d8.png">

I am thinking that maybe it is because perspectives are in the "local" object inside of a user.
The route in app.js

```
app.get("/perspectives", perspectivesController.all);
```

In our perspectives controller

```
all: function(req,res){
    perspectiveModel.find({}).populate("user", "email").then(function(perspective){
      res.json(perspective)
    })
  }
```

The model

```
require("../db/schema");
var mongoose = require("mongoose");
var PerspectiveModel = mongoose.model("Perspective");

module.exports = PerspectiveModel;
```

The schema

```
var mongoose = require("mongoose");
var bcrypt   = require('bcrypt-nodejs');


var Schema = mongoose.Schema;
var ObjectId = Schema.Types.ObjectId;

var PerspectiveSchema = new Schema (
  {
    title: String,
    longitude: Number,
    latitude: Number,
    date: { type: Date, default: Date.now },
    text: String,
    user: {type: ObjectId, ref: "User"}
  },
  {
    toObject: {virtuals: true},
    toJSON: {virtuals: true}
  }
);

var PerspectiveModel = mongoose.model("Perspective", PerspectiveSchema);
```

**Comment by RobertAKARobin** [comment]
I'm not sure what you mean by "full JSON". Can you be more specific about what's missing?

**Comment by lewis2ba** [comment]
I guess I want to list out all the properties of the perspective

```
var PerspectiveSchema = new Schema (
  {
    title: String,
    longitude: Number,
    latitude: Number,
    date: { type: Date, default: Date.now },
    text: String,
    user: {type: ObjectId, ref: "User"}
  },
```

Im trying to set it up so that we can make ajax calls to get the information from perspectives

**Comment by RobertAKARobin** [comment]
Gotcha. This code:

```
app.get("/perspectives", perspectivesController.all);

// ...

all: function(req,res){
    perspectiveModel.find({}).populate("user", "email").then(function(perspective){
      res.json(perspective)
    })
  }
```

...doesn't look like it'd show all the perspectives for one user -- it looks like you want to show all the perspectives in general. Is that true?

**Comment by lewis2ba** [comment]
Yes, I think we want all the perspectives listed out like /songs in Tunr, so we can make an ajax call(fetchPerspectives?) to "/perspectives".

**Comment by RobertAKARobin** [comment]
Gotcha. The JSON you screenshotted is the JSON for Users... Do you have JSON for Perspectives? This code you gave me should work fine... It definitely shouldn't be rendering the JSON you screenshot.

```
all: function(req,res){
    perspectiveModel.find({}).populate("user", "email").then(function(perspective){
      res.json(perspective)
    })
  }
```

**Comment by lewis2ba** [comment]
<img width="421" alt="screen shot 2015-12-08 at 11 12 32 am" src="https://cloud.githubusercontent.com/assets/13842987/11660760/a8be7a48-9d9c-11e5-9538-ccc378f9274a.png">

Here is "/perspectives", it doesnt seem to be getting anything back even though some of our users have perspectives.

**Comment by lewis2ba** [comment]
THANKS!
