### ISSUE TITLE
Angular folders

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project3#420]
Are we able to use the app.js and html files generated in Rails to put our Angular code in? Or do we have to make separate folders? If we can't use the rails files, can you explain why?

Thank you!!

**Comment by nayana487** [comment]
It'll be more straightforward if you make two separate apps, but you can put your angular code in assets

**Comment by nayana487** [comment]
You can do either way, but generally there are more issues with deployment if you combine into one app.

**Comment by nrc0004** [comment]
Thanks!

**Comment by nayana487** [comment]
no prob! gonna close, re-open if ya need.
