### ISSUE TITLE
Nesting in Angular

### ISSUE THREAD

**Issue by dlin2102** [ga-wdi-exercises/project3#421]
How would we nest models in angular? I'm currently using ngResoure and ui.router. Our activities model is nested in our locations model. Would we need to create two sets of factory and controllers?

**Comment by amaseda** [comment]
You've got a couple options here...

One is to create multiple factories, each corresponding to a particular model. If you're using nested resources in your back-end, then the factory for that nested model would need to have the corresponding URL (e.g., `/posts/:post_id/comments/:id`).

Continuing with Posts and Comments as sample models, the other option would be to make it so that whenever you retrieve a Post from your backend, it also sends all the Comments associated with it. You would do this using Rails' `include:` feature. Check out this [StackOverflow post](http://stackoverflow.com/questions/17730121/include-associated-model-when-rendering-json-in-rails). I would also recommend Googling it because it can be used in different ways.

Let me know if I can clarify any of this further.

@dlin2102

**Comment by dlin2102** [comment]
So would the syntax for doing it in the front end look like this:
```
  .factory("LocationFactory", "ActivityFactory"
  ["$resource",
LocationFactoryFunction, ActivityFactoryFunction])

  .controller("LocationShowController", "ActivityShowController" [
    "LocationFactory",
    "ActivityFactory"
    "stateParams",
    LocationShowControllerFunction,
    ActivityShowControllerFunction
  ]);

function LocationFactoryFunction($resource){
  return $resource("http://localhost:3000/locations/:id");
}
function ActivityFactoryFunction($resource){
  return $resource("http://localhost:3000/locations/activities/:id");
}
```

**Comment by amaseda** [comment]
You would create two separate factories. So...

```js
angular
  .module( ... )
  .factory("FirstFactoryName", ["$resource", FirstFactoryFunction])
  .factory("SecondFactoryName", ["$resource", SecondFactoryFunction])
```

You would then inject these factories into whichever controllers need them.

**Comment by amaseda** [comment]
Also the second factory would need an id for the parent model, which in your case is locations.

```js
function LocationFactoryFunction($resource){
  return $resource("http://localhost:3000/locations/:id");
}
function ActivityFactoryFunction($resource){
  return $resource("http://localhost:3000/locations/:location_id/activities/:id");
}
```

**Comment by dlin2102** [comment]
Awesome! And it would have separate states and controllers as well?

So like:   .controller("ActivityShowController", [
    "ActivityFactory",
    "stateParams",
    ActivityShowController
  ]);

and I can:
  .state("activityIndex", {
    url: "/locations/:id/activites/:id",
    templateUrl: "js/ng-views/activitiesindex.html",
    controller: "ActivityIndexController",
    controllerAs: "vm"
  })

**Comment by amaseda** [comment]
That depends on your app's UI. For example, if you have a state/view that's going to make use of both Locations and Activities, you would pass both factories into the corresponding controller.

**Comment by dlin2102** [comment]
So the activities would depend on the location. So
  .state("locationIndex", {
    url: "/locations",
    templateUrl: "js/ng-views/index.html",
    controller: "LocationIndexController",
    controllerAs: "vm"
  }) 
  .state("activityIndex", {
    url: "/locations/:id/activities/:id",
    templateUrl: "js/ng-views/activitiesshow.html",
    controller: "ActivityShowController",
    controllerAs: "vm"
  });

**Comment by dlin2102** [comment]
wait so we can only have one controller in a module

**Comment by amaseda** [comment]
You can have as many controllers and factories as you want!

**Comment by amaseda** [comment]
If your location index page is going to show both locations and activities, then you would need to inject both factories into the controller function. If it's only going to show locations, then you only need to pass in the location factory.

**Comment by dlin2102** [comment]
Okay so for the controller:
```js
angular
  .controller("LocationShowController", "ActivityShowController", [
    "LocationFactory",
    "ActivityFactory",
    "stateParams",
    LocationShowController,
    ActivityShowController
  ]);
```
and then for my states:
```js
function RouterFunction($stateProvider){
  $stateProvider
  .state("locationIndex", {
    url: "/locations",
    templateUrl: "js/ng-views/index.html",
    controller: "LocationIndexController",
    controllerAs: "vm"
  })

  .state("locationShow", {
    url: "/locations/:id",
    templateUrl: "js/ng-views/show.html",
    controller: "LocationShowController",
    controllerAs: "vm"
  });

  .state("activityIndex", {
    url: "/locations/:id/activities",
    templateUrl: "js/ng-views/activitiesindex.html",
    controller: "ActivityShowController",
    controllerAs: "vm"
  });

  .state("activityShow", {
    url: "/locations/:id/activities/:id",
    templateUrl: "js/ng-views/activitiesshow.html",
    controller: "ActivityShowController",
    controllerAs: "vm"
  })
  })
```

**Comment by amaseda** [comment]
You would have multiple `.controller` statements, so...

```js
angular
  .controller( ... ) // one controller
  .controller( ... ) // another controller
```
> Make sure to replace `...` with the usual controller info

**Comment by dlin2102** [comment]
ohhhhh ok but then I can still put it into one router function

function RouterFunction($stateProvider){
  $stateProvider
  .state("locationIndex", {
    url: "/locations",
    templateUrl: "js/ng-views/index.html",
    controller: "LocationIndexController",
    controllerAs: "vm"
  })

  .state("locationShow", {
    url: "/locations/:id",
    templateUrl: "js/ng-views/show.html",
    controller: "LocationShowController",
    controllerAs: "vm"
  })

  .state("activityIndex", {
    url: "/locations/:id/activities",
    templateUrl: "js/ng-views/activitiesindex.html",
    controller: "ActivityShowController",
    controllerAs: "vm"
  })

  .state("activityShow", {
    url: "/locations/:id/activities/:id",
    templateUrl: "js/ng-views/activitiesshow.html",
    controller: "ActivityShowController",
    controllerAs: "vm"
  })

**Comment by amaseda** [comment]
Yup!

**Comment by dlin2102** [comment]
Awesome! Thank you so much!!!!!!!

**Comment by amaseda** [comment]
:+1:

**Comment by amaseda** [comment]
Going to close for now but feel free to re-open and post errors in here when you start implementing this.
