### ISSUE TITLE
Front end to back end

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project3#422]
We cannot get out rails server to communicate with the front end. When the front end requests localhost:8080/#/events (events is one of our models), we get a '500 internal server error' However the error it links to is is in the def new section of the rails controller. How do we get these two to communicate. We have installed rack-cors. Thanks!

**Comment by avalant** [comment]
@justwes2 Did you test your rails API in postman to make sure that it's working? That would be the first step to take. Once, you have established that you are able to run all of the methods, then move to connecting your API to your front-end.

To connect your API to your front-end, you will need to use factories and resources.

**Comment by amaseda** [comment]
Are your front-end and back-end separate? Or part of the same app?

**Comment by justwes2** [comment]
We have front and back ends as separate apps. I ran a get request for localhost:3000/events.json in postman, it default html, when I specify json, it returns "Unexpected '<' ". The controller for in rails looks like
```  def index
    @events = Event.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @events}
    end ```

**Comment by justwes2** [comment]
Postman also warns of a 500 internal server error

**Comment by avalant** [comment]
Okay, I would recommend cleaning up your method:

```
  def index
    @events = Event.all
    render json: @events
  end
```

Double check your that your routes are setup correctly. Also, make sure you are running your rails server when submitting that GET request using postman. Also, you don't need to add .json to the end of your path name when using postman.

**Comment by justwes2** [comment]
I confirmed my rails server is active (console log running, rails homepage appears). Here are our rails routes:
```$ rails routes
      Prefix Verb   URI Pattern                  Controller#Action
      events GET    /events(.:format)            events#index
             POST   /events(.:format)            events#create
   new_event GET    /events/new(.:format)        events#new
  edit_event GET    /events/:id/edit(.:format)   events#edit
       event GET    /events/:id(.:format)        events#show
             PATCH  /events/:id(.:format)        events#update
             PUT    /events/:id(.:format)        events#update
             DELETE /events/:id(.:format)        events#destroy
    students GET    /students(.:format)          students#index
             POST   /students(.:format)          students#create
 new_student GET    /students/new(.:format)      students#new
edit_student GET    /students/:id/edit(.:format) students#edit
     student GET    /students/:id(.:format)      students#show
             PATCH  /students/:id(.:format)      students#update
             PUT    /students/:id(.:format)      students#update
             DELETE /students/:id(.:format)      students#destroy
```
I am still getting html only in postman

**Comment by avalant** [comment]
Are you switching the datatype in postman to json?

**Comment by justwes2** [comment]
in the dropdown menu? when i switch the json i get the unexpected '<'

**Comment by avalant** [comment]
Can you provide link to your API repo?

**Comment by justwes2** [comment]
https://github.com/justwes2/CCG-Ltd

**Comment by avalant** [comment]
Thanks, give me a minute to look at it.

**Comment by justwes2** [comment]
Absolutely. Thanks

**Comment by avalant** [comment]
When I run your API in my postman -- it's throwing errors against the following:

```
def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html {redirect_to @event, notice "Event added"}
        format.json {render json: @event, status: :created, location @event}
      else
        format.html {render :new}
        format.json {render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end
```

It doesn't like the following lines of code:
```
  Line 27: format.html {redirect_to @event, notice "Event added"}
```
And, it's throwing errors at line 28 with the following:
```
format.json {render json: @event, status: :created, location @event}
```


The issues you are having appear to be syntax. If you hit the `preview` option in Postman it should show you those errors.

**Comment by avalant** [comment]
Corrected Method
```
def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html {redirect_to @event, notice: "Event added"}
        format.json {render json: @event, status: :created, location: @event}
      else
        format.html {render :new}
        format.json {render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end
```

You should be able to render your information with that above.

**Comment by justwes2** [comment]
That works, thanks. Whats the difference between your method and mine? I don't see one. Also, why is it having issues with the create method when we are only using the index method?

**Comment by avalant** [comment]
Rails wants what rails wants. My best guess, is that the entire controller is being read by rails checking all methods for methods (and potentially conflicting controllers) to push our an error before actually rendering the information request -- just a guess from me.

Corrected for your Students:
```
def index
      @students = Student.all
      respond_to do |format|
        format.json {render json: @students}
      end
    end
```
```
  def create
      @student = Student.new(student_params)
      respond_to do |format|
        if @student.save
          format.html {redirect_to @student, notice: "Student added"}
          format.json {render json: @student, status: :created, location: @student}
        else
          format.html {render :new}
          format.json {render json: @student.errors, status: :unprocessable_entity}
        end
      end
    end
```

**Comment by avalant** [comment]
Oh the difference?  a few colons were missing from your code -- closing this. feel free to re-open if needed.
