### ISSUE TITLE
Angular cannot access Rails API

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#423]
I have a minimal Rails API and a minimal Angular app designed to get JSON from the API. I have already tested the API with Postman, and it works there. When I try it with Angular, I get this error in the console: "XMLHttpRequest cannot load http://localhost:3000/posts. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access."

I googled around a bit, and it looks like this has something to do with allowing cross-origin request sharing (CORS). I copy/pasted these in the Gemfile (because they were in the wdinstagram_rails_api) ...

```
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Allow CORS requests
gem 'rack-cors', require: 'rack/cors'
```

Then I did `bundle update`, `bundle install`, `rails db:drop db:create db:migrate db:seed`, `rails s`. Still no luck. I tried the `bundle exec rake doc:rails` from the comment above. Same error. It looks like there are a bunch of different approaches to fixing this, so I figured it was best to nip it in the bud by asking you all what the best practice is at this point.

Thanks,
Nat

**Comment by superbuggy** [comment]
from https://github.com/cyu/rack-cors:
>In `config/application.rb` add the following to

```rb
class Application < Rails::Application
  
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*' #this allows any origin. for testing purposes this is fine, but for deployment, you'll want to permit your `gh-pages`-deployed front end to interact with your API
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end

end
```

**Comment by ghost** [comment]
That worked. Thank you.

**Comment by superbuggy** [comment]
a little late now, but `rails new my-sick-api --api -d postgresql` will config your app as an API that uses a pg backend. 

from there, check out `cors.rb` in the `config` directory. The script that I included above will be in `cors.rb` in a comment--you can just uncomment and add it in. 

It's a nice shortcut that you can use to spin up a quick API.

**Comment by ghost** [comment]
Roger that. I read a Rails API tutorial a bit before your first answer that suggested that. I ended up just starting over that way; it seemed simpler than making all the necessary modifications. Thanks again.
