### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#424]
I know, I know: We are strongly discouraged from using it. But we are making a social networking app for gamers, so it seems pretty essential. Any tips on a lightweight-yet-secure way to get Angular to talk to Devise in the Rails API? So far we have found two major approaches:

1. Use devise_token_auth on the back end and ng-token-auth on the front end. This looks pretty reputable, but it also looks pretty heavy and might have a steep learning curve.

2. Use regular Devise on the back end and angular_devise on the front end. This looks much more manageable, but angular_devise looks much less reputable than the alternative, and it appears to require websockets for secure password transmission (that might be true of the first option as well; we haven't been able to read all of the docs yet).

Is there a third or fourth option we are missing? We don't want to sink too much time or energy into authentication, but it seems like an important part of our project.

Thanks,
Nat (speaking on behalf of Group 1)

**Comment by amaseda** [comment]
In the past, students who have tackled user auth in Project 3 have followed the first route, so I would recommend that.

This is the first I've heard of `angular_devise` so can't really comment on that!

**Comment by ghost** [comment]
We'll go with Option 1, then. Thanks!

**Comment by ghost** [comment]
As promised, this is extremely difficult. I think I have devise_token_auth figured out for now, and I think I have the ng-token-auth installed and configured. But it is not at all easy to figure out how I'm supposed to set up the routes, controllers, etc. All the docs and tutorials I see are using syntax pretty different from what we're used to (e.g., $scope, CoffeeScript, anonymous functions instead of dependency injections).

Can you point me in the direction of a relatively simple app that uses ng-token-auth with devise_token_auth, and that uses Angular syntax similar to what we've been using? All we need (at least for now) is sign up, sign in, sign out, and current_user (or whatever is equivalent to that in ng-token-auth).

As a side note, our plan is to use email authentication instead of OAuth. Is that a mistake? Is OAuth easier to implement?

Any answers to these questions, and any other tips, would be much appreciated.

Thanks,
Nat

**Comment by amaseda** [comment]
Off the top of my head don't know of a specific app that uses this but let me do some digging.

Can you give some examples from the docs/tutorials that need clarification? As far as `$scope` goes, it's an alternative to the controller syntax we currently use. In general (but not always) you can replace `$scope` with `this`.

If you're using Devise on the back-end, then email authentication will most likely be easier since that's ready to go out-of-the-box.

**Comment by amaseda** [comment]
This past project implements auth using JSON web tokens. May not use the specific tools you mentioned in your first post but could be helpful nonetheless.

- [Repo](https://github.com/nickoki/recourse)
- [Gemfile](https://github.com/nickoki/recourse/blob/master/Gemfile)
- [Angular Code](https://github.com/nickoki/recourse/blob/b3f24ed04192e3b13de0b6bb507351e370b9bef2/app/assets/javascripts/recourse.js)

@ngcarter

**Comment by amaseda** [comment]
Going to close this one for now but feel free to re-open if you have any questions/comments/issues.
