### ISSUE TITLE
HTTP status code 404

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/project3#425]
I'm getting error when I try to update one of my activities, this occurs when I click the update button, I get these two messages

```
OPTIONS http://localhost:3000/activities/1 404 (Not Found)
(anonymous) @ angular.js:9866
n @ angular.js:9667
f @ angular.js:9383
(anonymous) @ angular.js:13248
$eval @ angular.js:14466
$digest @ angular.js:14282
$apply @ angular.js:14571
(anonymous) @ angular.js:21571
c @ angular.js:3032
```

```
XMLHttpRequest cannot load http://localhost:3000/activities/1. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by laurkgol** [comment]
I'm also having this issue, was this resolved?

**Comment by amaseda** [comment]
Not sure what the cause of the original issue was, but my first hunch is that you need to install and set up this gem: https://github.com/cyu/rack-cors

Let me know how that goes.

@laurkgol

**Comment by laurkgol** [comment]
We have the cors gem and we can add to the database but we get this error when attempting to edit or delete anything: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header

**Comment by laurkgol** [comment]
Actually I get that error when I delete and edit -the delete goes through but edits don't go through.

**Comment by amaseda** [comment]
What error do you see in the terminal window running your Rails server after editing. Does the error there have to do with that header or do you see something different? Or is there an error at all?

**Comment by laurkgol** [comment]
ok fixed it, added :put and :delete to the allowed methods for cors in config/application.rb
