### ISSUE TITLE
Backend API /Frontend Question

### ISSUE THREAD

**Issue by evalaidc** [ga-wdi-exercises/project3#426]
Can the frontend have crud and still add/edit the database but the backend not have crud? or do both ends need to have crud in order for the database to be manipulated?

**Comment by superbuggy** [comment]
Both ends need to have CRUD ultimately, but specifically the back-end is going to the layer that interacts with the database, through `ActiveRecord` in this case.

**Comment by superbuggy** [comment]
Closing for now!
