### ISSUE TITLE
Accessing Nested Resources Through Angular

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/project3#427]
Help meeeeeeeee!

We're trying to figure out how to make Ajax queries using URLS with multiple variables.

We're trying to query this URL: http://localhost:3000/activities/:activity_id/people/:id

We're just a little confused on how exactly we'd want to set up our PersonFactory to be able to access both Params.

A suggestion on where to start would be greatly appreciated!

**Comment by amaseda** [comment]
That URL looks great. You need to make sure that when you call a resource method, it should look something like this...

```js
People.get({id:12, activity_id:55})
```

You would presumably be pulling this information from `$stateParams`. Does that help? If not let me know and can drill down further.

Googling something along the lines of `ngresource multiple parameters` might help too.

**Comment by superbuggy** [comment]
Check this out:
http://stackoverflow.com/questions/15623739/angularjs-ngresource-for-nested-api-resurces-with-different-endpoints

If for whatever reasons you don't get it working, you can always use 2 factories also.

**Comment by amaseda** [comment]
Took care of this one IRL with a token. Going to close for now but please re-open if you have anymore questions/comments/errors relating to this issue!

@hawkins-will
