### ISSUE TITLE
Rerouting forms

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project3#428]
I'm trying to get my .create function to reroute once it has run successfully. Currently, I have the following code (like we did in the Grumblr exercise) : 

```js
  .controller(
    "StudentNewController",
    [ "StudentFactory","$state", StudentNewControllerFunction
  ])

    .state("studentNew", {
         url: "/students/new",
         templateUrl: "js/ng-views/students/new.html",
         controller: "StudentNewController",
         controllerAs: "vm"
   })

  function StudentNewControllerFunction(StudentFactory, $state){
    this.student = new StudentFactory()
    this.create = function(){
      this.student.$save(function(student){
        console.log ("hello")
        $state.go("studentShow",{id: student.id})
      })
    }
  }
```
I should also note that the function itself works-- when I create, the new student gets created and shown in index. It just looks like the new function stops working after .$save as nothing gets logged in console.

**Comment by amaseda** [comment]
What does the corresponding controller action (presumably `StudentsController#create`) in your Rails API look like?

**Comment by nrc0004** [comment]
def new
    @student = Student.new
  end

**Comment by amaseda** [comment]
What about your `create` method -- not `new`?

**Comment by superbuggy** [comment]
and also your `studentShow` state?

**Comment by nrc0004** [comment]
```rb
def create
      @student = Student.new(student_params)
      respond_to do |format|
        if @student.save
          format.html {redirect_to @student, notice: "Student added"}
          format.json {render json: @student, status: :created, location: @student}
        else
          format.html {render :new}
          format.json {render json: @student.errors, status: :unprocessable_entity}
        end
      end
    end
```

```js
.state("studentShow", {
        url: "/students/:id",
        templateUrl: "js/ng-views/students/show.html",
        controller: "StudentShowController",
        controllerAs: "vm"
      })
```

**Comment by superbuggy** [comment]
try using `.then()`

```js
function StudentNewControllerFunction(StudentFactory, $state){
  this.student = new StudentFactory()
  this.create = function(){
    this.student.$save().then(function(student){
    console.log ("hello")
    $state.go("studentShow",{id: student.id})
    })
  }
}
```

Any difference?

**Comment by nrc0004** [comment]
No change, it still stays on the page when I submit

**Comment by superbuggy** [comment]
hrm, can you push your code up and link the repo & branch?

**Comment by superbuggy** [comment]
Are there any errors in console after you hit submit?

**Comment by nrc0004** [comment]
angular:  https://github.com/laurkgol/Front_End_Link_Proj_3.git

rails : https://github.com/nrc0004/CCG-Ltd.git

both have been updated to what I’m working with currently.

**Comment by nrc0004** [comment]
Sorry, here are the repos as well: 
https://github.com/nrc0004/CCG-Ltd
https://github.com/laurkgol/Front_End_Link_Proj_3

**Comment by superbuggy** [comment]
I suspect this is a file management issue and that you weren't making changes in `merge.js`. Delete the redundant files, this is what git is for, you can can always revert to the old version.

**Comment by amaseda** [comment]
We got this one to work yesterday IRL. Going to close but feel free to re-open if you have any additional questions/comments/issues.
