### ISSUE TITLE
join table json data

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project3#430]
I have a join table 'attendances' to join 'students' and 'events'. I have seed data for an attendance, 
```
Attendance.create(
  student_id: 1,
  event_id: 1,
  comment: "test of thing"
)
```

but when I go to http://localhost:3000/events/1/attendances.json (the index controller is set to handle json formatted requests), the page says null. I know the student and event seeds took, and the routes are good, per rails routes. I'm not sure why the join seeds didn't take. 
Here is the link to the repo:
https://github.com/justwes2/CCG-Ltd/tree/join-table

**Comment by amaseda** [comment]
Can you use `create!` instead of `create` and see if that generates an error?

**Comment by superbuggy** [comment]
the `null` is coming from `protect_from_forgery with: :null_session`, let me check your controllers.

**Comment by justwes2** [comment]
@amaseda I added the bang and reran the db, it did not give an error in the seeding, but it is still returning null.

**Comment by superbuggy** [comment]
```rb
  def index
    @attendances = Attendance.all
    respond_to do |format|
      # format.html {render :index}
      format.json {render json: @events} #change to @attendances
    end
  end
```

**Comment by justwes2** [comment]
Oh, right. duh. That got it. Thanks!

**Comment by superbuggy** [comment]
Coincidentally, I'm not sure my comment on `protect_from_forgery` was correct or germane.
