### ISSUE TITLE
Angular factory get request for all values that contain a certain id

### ISSUE THREAD

**Issue by atflick** [ga-wdi-exercises/project3#431]
Hello, I have been struggling with getting a certain get request I am trying to make.  Basically we have events and photos, an event can have many photos.  I am trying to  send a request to pull all photos back that have an event_id based on a param value from the page they navigate to.  I don't have any problem with the param value, that is correct, but I can't seem to get the right formula down for pulling just those items from the database that have that matching event_id, I either get all table values or just one.  Here is what I have tried in my controller:

`this.photos = PhotoFactory.query({where: {event_id: this.event}});`
`this.photos = PhotoFactory.get({} , {event_id: this.event});`
`this.photos = PhotoFactory.get({event_id: this.event});`

I have also changed this line in my factory, for both `get` and `query`
`'get': {method: "GET", isArray: true }` (tried true and false)
`'query': {method: "GET", isArray: true }` (same here)

Also tried messing with the controller in the API by changing this around in the controller:
`@photos = Photo.all`
`@photos = Photo.where(event_id: params[:id]` 
^ this spits out the correct json in the browser but for some reason I still get all values when I query and log to the console in the front end app.  So I feel like I am on to something there but not sure whats going on and why the two apps are getting different values. 

Here's my factory:
```
function PhotoFactoryFunction($resource) {
  return $resource("http://localhost:3000/photos/:id", {}, {
    update: { method: "PUT" }
  })
}
```

**Comment by amaseda** [comment]
`.query` and `.get`, unless you customize them, are going to hit your `index` and `show` actions on the back-end. The latter pair are always going to return either all of your photos or just one of them unless, again, you customize them.

It's strange that, even when using `.where` on the back-end, you're still getting everything on the front-end. Did you update your `render json:` statement accordingly? What's your API controller method look like?

**Comment by amaseda** [comment]
Also, haven't tested this out but if creating a custom API endpoint sounds appealing, take a look at this StackOverflow post. It uses ngResource in a slightly different way but it looks like there might be some valuable stuff in here: http://stackoverflow.com/a/32060572

**Comment by atflick** [comment]
```
  def index
    @photos = Photo.all
    render json: @photos
  end

  def show
    @photos = Photo.all
    render json: @photos
  end

```

**Comment by amaseda** [comment]
So you're saying that the following did not work in your front-end app, despite displaying the correct JSON when visiting the API endpoint in the browser?

```rb
def index
  @photos = Photo.where(event_id: params[:id])
  render json: @photos
end
```

If not, what did your Angular controller look like when accessing this particular API endpoint?

**Comment by atflick** [comment]
Thought about the custom controller, but figured there may be an easier way.  Also thought about just parsing through the array and pulling what I need, but if this app ever goes big time, the amount of data to parse through would be a little insane, so trying to figure out the best way

**Comment by atflick** [comment]
correct, same controller layout as above using .query()
`this.photos = PhotoFactory.query();`

**Comment by atflick** [comment]
Actually this configuration does not pull any data in the angular app

**Comment by atflick** [comment]
<img width="416" alt="screen shot 2017-03-14 at 9 22 20 am" src="https://cloud.githubusercontent.com/assets/18269370/23902511/ccdf70a0-0897-11e7-8741-784455e3db6e.png">

also been getting this 404 error on the same page, regardless if getting data or not.  I don't think it's related but maybe it is

**Comment by amaseda** [comment]
Yeah, I'm guessing that's because no id is being pass through in params. And because it's the `index` action, it's not going to be triggered if there is a value for `:id` in the URL -- that would just trigger `show`. 

Some options...

1. Take care of this using `show`. Downside here is that it's no longer truly RESTful.
2. Use nested resources in `routes.rb`. This will make it so that you have a RESTful route that requires attaching an `event_id` with each `photo`. This doesn't mean that you need to replace what you already have - could just add it on top of your existing routes.
3. Do something custom like we mentioned before.

Personally, I lean towards option 2. That way, when you call `.query` you would say something like `PhotoFactory.query({event_id: 2})`. The corresponding factory URL would be something like `http://localhost:3000/events/:event_id/photos/:id`.

Happy to elaborate on any of these three options. Let me know.

**Comment by atflick** [comment]
How would the first work?  I am already kind of forgoing the index page because I only have one page for all photos that correspond to an event and using a gallery to show them.

I would like to try option 2, but curious what my factory will look like afterwards.  I don;t think we ever really covered nested resources with this kind of setup so not sure what all is involved or how long it will take me to rework this.  I would like to learn this though since this is the proper way to do it.

**Comment by amaseda** [comment]
#### Option 1

You would just change the contents of `show` so that it returns exactly what you want (i.e., use `.where`). Again, not the greatest option because `show` would no longer function the way it's supposed to -- it would return a collection of photos.

#### Option 2

Your factory would look the same, except the URL would look like it does in a Rails app that uses nested resources. Here's an example using Grumbles and Comments...

```js
function CommentFactoryFunction( $resource ){
  return $resource( "http://localhost:3000/grumbles/:grumble_id/comments/:id", {}, {
      update: { method: "PUT" }
  });
}
```

Let's say you want to get all Comments that belong to a particular Grumble, you would do something like...

```js
CommentFactory.query({grumble_id: $stateParams.grumble_id})
```
> In this case the `grumble_id` is coming from `$stateParams`, but it can come from wherever.

The `grumble_id` in the above example corresponds to the `:grumble_id` in the factory URL.

And if you want to retrieve just one Comment that belongs to a particular Grumble, you would make sure to include that Comment's `id` when using `.get`...

```js
CommentFactory.get({grumble_id: $stateParams.grumble_id, id: $stateParams.id})
```

**Comment by atflick** [comment]
Alright sweet, I'll try this on a different branch in a little bit.  I'll close the issue and reopen if I need more help.

Thanks Adrian!

**Comment by atflick** [comment]
Alright, so I got the nested routes setup correctly and working, but now I am struggling with getting the first item in the array that the query produces.  When I c-log it, I definitely see an array so you would think this would work:

snippet from my controller
```
this.photos = PhotoFactory.query({event_id: $stateParams.event_id}, function(){
    this.currentImage = this.photos[0]
  })
```

I am just trying to get the first photo from the query, but it's giving me a really hard time and can't find much about it on the interwebs.  

Have also tried without the promise function and just doing:
` this.currentImage = this.photos[0]` but to no avail.

Must be some trick to this that I can't figure out?  

edit: keep getting undefined with all my returns

**Comment by superbuggy** [comment]
is `this.photos[0]` undefined?

**Comment by atflick** [comment]
yea

**Comment by superbuggy** [comment]
try this:

```js
PhotoFactory.query({event_id: $stateParams.event_id}, function(res){
  this.photos = res;
  this.currentImage = this.photos[0];
  console.log(this.photo, this.photos)
})

**Comment by atflick** [comment]
also undefined

**Comment by superbuggy** [comment]
is `$stateParamas.event_id` defined?

**Comment by atflick** [comment]
yep, pulling the param down correctly.  ng-repeat also works on this.photos in the code snippet I had above and I can log an array

**Comment by atflick** [comment]
<img width="509" alt="screen shot 2017-03-14 at 5 03 27 pm" src="https://cloud.githubusercontent.com/assets/18269370/23922362/739a3548-08d8-11e7-8e26-084c3a90f0df.png">

**Comment by superbuggy** [comment]
```js
  //sorry meant this:
  console.log(this.currentImage, this.photos)
```

**Comment by atflick** [comment]
undefined twice with what you gave me:

```
PhotoFactory.query({event_id: $stateParams.event_id}, function(res){
    this.photos = res;
    this.currentImage = this.photos[0];
  })
```

**Comment by atflick** [comment]
my screenshot above is what i get from 
```
this.photos = PhotoFactory.query({event_id: $stateParams.event_id}, function(){
    this.currentImage = this.photos[0]
  })
```

**Comment by superbuggy** [comment]
```js
PhotoFactory.query({event_id: $stateParams.event_id}, function(res){
  this.photos = res;
  this.currentImage = this.photos[0];
  //c-logs must be in callback
  console.log(this.photos);
  console.log(this.currentImage);
})
```

**Comment by atflick** [comment]
ok that returns what i need, but is that then scoped to that function?  Can't seem to access it in the view

**Comment by superbuggy** [comment]
Do you have`vm.photos` in an `ng-repeat` somewhere in the view?

**Comment by atflick** [comment]
yep

**Comment by superbuggy** [comment]
it's scoped to that vm or controller

**Comment by superbuggy** [comment]
does `vm.currentImage` work in the view?
what isn't working in the view?

**Comment by atflick** [comment]
nope, neither vm.photos or vm.currentImage work with them both being defined in the callback

**Comment by superbuggy** [comment]
can you link your repo with current code?

**Comment by atflick** [comment]
https://github.com/atflick/tourist-app-angular-project-3/blob/andy/js/app.js

**Comment by superbuggy** [comment]
So this is PhotosIndexController right?

Is photos nested within events?

**Comment by superbuggy** [comment]
Is your backend 100% certainly responding with the proper data?

**Comment by superbuggy** [comment]
If this issue isn't related to the first can we open a new issue with all the relevant information, including the information requested in my last two 2 posts? 🤓 

if it is not a distinct issue, that is fine.

**Comment by atflick** [comment]
yes it's nested, definitely pulling the data I want

**Comment by superbuggy** [comment]
Is your view just taking a minute to update? you can't see the value of `vm.currentImage.title` in your view?

**Comment by atflick** [comment]
and I am using the index because it is a single photo gallery page, so all the photos related to the event show up, but i want to be able to set up the first image as the main image in the gallery when the page first loads

**Comment by superbuggy** [comment]
It doesn't make sense to me that vm.currentImage isn't defined in your view if the right controller is linked. Have you linked a different controller?

**Comment by atflick** [comment]
nope, can't see anything except for my vm.event.name, which is unrelated

**Comment by superbuggy** [comment]
This also seems like a distinct issue. Can we close this one and create a new issue targeted at this issue?

**Comment by atflick** [comment]
yea sure

**Comment by superbuggy** [comment]
awesome thanks!

**Comment by superbuggy** [comment]
be sure to include all the relevant info and links to your code!
