### ISSUE TITLE
Associations with Auth0

### ISSUE THREAD

**Issue by nairul** [ga-wdi-exercises/project3#433]
Using [Auth0](https://auth0.com/), we're implementing user authentication into GABook, our General Assembly Social Media app.

I've followed this guide on setting up Auth0 for a SPA using Angular 1.x
https://auth0.com/docs/quickstart/spa/angularjs

Now users can sign in and sign out using their LinkedIn/Facebook/Twitter/Google.
That user information goes to an Auth0 database. On their site I'm able to view a list of the users who have signed into the app.
 
Additionally, information on the page can be shown/hidden IF a user is logged in vs. logged out.

**Now for the million dollar question:** Using Auth0, is there a way to tie specific resources defined in our Rails API to specific users? i.e. Adam logs into GABook. Adam creates his GABook profile. Adam can ONLY edit/delete the profile that belongs to him, not profiles that belong to other users.    

I understand instructors might not have any experience using Auth0... but we'd appreciate any help at all!

**Comment by amaseda** [comment]
What sort of information do you have in your Auth0 database that identifies a unique user? Is any of this information accessible in your Angular app? Could you potentially send that information to your database?

**Comment by superbuggy** [comment]
Couldn't you just use the data from the Auth0 db/table on the back-end? It would be like using `current_user` with devise in a rails app, but you'd be defining `current_user` using the Auth0 data... You could then restrict CUD actions to records that belonged to the logged in user, within the specific controller methods (`create`,`update`,`destroy`) on your back end.

**Comment by superbuggy** [comment]
You'd have to configure your Auth0 dashboard to accept requests from your backend it seems like. And also make those requests.

**Comment by amaseda** [comment]
Going to close this one since it's been sitting here for a bit, but please re-open if you have any additional questions/comments/issues.
