### ISSUE TITLE
Creating a new Attendance in ShowEventController

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project3#434]
@superbuggy 
Not sure. Lets check the code:
```
  <select placeholder="Who's going?" class="rsvp" name="rsvp" ng-model="vm.studentGoing">
       <option ng-repeat="student in vm.students" value={{student.id}} ng-model = "vm.newAttendance">{{student.name}}</option>
      </select>
      <button type="submit" value="Submit" **ng-click = "vm.addAttendance()**">I'm going</button>
```
The submit button has ng-click to run the function, I don't see any spelling errors, and the console stayed empty- no logs or errors. That should bridge to `  function addAttendance(AttendanceFactory, attendance) {` but since the next line is the console log, we know it doesn't

**Comment by superbuggy** [comment]
take out the asterisks!!! oh wait, are those actually in the code or were you trying to use `.md` emphasis?

**Comment by justwes2** [comment]
That asterisks were supposed to bold that span. guess it doesn't work in markdown. they are not in the code itself.

**Comment by superbuggy** [comment]
ahh they get escaped in the code snippet block.

**Comment by superbuggy** [comment]
So what exactly is happening? I see your code up there. Is the function not being called at all? Put a console.log as the very first line of the function to determine.

**Comment by justwes2** [comment]
Here the function within the controller:
```
function addAttendance(AttendanceFactory, attendance) {
      console.log(attendance)
      vm.newAttendance = new AttendanceFactory()
      this.create= function() {
        this.newAttendance.$save(function(attendance) {
           $state.go("eventShow", {id: attendance.event_id})
        })
      }
```
When I click the button, it does not console log

**Comment by superbuggy** [comment]
You have kind of an ruly tangle of function definitions there.  This is sticking out like a sore thumb. Just write your create method here like you did in the other controller.

Get rid of this line
```js
function addAttendance(AttendanceFactory, attendance) {
```

**Comment by superbuggy** [comment]
your Routing function contains state definitions that configure what your view-model or controller-instance is called on the view/template side. 

You may have defined it or aliased it as 'vm' there, It won't be `vm` in the controller, it will be `this.addAttendance = function(){}`

**Comment by justwes2** [comment]
Great. That gave me a console log. Part of the problem is that in the attendance object, the event_id is logged, but the student_id is undefined. I need to tie the `student.id` in the value of the `option` to the attendance creation. I'm also realizing that the code I've been working with is part of a larger block that I wasn't even cognizant of: 
```
this.addAttendance = function() {
    this.student= StudentFactory.get({id: this.studentGoing});
    let attendance = {
      student_id: this.student.id,
      event_id: this.event.id
    }
    this.addAttendance = function() {
      console.log(attendance)
      this.newAttendance = new AttendanceFactory()
      this.create= function() {
        this.newAttendance.$save(function(attendance) {
           $state.go("eventShow", {id: attendance.event_id})
        })
      }
    }
  }
```

so i need to fix that... 
```
  this.addAttendance = function() {
    this.student= StudentFactory.get({id: this.studentGoing});
    let attendance = {
      student_id: this.student.id,
      event_id: this.event.id
    }
    console.log(attendance)
    this.newAttendance = new AttendanceFactory()
    this.create= function() {
      this.newAttendance.$save(function(attendance) {
         $state.go("eventShow", {id: attendance.event_id})
      })
    }  
  }
}
```
I also added a console log for `this.student` after it is defined. That returns the correct student object, but `this.student.id` is undefined. I'm trying to drill down, but it returns an object for `this.student.$promise.$$state` but is undefined at the next level, `this.student.$promise.$$state.value`

**Comment by superbuggy** [comment]
in `this.addAttendance`, you need to define `this.event`. it's undefined. define it in a similar way to `this.student`.

**Comment by justwes2** [comment]
event_id is the one that is working. If I add `this.event = EventFactory.get({id: $stateParams.id});`, it becomes undefined. I need to find a way to access the id property of the `this.student` object. When I explore in in the console, it does this weird recursive thing: 
<img width="365" alt="screen shot 2017-03-14 at 6 39 19 pm" src="https://cloud.githubusercontent.com/assets/24883096/23925441/9a853380-08e5-11e7-9b62-4ee9a00a9053.png">
Where it just falls into a loop. I'm not sure why its' doing that.

**Comment by superbuggy** [comment]
that's just the structure of the object.

**Comment by superbuggy** [comment]
you probably need `{event_id: $stateparams.id}`
