### ISSUE TITLE
Trouble accessing scoped variables in view

### ISSUE THREAD

**Issue by atflick** [ga-wdi-exercises/project3#435]
I have a photos index page that i am using to display all photos for an event.  The photos are nested within events on my backend and am able to get the correct data when I look at localhost/3000.  However, I am specifically trying to access the first item of an array of photos after I query them from the database.  Here was my original setup within my controller
```
this.photos = PhotoFactory.query({event_id: $stateParams.event_id})
this.currentImage = this.photos[0];
```
^I am able to access vm.photos in my view but vm.currentImage is returning undefined

```
PhotoFactory.query({event_id: $stateParams.event_id}, function(res){
    this.photos = res;
    this.currentImage = this.photos[0];
  })
```
^I switched to this and cannot access either vm.photos or vm.currentImage in my view, but when i c-log them inside the function it does return the correct values I should be getting...

app.js > https://github.com/atflick/tourist-app-angular-project-3/blob/andy/js/app.js
code starts at line 274

view for this controller > https://github.com/atflick/tourist-app-angular-project-3/blob/andy/js/ng-views/photos/index.html

**Comment by amaseda** [comment]
You made the right move in adding a callback to `.query`. The issue could have to do with context -- `this` might not represent the controller function inside of that callback.

What happens if you do something like this...

```js
function PhotoControllerFunction( ... ){
  let self = this
  PhotoFactory.query({event_id: $stateParams.event_id}, function(res){
    self.photos = res;
    self.currentImage = this.photos[0];
  })
}
```

Does that change anything? If not, forget about the `self` approach and try replacing the callback with an arrow function.

**Comment by atflick** [comment]
You sir, are a genius.  I knew it was losing context but was confused on how to bind 'this' inside the callback.  I will have to remember this little trick.

**Comment by atflick** [comment]
closing, thanks again!
