### ISSUE TITLE
Post request routing to wrong address for join table

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/project3#436]
@superbuggy 
When I try to submit a post request, it routes to `localhost:3000/events/attendances.json` instead of `localhost:3000/events/:id/attendances.json`. The factory lists the latter as the url. Where in the code should I be looking to address this error?

**Comment by superbuggy** [comment]
are you passing in an object to SomeFactory`.query`/`.get` with key that isn't `id`?

**Comment by justwes2** [comment]
```js
function ShowEventControllerFunction(EventFactory, $stateParams, AttendanceFactory, StudentFactory){
  this.event = EventFactory.get({id: $stateParams.id});
  this.attendances = AttendanceFactory.query({id: $stateParams.id});
  this.students= StudentFactory.query();
  this.addAttendance = function() {
    this.student= StudentFactory.get({id: this.studentGoing});
    let attendance = {
      student_id: this.studentGoing,
      event_id: this.event.id
    }
    this.newAttendance = new AttendanceFactory()
    this.newAttendance.$save(function(attendance) {
       $state.go("eventShow", {id: attendance.event_id})
    })
  }
}
```
It looks like all of the get and query keys are ids. `this.event` contains the id we are looking for.

**Comment by superbuggy** [comment]
```js
  this.addAttendance = function() {
    // is value of `this` different here INSIDE this function?
    this.student= StudentFactory.get({id: this.studentGoing});
  }
}
```

**Comment by justwes2** [comment]
I ran a console log under it, and came back with the object I expected. And I'm defining student but `studentGoing` which returns the value I want (the student id). The issue I'm having is getting the event id from `this.event = EventFactory.get({id: $stateParams.id});` into the destination with this factory: 
```
function AttendanceFactoryFunction($resource){
  return $resource("http://localhost:3000/events/:id/attendances.json", {}, {
    update: {method:"PUT"}
  })
}
```

**Comment by superbuggy** [comment]
are you getting back a path that is `localhost:3000/events/attendances.json` or are you actually getting back `localhost:3000/events//attendances.json`?

the latter seems more likely

**Comment by superbuggy** [comment]
is `$stateParams.id` defined?

**Comment by justwes2** [comment]
used a token. Thanks
