### ISSUE TITLE
Re-direct 

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/project3#438]
Hello-- So this is building on the issue I had earlier with re-direct. I attempted to use the ".then(function)... $state.go" approach for after I hit submit on my edit functions but when I do "update" throws no errors (it just doesn't change pages) and "delete" throws the following error:

"TypeError: Cannot read property 'go' of undefined"

Here is the code I have so far:

```
.controller("StudentEditController", [
    "StudentFactory",
    "$stateParams", "$state",
    StudentEditControllerFunction
  ])

  .state("studentEdit", {
      url: "/students/:id/edit",
      templateUrl: "js/ng-views/students/edit.html",
      controller: "StudentEditController",
      controllerAs: "vm"
    })

function StudentEditControllerFunction( StudentFactory, $stateParams, $state ){
 this.student = StudentFactory.get({id: $stateParams.id});
 this.update = function(){
   this.student.$update({id: $stateParams.id}).then(function(student){
     $state.go("StudentShow", {id: student.id})
   })
   console.log("student updated")

 }

 this.destroy = function(){
    this.student.$delete({id: $stateParams.id}).then(function(student){
      $state.go("StudentIndex")
    })
    console.log("student deleted")
  }
}
```

**Comment by amaseda** [comment]
Hm, from what I can tell here you're injecting the `$state` dependency properly. Would you mind pushing up your code and letting me know which branch/file(s) to look at?

**Comment by nrc0004** [comment]
JK I got it to work-- don't know how but yeah xD thanks though!!

**Comment by amaseda** [comment]
lol word!
