### ISSUE TITLE
Creating a New Workout

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#44]
We have been stuck on this for quite a while.  We cannot seem to figure out how to properly add a Workout.  We believe that we have the post method defined in the controller correctly but cannot seem to grasp rendering the new workout form and the other methods that go in the views.  This is the link to our repo https://github.com/murgia/SwoleMate and the lines that we are having trouble with are public/js/views/workoutView.js on lines 35.  So far we just have the click event testing.

**Comment by jshawl** [comment]
are there any errors in the console?

**Comment by murgia** [comment]
So we got to another point where we are now displaying the proper form when we click on the element but we are displaying the template 4 times.

**Comment by murgia** [comment]
We do not currently have errors in the console.

**Comment by murgia** [comment]
So when we originally did it we had the values of the form filled in similarly to the edit form.  The actual content of the form was Arms Arms Legs Legs so it was displaying two forms for each workout.

**Comment by murgia** [comment]
We just tried deleting all of our workouts and it was still displaying four.

**Comment by RobertAKARobin** [comment]
Is your seed data functioning?

**Comment by murgia** [comment]
our seed data is loading properly
