### ISSUE TITLE
Back End Deployment

### ISSUE THREAD

**Issue by SavrajSingh** [ga-wdi-exercises/project3#441]
Is there anyway to check if the deployment was successful. I read through the command line prompts while it was migrating and it says all tables were made. PLS HALP ME I AM WEARY

**Comment by nayana487** [comment]
you should be able to go to the site and see if it's live. from the command line in your project folder, you can just type `heroku open`

**Comment by superbuggy** [comment]
`heroku open` will open sys default browser and navigate to your app's deployment url
`heroku logs` shows logs w/ errors, if any occurred

**Comment by superbuggy** [comment]
closing for now!
