### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/project3#447]
Quick question: how to insert line breaks into the seed data so it doesn't look like one big chunk? Tried \n and < br>

**Comment by amaseda** [comment]
Hm, not sure what else you could add to your seed data to make that happen aside from `\n` and `<br>`.

Can you use CSS to do this?

**Comment by superbuggy** [comment]
try `&#13;&#10;` if the initial suggestions don't work. ([reference](http://code.cside.com/3rdpage/us/newLine.html))

**Comment by fanelenan7** [comment]
Didn't work either.

**Comment by amaseda** [comment]
What about `&nbsp;`? Might need to use two of them together, try it out...

**Comment by fanelenan7** [comment]
Also no :(

**Comment by amaseda** [comment]
What do your seeds look like? And where/how are you rendering this information in your Angular app?

**Comment by fanelenan7** [comment]
https://github.com/fanelenan7/project3/blob/rails-back-end/db/seeds.rb

Yes, we are trying to render it in the Angular app.

**Comment by superbuggy** [comment]
What about `\r\n\r\n` or `\n\r\n\r`?

**Comment by fanelenan7** [comment]
We got it with this: white-space: pre-line;
It will display \r or \n (enter) in user input as a new line.

Thanks for the help.
