### ISSUE TITLE
User Authentication & Login using Ajax Requests

### ISSUE THREAD

**Issue by beckybeauchamp1** [ga-wdi-exercises/project3#45]
I am trying to submit a post request through AJAX from a form to login Users from the client side without having a page refresh. My request for User.postLogin is failing each time, as I believe it has something to do with my middleware calls to set a session. Is there a way I can do this using Passport and Ajax, or would I have to hand roll my user authentication in order for this to work? 

Any help would be greatly appreciated, I am really interested to know a potential solution!! 

Here is my code and specifically my ajax requests from client side:

``` js
User.post = function(){
  var self = this;
  var url = "http://localhost:3000/signup";
  var request = $.ajax({
    url: url,
    type: "POST",
    dataType: "json",
    data: {
      firstname: $("#firstname").val(),
      lastname: $("#lastname").val(),
      email: $("#email").val(),
      password: $("#password").val()
    }
  }).then(function(postedUserinfo){
    self.reload(postedUserinfo);
  });
  return request;
};

User.postLogin = function(){
  var self = this;
  var url = "http://localhost:3000/login";
  var request = $.ajax({
    url: url,
    type: "POST",
    dataType: "json",
    data: {
      firstname: $("#firstname").val(),
      lastname: $("#lastname").val(),
      email: $("#email").val(),
      password: $("#password").val()
    }
  }).then(function(res){
    alert("sucess user!");
  }).fail(function(res){
    console.log(res);
    alert("failure from user post");
  });
};
```

My users routes:

```
var passport = require("passport");

var usersController = {
  getSignup: function(req, res){
    res.json({message: 'get request from signup'});
    res.render('/');
  },
  postSignup: function(req, res){
    var signUpStrategy = passport.authenticate('local-signup', {
      successRedirect: '/',
      failureRedirect: '/signup',
      failureFlash: true
    });

    return signUpStrategy(req, res);
  },
  getLogin: function(req, res) {
    res.render('/');
  },
  postLogin: function(req, res) {
    console.log("Route being hit");
    var loginProperty = passport.authenticate('local-login', {
      successRedirect : '/',
      failureRedirect : '/',
      failureFlash : true
    });
    console.log(global.currentUser);
    return loginProperty(req, res);
  },
  getLogout:  function(req, res) {
    req.logout();
  },
};

module.exports = usersController;
```

Thank you so much!

**Comment by jshawl** [comment]
are you returning JSON? http://stackoverflow.com/a/5745195/850825

**Comment by beckybeauchamp1** [comment]
no, not in my controller for the post request for the users login, i had it
set up similar to the routes/controller in passport using redirect '/'

**Comment by RobertAKARobin** [comment]
When you say it's failing, do you mean you're getting an error? If so, what is it?

**Comment by beckybeauchamp1** [comment]
The User.getlogin ajax request is displaying .fail  and my alert("failure
from user post") after i am clicking submit to send the post request with
the user's data and information

it is hitting the route and i am getting a console.log on my terminal for
the route is being hit, but the user is coming back undefined

**Comment by RobertAKARobin** [comment]
Cool! Well, that's good at least. Is the `console.log(global.currentUser)` working?

**Comment by beckybeauchamp1** [comment]
It's displaying, but returning undefined!

**Comment by RobertAKARobin** [comment]
Take a look at your `config/passport.js` file. The problem must be in the `passport.use('local-login'...` block, since that's what is being activated with `var loginProperty = passport.authenticate('local-login'...`.

Put some `console.logs` in that mammajamma.

**Comment by beckybeauchamp1** [comment]
Hi Robin, I put in console.logs into passport.use and it seemed to have
return the user when i passed into the console.log at the end of the
function:

``` js
passport.use('local-login', new LocalStrategy({
    usernameField : 'email',
    passwordField : 'password',
    passReqToCallback : true
  }, function(req, email, password, callback) {
    User.findOne({ 'local.email' :  email }, function(err, user) {
      if (err) {
        console.log("This is passport middleware error: " + err);
        return callback(err);
      }
      // If no user is found
      if (!user) {
        console.log("This is passport middleware error no User found");
        return callback(null, false, req.flash('loginMessage', 'No user
found.'));
      }
      // Wrong password
      if (!user.validPassword(password)) {
        console.log("This is passport middleware, wrong password!");
        return callback(null, false, req.flash('loginMessage', 'Oops! Wrong
password.'));
      }
        console.log("This is being returned from passport:" + user);
      return callback(null, user, req.flash('loginMessage', "You have
signed in sucessfully!"));
    });
  }));
```

This was displayed on my terminal:

```
Route being hit
undefined
```

This is being returned from passport:

``` json
{ local:
   { email: 'beckybeauchamp1@gmail.com',
     password:
'$2a$08$eqmrtKBjKsx.bHlzPbYuGe4HPNon2tCaSv6VYL.QBQ7pAd.9PDuFK' },
  twitter: {},
  votes:
   [ { createdAt: Mon Dec 07 2015 18:47:37 GMT-0500 (EST),
       location_id: 'ChIJM_l-a-a3t4kRQa_lW1A7W8k',
       votes: true,
       _id: 56661a99dadb9b0c8901ee09 },
     { createdAt: Mon Dec 07 2015 18:47:37 GMT-0500 (EST),
       location_id: 'ChIJgRwXf723t4kRdfqt36VafUU',
       votes: true,
       _id: 56661a99dadb9b0c8901ee0a },
```

POST /login 302 148ms - 35b

**Comment by RobertAKARobin** [comment]
Hm. So none of the messages you put in there -- all the "This is passport" things -- are showing up?

**Comment by beckybeauchamp1** [comment]
The only one is the console.log before return (null, user)

 it's -console.log("This is being returned from passport:" + user);

**Comment by beckybeauchamp1** [comment]
Hi Robin, I wanted to give you an update!

I changed my controller for users on sucessRedirect to "/currentuser" and
created a new route '/currentuser' which sends the json response for
current user and it was successful. It seems like it's working, but i'm
still confused about whats going on with the routes and and redirect

**Comment by RobertAKARobin** [comment]
Hey, I'm sorry, Becky -- got caught up planning Angular for next week.

I'm glad you got it! I'm not sure what you're confused about, though, since it seems like your redirect is working. Which behavior is unexpected?

**Comment by beckybeauchamp1** [comment]
I think I am confused since I had previously tried another route for the
redirect and it did not work, but that must be specific to our code. Thank
you so much for your help!
