### ISSUE TITLE
/Species, index page 

### ISSUE THREAD

**Issue by cconnerj** [ga-wdi-exercises/project3#468]
https://github.com/zonekid/Delmarvalous
work off the master branch
-------------------------
js/ng-views/specie_views/index.html

<div data-ng-repeat="specie in vm.species">
{{specie}}
</div>
------------------------
js/app.js

function CategoryShowControllerFunction (AnimalFactory, $stateParams){
  this.category = AnimalFactory.get({id: $stateParams.id})
  this.species = AnimalFactory.query()
}
-------------------------------
the above code is returning us with raw seed data, whenever we try to do {{specie.common_name}} it returns with nothing, i know we are missing something in our controller, but just cant figure out the logic of it.

**Comment by cconnerj** [comment]
sorry about that format dont know what happened 
our specie view page looks like this 

<div data-ng-repeat="specie in vm.species">
{{specie}}
</div>

**Comment by cconnerj** [comment]
sorry about the format, the carrots hid it for w/e reason, our species view index.html looks like

div data-ng-repeat="specie in vm.species"
{{specie}}
/div

**Comment by cconnerj** [comment]
ahhhh sorry we are working on the category show view page!! sorry for being all over the place, but its the same code

**Comment by AndyWhitley** [comment]
I'm testing it now. Is the problem with the index or show view?

**Comment by cconnerj** [comment]
the show view, we also are missing a "$" in stateParams, in the controller which we fixed

**Comment by AndyWhitley** [comment]
```js
function CategoryShowControllerFunction (AnimalFactory, $stateParams){
  this.category = AnimalFactory.get({id: $stateParams.id},() => {
    this.species = this.category.species
  })
}
```
