### ISSUE TITLE
seeding data for users

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project3#47]
I have the following code in my seed.js file regarding users:

```
var daniel = UserModel.new({
    email: "daniel@email.com",
    password: "password"
})
DashboardItem.create({
  partner_message: "Join us today!",
  partner_link: "www.facebook.com",
  city: "Chicago"
}).then(function(err, DashboardItem){
  daniel.dashboardItems.push(DashboardItem);
  daniel.save();
})
```

When I try to run "node seed.js" I get the following error: "TypeError: Invalid value for schema path `type`".  I have tried googling this error but have not found solutions.

**Comment by RobertAKARobin** [comment]
I think that's referring to a different part of your code. Is there a line number given with that error?

**Comment by dan-ator** [comment]
376

**Comment by RobertAKARobin** [comment]
Could you show the code around that line?

**Comment by dan-ator** [comment]
I don't have that many lines.  It is referencing something in the node modules, which for some reason is greyed out.  I did run npm install again just to be sure.

**Comment by RobertAKARobin** [comment]
Could you show the full text of the error?

**Comment by dan-ator** [comment]
```
/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:376
      throw new TypeError('Invalid value for schema path `' + prefix + key + '`');
      ^

TypeError: Invalid value for schema path `type`
    at Schema.add (/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:376:13)
    at new Schema (/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:93:10)
    at Function.Schema.interpretAsType (/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:561:25)
    at Schema.path (/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:499:29)
    at Schema.add (/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:394:12)
    at new Schema (/Users/danielalexander/wdi/projects/projectThree/Project3/node_modules/mongoose/lib/schema.js:93:10)
    at Object.<anonymous> (/Users/danielalexander/wdi/projects/projectThree/Project3/models/user.js:10:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/danielalexander/wdi/projects/projectThree/Project3/seed.js:8:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by dan-ator** [comment]
When I comment out my new code that I added, including `var User = require('./models/user');` it works to seed the other data that was already there.  So I gather it is something in `var User = require('./models/user');`.  But the path is right, I tried calling it UserModel also, and still got the error.

**Comment by dan-ator** [comment]
Ok the issue seems to have been that 'Id' was spelled 'ID' in the model.js file.  Now with this code:

```
var daniel = User.new({
    local : {
    email: "daniel@email.com",
    password: "password"
    }
});
DashboardItem.create({
  partner_message: "Join us today!",
  partner_link: "www.facebook.com",
  city: "Chicago"
}).then(function(err, DashboardItem){
  daniel.dashboardItems.push(DashboardItem);
  daniel.save();
})
```

I get error 

```
/Users/danielalexander/wdi/projects/projectThree/Project3/seed.js:25
var daniel = User.new({
                     ^

TypeError: User.new is not a function
```

**Comment by dan-ator** [comment]
and i defined the variable `var User = require('./models/user');`

**Comment by dan-ator** [comment]
Update: my seed file looks like this: 

```
var daniel = new User({
    local : {
    email: "daniel@email.com",
    password: "password"
    }
});
DashboardItem.create({
  partner_message: "Join us today!",
  partner_link: "www.facebook.com",
  city: "Chicago"
}).then(function(err, DashboardItem){
  daniel.dashboardItems.push(DashboardItem);
  daniel.save();
  console.log("DashboardItem");
})
```

and when I run 'node seed.js' there are no errors, but it isn't console.logging that message, so I don't think it is actually seeding.

**Comment by dan-ator** [comment]
I checked mongo and it is seeding a user, in fact many times doing that, but the dashboard item is empty string."{ "_id" : ObjectId("56672150e11c0f9afe4b6649"), "dashboardItem" : [ ], "local" : { "email" : "daniel@email.com", "password" : "password" }, "__v" : 0 }"

**Comment by jshawl** [comment]
in your promise, can you try logging both variables:

``` js
}).then(function(err, DashboardItem){
  daniel.dashboardItems.push(DashboardItem);
  daniel.save();
  console.log(err)
  console.log(DashboardItem); //notice missing quotes
})
```

**Comment by dan-ator** [comment]
Still neither gets logged.

**Comment by jshawl** [comment]
can you link to your repo? ill pul it down and check it out

**Comment by dan-ator** [comment]
https://github.com/dan-ator/Project3/tree/add_user

**Comment by jshawl** [comment]
dashboard items are being seeded to a different collection:

was able to verify by typing:

```
$ mongo
> use dan //the name of your mongo collection
> db.getCollectionNames()
> db.cities.find()
```

**Comment by dan-ator** [comment]
When I execute that last command I see all the cities but I don't see my dashboard item that I created.  The only collections are still "cities" "system.indexes" and "users".

**Comment by jshawl** [comment]
aren't the dashboard item and user one in the same? https://github.com/dan-ator/Project3/blob/5e52c21ee4c78e02a030b23d07585c80ef33f61c/seed.js#L8-L9

**Comment by dan-ator** [comment]
Well dashboard item is nested or referenced in user and they are defined in the same model file but they are different.

**Comment by jshawl** [comment]
In this file, you need to export two things, or create a separate file for dashboard item: https://github.com/dan-ator/Project3/blob/5e52c21ee4c78e02a030b23d07585c80ef33f61c/models/user.js

also check out https://github.com/ga-dc/tunr_mongo_oojs/blob/0618f5541a92c9cc5f2596a13ed29b61e8680e1c/db/seeds.js#L15-L16 for reference with respect to nested collections and separate model files.

Going to close this issue. Feel free to open a new one with a reference to this one!
