### ISSUE TITLE
nested resource show page 

### ISSUE THREAD

**Issue by Costle784** [ga-wdi-exercises/project3#470]
Hello, I'm having trouble getting the 'animal_show' page to render correctly. one location has many animals. when I hover over the link to the animal show from the location show page. I get `http://127.0.0.1:8080/#/locations//animals/`    So it's not picking up the location_id or the id.    

There's a rails error in the 'network' section in the dev tools inside of the locations_controller show method. This seems strange because i'm pretty sure it should be handled by the animals_controller show method within rails. I don't know where or how the rails controllers are activated from angular though. Any help would be great. Thanks

**Comment by juancgarcia** [comment]
Sounds like a few different issues might be happening here, let's deal with that link first.

Inside of your `ng-repeat` block, you're building a link to this animal with an `<a>` tag. Inside that tag is the `ui-sref` attribute containing the name of the angular state you want to visit. Something like this?:
```js
<div data-ng-repeat="animal in vm.location.animals">
    <a data-ui-sref="animalShow">{{animal.name}}</a>
</div>
```

A state name (`animalShow` in this example) can often be used all by itself in the `ui-sref` attribute, but if the state's url has named parameters (`url: "/places/:place_id/things/:id"`) you'll need to explicitly pass those values in an object literal (`thingShow({place_id: vm.place.id, id: thing.id})`), or they will be left blank when angular builds the url.

Passing a hash like this should get the urls rendering correctly:
```js
<a data-ui-sref="animalShow({id: animal.id, location_id: vm.location.id})">{{animal.name}}</a>
```

**Comment by Costle784** [comment]
Thanks Juan! Indeed, i wasn't passing the object literal. 
I'm now having trouble adding a new animal. Sorry to keep bothering you this evening.

here's my controller:
```js
.controller("AnimalNewController", [
    "AnimalFactory",
    AnimalNewControllerFunction
```

controller function: 
```js
function AnimalNewControllerFunction(AnimalFactory) {
    this.animal = new AnimalFactory();
    this.create = function() {
      this.animal.$save()
    }
  }
```

The rails error in the network dev tools is 'No route matches [POST] "/locations/animals"'     

Should I be passing 'Location Factory' or $stateParams to the AnimalNewControllerFunction?
Or is the problem in rails? 

```ruby
def create
    @location = Location.find(params[:location_id])
    @animal = @location.animals.create!(animal_params)
    render json: @animal
  end

  def new
    @location = Location.find(params[:location_id])
    @animal = @location.animals.new
    render json: @animal
  end
```

Thanks again

**Comment by juancgarcia** [comment]
This create/POST issue, is related to the how the previous link wasn't getting built out with your location or animal ids.

Inside your `AnimalNewControllerFunction`, `this.animal.$save()` is trying to build a POST url to send your data. It has is the resource url (`$resource("http://localhost:3000/locations/:location_id/animals/:id")`) but no ids to fill in the blanks.

Once again, you'll need to provide them to the method (`$save` in this case) by reading them from `$stateParams`.

As you suspected, you'll need to modify the `.controller` definition for AnimalNewController to include a dependency for `$stateParams`, and then add it to the function parameters in `AnimalNewControllerFunction`.

Once that plumbing is done, you'll be able to give the location_id to the save method like this:

```js
this.animal.$save({location_id: $stateParams.location_id})
```

**Comment by Costle784** [comment]
Thanks!
