### ISSUE TITLE
Making comment show

### ISSUE THREAD

**Issue by cconnerj** [ga-wdi-exercises/project3#471]
https://github.com/zonekid/Delmarvalous/
working on branch- "conner"

-i have one seed for the comment table with the species id and category id put in
-Im trying to get it to show up on http://localhost:8080/#/categories//species/11    (js/ng-views/specie_views/show.html) 

div data-ng-repeat= "comment in vm.specie.comments"
/div

-its showing up in the api on http://localhost:3000/comments.json 
-i only really need a commentfactory function to be able to show it right?

**Comment by juancgarcia** [comment]
There's a few ways to skin this cat. One way is with a comment factory to wrap an ngResource url like you're suggesting. But I think a simpler option to display existing comments is using `include` inside the `respond_to` of your rails api https://github.com/ga-wdi-lessons/rails-api#pro-tip-include.

In your specie show page, you already have an ng-repeat to loop `specie.comments`. Lets provide that list from the specie show route in rails:

```ruby
format.json { render json: @specie, include: :comments }
```

With that tiny change, you'll get a list of comments attached to your `specie` and then you can show them as usual:
```js
<div data-ng-repeat= "comment in vm.specie.comments">
    {{comment.content}}
</div>
```

**Comment by cconnerj** [comment]
so if i were to nest them, i wouldnt need the commentfactoryfucntion? im trying to wrap my head around this, so if we were to do full crud on comments we would be able to access and add comments to that nested file through the speciesfactoryfunction?

**Comment by cconnerj** [comment]
but if i was creating them i would need the commentfactory to have them all in one page, then that can be used to nest, then they can be called from the species def show include? sorry if i may not making any sense, having trouble with the concepts, I'm gonna be taking a token from john to understand it more
