### ISSUE TITLE
nested resource showing as an object

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project3#472]
hey guys - 
icck and i are trying to get our votes to show on our station pages.  (votes in nested inside station).  right now, we are getting back the entire object:
<img width="1146" alt="screen shot 2017-05-15 at 10 14 20 am" src="https://cloud.githubusercontent.com/assets/16961196/26061927/53166c4c-3957-11e7-8653-34c46a4e0d5c.png">

i have tried using the active model serializer 'except: []', but to no avail.

```js  
def show
    @station = Station.find(params[:station_id])
    @vote = Vote.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @vote, except: [:created_at, :updated_at]}
    end
  end
```

any thoughts?

**Comment by juancgarcia** [comment]
So I think you might not be targeting the right rails route. On your station page I imagine you'll want to see all votes and not just a single one.

There's two ways to handle this:

1. pass the `include` the votes association for `format.json` in StationsController show. https://github.com/ga-wdi-lessons/rails-api#pro-tip-include Then in your angular view, you'll be able to get votes via `vm.station.votes`

2. Create a new resource factory for votes `$resource("http://localhost:3000/stations/:id/votes")` and `.get` that list of votes in your station's show controller in angular:

```js
this.votes = VotesFactory.get({id: $stateParams.id});
```

and show it as usual:
```js
<div class="index" data-ng-repeat="vote in vm.votes">
  <p>{{vote.score}}</p>
</div>
```

**Comment by edawson1980** [comment]
cool, thank you.  we had tried both of those options before, with no success, but i think we were missing something on our end.
icck and ammar got it to work while i was at lunch..hopefully it sticks.
