### ISSUE TITLE
Edit comment show page

### ISSUE THREAD

**Issue by cconnerj** [ga-wdi-exercises/project3#474]
https://github.com/zonekid/Delmarvalous/
working branch "conner"

should be a quick one, my edit page (js/ng-views/comment_views/edit.html) will not show whats on the edit.html page

-I can get to the correct comment id page by clicking edit under the comment, but not even text will show
-my .state router function for commentEdit has the correct templateUrl
-Cant see whats wrong, the only error i get is a 404 which i think is nothing really

.state("commentEdit", {
  url: "/categories/:category_id/species/:species_id/comments/:id/edit",
  teplateUrl: "js/ng-views/comment_views/edit.html",
  controller: "CommentEditController",
  controllerAs: "vm"
})

**Comment by jsm13** [comment]
Does the header (`<h1>edit comment</h1>`) show up? A 404 on the favicon is fine but if the 404 is on the comment that would cause a problem

**Comment by cconnerj** [comment]
the header does not, its actually a GET 404 error, i realize it could be the rails controller bc thats commented out, but the fact that the text wasn't showing made me think that something else was wrong

**Comment by cconnerj** [comment]
angular.js:9866 GET http://localhost:3000/species/comments.json?id=23 404 (Not Found)

^^error on the- http://localhost:8080/#/categories//species//comments/23/edit

**Comment by jsm13** [comment]
What is the URL template string? This looks like it may be something like `http://localhost:3000/species/:species_id/comments.json` in which case you need to use `.get({species_id: $stateParams.speciesId})`

**Comment by cconnerj** [comment]
-the url template string is /categories/:category_id/species/:species_id/comments/:id/edit
-i tried changing it to /species/:species_id/comments.json 

- I added "this.comment = CommentFactory.get({species_id: $stateParams.speciesId})" to the CommentEditControllerFunction.... i did this to both urls, still running same error

**Comment by jsm13** [comment]
I was thinking getting all the comments (but that should have used `query` instead of `get` so `.query({species_id: $stateParams.speciesId})`. But you don't need that since you're getting all the comments back with the specie. For getting the individual comment, since you have the id and you have rails routes for comments at the top level you'll probably want the `commentsFactory` to use the `$resource(http://localhost:3000/comments/:id)`. You can then call `commentsFactory.get(id: comment_id)` << note I updated this adding `.get` to commentsFactory

**Comment by cconnerj** [comment]
-Yeahhh but that would break my code in the SpecieShowControllerFunction for creating comments, i realize i should be able to apply it, but dont know enough about whats going in the background

-when i try to call commentsFactory(id: comment_id) into that SpecieShowFunction it just runs more errors.... it was grabbing the species id from the factory function earlier

**Comment by jsm13** [comment]
I had a typo in the note above and updated `commentsFactory(id: comment_id)` to `commentsFactory.get(id: comment_id)`

**Comment by jsm13** [comment]
What I'd recommend doing to keep the specie show controller working is add a custom action `comment` to `specieFactory` (third argument to $resource should look like `{method: 'POST', url:'localhost:3000/species/:id/comments', isArray: true}`). This isArray needs to be there if your Rails app responds to this request with a collection (all the comments). After adding the custom action you can create a new comment by calling `speciesFactory.comment(params, comment)` where `params` is an object with the species id and comment is an object with the data for creating a comment

**Comment by cconnerj** [comment]
-so this is all with the commentFactory  using http://localhost:3000/comments.json?
-and would i have to put "comment: {method: 'POST', url:'localhost:3000/species/:id/comments', isArray: true}" into the third argument of specieFactory correct? or no "comment:" before it

**Comment by jsm13** [comment]
- commentFactory should use `http://localhost:3000/comments/:id.json` (if you don't provide an id, e.g. `commentFactory.query()` it will make the request to `localhost:3000/comments` but you need the id for when posting or getting a specific comment
- you would need to put `{comment: {method: 'POST', url:'localhost:3000/species/:id/comments', isArray: true}}` as the third argument to **`$resource(url, paramDefaults, actions)`** when you call that inside of `specieFactoryFunction` (currently just has the `url`, and `paramDefaults` should just be an empty object)

**Comment by cconnerj** [comment]
Ok i believe i got most of it down up to this part

 "After adding the custom action you can create a new comment by calling speciesFactory.comment(params, comment) where params is an object with the species id and comment is an object with the data for creating a comment"


I know i have to apply it to the SpeciesShowControllerFunction, and i replace that with the CommentFactory(well maybe not since its adding to the api) since it isn't grabbing the species id from that anymore... so i should put 

"let comment = new SpecieFactory(params, comment)"


im sorry but i cannot follow this well, we may have to use another token tomorrow morning
