### ISSUE TITLE
1. accessing parent properties in ng-repeat. 2. refreshing the display after redirect. 

### ISSUE THREAD

**Issue by Costle784** [ga-wdi-exercises/project3#475]
1. Hello I'd like to display an animals location address on the animal index page. I've tried animal.location and many other things. $parent supposedly gives access to parent properties, but doesn't seem to work. 

`<div ng-repeat = "animal in vm.animals">
  <h1><a ui-sref="animalShow({id: animal.id, location_id: animal.location_id})">{{animal.name}}</a></h1>
  <h2>{{$parent.location.address}}</h2>
  <p><img ng-src={{animal.photo_url}}></p>
  <hr>
</div>`

2. Our redirects are all working using $locationProvider. It does not however reflect the updates made to the database unless you reload the page. It would be nice to have this dynamically done if possible. Thanks!!

**Comment by Costle784** [comment]
Sorry, here's the code for #1.

<div ng-repeat = "animal in vm.animals">
  <h1><a ui-sref="animalShow({id: animal.id, location_id: animal.location_id})">{{animal.name}}</a></h1>
  <h2>{{$parent.location.address}}</h2>
  <p><img ng-src={{animal.photo_url}}></p>
  <hr>
</div>

**Comment by Costle784** [comment]
and it still didn't work

**Comment by Costle784** [comment]
`<div ng-repeat = "animal in vm.animals">
  <h1><a ui-sref="animalShow({id: animal.id, location_id: animal.location_id})">{{animal.name}}</a></h1>
  <h2>{{$parent.location.address}}</h2>
  <p><img ng-src={{animal.photo_url}}></p>
  <hr>
</div>`

**Comment by Costle784** [comment]
weird

**Comment by jsm13** [comment]
`$parent` gives access to the scopes parent (if there is a controller within a controller, let's you get at the parent controller. [docs here](https://docs.angularjs.org/api/ng/type/$rootScope.Scope)) Generally, I'd advise against this approach and consider it more of an escape hatch. If you need to share information between controllers, it's best to put that into a service which is injected into both. Not totally sure what you mean by parent properties

**Comment by jsm13** [comment]
As far as keeping the app up to date with the db, you'll need to update the state of the app after you make any changes in the `.then(...)` block of the resource method.

**Comment by Costle784** [comment]
Thanks John. We have two models for our animal adoption project. One 'location' has many 'animals'. However, we have a separate animal index (a list of just animals) on which we'd also like to print the location that owns the animal. For this, i was trying to access the animal's parent (location) "address" attribute.

Any chance you could give a code snippet for syntax regarding the .then()? Does it involve passing the $state? Not sure exactly where to put this code. Thanks again

**Comment by juancgarcia** [comment]
For the `animals.location` display, have you updated your AnimalsController.index to use the `include` property inside of your json renderer?

Also you mentioned having edit/new forms that you'd like to display the results in angular without hard-refreshing your page. Can you give some more info on that and link to the view(s) and app.js line number for the controller function? We'll have a better chance at directing you to the best approach.

**Comment by Costle784** [comment]
i added `include` and it worked. Thanks!   

As you mentioned one needs to refresh the page manually after an update in order for the data to change. We've got the url and the view changing correctly. 
controllers:

```js
.controller("AnimalNewController", [
    "AnimalLocationFactory",
    "$stateParams",
    "$location",
    AnimalNewControllerFunction
  ])
```
```js
.controller("AnimalEditController", [
    "AnimalLocationFactory",
    "$stateParams",
    "$location",
    AnimalEditControllerFunction
  ])
```

functions:

```js
function AnimalNewControllerFunction(AnimalLocationFactory, $stateParams, $location) {
    this.animal = new AnimalLocationFactory();
    this.create = function() {
      this.animal.$save({location_id: $stateParams.location_id})
      $location.path('/locations/' + $stateParams.location_id)
    }
  }
```

```js
function AnimalEditControllerFunction(AnimalLocationFactory, $stateParams, $location) {
    this.animal = AnimalLocationFactory.get({location_id: $stateParams.location_id, id: $stateParams.id})
    this.update = function(){
      this.animal.$update({location_id: $stateParams.location_id, id: $stateParams.id});
      $location.path('/locations/' + $stateParams.location_id + '/animals/' + $stateParams.id)
    }
    this.destroy = function(){
      this.animal.$delete({location_id: $stateParams.location_id, id: $stateParams.id})
      $location.path('/locations/' + $stateParams.location_id)
    }
  }
```

**Comment by juancgarcia** [comment]
I was going to suggest another option, but I think there's an easier solution here.

You're redirecting with `$location.path()` just after calling the $save/$update/$delete methods. But since those methods are asynchronous, the update (or save or delete) hasn't necessarily finished before you do the redirect. So in the location show page you're getting the original location and animals data.

We can simply wait for the update/save/delete methods to finish before redirecting, by passing a callback function as a second argument to the `$` methods.

Here's an example for `$save`:

```js
this.animal.$save({location_id: $stateParams.location_id}, ()=>{
    $location.path('/locations/' + $stateParams.location_id)
})
```
