### ISSUE TITLE
issue with edit url navigation

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project3#477]
we are having a problem with our edit path.  we can click on a particular comment to edit, from the station show view, but the station_id and vote_id are missing in the resulting url.
 so we are unable to target a specific vote.

**Comment by jsm13** [comment]
the [s-ref directive](https://github.com/angular-ui/ui-router/wiki/quick-reference#ui-sref) needs to be passed all of the necessary path parameters. So if the state looks something like:

```javascript
$stateProvider.state({
  name: 'commentEdit',
  url: '/station/:station_id/vote/:vote_id/comment/:id',
  ...
});
```
Then the link in the station show page should look something along the lines of 
```
<a s-ref='commentEdit({station_id: vm.station.id, vote_id: vote.id, id: comment.id})'> Edit comment </a>
```
