### ISSUE TITLE
problems with search button and user authentication

### ISSUE THREAD

**Issue by MohamedGood** [ga-wdi-exercises/project3#48]
We have a few buttons on are index page that do not work.

And we need help coding are login, signup pages and other authentication functionalities.

**Comment by RobertAKARobin** [comment]
What do you mean they do not work? Do you get an error? If so, could you show the error?

**Comment by MohamedGood** [comment]
![screen shot 2015-12-08 at 12 49 22 pm](https://cloud.githubusercontent.com/assets/15020378/11663438/394b0a2e-9daa-11e5-8bc7-7104e3940615.png)
this is the error page that loads when you click on the signup button

**Comment by RobertAKARobin** [comment]
Cool. Do you have a route defined for your navbar? It would be `app.get("/navbar")` or something similar.

**Comment by MohamedGood** [comment]
let me check that out, Might of forgot to add that in

**Comment by amaseda** [comment]
Going to close this one since it's been inactive for a bit, but feel free to reopen if you have additional questions.

**Comment by MohamedGood** [comment]
I added the app.get("/navbar"
It didnt change anything
