### ISSUE TITLE
Group 3 error seeding data

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/project3#495]
We are using  ```t.text :type, array: true``` in our model and trying to seed an array. We are using postgresql that allows arrays as data types. What can we modify to keep arrays in the seed data?

Seed Data Example:
```nancy = Sitter.create(name: "Nancy Price", photo_url: "https://pbs.twimg.com/profile_images/467092443/fp_1713383_jennifer_aniston_shares_a_smile_with_the_photographers.0.0.0x0.400x633.jpeg", phone: "1223", email: "nancy@goote.com", start_date: "2017-6-30 9:45", end_date: "2017-7-02 12:30", zipcode: 22182, type: ["dog", "cat", "reptiles", "birds"], price: 50, service: ["boarding", "drop-in"]);```

Terminal Error:
```rails aborted!
TypeError: no implicit conversion of Array into String
/Users/scotty_pierce/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/inflector/methods.rb:269:in `const_get'
/Users/scotty_pierce/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.1/lib/active_support/inflector/methods.rb:269:in `block in constantize'```

**Comment by amaseda** [comment]
Not sure if this is the cause of the problem, but you cannot have a column called `type` since that is a reserved word in ActiveRecord. Can you rename the column, re-run your migrations and see if the error persists?

**Comment by amaseda** [comment]
@scottpiercew Were you able to make any progress on this issue?

**Comment by scottpiercew** [comment]
We were able to move past the issue. Thank you.

**Comment by amaseda** [comment]
:+1:
