### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/project3#496]
Currently getting "landing.html" before the hashtag in the URI. How can I ensure the browser is reading the routes and not my file structure? 
ex. localhost:8080/landing.html#/sitters

<img width="427" alt="screen shot 2017-06-26 at 1 57 28 pm" src="https://user-images.githubusercontent.com/28062032/27553016-6c72dc84-5a77-11e7-9903-05b9c4cf2562.png">

**Comment by amaseda** [comment]
Make sure you're running `hs` from the directory that contains the main `index.html` file. Does that change anything?

**Comment by scottpiercew** [comment]
```hs``` is running in the correct directory. I'm able to navigate through my whole directory structure in the browser. When clicking through ng-views I can see each view displayed with all of the correct information.

**Comment by amaseda** [comment]
What files are in your current directory?

**Comment by scottpiercew** [comment]
landing.html and js

**Comment by amaseda** [comment]
`hs` looks for a file called `index.html` so you'll need to change that filename.

**Comment by scottpiercew** [comment]
That fixed the problem. Looks like everything is running normally now. Thanks.

**Comment by amaseda** [comment]
:+1:
