### ISSUE TITLE
Trouble passing owner_id into new pet form

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/project3#497]
Our current code to include the ```owner_id```. ```<p><a data-ui-sref="petNew({id: pet.owner_id})">Add Pet</a></p>``` This is in the owner show view and links to the pet new view (form). How can we ensure the ```owner_id``` is included? 
The url before clicking on add pet includes the ```owner_id```.
<img width="326" alt="screen shot 2017-06-27 at 9 05 50 am" src="https://user-images.githubusercontent.com/28062032/27589325-0d482802-5b19-11e7-8b17-3cbc702cfdac.png">

After clicking add pet the ```owner_id``` is missing.
<img width="407" alt="screen shot 2017-06-27 at 9 06 17 am" src="https://user-images.githubusercontent.com/28062032/27589361-266d3980-5b19-11e7-969a-6b7aa7fb7b7b.png">

This is the error we are getting in the browser, after clicking the create button.
<img width="927" alt="screen shot 2017-06-27 at 9 09 39 am" src="https://user-images.githubusercontent.com/28062032/27589373-329d67f2-5b19-11e7-9f83-b2fc476aea04.png">

**Comment by amaseda** [comment]
What does the link for "Add Pet" (i.e., `<a ui-sref="...">Add Pet</a>`) look like?

**Comment by amaseda** [comment]
What does the JSON for each pet look like? Does it definitely have an `owner_id`?

**Comment by amaseda** [comment]
Also do you have access to a local variable `pet` where you're creating the link? Or does it need to be `vm.pet`?

**Comment by scottpiercew** [comment]
```<p><a data-ui-sref="petNew({id: pet.owner_id})">Add Pet</a></p>```

<img width="427" alt="screen shot 2017-06-27 at 9 31 38 am" src="https://user-images.githubusercontent.com/28062032/27590081-8165650e-5b1b-11e7-9d90-30d6f0373fbb.png">

**Comment by amaseda** [comment]
One more question: what does the state definition for `petNew` look like?

**Comment by scottpiercew** [comment]
We have tried vm.pet and gotten the same result. Here is our .state and function.
```
.state("petNew", {
      url: "/owners/:id/pets/new",
      templateUrl: "js/ng-views/pets/new.html",
      controller: "PetNewController",
      controllerAs: "vm"
    })
```
```
function PetNewControllerFunction(PetSitterOwnerShowFactory){
    this.pet = new PetSitterOwnerShowFactory();
    this.create = function(){
      this.pet.$save()
    }
  }
```

**Comment by scottpiercew** [comment]
```.state("petNew", {
      url: "/owners/:id/pets/new",
      templateUrl: "js/ng-views/pets/new.html",
      controller: "PetNewController",
      controllerAs: "vm"
    })```

**Comment by scottpiercew** [comment]
```
.state("petNew", {
      url: "/owners/:id/pets/new",
      templateUrl: "js/ng-views/pets/new.html",
      controller: "PetNewController",
      controllerAs: "vm"
    })
```

**Comment by amaseda** [comment]
What about the controller and view for the owner show page? The issue is probably there since the new page's URL is not populating correctly.

**Comment by scottpiercew** [comment]
Owner's Show Page
```
<h1>Owner's Profile</h1>
<p>{{vm.owner.name}}</p>
<p>{{vm.owner.phone}}</p>
<p>{{vm.owner.email}}</p>

<h1>Pet's Profile</h1>
<p><a data-ui-sref="petNew({id: vm.pet.owner_id})">Add Pet</a></p>
<div data-ng-repeat="pet in vm.owner.pets">
  <p>{{pet.name}}</p>
</div>
```

**Comment by scottpiercew** [comment]
Owner's Show Controller
```
.controller("OwnersShowController", [
    "$stateParams",
    "PetSitterOwnerShowFactory",
    PetSittersOwnersShowControllerFunction
  ])
```

**Comment by amaseda** [comment]
Can you show me the controller function as well?

**Comment by scottpiercew** [comment]
Owner's Show Controller Function
``` js
 function PetSittersOwnersShowControllerFunction($stateParams, PetSitterOwnerShowFactory) {
    this.owner = PetSitterOwnerShowFactory.get({id: $stateParams.id})
  }
```

**Comment by amaseda** [comment]
Ok so the issue is most likely because you were trying to reference `pet` outside of the `ng-repeat`. So if you want the link to populate properly, you need to move it inside of `ng-repeat`.

Otherwise, if you want to use the `vm.pet` approach, you would need to define that value inside of your show controller function. But because the page will have multiple pets, this probably is not the ideal approach.

**Comment by scottpiercew** [comment]
We moved pet inside ng-repeat. In the rails server, we are getting the below POST request error:

Started POST "/owners" for 127.0.0.1 at 2017-06-27 10:01:50 -0400
Processing by OwnersController#create as HTML
  Parameters: {"name"=>"New", "pet_type"=>"Dog", "photo_url"=>"https://images.pexels.com/photos/26348/pexels-photo.jpg?h=350&auto=compress&cs=tinysrgb", "zipcode"=>"20009", "medical_needs"=>"false", "start_date"=>"2017-8-01 9:00", "end_date"=>"2017-8-20 12:30", "owner"=>{"name"=>"New", "photo_url"=>"https://images.pexels.com/photos/26348/pexels-photo.jpg?h=350&auto=compress&cs=tinysrgb"}}
  Owner Load (0.2ms)  SELECT  "owners".* FROM "owners" WHERE "owners"."id" = $1 LIMIT $2  [["id", nil], ["LIMIT", 1]]
Completed 404 Not Found in 1ms (ActiveRecord: 0.2ms)


**ActiveRecord::RecordNotFound (Couldn't find Owner with 'id'=):**

app/controllers/owners_controller.rb:20:in `create'

and this error in the browser:
<img width="927" alt="screen shot 2017-06-27 at 9 09 39 am" src="https://user-images.githubusercontent.com/28062032/27591612-3417d142-5b20-11e7-9444-b2410194b564.png">

**Comment by amaseda** [comment]
What does your owners controller look like?

**Comment by scottpiercew** [comment]
Owner's Controller in Rails
```rb
def new
    @owner = Owner.find(params[:owner_id])
    @pet = @owner.pets.new
  end

  def create
    @owner = Owner.find(params[:owner_id])
    @pet = @owner.pets.create!(pet_params)

    respond_to do |format|
      if @pet.save!
        format.html { redirect_to @owner, notice: 'Your pet was successfully added.' }
        format.json { render json: @owner, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def pet_params
    params.require(:pet).permit(:name, :pet_type, :photo_url, :zipcode, :medical_needs, :start_date, :end_date, :owner_id)
  end
```

**Comment by amaseda** [comment]
The path for owners#create (i.e., `/owners`) is not going to have an owner id in it, so `Onwer.find(params[:owner_id])` is going to error out. 

This controller action is intended to create an owner. But it seems like you're trying to create a pet, so I don't think this is the route/action you want to be hitting. Would expect it to be `pets#create`.

**Comment by scottpiercew** [comment]
We originally had the new and create function in the pets controller. We get the same error message with the code in either controller.

**Comment by scottpiercew** [comment]
It looks like we are not hitting the rails functions. We think the problem in on the Angular side.

**Comment by amaseda** [comment]
You're hitting `owners#create` right now, so the request is definitely hitting your Rails back-end.

If you need to pull `owner_id` from the URL on the back-end, you don't want to be hitting `owners#create`.

Try hitting `pets#create` and let me know what the error is.

**Comment by superbuggy** [comment]
You can also log to the terminal window where you have your rails server running with...
```rb
puts "=" * 60
puts "in create"
puts "=" * 60
```

**Comment by scottpiercew** [comment]
We were able to get the error to change to ```owners/pets``` but not ```owners/:owner_id/pets```

<img width="925" alt="screen shot 2017-06-27 at 10 32 50 am" src="https://user-images.githubusercontent.com/28062032/27593150-61848f2c-5b24-11e7-88f6-d7858b43680d.png">

```js
.controller("PetNewController", [
  "$state",
  "CreatePetFactory",
  PetNewControllerFunction
  ])

  .factory("CreatePetFactory", [
    "$resource",
    FactoryCreatePetFunc
  ])

.state("petNew", {
      url: "/owners/:id/pets/new",
      templateUrl: "js/ng-views/pets/new.html",
      controller: "PetNewController",
      controllerAs: "vm"
    })

function FactoryCreatePetFunc($resource) {
    return $resource("http://localhost:3000/owners/:owner_id/pets");
  }

  function PetNewControllerFunction($state, CreatePetFactory){
    this.pet = new CreatePetFactory();
    this.create = function(){
      this.pet.$save()
    }
  }
```

**Comment by superbuggy** [comment]
It seems likely that you are passing an param for an owner somewhere in your angular code.

**Comment by amaseda** [comment]
Looks like you're missing owner id in the link again. When calling `.$save` you need to make sure you indicate the specific owner whose pet you are updating.

Try `this.pet.$save({owner_id: INSERT OWNER ID HERE})`

**Comment by superbuggy** [comment]
Is the `petNew` state for showing a form for creating a new pet?

`<p><a data-ui-sref="petNew({id: pet.owner_id})">Add Pet</a></p>`

In that case, `pet.owner_id` may be `undefined`.

**Comment by scottpiercew** [comment]
Gentlemen, the problem has been solved by passing in the owner_id with $stateparams. We successfully created a new pet that belongs to an owner.

Thank you,
Group 3

**Comment by superbuggy** [comment]
SICK!

**Comment by amaseda** [comment]
:+1:
