### ISSUE TITLE
Problem removing blank option from dropdown and getting user selection to be displayed.

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/project3#498]
We are using the following code to accomplish our search feature with a drop-down menu. 
1. How can we remove the initial blank space or hard code an initial view in the dropdown?
2. After the user selects an item from the dropdown, how do we get the dropdown to display the user's pick?

The ```ng-select``` dropdown item gets binded to the ```input``` and that is filtered in the ```ng-repeat```.

```<input type="text" data-ng-model="vm.byPetType">

    <select ng-model="vm.byPetType">
      <option ng-selected="vm.byPetType" ng-repeat="pet in vm.pets | unique: 'pet_type'" ng-value="vm.pet_type">{{pet.pet_type}}</option>
    </select>

<div class="sitters_wrapper" data-ng-repeat="pet in vm.pets | filter: {pet_type: vm.byPetType} | filter: {zipcode: vm.byZipcode} | filter: {x: vm.petType} | filter: {medical_needs: vm.byMedication}">
```

**Comment by amaseda** [comment]
What does the corresponding controller function look like?

**Comment by scottpiercew** [comment]
```function PetSittersOwnersControllerFunction(PetSitterOwnerFactory) {
    this.pets = PetSitterOwnerFactory.query()
  }```

**Comment by scottpiercew** [comment]
```
function PetSittersOwnersControllerFunction(PetSitterOwnerFactory) {
    this.pets = PetSitterOwnerFactory.query()
  }
```

**Comment by amaseda** [comment]
So I haven't used `ng-selected` before, but the documentation says that you should **NOT** use both `ng-model` on `<select>` and `ng-selected` on the `<option>` at the same time.

https://docs.angularjs.org/api/ng/directive/ngSelected

Going to keep looking into it but see if removing one solves this.

**Comment by scottpiercew** [comment]
We choose to use ng-selected instead of ng-options because with ng-selected we were able to bind the user selection to ```<input type="text" data-ng-model="vm.byPetType">``` which produced our filtered results.

**Comment by amaseda** [comment]
That's fine to not use `ng-options` – the `ng-options` documentation says you can get the job done with `ng-repeat`: https://docs.angularjs.org/api/ng/directive/ngOptions

But the `ng-selected` documentation says you should not use both it and `ng-model`: https://docs.angularjs.org/api/ng/directive/ngSelected

What happens when you remove `ng-model`?

**Comment by scottpiercew** [comment]
We removed ```ng-selected``` and that keeps the user selection displayed! Thanks.
```
    <select ng-model="vm.byPetType">
      <option ng-repeat="pet in vm.pets | unique: 'pet_type'" ng-value="vm.pet_type">{{pet.pet_type}}</option>
    </select>
```

**Comment by amaseda** [comment]
Oh, cool! :+1:

**Comment by scottpiercew** [comment]
Removing ```ng-model``` also removed the binding to the input.
