### ISSUE TITLE
unsolved issue

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project3#50]
```
var request=require('request');
var env=require('../env');


function home(req, res){

  var info;
  request("http://api.nytimes.com/svc/elections/us/v3/finances/2016/president/totals.json?api-key="+env.api_key+"", function(error, response, body){
    if(!error && response.statusCode ==200){
      var candidates=[];
      // info=body;
      candidates.push(response.body.results);
      console.log(candidates);
      // console.log(info.results);
      // console.log(candidates);
      res.render('./candidates/index', {candidates});
    }
  });

  // for(var i=0; i<candidates.length; i++){

  // }
}

module.exports = {
  home: home
}
```

unless you pass down body in request function, it shows as undefined.

**Comment by jshawl** [comment]
sorry what is the issue?

**Comment by onesick** [comment]
console.log(body);
prints the data I get back from the URL.
with the data I get back, I cannot manipulate them. EX) within the data I get there's a key-value with a key called results. So I want to get this data and type body.results, which would return undefined

**Comment by onesick** [comment]
And also, it looks like require(){
//code
}
is getting executed after all the codes are executed. Can you please help me understand why is this?

**Comment by amaseda** [comment]
@onesick Can you link to your repo and specify which branch contains this code? Thanks.

**Comment by onesick** [comment]
https://github.com/onesick/campaign-finance/tree/wonsik_apiConnect

it's it wonsik_apiConnect branch. Thank you

**Comment by jshawl** [comment]
comin to find you cause I dont have a key and it took me more than 5 mins to set up - giving up set up locally

**Comment by jshawl** [comment]
Actually you're in a class right now and should be paying attention to that class. Feel free to open an issue when you're not in class

**Comment by onesick** [comment]
yeah tnx jesse
