### ISSUE TITLE
"Access-Control-Allow-Origin" Error.

### ISSUE THREAD

**Issue by BaoPham92** [ga-wdi-exercises/project3#500]
<img width="241" alt="screen shot 2017-06-28 at 8 20 14 pm" src="https://user-images.githubusercontent.com/26471655/27666074-4ec58f96-5c3f-11e7-96b7-536dd2665387.png">

Hello instructors of WDI16! 

I have recently been running into a rather irritating error that has prevented me from seeing any further changes in our project. 

I have tried:

- Google with multiple searches.
- Create a back-up/resetting and pulling from main repo directory.
- adding a '~> *' to the 'rack-cors' line in the gemfile.
- reconfigure with db commands.
- asking team members for advice.

-------------------------------------------------------------------------

This is an error appearing on multiple pages of the front-end angular file, and with multiple similar errors on a few of the pages at times.

**Comment by amaseda** [comment]
If you're using [rack-cors](https://github.com/cyu/rack-cors), have you...

1. Included it in your Gemfile [per the documentation](https://github.com/cyu/rack-cors#installation)?
2. Then run `bundle install`?
3. Added the Rails 5 section of [the code referenced in the documentation](https://github.com/cyu/rack-cors#rails-configuration) to the `application.rb` file of your Rails API?

**Comment by BaoPham92** [comment]
I appreciate the response! 

I have attempted,  all of the following whilst going over the pages with my partner Rob over voice chat making sure I am following the directions as stated. 

We agreed to use a token for this matter tomorrow, I will see you soon!

**Comment by amaseda** [comment]
Gotcha. In the meantime, push up your code and link to the relevant repo/branch and I can take a look.
