### ISSUE TITLE
Issue with passing the information from our app.js into the slider

### ISSUE THREAD

**Issue by scottpiercew** [ga-wdi-exercises/project3#501]
We are trying to implement angularjs-slider and are having difficulty passing the 150 number into the slider. We have included the CDNs and rzModule in our app.
Source: https://www.npmjs.com/package/angularjs-slider

In the controller:
``` 
 function PetSittersControllerFunction(PetSitterFactory) {
    this.sitters = PetSitterFactory.query()
    this.priceSlider = 150;
  }
```
In the html:
```
    <div>
      <rzslider rz-slider-model="priceSlider" ng-model="vm.byPrice" ng-value="vm.price">
      </rzslider>
    </div>
```

Currently using the below code to create a slider bar for price ranges but, would like to change it to angularjs-slider.
``` 
   <input type="range" value="30" min="10" max="90" step="5" list="tickmarks" ng-model="vm.byPrice" ng-value="vm.price"/>
    <datalist id="tickmarks">
      <option value="0">
      <option value="10">
      <option value="20">
      <option value="30">
      <option value="40">
      <option value="50">
      <option value="60">
      <option value="70">
      <option value="80">
      <option value="90">
      <option value="100">
    </datalist>
```

**Comment by amaseda** [comment]
Do you have any particular questions about this? Unfortunately I have not used `angularjs-slider` so I can't recommend any strategies for implementing it. If you try implementing it and receive an error, however, happy to try troubleshooting it together from there.

**Comment by superbuggy** [comment]
you may have to set the min and max on the javascript side...

```js
    $scope.minRangeSlider = {
        minValue: 10,
        maxValue: 90,
        options: {
            floor: 0,
            ceil: 100,
            step: 1
        }
    };
```

**Comment by scottpiercew** [comment]
The css is showing the slider bar. Ideally, this is the code we want to use. We don't get an error but none of the values are from the controller function are passed into the html.

```
this.slider = {
    minValue: 10,
    maxValue: 90,
    options: {
        floor: 0,
        ceil: 100,
        step: 1
    }
};

<rzslider rz-slider-model="slider.minValue"
          rz-slider-high="slider.maxValue"
          rz-slider-options="slider.options"></rzslider>
```

**Comment by amaseda** [comment]
Should you be saying `vm.slider` instead of `slider`?

**Comment by scottpiercew** [comment]
```vm.slider``` fixed the communication error. Do you know of a min max angular filter? I'm searching for one before builing a custom filter.

**Comment by amaseda** [comment]
Not aware of a filter that can be used with this. If you're going to use this external plug-in, would recommend following whatever their documentation says. If there's nothing, see what Google turns up!

**Comment by scottpiercew** [comment]
Okay, thanks.

**Comment by superbuggy** [comment]
Do you mean directive-attributes? 

https://www.npmjs.com/package/angularjs-slider#directive-attributes

**Comment by scottpiercew** [comment]
directive-attributes are what we are using and gives a min and max value. The ng-repeat filter expects a single value to filter by. I'm searching for a filter that can filter numbers out not between the min and max range.

**Comment by superbuggy** [comment]
If the numbers are stored in an array, you could use [.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).
