### ISSUE TITLE
ng-show page issue

### ISSUE THREAD

**Issue by tedlayea** [ga-wdi-exercises/project3#502]
The index page works fine for ng-resource,
![showpageissue](https://user-images.githubusercontent.com/27984226/27691288-92f6651a-5cb1-11e7-8513-bb8be86c6378.png)
 but not for show page. I log and check it's getting the id. But getting the data has some issue.

**Comment by amaseda** [comment]
- What error are you getting for show page (if you have one)?
- How do you know it's not working?
- Take a look at the terminal window that's running your Rails API. Does it look like it received a request? If so, what kind?

**Comment by tedlayea** [comment]
It's funny, I was trying to solve it for more than 1hr but when you just left I found the error. I didn`t add controllerAs: "vm". But thanks

**Comment by amaseda** [comment]
:+1:
