### ISSUE TITLE
Project 3 Ideas 

### ISSUE THREAD

**Issue by mitcheguevara** [ga-wdi-exercises/project3#503]
1. An app that blurts "Shame! Shame! Shame!" during class hours,  when ever you pick up your phone.
2. An app that tracks the stock market based on trumps tweets.
3. An app that tracks flight prices when disaster strikes at the desired destination.

**Comment by preese13** [comment]
Neckflicks:  Netflicks for ties.

**Comment by lizardbird** [comment]
1. An app that identifies where all confederate statues are currently standing
2. An app that translates Angular documentation into plain English
3. An app that answers "Can I park here?" for the DC area

**Comment by jessamarie** [comment]
My team gets 1!
