### ISSUE TITLE
implementing current user options without handlebars 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#51]
We are using one index.html page and can't figure out how to implement the current user option and have an if statement where options are hidden if the user is not signed in. We've gone through the class curriculum but it seems to only apply if you use hbs.  We tried to convert our index.html to .hbs just to see if it would work, but that seems to break other things.  

We have passport implemented, so the user can signup and login but since that causes a full page refresh we can't figure out how to keep options hidden after login.  

Thanks

**Comment by amaseda** [comment]
You can still have a single page application and use an `.hbs` file as that page. If it's just `.html` then you can't make use of if-statements in your server-side view.

If you link to the script tags that are responsible for front-end functionality from your `index.hbs`, then you'll still have that SPA functionality.

Let me know if I can clarify that further!

**Comment by joe-gz** [comment]
@amaseda on that note, I'm working on converting html to hbs, but having a small issue.  I've changed the file to .hbs, and changed the below code to account for that.  The page loks fine until i add in the actual {{}} code in the hbs file, and then it refreshes showing literally just my source code.. Have you ever seen anything like that?

in my index.js file I have
 `app.set('view engine', 'hbs');
app.set("views","./public/html");`
and my route should render index.hbs:
`app.get('/', function(req, res){
  res.sendFile(__dirname + '/public/html/index.hbs')
})`

**Comment by amaseda** [comment]
@joe-gz Does the same thing happen if you render the view like so: `res.render( "index.hbs" )`?

**Comment by joe-gz** [comment]
oof, that works perfectly.. haha thank you!!

**Comment by RobertAKARobin** [comment]
Make sure to close the issue if you're good to go!

**Comment by joe-gz** [comment]
Oops, sorry! done.

**Comment by joe-gz** [comment]
when Alea comes back since this is hers.. sorry again haha

**Comment by amaseda** [comment]
@ScreenName4eva Let me know if you have any additional questions on this issue. If not, go ahead and close it. Thx!
