### ISSUE TITLE
Matt's App Ideas

### ISSUE THREAD

**Issue by mattcfilbert** [ga-wdi-exercises/project3#516]
1. An app that gives you updates on the sports (and/or teams?) of your choosing without ESPN level spam.

2. Tutors in various subjects connecting with potential students.

3. Fight Club: The App: The Musical

**Comment by jessamarie** [comment]
Could I earn money off 2?

**Comment by mattcfilbert** [comment]
Tutors have to pay for the privilege of teaching

**Comment by jessamarie** [comment]
Who said I wanted to be a tutor?

**Comment by mattcfilbert** [comment]
Students pay double

**Comment by jessamarie** [comment]
Who said I wanted to be a student?
