### ISSUE TITLE
Project 3 ideas

### ISSUE THREAD

**Issue by jdpolakoff** [ga-wdi-exercises/project3#517]
1) A site that displays the ingredients in a restaurant's kitchen and could be updated dynamically. Could be used as an inventory service.

2) Fitness-tracker. An app that lets users make fitness profiles and view other users' fitness profiles.

**Comment by jessamarie** [comment]
I think 1 is an excellent idea to realistically help restaurants! Most employees have to do this on paper at the end of the day usually.
