### ISSUE TITLE
Group 2 question: External API calling and Rails API

### ISSUE THREAD

**Issue by cwcox** [ga-wdi-exercises/project3#520]
Our app will associate pictures from Flickr with the words in sentences/tweets provided by the user.

We would like to query the flickr and twitter APIs only when a user inputs a new search.  Therefore the database will be populated over time as searches happen.  The angular front end will then query the Rails API to retrieve the results of the external API queries.

Path:  User Input (angular) -> external api call (rails) -> save api response to DB (rails) -> display results (angular call to the rails api)

Does this satisfy the project requirement of use the Rails API to drive the app?

**Comment by juancgarcia** [comment]
`Does this satisfy the project requirement of use the Rails API to drive the app?`

Not exactly.

Your intended usage path for search doesn't seem to ever really hit the DB directly.

If, however you have a "history" view (perhaps on the index) to show these previously cached results then that will satisfy the Rails API requirement so long as this data uses your minimum 2 models.

**Comment by cwcox** [comment]
We were planning on doing that history view, and in a more advanced version allowing people to guess the tweet/phrase based on a set of photos.  That would be retrieved from the DB.
