### ISSUE TITLE
Group 3: AngularJS External API Issue

### ISSUE THREAD

**Issue by jessamarie** [ga-wdi-exercises/project3#521]
Problem Link: https://github.com/jessamarie/this-day-in-history/blob/master/js/app.js#L28-L44

**Problem**

I am trying to get data from this api: http://history.muffinlabs.com/date/:month/:date

Ex: http://history.muffinlabs.com/date/9/12

**I tried**

I was using $resource, but that returned a cross-origin error. Googling the issue, I have found multiple sources (like this one)[https://stackoverflow.com/questions/12066002/parsing-jsonp-http-jsonp-response-in-angular-js] that suggest using $http since we only need to GET this data.

**Errors** 

With my current code, I am getting the following error:

```
angular.js:11655 TypeError: h.replace is not a function
    at angular.js:9796
    at n (angular.js:9667)
    at f (angular.js:9383)
    at angular.js:13248
    at n.$eval (angular.js:14466)
    at n.$digest (angular.js:14282)
    at n.$apply (angular.js:14571)
    at l (angular.js:9698)
    at M (angular.js:9888)
    at XMLHttpRequest.F.onload (angular.js:9829)
```

Further debugging leads to to believe that the `$sce.trustAsResourceUrl(url)` line might be the issue, but I cannot determine how to resolve this issue. Can you help?

**Comment by jessamarie** [comment]
I solved the issue! I realized I am using angular version 1.3.15.

So, instead of:

```
  var url = 'http://history.muffinlabs.com/date'
  var trustedUrl = $sce.trustAsResourceUrl(url)

  function get () {
    $http.jsonp(trustedUrl, {jsonpCallbackParam: 'callback'})
      .success(function (data) {
        console.log(data)
        return data
      })
    .error(function (data) {
      console.log('failure')
    })
```

I can use:

```
    $http.jsonp(url + '/8/12' + '?callback=JSON_CALLBACK')
    .success(function (data) {
      console.log('SUCCESS!')
      console.log(data)
      return data.found
    })
```

**Follow-up Question**
----------------------
Is it okay to use a later version of angularjs (1.5+) for this project?

**Comment by AndyWhitley** [comment]
@jessamarie For sure, I would recommend using 1.5.6 (most recent stable version)

**Comment by AndyWhitley** [comment]
@jessamarie And good job finding a solution to the json problem. If you choose to go with $http, you will want to configure your own service with custom methods (as opposed to using $resource and its associated .get, .query, etc.).

Alternately, there is a way to configure $resource to use JSONP. Refer to the link below. Either option is perfectly acceptable.

https://www.bennadel.com/blog/2610-using-jsonp-with-resource-in-angularjs.htm

**Comment by jessamarie** [comment]
Awesome! Thanks for the link. I couldn't find a resource solution before. So, I will check it out!
