### ISSUE TITLE
API Key Issue

### ISSUE THREAD

**Issue by kadkins4** [ga-wdi-exercises/project3#522]
We are using dotenv gem to hide our API key during dev/testing.  It is telling us to put the info in a env file, are we supposed to manually create this file or are we missing a step that isn't mentioned.  

*we have already installed the gem on our Gemfile

https://github.com/bkeepers/dotenv

**Comment by AndyWhitley** [comment]
@kadkins4 Yep, using dotenv, you will want create a file with `.env` file extension (maybe `config.env`) at the **root** directory of your rails app.
