### ISSUE TITLE
Nested route ID issue

### ISSUE THREAD

**Issue by lizardbird** [ga-wdi-exercises/project3#525]
We have pushed our latest code to the 'development' branch for reference, but:

- We are trying to nest the artwork show views under museum show parents
- On the museum show page (http://localhost:8080/#/museums/1), each artwork is rendered properly, but the routes are pulling the artwork id instead of the museum id. E.g. when you hover over image 1, it says http://localhost:8080/#/museums/1/artworks/1, but artwork 2 says http://localhost:8080/#/museums/2/artworks/2
- Weirdly, the view is rendering properly on the artwork show pages, but we are getting errors in our console because the app is looking for museums/2 which does not exist. 

Any guidance on pulling the correct id for the parent element?

REPOS:
- [Front End Repo](https://github.com/jdpolakoff/museogramFrontEnd)
- [Back End Repo](https://github.com/jdpolakoff/museogramBackEnd)

**Comment by AndyWhitley** [comment]
@lizardbird Where are your front-end routes for artworks located? It sounds to me like you are having the same named parameter put into the URL somewhere. For nested routes, you need to use differently named parameters (as opposed to `:id` for both the museum and artwork id). Example:

```js
$stateProvider
  .state('museumsShow', {
    url: '/museums/:id',
    controller: 'MuseumsShow',
    controllerAs: 'vm',
    templateUrl: '...some url'
  })
  .state('artworksShow', {
    url: '/museums/:museum_id/artworks/:id',
    // note the change in name for museums' id
    controller: 'ArtworksShow',
    controllerAs: 'vm',
    templateUrl: '...some url'
  })
```
Example links to each:
```html
<a ui-sref="museumsShow({ id: museum.id })>{{ museum.name }}</a>
<a ui-sref="artworksShow({ museum_id: vm.museum.id, id: artwork.id })>{{ artwork.name }}</a>
```
> Note that in the second example, **two** interpolations are being made into the parameters

**Comment by AndyWhitley** [comment]
@lizardbird EDIT:
If you are using true nested routes / states in angular, your route config will look like this (but the same concept still applies):
```js
$stateProvider
  .state('museumsShow', {
    url: '/museums/:museum_id',
    controller: 'MuseumsShow',
    controllerAs: 'vm',
    templateUrl: '...some url'
  })
  .state('artworksShow', {
    parent: 'museumsShow',
    url: '/artworks/:id',
    controller: 'ArtworksShow',
    controllerAs: 'vm',
    templateUrl: '...some url'
  })
```

**Comment by lizardbird** [comment]
Thank you, we got it working!
