### ISSUE TITLE
.env/API key revealed

### ISSUE THREAD

**Issue by cwcox** [ga-wdi-exercises/project3#526]
We had our Flickr API key hardcoded during testing.  We then committed and pushed to the repo without removing the API key so that it is now exposed on GitHub.  What is the best way to remove this?

Our first thought is to delete the current GitHub repo repo, create a new one and populate it with a local copy that has the API key hidden.

Is there a better way to fix this?

Also note that we had a .env file that we were going to use to hide the API key, but this was also pushed to the repo and was public.  We thought that was not supposed to happen.  We're we wrong?

**Comment by jsm13** [comment]
Best is to just go to Flickr and get a new key. Should be a click of a button.

As far as why, git will read from a [.gitignore file](https://help.github.com/articles/ignoring-files/) in the repo that you can add and list files not to track. There is also a global git ignore file the was put in your `~` directory at installfest that has some defaults. It is good practice to put the gitignore file in the repo though

**Comment by cwcox** [comment]
We created a .gitignore file in the repot and that solved the issue.  Thanks
