### ISSUE TITLE
Unexpected token < error

### ISSUE THREAD

**Issue by lizardbird** [ga-wdi-exercises/project3#527]
Our code seems to be working fine, but in Chrome, we are getting the following errors in the console on every html page. There are no hanging carrots in our HTML files, and after some googling, it looks like this is a common problem, but we have not been able to find a solution to match our specific issue. Thoughts?

```
Uncaught SyntaxError: Unexpected token <           | museum.index.html:1 
Uncaught SyntaxError: Unexpected token <           | museums.show.html:1 
Uncaught SyntaxError: Unexpected token <           | museums.artwork.show.html:1 

```

**Comment by jsm13** [comment]
This will happen when a browser thinks it's requesting  a js file and gets an HTML file. Is there a file name on the error?

**Comment by lizardbird** [comment]
Just the ones listed up there - its saying it's on line 1 of all the HTML files.

**Comment by jsm13** [comment]
could you link the most current repo/branch?

**Comment by lizardbird** [comment]
Sorry about that - just pushed the latest:

[Front End Repo](https://github.com/jdpolakoff/museogramFrontEnd/tree/development)
[Back End Repo](https://github.com/jdpolakoff/museogramBackEnd/tree/development)

**Comment by superbuggy** [comment]
can you also paste in the Terminal/bash commands you've used to start up a server to view your rendered angular front-end code? Want to make sure you're not passing a weird flag into `hs`.

**Comment by lizardbird** [comment]
Resolved it - we were passing in the html templates in our index file, once we removed those, error is gone! :)
