### ISSUE TITLE
Angular Logic

### ISSUE THREAD

**Issue by awandres** [ga-wdi-exercises/project3#528]
Quick question. I have a Letter, that corresponds to an Image, and I need to analyze a string, and turn the letters into the images. What I'm wondering is where would I put that logic? In the Index controller? Can I do the logic there just like normal javascript?

**Comment by jsm13** [comment]
That generally should go in a service. Not sure exactly what you're describing but general logic goes in a service so the controllers can focus just on sticking stuff to the viewmodel

**Comment by superbuggy** [comment]
are `Letter` and `Image` services that use `$resource`, or are they entities on your backend?

**Comment by superbuggy** [comment]
How are `Letter`s and `Image`s related?

**Comment by awandres** [comment]
They use $resource, but the reference URL is the rails server, which is what is accessing the API. Right now, there is no relationship to Letter and Images. However, each letter value should correspond to a key/value pair in the Images object array, so I'm thinking I'll just have a translate function that runs through each and converts them

**Comment by jsm13** [comment]
It's fine to have this logic in the controller but ideally it would have it's own service that has the `Letter` and `Image` services injected into it (it's very common to inject services into other services). I'd recommend getting it working in the controller and then considering refactoring it to a service so the controller can just ask that service for what it needs rather than containing the logic itself.

**Comment by awandres** [comment]
I've started to do some of the logic in the service, with the other services injected, but im having a really basic issue thats bothering me and preventing me from doing anything further.

I have a 'translate' function in a 'logic' service, where I'm trying to access the content(string) of a post object. I'm getting an individual post through state params (console log puts out the correct object) but using post.content is returning undefined. However, I can access post.content in the view no problem. I tried using JSON.parse, but that errored out, saying the data was already a JS object. I have no idea why I can't access this object's properties

**Comment by jsm13** [comment]
Can you link to the service in question?

**Comment by awandres** [comment]
https://github.com/mitcheguevara/Group4Angular-

most everything I have up right now is just for testing purposes. The issue in question is coming through the translate function in the logic service, with the 'outputs' displaying in the show view. I'd like to apply some logic to the 'content' attribute of this object but I can't access it
