### ISSUE TITLE
Targeting comments to update/destory

### ISSUE THREAD

**Issue by mattcfilbert** [ga-wdi-exercises/project3#529]
Hey John,

Having some trouble getting full CRUD functionality for comments (can create and read though!).

The primary issue is that we don't know how to target the specific comments on our meme show page (since we can't grab their id from the params). 

I tried a bootleg version with a for loop that updated all of a given memes comments, but got the same error, "TypeError: this.meme.comments[i].$update is not a function", (to clarify, I am calling the function in the controller).

Here are the links to the repos:
https://github.com/mattcfilbert/text_2_pix_client
https://github.com/mattcfilbert/text_2_pix_server

Thanks and enjoy the eclipse!

**Comment by jsm13** [comment]
You should use the id of the comment and add a method to the controller that takes the id and uses a $resource for comments to make the update you want

**Comment by mattcfilbert** [comment]
Word, I'll look into that. Thanks, John!

**Comment by mattcfilbert** [comment]
Hey John, since we are editing the comments on the meme show page within an ng-repeat, we're not entirely sure how to grab the id of each individual comment for the function that we run via ng-change.

**Comment by mattcfilbert** [comment]
Would $scope be at all useful for grabbing the id? Or is that outdated and the wrong direction?

**Comment by mattcfilbert** [comment]
<3
