### ISSUE TITLE
For Loop Issues 

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/project3#53]
<p>We are iterating through an array of 'podcasts' by using the Jquery $.each method. We are trying to put a click function on each instance of the array items. It's not working. Is this allowed?</p>

``` js
var podcast = frequency.podcasts;
  $.each( podcast, function( index, pod ){
    $("div[class = "+ pod.id +"]").on("click", function(){
      console.log("hi");
    })
      // console.log(pod.id)
  });
```

<p>It does console log the pod.id, but ca't get the console.log("hi") to show up.</p>

**Comment by amaseda** [comment]
Do those `<div>`'s already exist in the DOM when you're creating the event listener?

You're definitely allowed to do this!

**Comment by mcgrodsky** [comment]
They do already exist. They are being appended right before we are calling this action.

**Comment by amaseda** [comment]
Hm. Is this code pushed to a repo so I can take a look? Thx!

**Comment by mcgrodsky** [comment]
WAIT! Let us think about this for a minute. We think they are being created asynchronously, so no they aren't technically created yet. We think we have a solution but will update you

**Comment by amaseda** [comment]
Ah, that's probably it then. If you're able to figure it out close this issue please. Thx!

**Comment by mcgrodsky** [comment]
Ok. Can we come talk to you about this problem or send you our code? We understand why it isn't working, but not sure how to fix it

**Comment by amaseda** [comment]
Send the code over. I'll take a look and then find you.

**Comment by mcgrodsky** [comment]
Thanks.

https://github.com/mcgrodsky/frequen_c/tree/crud_functionality

branch "crud_functionality"
file - public/js/views/frequency/frequencyView.js
lines - 13 - 27

**Comment by mcgrodsky** [comment]
@amaseda  I think we've figured this out. It's pretty messy, but we have a working solution!

**Comment by amaseda** [comment]
@mcgrodsky Sorry, stepped away to meet with my group. Let me know if you'd like me to take a look at your solution!
