### ISSUE TITLE
Git pull won't update changes

### ISSUE THREAD

**Issue by jdpolakoff** [ga-wdi-exercises/project3#530]
My attempts to pull remote changes onto my local branch are unsuccessful. 

I started by specifying 'git pull origin development' (development is my local branch) and have also tried nearly everything on StackOverflow including 'git reset --hard HEAD' but nothing is working. 

Eventually I deleted my local repo and cloned it down anew from GitHub. The changes are still not reflected in my local copy.

**Comment by jsm13** [comment]
Only thing I can imaging is there are different branches. You checked out `development` after cloning?

**Comment by jdpolakoff** [comment]
Yea. I started by trying to pull from master to master, but I just tried to pull from development to development after you recommended that and it is still not updating.

**Comment by jsm13** [comment]
Does the output of `git status` say anything about the branch being up-to date, ahead, or behind of remote?

**Comment by jdpolakoff** [comment]
I get:

$ git status
On branch development
nothing to commit, working tree clean"

**Comment by jsm13** [comment]
and `git remote -vv`?

**Comment by jdpolakoff** [comment]
origin	git@github.com:jdpolakoff/museogramBackEnd.git (fetch)
origin	git@github.com:jdpolakoff/museogramBackEnd.git (push)

**Comment by jdpolakoff** [comment]
Ok I just tried pulling again and was successful.

**Comment by jdpolakoff** [comment]
There are some older changes that are still not fully reflected, though.

**Comment by jdpolakoff** [comment]
Here's the response I got from the git pull:

$ git pull origin development
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From github.com:jdpolakoff/museogramBackEnd
 * branch            development -> FETCH_HEAD
   0babee5..c42118f  development -> origin/development
Merge made by the 'recursive' strategy.
 app/controllers/museums_controller.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
