### ISSUE TITLE
remove commit with api

### ISSUE THREAD

**Issue by colleeno** [ga-wdi-exercises/project3#531]
I pushed to git before adding my .env file to gitignore. Accidentally published 2 sets of keys before getting it all hidden. 

It's now hidden none of the keys that were listed on this commit on git are being used, but do I need to delete this commit that showed them? If so, how to remove just this one and not effect the rest of the history?

https://github.com/mitcheguevara/Group4Project3/commit/cad2ac9a61390515512919dbbd58b58e413d6938

**Comment by jsm13** [comment]
Once you've gotten new keys there's no need to worry about getting rid of the commit which had them. 

If you wanted to rewrite the commits, the easiest way would be with an [interactive rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history).

Rebasing is interesting and totally doable but can be a little tricky and is not necessary if you have already got new keys. There are lots of articles about rebasing being destructive and dangerous but it's a very useful technique and can be done carefully.

**Comment by colleeno** [comment]
sweet, thanks!
