### ISSUE TITLE
search queries working rails, how to pass search from angular to rails and back

### ISSUE THREAD

**Issue by perryf** [ga-wdi-exercises/project3#532]
I have a basic search box working in rails.  I'm trying to figure out the best way to pass a search query from angular to rails.  I'm also having trouble getting search results to render in json.  Any thoughts/suggestions?

**Comment by perryf** [comment]
The usual 'format.json { render json: @recipes}' doesn't seem to be doing anything, no response for when I add .json to the end of the url

**Comment by jsm13** [comment]
As far as making the request I would use [a query string](https://stackoverflow.com/a/13329542). The bit about `render json: @recipes` surprises me though. Can you push your code and link to that?

**Comment by perryf** [comment]
hey John, 
Still having some trouble with the search function.  

**Controller**
https://github.com/jhosuedeveloper/myrecipeclient/blame/searchTest/js/recipes/index.controller.js#L13 
**Index**
https://github.com/jhosuedeveloper/myrecipeclient/blame/searchTest/js/recipes/index.html#L7

Tried to update the search results when a user clicks a submit button, but I get an error when I do that says ''index.html:1 POST http://localhost:8080/index.html 405 (Method Not Allowed)"
