### ISSUE TITLE
API Resolved Promise Does Not Return All Fields

### ISSUE THREAD

**Issue by jessamarie** [ga-wdi-exercises/project3#536]
**Problem Link:** 
https://github.com/jessamarie/Moments/blob/feature-discussions/public/app/src/discussions/show.controller.js#L33-L38 
(Data used on line 11)

**The Problem**
I need all the properties in the promise, which are: comments, id, month, year, and day. However, line 38 is only returning an object with the month, year, and day properties.

The source of the first log is from line 37, and the second from line 12

![image](https://user-images.githubusercontent.com/18352685/29595369-fc800894-8784-11e7-8023-48accf1ff767.png)

**I tried**
Setting the promise to an variable (line 36) and setting those fields directly to another object, like this:

```
var discussion = {
  comments: data.comments,
  id: data.id,
  month: data.month,
  day: data.day,
  year: data.year
}
```
This only gives me an undefined object.

**Comment by jessamarie** [comment]
Okay, so maybe I was just tired last night, but it works now.

**Comment by jsm13** [comment]
Hmm, not sure what that would have been but it's working fine now?

**Comment by jessamarie** [comment]
Yes, it's working fine!
