### ISSUE TITLE
Masonry reload issue

### ISSUE THREAD

**Issue by jdpolakoff** [ga-wdi-exercises/project3#537]
Hi, I'm working through an issue getting our masonry layout to display correctly on the first page load. The issue is that the images are different sizes, so the document can't properly account for all the spacing that will be needed to display them properly.

The masonry works fine on refresh, though. There are several solutions that I've tried including trying to refresh the page once an initial condition is met in the controller. But nothing is working ATM. Here's a link to the source of the masonry directive: https://github.com/passy/angular-masonry.

We found this solution, but are not sure how to implement it in a controller: https://stackoverflow.com/questions/15160010/jquery-masonry-collapsing-on-initial-page-load-works-fine-after-clicking-home

Our repos: 

https://github.com/jdpolakoff/museogramFrontEnd

https://github.com/jdpolakoff/museogramBackEnd

**Comment by lizardbird** [comment]
One additional piece - the masonry views only seem to work on Jonathan's computer - we're not sure what I would be missing for it to not run on my machine...

**Comment by jsm13** [comment]
Sorry to take a while on this, getting everything set up locally now. Will have an update in a few minutes

**Comment by jdpolakoff** [comment]
Cool, thanks. We now are getting Masonry to work on Rami's machine but still working on Liz's.

**Comment by jsm13** [comment]
Am I looking on the `develop` or `masonry` branch?

**Comment by jdpolakoff** [comment]
Everything is in development now.

**Comment by jdpolakoff** [comment]
Liz's machine is now working with Masonry. Still working on the first load issue, but possibly tabling while we take care of other stuff.

**Comment by jsm13** [comment]
All good, and I'll try to get something in here by the time you're back. `angular-masonry` is getting installed with NPM?

**Comment by jdpolakoff** [comment]
Cool. We're thinking once we have a nav bar on the side it will help us organically resize the main div and trigger the masonry resorting. Masonry was installed with bower.

**Comment by jdpolakoff** [comment]
bower install --save angular-masonry

**Comment by AndyWhitley** [comment]
@jdpolakoff Are you still having problems with using the masonry package?

**Comment by jdpolakoff** [comment]
Masonry package is all sorted out now. Thanks!
