### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by mitcheguevara** [ga-wdi-exercises/project3#538]
I just read somewhere that Turbolinks have to be removed in order to build a single page app. Is this accurate?

**Comment by jsm13** [comment]
This is just an issue when Rails is serving the Angular app (as opposed to running two different servers as we have most of the time in class). In the setup Andy described in his morning lecture, Turbo links are not included in the index page that gets served to start the angular app. Are you seeing a problem with something not running properly?

**Comment by mitcheguevara** [comment]
No We were debating going the single page route.
