### ISSUE TITLE
Token Request: Comments Feature

### ISSUE THREAD

**Issue by jessamarie** [ga-wdi-exercises/project3#540]
**Links**
Discussion Resource Service: https://github.com/jessamarie/Moments/blob/feature-discussions/public/app/src/services/discussion.js

Discussion Files: https://github.com/jessamarie/Moments/tree/feature-discussions/public/app/src/discussions

**Problem**
Discussion is a Model which has many Comments. When we get a discussion, it includes the comments it has. We would like help adding the comment (creating/views) feature to the [Show Controller](https://github.com/jessamarie/Moments/blob/feature-discussions/public/app/src/discussions/show.controller.js) and [Show View](https://github.com/jessamarie/Moments/blob/feature-discussions/public/app/src/discussions/ng-views/show.html)

**Comment by juancgarcia** [comment]
FYI. I'm on it
