### ISSUE TITLE
creating and accessing timestamps in mongoDB

### ISSUE THREAD

**Issue by comrade-kirby** [ga-wdi-exercises/project3#543]
it looks like mongoose >= 4.0 has a timestamp feature built in 
http://mongoosejs.com/docs/guide.html#timestamps
can't seem to get it working :/
time stamps aren't appearing in out db documents
any ideas?
backend repo: https://github.com/OppNHeimer/project3-back

**Comment by aspittel** [comment]
```js
const PostSchema = mongoose.Schema({
    name: String,
    title: String,
    content: String,
    tags: Array,
    date: {
        type: Date,
        default: Date.now
    }
}
}
```
I can't get that working either -- really weird. For now, the workaround would be the above. I will keep looking at it.

**Comment by ghost** [comment]
Maybe try this:
```
const PostSchema = new Schema({
    name: String,
    title: String,
    content: String
}, {
  timestamps: true
})
```
Timestamps here are passed in the options object.
