### ISSUE TITLE
Adding env.js to .gitignore

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/project3#55]
Our code looks like this: 

env.js

```
module.exports = {
  api_key: "170acc5d8f28435e95eb9f16e35036f0"
}
```

.gitignore

```
.env
```

When I go to github, I still see this:

```
module.exports = {
  api_key: "170acc5d8f28435e95eb9f16e35036f0"
}
```

As our committed api key. Why is it not hidden?

**Comment by RobertAKARobin** [comment]
It should match the name of the file: `env.js`.

**Comment by adambray** [comment]
also, once you've committed it, .gitignore won't matter. you've got to `git rm --cached file-name` to get git to stop tracking it

also also, once it's been committed, you need to treat the key as compromised and generate a new one and have whatever api generated the old one disable it.

**Comment by clarktsc39** [comment]
Hey Adam, I did what you and Robin said verbatim, and the new key is also showing up in github.

**Comment by clarktsc39** [comment]
I can show you my terminal output. It looks good. Still showing up on GH...

**Comment by clarktsc39** [comment]
<img width="312" alt="screenshot 2015-12-08 16 19 39" src="https://cloud.githubusercontent.com/assets/14867615/11668904/a83f97a2-9dc7-11e5-8c56-91af402a93b9.png">

<img width="460" alt="screenshot 2015-12-08 16 19 46" src="https://cloud.githubusercontent.com/assets/14867615/11668907/acabab00-9dc7-11e5-8ca7-1dff33773553.png">

**Comment by amaseda** [comment]
@clark-thomas Coming to you.
