### ISSUE TITLE
loop through objects in seed file 

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#57]
We've created a lot of objects in our seed file and originally put each variable name in an array.  Is there a way to call the object instead of each variable separately 

```
var mcPherson = new StationModel({
  name:"McPherson Square",
  metroLine:"Orange,Blue,Silver"
})

var metroCenter = new StationModel({
  name:"Metro Center",
  metroLine:"Orange,Blue,Silver",
})

var comment1 = new CommentModel({
  text:"Dupont is the worst"
})

var comment2 = new CommentModel({
  text:"mcPhereson is the 2nd worst"
})
```

originally the loop had var statins [stationname1, stationname2]
then I decided to try and put the object name in there and seed, but that seeded something weird. 

```
var stations = {StationModel};
console.log(stations);
var comments = [comment1,comment2,comment3];
console.log(comments);
for(var i = 0; i < stations.length; i++){
  stations[i].comments.push(comments[i])
  stations[i].save(function(err){
    if (err){
      console.log(err)
    }else {
      console.log("station/comment was saved")
    }
  })
}
```

**Comment by jshawl** [comment]
check out the tunr example for creating multiple things at once - https://github.com/ga-dc/tunr_mongo_oojs/blob/0618f5541a92c9cc5f2596a13ed29b61e8680e1c/db/seeds.js#L20-L30

**Comment by jshawl** [comment]
where `artistData` is an array of objects

**Comment by ghost** [comment]
thanks i'll work with that
