### ISSUE TITLE
Delete methods not working on other machines

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project3#58]
When Alice worked on delete functionality for our models, it worked, but when we merged those changes into the master branch, it stopped working and we can't pinpoint where it's going wrong.

The error message is: `Cannot POST /topics/566748e602b389491753e779?_method=delete`

Our route for deleting topics is: 

``` js
// app.js
app.delete("/topics/:id.:format?", topicsController.delete)
```

And in the controller we have:

``` js
// topicsController.js
var topicsController = {
// ... 
  delete: function(req, res) {
    var id = req.params.id;
    TopicModel.findByIdAndRemove(id, function(err, doc) {
      res.redirect("/topics");
    });
  },

// ...
}
```

Our view for the topic has a delete button in the form of:

``` html
<form method="post" action="/topics/{{../topic._id}}/links/{{_id}}?_method=delete">
  <input type="submit" value="Delete This Link">
</form>
```

What's really confuzzling us is the fact that it is working on Alice's computer but then not on anyone else's, although we can't find any differences in her code insofar as what's relevant to this method. (We're also having the same issue with deleting links; Alice can do it but we can't.) Any clue as to where we should look as far as perhaps other features that might be interfering? Or something else?

*\* I ran a `git diff` on the master branch that I merged the features into and the feature branch and only got the dependencies that we later used with our Passport authentication. :(

**Comment by jshawl** [comment]
do you need https://github.com/expressjs/method-override#override-using-a-query-value

**Comment by starrchen** [comment]
Nope, we do have that in our `app.js`. Its several lines above where we call our routes (I moved them all to `config/routes` since I submitted the issue but the problem remains) with a few more `app.use` for other modules that I put in there when implementing Passport authentication.

**Comment by jshawl** [comment]
can i see all of your routes for topics? feeling like there is an issue with ordering with respect to topics

**Comment by starrchen** [comment]
Yep! Here there are:

``` js
// routes.js
router.get("/.:format?", topicsController.index)
router.get("/topics.:format?", topicsController.index)
router.get("/topics/new.:format?", topicsController.new)
router.post("/topics.:format?", topicsController.create)
router.get("/topics/:id.:format?", topicsController.show)
router.delete("/topics/:id.:format?", topicsController.delete)
router.put("/topics/:id.:format?", topicsController.update)
router.get("/topics/:id/edit", topicsController.edit)
```

Should delete come after update/edit? (which also are not working :disappointed:)

**Comment by jshawl** [comment]
not sure. Try commenting out every route except the delete route to see

**Comment by starrchen** [comment]
I don't think that's working either :worried:

**Comment by RobertAKARobin** [comment]
Can you explain why you think it's not working? Are you getting an error? Or is it failing silently?

**Comment by starrchen** [comment]
Why I think it's not working? Because I keep getting the same error message `Cannot POST /topics/566748e602b389491753e779?_method=delete` that I was getting before.

**Comment by starrchen** [comment]
It just doesn't delete or edit on my machine but it does on Alice's, even when we're on the same branch at the same commit.

**Comment by RobertAKARobin** [comment]
Ah, gotcha. Could you push your code up to Github and link to it here? We'll figure this out!

**Comment by starrchen** [comment]
Yep! I believe all branches are up to date: https://github.com/starrchen/project-3

I had merged `crud2AF` into `master`, and we worked on edit/delete in `crud2AF`. We both did git pulls and it works on Alice's but not on mine. :cry:

**Comment by RobertAKARobin** [comment]
Well, it's not working on mine either, so that's something. Trying to figure this out now.

**Comment by starrchen** [comment]
Thanks @RobertAKARobin! Really appreciate it. And you're able to create new topics/links, right?

**Comment by jshawl** [comment]
DELETE works. It is an issue specifically with your form. Verified by `curl -X DELETE -i http://localhost:4000/topics/56682f8e7a96b00870a26d2f`

**Comment by RobertAKARobin** [comment]
Yeah, it works fine with `$.ajax`

**Comment by RobertAKARobin** [comment]
Ooh! It also worked for me with this:

``` html
<form method="post" action="/topics/{{topic.id}}">
  <input type="hidden" name="_method" value="DELETE" />
  <input type="submit" value="delete topic">
</form>
```

**Comment by RobertAKARobin** [comment]
I'ma close this, but please open a new one if necessary.
