### ISSUE TITLE
How to check if a user is currently logged in on the client side static page?

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project3#60]

**Comment by ghost** [comment]
There's a couple of us trying to do the same thing so if you solve this can you let us know

**Comment by jshawl** [comment]
could you give a little context. i.e. why does it need to be client-side and not server side?

**Comment by codedre** [comment]
Basically all of our views are server side and we want to dynamically place content on the client side on a server served template. Our login in pages are done with handlebars on the server side and when a user is logged in the navbar options change. If we move our views to client side we dont have a way of knowing if the user is signed in to let the client side js know to show a different navigation. 

Essentially what would be the equivalent of this on the client side?

```
<ul class="nav navbar-nav navbar-right">
     <li class="active"><a href="/user/index">Home</a></li>
     <li><a href="#">Community</a></li>
     {{#if currentUser}}
         <li><a href="/user/{{currentUser._id}}">My Profile</a></li>
         <li><a href="/logout">Logout {{currentUser.name}}</a></li>
      {{else}}
       <li><a href="/login">Login</a></li>
       <li><a href="/signup">Signup</a></li>
     {{/if}}
 </ul>
```

**Comment by RobertAKARobin** [comment]
The only thing I can think of is to create a route in your app that returns the JSON of the current user. You can then query that API with AJAX.

**Comment by tylercrosse** [comment]
Andre said it was ok to close this issue
