### ISSUE TITLE
git issues 

### ISSUE THREAD

**Issue by roshanad** [ga-wdi-exercises/project3#61]
I am getting this error -- 
error: failed to push some refs to 'git@github.com:codedre/project-3.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.

-- I already tried pull before pushing and it's not working. Please help!

**Comment by jshawl** [comment]
what is the output of `git pull git@github.com:codedre/project-3.git master`?

**Comment by roshanad** [comment]
From github.com:codedre/project-3
- branch            master     -> FETCH_HEAD
  Already up-to-date.

**Comment by jshawl** [comment]
and then what is the output  of `git push git@github.com:codedre/project-3.git master`?

**Comment by roshanad** [comment]
Everything up-to-date

**Comment by jshawl** [comment]
problem solved?

**Comment by roshanad** [comment]
To git@github.com:codedre/project-3.git
 ! [rejected]        googleLogin -> googleLogin (non-fast-forward)
error: failed to push some refs to 'git@github.com:codedre/project-3.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by jshawl** [comment]
what is the output of `git pull git@github.com:codedre/project-3.git googleLogin`?

**Comment by roshanad** [comment]
```
$ git pull git@github.com:codedre/project-3.git googleLogin
From github.com:codedre/project-3
 * branch            googleLogin -> FETCH_HEAD
Merge made by the 'recursive' strategy.
~/Project3/project-3 (googleLogin)
$ git status
On branch googleLogin
nothing to commit, working directory clean
```

It opened up atom with merge conflict we resolved after doing git rebase master from our googleLogin they appeared to be already resolved.

**Comment by RobertAKARobin** [comment]
Just in case this isn't resolved -- this can happen when you reset or rebase your repo. Git considers you to be "up-to-date" if your most recent commit matches the most recent commit on Github. Resetting and rebasing can cause earlier commits to change.

If you REALLY just want to get your stuff on Github, then you have to "force push". You do this using:

```
$ git push -f origin the-branch-name
```

**Bear in mind** that this will overwrite everything on Github, so if there's important stuff on there it'll be lost.

Also, this will cause everyone else with whom you're working to do a "force pull". They'll do this with:

```
$ git reset --hard origin/the-branch-name
```

Then, whatever they have locally will be wiped and replaced with what's on Github.
