### ISSUE TITLE
returning from calling a series of asynchronous functions in a for loop

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/project3#63]
Part of our project relies on getting information about a user from github.

One of our functions takes a github user name and gets all repos on that user's profile.  The callback of that function contains a for loop that makes another call to github based on each repo name.  In this for loop we construct an object, and when all the calls have returned from github, the object is complete.

The issue we're having is that we don't know how to return this object when every one of the inner calls is finished.  We're able to print it, or save it to our database, but what we'd really like to do is return that object or chain another promise onto the inner function so we can do the subsequent task only when the object is complete.

Some pseudo code of what we have right now:

``` js
function getMsgs(user){
   getAllRepos(user, function(err, res){
      var counter = 0
      var object = {}
      for (var i = 0; i< res.length; i++) {
         getCommitMessages(res[i], function(err, res) {
             counter++
             object.push(res)
             if (counter == res.length) {
                   console.log(object);
             }   
         })
      }
   })
}

```

Any suggestions or guidance about how to refactor this would be really helpful.

**Comment by solowt** [comment]
While I'm still working on this...another question I have is why this function is hanging after it prints.  Even if I add a return after the print, it just hangs forever.

**Comment by RobertAKARobin** [comment]
Asynchronous for loops are really, really tricky, I'm afraid. The root of the problem is the loop doesn't wait for one request to stop before it goes on to the next one, and by that point the local variables that you want to use have changed.

For the `tunr_mongo_oojs` class I made something that functions as an asynchronous for loop. Maybe you could try that?

https://github.com/ga-dc/tunr_mongo_oojs/blob/master/db/seeds.js#L40

**Comment by solowt** [comment]
I could be misunderstanding your method there, but it looks to me like you're relying on recursion (in forEach) to chain all of your db calls back-to-back rather than firing them all off in a loop.   Is that roughly correct?

**Comment by RobertAKARobin** [comment]
Yup.

**Comment by solowt** [comment]
Alright, I'll give that a go.

Thanks.
