### ISSUE TITLE
Still can't deploy

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project3#65]
So my deployment issue was really different from Andre's because we didn't even start incorporating an `env` yet, so would still love some insight as to what I can do to get this farely barebones app to deploy?

**Comment by RobertAKARobin** [comment]
Did you try deploying this?

https://github.com/ga-dc/super-simple-twitter-app/pull/2

**Comment by RobertAKARobin** [comment]
I'ma close this, but please open a new one if necessary!
