### ISSUE TITLE
Errors with flash & passport

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/project3#67]
I'm experiencing several errors with implementing passport, which all seem to be interconnected with flash messages, "next" function, and users not being saved to our database (currently they seem to just be saved into a session). 
As I alter the code, I hit several different errors - the first is a command line error: 

```
if (this.session === undefined) throw Error('req.flash() requires sessions');
                                  ^
Error: req.flash() requires sessions
    at Error (native)
```

I do have flash and sessions required in my index.js file: 

``` js
var express     = require('express')
var flash       = require('connect-flash');
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());
```

When I comment out the flash messages, I'm able to create a user and log-in, but when I attempt to log-in a second time, I hit a different error in the browser that says next is not a function, and the stack trace references the authenticate.js file.  

I do have "next" entered as an argument and callback (I think) in my app.use function and both the postSignup and postLogin functions: 

``` js
app.use(function (req, res, next) {
    res.locals.currentUser = req.user;
    next();
  });

  function postSignup(request, response, next) {
    var signupStrategy = passport.authenticate('local-signup', {
      successRedirect : '/',
      failureRedirect : '/signup',
      failureFlash : true
    });
    return signupStrategy(request, response, next);
  }
```

Sorry if this is too much to post for one issue - thanks in advance!

**Comment by RobertAKARobin** [comment]
Do you have `express-session` required?

**Comment by schersh** [comment]
Yes - in the index.js file: 

var session      = require('express-session');

**Comment by schersh** [comment]
Is the order important?

**Comment by RobertAKARobin** [comment]
It may be. Could you link to your repo and make sure it's up-to-date?

**Comment by schersh** [comment]
Sure - here is the repo: https://github.com/schersh/Travel_app_project_3/tree/s_user_auth
I am working on the s_user_auth branch.

**Comment by RobertAKARobin** [comment]
`express-session` doesn't appear to be in your package.json. Use `npm install --save express-session` to add it.

**Comment by RobertAKARobin** [comment]
...in fact, it looks like you'll need to do that with most of your dependencies.

**Comment by schersh** [comment]
Okay, thanks - I was working off of Dennis' branch - is that something that would need to be done each time someone locally installs, or was it just not done at set-up?

**Comment by schersh** [comment]
and the syntax for each dependency would be npm install --save "dependency name"?

**Comment by RobertAKARobin** [comment]
Any time you install something specific, you should probably use `--save`. Otherwise it doesn't get added to your `package.json`. Frankly, I have nooooo idea why that isn't the default, but oh well!

Yep, you got the syntax right. Don't need the double-quotes:

```
npm install --save this-is-my-dependency
```

**Comment by RobertAKARobin** [comment]
Found the problem!

Put `app.use(session({secret: "yo"}));` somewhere in with all of your `app.use`es.

Also, I'd recommend moving all of your `var ...controller`s to right before your `app.get`s, and putting your `app.listen` at the very end of the file.

**Comment by schersh** [comment]
Ok - do you means in all of these app.use(es) or just the ones relevant to passport?
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:true}))
app.use(methodOverride('_method'))
app.use(express.static(__dirname + '/public'))
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());

**Comment by schersh** [comment]
and do I just make something up for what the secret word is?

**Comment by schersh** [comment]
Sorry, I think we figured it out!

**Comment by schersh** [comment]
Thanks for your help - I'll install the dependencies and then test things out!

**Comment by schersh** [comment]
Hi again.. I went through and did npm install --save for all of the dependencies and changed the order of my index.js file, but I'm still getting this error for flash when I try to follow the sign-up route - is this an error with how I am calling my flash messages? 

Here is the beginning of the error stack trace: 

```
Error: req.flash() requires sessions
   at Error (native)
   at IncomingMessage._flash [as flash] (/Users/schersh/WDI/projects/Travel_app_project_3/node_modules/connect-flash/lib/flash.js:60:41)
   at getSignup (/Users/schersh/WDI/projects/Travel_app_project_3/controllers/usersController.js:16:54)
   at Layer.handle [as handle_request] (/Users/schersh/WDI/projects/Travel_app_project_3/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/schersh/WDI/projects/Travel_app_project_3/node_modules/express/lib/router/route.js:131:13)
```

**Comment by RobertAKARobin** [comment]
Could you link to your code? I'll make sure it's in the proper order.

**Comment by schersh** [comment]
Sure, thanks - I just pushed up to that same s_user_auth branch 

https://github.com/schersh/Travel_app_project_3/tree/s_user_auth

**Comment by RobertAKARobin** [comment]
Change this line:

```
app.use(passport.session({secret: "yo"}));
```

...to this:

```
app.use(session({secret: "yo"}));
```

And you don't have to use "yo" -- it can be any string.

**Comment by schersh** [comment]
Thank you!!!
