### ISSUE TITLE
.on event listener weirdness

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project3#70]
$(this).on("click", function() {}; works

$(".card").on("click", function() {}; doesn't ???

**Comment by jshawl** [comment]
what is the output of `console.log($(".card"))`

**Comment by tylercrosse** [comment]
Sorry for the super vague question to begin with

`$(".card").on("click", function() {
  console.log(event.target) }` doesn't return anything

`$(this).on("click", function() {
console.log($(".card"));` returns all of the cards with the context of the one clicked on

``` [div#566828b68eeae7fc44d11847.card.col-xs-12.col-md-3.col-lg-4,
div#566828b68eeae7fc44d11848.card.col-xs-12.col-md-3.col-lg-4,
div#566828b68eeae7fc44d11849.card.col-xs-12.col-md-3.col-lg-4,
div#566828b68eeae7fc44d1184a.card.col-xs-12.col-md-3.col-lg-4,
prevObject: n.fn.init[1], context: document, selector: ".card"]
```

We've also tried subbing in anything we could think of for ".card" and the only thing that seems to work is `this`

Also for context, this event listener is located in a `$(document.ready(function() {}'

**Comment by RobertAKARobin** [comment]
``` js
$(".card").on("click", function() { console.log(event.target) }
```

...won't do anything because `event` has to be passed in as an argument in that function:

``` js
$(".card").on("click", function(event) { console.log(event.target) }
```

**Comment by RobertAKARobin** [comment]
If this isn't working:

``` js
$(this).on("click", function() {
  console.log($(".card"));
}
```

...try this:

``` js
var cards = $(".card");
$(this).on("click", function() {
  console.log(cards);
}
```

**Comment by tylercrosse** [comment]
We have a page of cards and when the user clicks on one of them we want to clear the page and render that card. So ultimately I just need the id of the particular card. I was trying to avoid something like:

```
$(this).on("click", function() {
  var target = $(event.target);
  if (target.is(".card")) {
    // DO STUFF
  }
}
```

The other issue is that the `$(".card")` has a bunch of other elements in it and we just need info from `$(".card")` even if one of it's children are clicked on

**Comment by RobertAKARobin** [comment]
Put the event listener on `.card`, then. Clicking on anything inside it will fire a click event on `.card` itself.

In any case, `$(event.target)` won't work if `event` isn't passed as an argument in the function.

**Comment by tylercrosse** [comment]
Andre opened this, so I don't have permission to close it

**Comment by tylercrosse** [comment]
I'm actually still kind of confused by why it worked in the userView and not in the other file. A quick explanation would be tremendously helpful. We're sitting over in the middle of the long tables. Thanks!
