### ISSUE TITLE
Creating a New Workout

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#71]
When I try to create a new workout, the console displays this error message:

POST http://localhost:3000/workouts 404 (Not Found)

When i got to /workouts in my browser it displays the json objects we created in our seed data.

https://github.com/murgia/SwoleMate

I believe the problem is in public/js/models/workout in line 20.  I have modified that line a couple times to make sure that that is the failing request.

Thank you

**Comment by amaseda** [comment]
@murgia Cloning this now. Will get back to you in a few.

**Comment by murgia** [comment]
awesome thank you.  We are in classroom 1 if you feel like something would be better said in person.

**Comment by RobertAKARobin** [comment]
It's because you have:

``` js
router.post("/workouts", function(req, res) {
  Workout.create(req.body).then(function(workout){
    res.json(workout);
  });
});
```

...but `/workouts` is already prefixed to everything in this controller. So the path would actually be `localhost:3000/workouts/workouts`!

Just change it to `/` and you should be good!

**Comment by murgia** [comment]
Thank you very much!
