### ISSUE TITLE
Rendering edit form on click

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project3#72]
I am trying to find the edit button within the view in order to render an edit form but cannot find it. I tried to use self and this.find and the class name of the button but it is not consoling upon click that it has been clicked. It does not console log anything currently when I click the button.

Github repo: https://github.com/Ly900/SwoleMate.git

Snapshot as well:

![image](https://cloud.githubusercontent.com/assets/12722650/11691535/6947bfd2-9e69-11e5-9992-ec33dfbecb5f.png)

**Comment by ebirving** [comment]
Try `$el` and `self.$el.find` -- it looks like you're mixing jQuery and vanilla JS methods, which doesn't work...

**Comment by Ly900** [comment]
Tried this next, Erica, and it didn't work...
![image](https://cloud.githubusercontent.com/assets/12722650/11692605/569c51b8-9e6e-11e5-82f8-34093ff9f36a.png)

**Comment by amaseda** [comment]
@Ly900 The function is ending once it hits `return($el)` so the line after it isn't running. Does it work after you move it?

**Comment by Ly900** [comment]
I moved it above return($el) but now it says 
![image](https://cloud.githubusercontent.com/assets/12722650/11694351/ab3e16e4-9e77-11e5-93b2-2f2f8c05b4c7.png)

**Comment by amaseda** [comment]
What's the output of `self` and `self.$el` after setting $el to that big jQuery object?

**Comment by Ly900** [comment]
self comes as three exercise views and self.$el is undefined...

![image](https://cloud.githubusercontent.com/assets/12722650/11694692/7d854e14-9e79-11e5-8422-24261bb43d65.png)

**Comment by amaseda** [comment]
Doesn't look like you're attaching you're `$el` to the view object. It only exists as a local variable inside your render function. So `self.$el` won't have any value.

Instead of `var $el =` try `self.$el =`.

**Comment by Ly900** [comment]
please come. im in room 1.
