### ISSUE TITLE
deployment error

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project3#73]
I was following <a href="https://devcenter.heroku.com/articles/getting-started-with-nodejs#deploy-the-app">this tutorial</a> to deploy my app, but I'm getting the following error whenever I try to `heroku create`:

```
/usr/local/heroku/lib/heroku/jsplugin.rb:88: warning: Insecure world writable dir /usr/local/rvm/gems in PATH, mode 040777
!    Heroku client internal error.
```

I googled and found <a href="https://github.com/heroku/heroku/issues/1326">this</a>, so upon their suggestion I ran `heroku update` and `heroku plugins:update`. It gives me the same exact error, but appears to update anyway. It doesn't fix the problem though ...

**Comment by RobertAKARobin** [comment]
Sorry for the delay, I'm looking now!

In the meantime, remember that you use one bactick on either side of some words to do inline code, and 3 backtics _by themselves on their own line_ before and after to make a block of code.

**Comment by RobertAKARobin** [comment]
Woah, where did `/usr/local/rvm/gems` come from? Do you have a Gemfile or anything else Ruby-ish in your repo?

**Comment by rebeccaestes** [comment]
No ... That's in a different directory entirely from the project that I'm trying to deploy.

**Comment by RobertAKARobin** [comment]
Weird! Try this? Can't hurt anything.

http://stackoverflow.com/questions/2796421/warning-insecure-world-writable-dir-when-i-run-a-ruby-or-gem-command

**Comment by rebeccaestes** [comment]
OK, I did that (three times - I guess there were several error-causing directories) and now that error is gone. I still have one blocking the creation. I thought that was part of the Insecure world writable error, but apparently not:

```
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `netrc_filename' for Netrc:Class (NoMethodError)
    Command:     heroku create
    Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    46abddcc161c4f808cdadbc32c4bd77d
```

I don't know why it says 'ruby' in the version either, unless it's left over from project 2 or something, since I haven't been able to initialize anything yet.

**Comment by rebeccaestes** [comment]
Also one of my partners just reminded me about your PR about deploying to Heroku, which I forgot about ... I'll look at that and see if it helps.

**Comment by RobertAKARobin** [comment]
Oops, sorry, got buried in some other issues.

Yeah, this is weird. Maybe try doing `Heroku create` again? If that doesn't fix it, honestly I'd recommend you contact Heroku support. I think this is beyond the scope of regular programming issues.

**Comment by rebeccaestes** [comment]
I uninstalled and then reinstalled Heroku and now it works! Or at least, `heroku create` ran correctly, which is progress.
