### ISSUE TITLE
Event Click listener not responding as expected

### ISSUE THREAD

**Issue by toryburgett** [ga-wdi-exercises/project3#75]
Hello GA,

I have an issue. An event click listener is not responding as I would like it to (see code below). We've tried replicating the issue and creating a new button, but the problem persists. Any guidance will be warmly recieved. 

```
EventPostView.new = function(){
  // upon clicking create new Event post button, the button dissapears
  $(".createEventPost").hide();

  var html = $("<div>");
  html.append("<p>Event Title : <input name='title' value=''></p>");
  html.append("<p>Date: <input name='date' value=''></p>");
  html.append("<p>Photo Url: <input name='photoUrl' value=''></p>");
  html.append("<p>Wiki Page: <input name='wikiPage' value=''></p>");
  html.append("<button class='createEventPostButton btn btn-success'>New Event</button>");
  html.append("<button class='cancelCreateEventPost btn btn-danger'>Cancel</button>");

  var createButton = $(".createEventPostButton");

  createButton.on("click", function() {
    console.log("Button Clicked!!!");
    // var data = {  title: $('input[name=title]').val(),
    //               date: $('input[name=date]').val(),
    //               photoUrl: $('input[name=photoUrl]').val(),
    //               wikiPage: $('input[name=wikiPage]').val()
    //             };
    //
    // EventPost.create(data);

  });

  $(".cancelCreateEventPost").on("click", function(){
    console.log("Luke I am your father!");
  });



  return(html);
};
```

**Comment by amaseda** [comment]
Have a hunch that it has to do with your jQuery selectors. If you run something like `$(".createEventPostButton")`, your code will look to see if that exists in the DOM. This does not include an `$el` that has not yet been attached to the DOM.

If it hasn't yet been attached to the DOM, you'll want to do something like...

``` js
var createButton = this.$el.find( ".createEventPostButton" )
createButton.on( "click", function( ){ } )
```

Let me know if that works or not!

**Comment by toryburgett** [comment]
Thank you Adrian for your quick response! We have sucessfully selected the button on our HTML page on the console with 

```
var createButton = $(".createEventPostButton");
```

So, we think we're selecting the right element... It's just when we try to click this button, our console does not respond with the provided message.

**Comment by RobertAKARobin** [comment]
Sorry Tory for my slow response!

So this doesn't work?

``` js
var createButton = $(".createEventPostButton");
createButton.on("click", function(){
  console.log("Yo, I got clicked");
});
```

What's the output of this?

``` js
var createButton = $(".createEventPostButton");
console.log(createButton);
```

**Comment by toryburgett** [comment]
Hi Robin! When we try this, the output is: 

```
[prevObject: n.fn.init[1], context: document, selector: ".createEventPostButton"]context: documentlength: 0prevObject: n.fn.init[1]selector: ".createEventPostButton"__proto__: n[0]
```

**Comment by RobertAKARobin** [comment]
And the thing with "Yo, I got clicked" doesn't work?

**Comment by toryburgett** [comment]
Correct, when clicked we do not get a response in the console

**Comment by RobertAKARobin** [comment]
Try doing something else to it to make sure the thing you're clicking is the correct element. Remember, if you do `$(".something")` it's going to select everything with the class of `something`.

Try this, maybe:

```
var createButton = $(".createEventPostButton");
createButton.fadeOut();
```

...or:

``` js
var createButton = $(".createEventPostButton");
createButton.css("border", "1px solid red");
```

Something visible.

**Comment by RobertAKARobin** [comment]
Tyler actually just had the same issue. Your `.createEventPostButton` elements are created by Javascript, right? (As in, they're not hard-coded into your HTML.)

My guess is that you're adding this event listener when the page first loads. The page loads before those postButton elements are created. If the event listener gets added when the page loads, then that means you're trying to add the event listener to the postButtons _before_ the postButtons elements are created!

You want to add the event listener after _each_ postButton is created. If you have a `postButton.render()` method or something similar, you're going to want to put it inside that method.

**Comment by toryburgett** [comment]
Thank you Robin! We're trying to decide what the best step forward would be. Should we create a form on our index.html or is it possible to create an object like

``` js
EventPost.new = { 
renderNewEventPost: function(){
//code calling on eventpost template function & then making button click listeners }, 
renderNewEventPostTemplate: function(){
//code creating input fields and buttons
 }
};
```

**Comment by RobertAKARobin** [comment]
Without worrying about new code, can you tell me where the `createEventPostButton` elements from from right now? Are they hardcoded into your HTML? Are they created in some Javascript method?

**Comment by toryburgett** [comment]
Thank you so much Robin!! The CSS and console.log are working now, we've got a form in our html that's hiding until we click another buitton. We're going to try to expand off of this to create a new element (the hard part), but having & understanding the event listener has me and the group feeling a lot more comfortable with this

**Comment by RobertAKARobin** [comment]
Wooooo! I'm so glad!

/giphy party

Oh. Darn.
