### ISSUE TITLE
check if user is signed in on client side

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project3#76]
So I modified the authenticatedUser function from the lesson to return a json object that I can read on the client side. In the truthy case it works as expected but Im not sure how to handle the false case

SERVER SIDE
config/routes.js

```
function authenticatedUser(req, res, next) {
  // If the user is authenticated, then we continue the execution
  if (req.isAuthenticated()){
    // res.json({isAuthenticated : "true"});
    return next();
  } else {
    res.json({isAuthenticated : "false"});
  }
    // res.redirect('/');
  // Otherwise the request is always redirected to the home page
}
```

```
router.route('/')
  .get(authenticatedUser,staticsController.home);
```

controllers/statics.js

```
function home(req, res) {
  res.render('index');
}
```

CLIENT SIDE
public/js/main.js

```
  $.getJSON('/', function(auth, err) {
    console.log(auth);
  });
```

**Comment by amaseda** [comment]
So from the way you describe it, when `req.isAuthenticated( )` is true it returns a JSON object containing `{isAuthenticated : "true"}`.

What happens currently when it evaluates to false?
