### ISSUE TITLE
create function not working entirely properly

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project3#77]
I have a create function to create a new dashboard item and push it to the user that is currently signed in and creating it.  The functions looks like this:

```
create: function (request, response) {
  var newDash = new DashboardItem({
    partner_message: request.body.partner_message,
    partner_link: request.body.partner_link,
    city: request.body.city
  });
  newDash.save().then(User.findOne({_id: request.user._id})).then(function(user){
    user.dashboardItems.push(newDash).then(
      user.save(function(err){
        if(!err){
          response.redirect('/partners/dashboard');
        };
      }));
    });
  },
```

It does not redirect, instead it hangs.  But when I check Mongo it does create the dashboard item, it just does not appear to be putting it into the user.  The user looks like this in Mongo:

```
{ "_id" : ObjectId("56685527632956a4274408de"), "dashboardItems" : [ ObjectId("566864ce82268baf2c71a90a") ], "local" : { "password" : "$2a$08$2phJ1tMi0w/H/./GI.cTsOCsiaCKNoXiI7Wcd6uHfeKv5mVlJIbQS", "email" : "dan@email.com" }, "__v" : 1 }
```

There is an objectid for dashboarditems but it does not match the id of the dashboard item created, so I am not even sure what that refers to.

**Comment by amaseda** [comment]
Does it still hang if you get rid of the `if(!err)` statement surrounding `response.redirect`?

**Comment by dan-ator** [comment]
It does.

**Comment by amaseda** [comment]
Can you send a link to your repo? Going to clone and try something out.

**Comment by dan-ator** [comment]
https://github.com/dan-ator/Project3/tree/add_user

**Comment by RobertAKARobin** [comment]
I'd start removing things one at a time, or putting in console logs one at a time, until you can pinpoint which method is causing the hanging.

**Comment by dan-ator** [comment]
Well my foremost concern is that it does not appear to be actually pushing the dashboard items it is creating into the user's dashboard items.

**Comment by RobertAKARobin** [comment]
I'd be more worried about the hanging. If it starts hanging before it can push stuff, then that'll need to get fixed first.

**Comment by dan-ator** [comment]
Does each then() need to have function called within it?

**Comment by RobertAKARobin** [comment]
Yep.

**Comment by dan-ator** [comment]
I refactored some code and it appears the hanging error is something in between "here" and "there":

``` js
create: function (request, response) {
  var newDash = new DashboardItem({
    partner_message: request.body.partner_message,
    partner_link: request.body.partner_link,
    city: request.body.city
  });
  newDash.save()
  .then(function(users){
    console.log("here")
    users.findOne({_id: request.user._id}, function(err, doc){
    console.log("there", doc.email)
    })
  }).then(function(user){
    user.dashboardItems.push(newDash)
      user.save().then(function(){
        response.redirect('/partners/dashboard')})
      });
  },
```

I tried using 'User', 'users', and 'user', changing both the thing passed into the function and the word on the line `users.findOne({_id: request.user._id})`.  I found that syntax from https://mongodb.github.io/node-mongodb-native/markdown-docs/queries.html. Not sure what else could be causing the hanging on that line.

**Comment by RobertAKARobin** [comment]
It's because promises are weird. You're missing a bunch of `return` statements. Check out this format:

``` js
User.someMongoMethod()
.then(function(response){
  return User.someOtherMongoMethod();
}).then(function(response){
  return User.yetAnotherMongoMethod();
}).then(function(response){
  return User.theFinalMongoMethod();
}).then(function(response){
  console.log("Done");
});
```

**Comment by RobertAKARobin** [comment]
If that seems weird, don't use `.then` at all and just stick to making the pyramid:

``` js
User.someMongoMethod(function(response1){
  User.someOtherMongoMethod(function(response2){
    User.yetAnotherMongoMethod(function(response3){
      User.theFinalMongoMethod(function(response4){
        console.log("Done");
      });
    });
  });
});
```

**Comment by dan-ator** [comment]
You mean if I have the pyramid without thens, they will run in order?  I thought that they wouldn't and that was why I had to explicitly tell it when to run each line of code.

**Comment by dan-ator** [comment]
I added return statements and a few more console.logs and now it appears to be getting stuck at 
`return user.dashboardItems.push(newDash)`.  I do not know why.  Moreover, I wonder what exactly is it that is being passed into a function in the `}).then(function(user){`?  Does that 'user' have to match something else?

**Comment by RobertAKARobin** [comment]
Yes, they'll run in order. The pyramid and `.then` do the exact same thing. The pyramid's just uglier.

The pyramid doesn't have any `return`. Use the pyramid!

**Comment by dan-ator** [comment]
Ok, but I have all the .then's and the return statements, so I suspect the problem lies in some other part of that line.

**Comment by RobertAKARobin** [comment]
Trust me on this one.

**Comment by dan-ator** [comment]
Ok.  What are all the responses inside those parenthesis?  Also, if I am starting this pyramid, I don't even need a .then after the .save()?

**Comment by RobertAKARobin** [comment]
No. The `.then` example and the pyramid example I showed above are exactly equivalent.

**Comment by dan-ator** [comment]
I mean since I don't start with User, it starts with `newDash.save()`.
