### ISSUE TITLE
Cannot get proper view once something is created

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/project3#78]
The idea of the create a new workout function is when you click on add a new workout, the form appears and then when you click create, the form disappears and the workout is now listed on the page without a refresh.  I currently have it so a new workout is created but the view does not change.  I have tried to look at similar rendering in the update method which works correctly but I am not sure if I am looking in the right spot since this is not an instance.  I have tried adding this after I create the new workout:

.then(function(newWorkOut) { self.prototype.render(); });
  });

but i am getting this error Uncaught TypeError: Cannot read property 'html' of undefined.

I would be happy to come show someone a couple of other things I have tried.

Thank you

**Comment by amaseda** [comment]
WE DID IT. Closing, but feel free to re-open if you've got more questions on this.
