### ISSUE TITLE
API usage and passing user params

### ISSUE THREAD

**Issue by MarkhamShofner** [ga-wdi-exercises/project3#79]
We are currently formalizing our logic on how to make API calls within our app. Currently, the calls are statically made from the backend (through a controller). But we are attempting to get inputs from the client passed to the backend and into the API search. We have created a params object that we're having trouble passing from front to back so that's question 1) how can we pass an object created in the front-end script.js through our routing file/controller/APImodel, and receive the JSON object output from the backend search function. 
Additionally, should we even have the API call made on the backend? It seems like the way Yelp wants it to be done, but Andy's blog post (and other intro API guides we've looked at) seem to have API queries made on the front end.

**Comment by RobertAKARobin** [comment]
I greatly prefer API queries on the back-end if at all possible. Try it on the front-end and you'll probably get "Cross Domain" errors.

Hm. You should be able to pass any object you create on the front-end like this:

``` js
$.ajax({
  url: "google.com",
  data: {name: "Mark", cats: ["Juan", "Consuela"]}
})
```

What are you trying right now?

**Comment by MarkhamShofner** [comment]
this is currently retrieving a static search we have in the back

```
        $.ajax({
          type: 'GET',
          dataType: 'json',
          url: "http://localhost:3000/yelp"
        }).done(function(response) {
          console.log(response);
        }).fail(function(response){
          console.log("Ajax get request failed.");
        });
```

we're having a few issues passing in data, that the backend then uses in its own search

**Comment by MarkhamShofner** [comment]
so, it seems like we should use a line like `data: {name: "Mark", cats: ["Juan", "Consuela"]}` and then call that in the backend search function? also, +1 for Consuela

**Comment by RobertAKARobin** [comment]
If you're POSTing:

``` js
$.ajax({
  url: "google.com",
  method: "POST",
  data: {name: "Mark", cats: ["Juan", "Consuela"]}
})
```

...then on the back end you'll access that data with `req.body`:

``` js
app.post("/", function(req, res){
  res.json(req.body);
});
```

**Comment by MarkhamShofner** [comment]
``` js
  search: function(req, res) {
    var backParams = req.body.data;
    var params = {
      term: backParams.term,
      ll: backParams.latitude + backParams.longitude,
      limit: 3
    };
    Yelp.search(params)
    .then(function(data) {
      res.json(data);
    });
  }
```

isn't working dynamically (or at all),

where before the same code was working statically with 

``` js
  var params = {
      term: 'bar',
      ll: "38.999, -79.011",
      limit: 3
    };
```

as the params declaration line

**Comment by RobertAKARobin** [comment]
What do you get when you console log `req.body`?

**Comment by MarkhamShofner** [comment]
{}, empty object. How can we make that a happy, parameter filled object?
