### ISSUE TITLE
Creating new perspective without page refresh.

### ISSUE THREAD

**Issue by lewis2ba** [ga-wdi-exercises/project3#80]
We are trying to create new perspectives/markers on our mapbox map. We are using a form in a popup on the map where a user clicks. The perspective is created in the db after post but the icon doesn't show up until we refresh the page(via redirect). I am not sure if I need an ajax call from the front end to create the marker...

Here is our create function in the controller:
<img width="651" alt="screen shot 2015-12-09 at 2 27 19 pm" src="https://cloud.githubusercontent.com/assets/13842987/11696173/058d47f6-9e81-11e5-914c-6d9b60a9f46d.png">

Do we need a function that gets the json of the perspective we just created?
<img width="559" alt="screen shot 2015-12-09 at 2 28 57 pm" src="https://cloud.githubusercontent.com/assets/13842987/11696218/36ecc786-9e81-11e5-82de-ccf6bb61115f.png">

**Comment by RobertAKARobin** [comment]
The map won't reflect any changes until either you refresh, or you use front-end Javascript to explicitly add in the changes. That's totally doable, but may be more complicated than you bargained for depending on the API you're using. Timebox it: if it takes too long, just stick with a page refresh.
