### ISSUE TITLE
User Authorization and HBS

### ISSUE THREAD

**Issue by aoave** [ga-wdi-exercises/project3#81]
I need help with getting hbs to generate my views, I have everything linked up but when I click my login button or sign up button my browser is telling me it cannot find GET /login. Also we started everything in html, and since the user auth was taught in HBS we have to convert to HBS. I feel like its an easy fix but I  haven't been able to find a solution.

**Comment by RobertAKARobin** [comment]
That must mean there's a problem with your routes. Can you show me how they're set up?

**Comment by aoave** [comment]
``` js
var express = require('express');
var router = express.Router();
// Parses information from POST
var bodyParser = require('body-parser');
// Used to manipulate POST methods
var methodOverride = require('method-override');
var passport = require("passport");
var usersController = require('../controllers/users');
var staticsController = require('../controllers/statics');

router.route('/')
  .get(staticsController.home);

router.route('/signup')
  .get(usersController.getSignup)
  .post(usersController.postSignup)

router.route('/login')
  .get(usersController.getLogin)
  .post(usersController.postLogin)

router.route("/logout")
  .get(usersController.getLogout)

module.exports = router
```

**Comment by RobertAKARobin** [comment]
Are any other routes working?

Also, what does your UsersController look like?

**Comment by aoave** [comment]
None of the routes are working

``` js
var passport = require("passport")

// GET /signup
function getSignup(request, response) {
  response.render('signup.hbs', {
    message: request.flash('signupMessage')
  });
}

// POST /signup
function postSignup(request, response) {
  var signupStrategy = passport.authenticate('local-signup', {
    successRedirect: '/',
    failureRedirect: '/signup',
    failureFlash: true
  });

  return signupStrategy(request, response);
}

// GET /login
function getLogin(request, response) {
  response.render('login.hbs', {
    message: request.flash('loginMessage')
  });
}

// POST /login
function postLogin(request, response) {
  var loginProperty = passport.authenticate('local-login', {
    successRedirect: '/',
    failureRedirect: '/login',
    failureFlash: true
  });

  return loginProperty(request, response);
}

// GET /logout
function getLogout(request, response) {
  request.logout();
  response.redirect('/');
}


module.exports = {
  getLogin: getLogin,
  postLogin: postLogin,
  getSignup: getSignup,
  postSignup: postSignup,
  getLogout: getLogout
}
```

**Comment by RobertAKARobin** [comment]
Can you push your code up to Github and provide a link so I can look?

**Comment by aoave** [comment]
https://github.com/murgia/SwoleMate/tree/aureliooo

here is my branch.

**Comment by RobertAKARobin** [comment]
I'm attempting to run your code now. Looks like you're missing some things in your `package.json`. Please go through and `npm install --save dependency-name` everything to make sure it's all in your `package.json`.

**Comment by RobertAKARobin** [comment]
Looks like it's just `connect-flash`

**Comment by RobertAKARobin** [comment]
Your UsersController has two `module.exports`. You can only have one. It's like a `return` statement.

**Comment by aoave** [comment]
I got connect flash and my login is popping up but when I submit I can not get Cannot get post /login.
Also Matt and I were looking for the other module.exports and couldn't find a second in the controller

**Comment by RobertAKARobin** [comment]
My bad on the exports thing... Don't know where I saw that.

You haven't required your `config/routes` file in your `app.js`.

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to take this issue of the market. Feel free to open a new one!
