### ISSUE TITLE
Returning true/false from a promise

### ISSUE THREAD

**Issue by tomiteo** [ga-wdi-exercises/project3#83]
Hi! 

A user submits a username through a form.
There is an event listener, which calls a function on the view prototype, which fires off a $.getJSON request to the github API.
If the user exists, I want this function on the prototype to return true, else false, so that we don't end up creating profiles in our database for Github profiles that don't exist.

Here's the code, which I expected to return true or false, but it appears the function always returns undefined because it only returns out of the promise, not the overarching function.

``` js
newProfileView.prototype = {
  checkProfile: function(username){
    var url='https://api.github.com/search/users?q=';
    .then(function(data){
      if (data.total_count){
        console.log(data.total_count);
        boolean = true;
      }
      else {
        console.log(data.total_count);
        boolean = false;
      }
    });
  }
};
```

And then here's the event listener: 

``` js
var newProfileView = function(profile){
  var self = this;
  self.$el = $(".newProfileView");
  $(".newProfile").on("submit", function(){
    event.preventDefault();
    if (self.checkProfile($('.username_input').val())){
      console.log('valid user');
    }
    else {
      console.log('invalid user');
    }
    //if checkProfile(username) returns truthy,
    //self.createProfile();
    //else 'try again'

    // self.createProfile();
  });
};
```

Am I going about this the right way? Thanks!

**Comment by RobertAKARobin** [comment]
Your `.then` doesn't appear to be attached to anything here...?

``` js
newProfileView.prototype = {
  checkProfile: function(username){
    var url='https://api.github.com/search/users?q=';
    .then(function(data){
      if (data.total_count){
        console.log(data.total_count);
        boolean = true;
      }
      else {
        console.log(data.total_count);
        boolean = false;
      }
    });
  }
};
```

**Comment by tomiteo** [comment]
Eek! Yes I was altering things for debugging, but now I've figured it out...Sorry to bother!!!!
