### ISSUE TITLE
User Authentication Sign-Up Hangs When Clicked

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-wdi-exercises/project3#89]
I'm having issues with the login and signup routes. 

When I clicked on the element it never goes to it's intended route, it just hangs for a long time.

**Comment by andrewsunglaekim** [comment]
can you post the code for login and sign up?

**Comment by KoryJCampbell** [comment]
nvmd i figured it out lol thanks

**Comment by andrewsunglaekim** [comment]
Great!
