### ISSUE TITLE
How can we store API key safely into express?

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/project3#9]
Hello,

How can we achieve function of figaro gem in rails on using express node.

**Comment by jenpen** [comment]
Great question! Also interested to know.

**Comment by amaseda** [comment]
One way to do this is to create an `env.js` file that contains your API key (and any other information you want to keep hidden). You'll want to make sure this `env.js` is included in `.gitignore` so it's not pushed  to your repo.

The contents of `env.js` can simply be an object. You'll then export that object so it can be used throughout your application. It will look something like this...

``` js
module.exports = {
  api_key: ...
}
```

You can then require that file and reference your key like so...

``` js
env = require( "./env" );
// ...
url = "http://someapi.com/search=cute_dog&api_key=" + env.api_key
$.getJSON( url ).then( ... );
```

Hope that helps. Let me know if you have any additional questions.
