### ISSUE TITLE
can't load in Heroku

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project3#91]
I've gone through Robin's example, removed the `var env = require(env)` lines, and changed the `env.whatever` variables to `process.env.whatever`. I have a Procfile. I followed the <a href="https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-config-vars">Heroku tutorial</a> as best as I could, and I set up my config vars in the Heroku dashboard. 

Running 'heroku logs -t' just gives me extensive `npm ERR!` messages - too many to paste here, but the specific message `npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"` repeats a lot. 

I looked at the other Heroku issues posted, but none of them help. The branch I am trying to deploy is <a href="https://github.com/MarkhamShofner/Project-3-API/tree/heroku_deployment">here</a>.

**Comment by RobertAKARobin** [comment]
This is a toughie! I've been working on this for like 15 minutes now.

**Comment by jshawl** [comment]
https://github.com/MarkhamShofner/Project-3-API/blob/1ef17ebc4548208fbdb08b4237e210d551ea4fe3/db/seeds.js#L5 should reference mongolab uri

**Comment by RobertAKARobin** [comment]
Also, put the connection URL in your `schema.js` instead of your `seeds.js`.

**Comment by RobertAKARobin** [comment]
Here are the changes I made to get this to work: https://github.com/MarkhamShofner/Project-3-API/pull/12

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to take this issue of the market. Feel free to open a new one!
