### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/project3#92]
Can I get a walkthrough of how to edit a document? I have a button that is clickable but not sure how to target the correct document when I press update and what to write in the controller and model files.

This is the form currently and it shows the correct exercise.

![image](https://cloud.githubusercontent.com/assets/12722650/11699390/26c38d20-9e92-11e5-889a-b081e57fc748.png)

**Comment by RobertAKARobin** [comment]
Could you be more specific about what you mean by "how to edit a document"?

**Comment by Ly900** [comment]
I have that exercise showing in the form. I would like to be able to edit and update it.

**Comment by RobertAKARobin** [comment]
I'm afraid we can't give you a walkthrough without re-teaching the class! I'd recommend you take a look at the OOJS1 and OOJS2 lesson plans, and this branch of this repo:

https://github.com/ga-dc/tunr_mongo_oojs/tree/create-read-update-delete

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to take this issue of the market. Feel free to open a new one!

**Comment by Ly900** [comment]
I don't understand it completely but I got it to work. Thanks!
