### ISSUE TITLE
Async issues with API

### ISSUE THREAD

**Issue by neka-io** [ga-wdi-exercises/project3#93]
We are using a middleware that parses the Amazon API response from XML to JSON, which makes it hard to attach promises to the API call itself. The function that handles the multiple API calls is acting like a synchronous function and we have trouble making the rest of the code run only after all API calls are complete. 
https://github.com/Mahartney/BasketCase

**Comment by RobertAKARobin** [comment]
Cool! Can you point me to the relevant part of your code?

**Comment by neka-io** [comment]
the amazonCall function in itemcontroller is invoking APIcall in the same file which makes the API a certain number of times.

**Comment by RobertAKARobin** [comment]
For reference: https://github.com/Mahartney/BasketCase/blob/master/controllers/itemController.js

**Comment by RobertAKARobin** [comment]
Yeah, asynchronous stuff in loops is super, super tricky. The best thing I can give you is my solution from when I was working on Tunr:

https://github.com/ga-dc/tunr_mongo_oojs/blob/master/db/seeds.js#L40

That function can be used for pretty much anything that's asynchronous.

**Comment by neka-io** [comment]
thanks Robin. In the solution you posted, what is setting index?

**Comment by RobertAKARobin** [comment]
You can ignore it. Just supply the first 2 arguments, the collection and the callback.
