### ISSUE TITLE
my layout.hbs file got deleted when we merged branches

### ISSUE THREAD

**Issue by tkentor** [ga-wdi-exercises/project3#94]
My changes to the layout.hbs file were erased when we merged. I committed and pushed multiple times, but I cannot find where those commits went. Terminal history indicates that I was indeed committing and pushing up, on a branch called views-branch, yet commits are not there.

https://github.com/tkentor/campaign-finance

**Comment by RobertAKARobin** [comment]
Not this branch? https://github.com/tkentor/campaign-finance/tree/views-branch

If not, take a look at the answer to this question:

http://stackoverflow.com/a/2531803/2053389

You can recover just about anything with Git's "reflog" (as in "reference log", not as in "re-flog").

**Comment by tkentor** [comment]
No not there unfortunately.

Hm, so I ran git reflog. And I want the HEAD@{2} changes, so I run git
reset HEAD@{2}... does that mean I can recover that stage? Changes don't
seem to be reflected in atom.

Thanks--

**Comment by jshawl** [comment]
Do you know which commit removed the changes you want?

**Comment by tkentor** [comment]
Yeah, when I merged with Won's master file, which my branch was forked and
cloned from

**Comment by jshawl** [comment]
what is the commit sha?

**Comment by tkentor** [comment]
huh?

**Comment by jshawl** [comment]
https://github.com/tkentor/campaign-finance/commits/views-branch

look on the right. which one is it?

![](https://dl.dropboxusercontent.com/s/55rxxpt8prvy40v/Screenshot%202015-12-10%2009.50.38.png?dl=0)

**Comment by tkentor** [comment]
Ah, that one. 7ff3691.

**Comment by tkentor** [comment]
Ok got it back! Thanks!

**Comment by ghost** [comment]
schwing!

**Comment by jshawl** [comment]
ok great!
