### ISSUE TITLE
Heroku ignoring pushes??

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project3#95]
I have pushed my updated app to Heroku several times this evening, but nothing appears to be happening. I immediately get an "Everything up-to-date" message in the terminal, and none of those updates are reflected on my dashboard:

<img width="774" alt="screen shot 2015-12-09 at 9 03 11 pm" src="https://cloud.githubusercontent.com/assets/3891862/11704744/8081da80-9eb8-11e5-9c20-6d0a9818d178.png">

I even tried to create a new Heroku page entirely, but the same thing happened - no activities recorded on the dashboard, and I never had to wait for any commands to run ...

<img width="680" alt="screen shot 2015-12-09 at 9 01 30 pm" src="https://cloud.githubusercontent.com/assets/3891862/11704850/6e677430-9eb9-11e5-841e-ddeadd005884.png">

**Comment by mattscilipoti** [comment]
Your `git push heroku master` command is pushing the master branch on heroku.  Your changes are in the "heroku_deployment" branch.  Either merge your changes into the master branch or push that branch to heroku: `git push heroku heroku_deployment:master`

**Comment by rebeccaestes** [comment]
Thanks! I'd tried pushing both branches, but didn't know about the colon structure.
