### ISSUE TITLE
Ajax patch request returns null for all properties 

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/project3#96]
My update(patch) form is not saving the new changes to the db and then returns the updated json object as null for all properties. When it gets to the controller action it has the correct id to look up the document but <code>req.body</code> logs out as:

```
{ '{"name":"Roshana Devkota afadf"}': '' }
```

At first I thought that was weird because its missing the key : pair but it gets sent to the db as follows according to the mongoose docs but that might not be it and its 3 am and im not getting anywhere lol

```
{ $set : '{"name":"Roshana Devkota afadf"}' }
```

**Comment by jshawl** [comment]
can you share the code that's making the patch request?

**Comment by codedre** [comment]
```
User.prototype = {
  update: function(userData) {
    console.log(this.id);
    var self = this;
    var url = '/user/' + this.id;
    var request = $.ajax({
      url: url,
      type: 'PATCH',
      dataType: 'json',
      data: JSON.stringify(userData)
    })
    .then(function(updatedUserInfo) {
      self.reload(updatedUserInfo);
    });
    return request;
  },
  reload: function(newData) {
    for(var attrname in newData) {
      console.log("I get here");
      // this[attrname] = newData[attrname];
      null !== newData[attrname] ? this[attrname] = newData[attrname] : this[attrname] = '';
    }
  }
```

**Comment by jshawl** [comment]
I think this line in your AJAX request: `data: JSON.stringify(userData)` is causing the issue. Does it work without JSON.stringify?

can you make a successful PATCH using postman w/ json? if so, how does that json relate to this `userData` json?

**Comment by RobertAKARobin** [comment]
It's been an hour, so I'm going to close this. Feel free to open a new one.

**Comment by codedre** [comment]
OMG it was stringify the entire time 😩!!!!!!!
