### ISSUE TITLE
HTTP response from a custom function

### ISSUE THREAD

**Issue by neka-io** [ga-wdi-exercises/project3#98]
Is there a way to send an HTTP response with a json from a custom function that is not taking request and response as its arguments?

**Comment by jshawl** [comment]
yeah but you have to pass `req, res` to that function, so no?

e.g.

``` js
app.get("/", function(req,res){
  myCustomFunction(req,res)
})

function myCustomFunction(req,res){
  res.json([])
}
```

**Comment by neka-io** [comment]
Thanks Jesse. That's what we are doing but our ajax call to get the json is failing. Can we chat with you about it?

**Comment by jshawl** [comment]
is it ok to keep working here?

**Comment by jshawl** [comment]
do you have any errors in the console? how do you know it's failing

**Comment by neka-io** [comment]
we get an ERR_CONNECTION_REFUSED

**Comment by jshawl** [comment]
this suggests the server isn't running. can you take a screenshot of the error?

**Comment by RobertAKARobin** [comment]
It's been an hour, so I'm going to close this. Feel free to open a new one.
